"""
Mirror of <freerdp/server/ainput.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
AINPUT_SERVER_OPEN_RESULT_CLOSED = 1
AINPUT_SERVER_OPEN_RESULT_ERROR = 3
AINPUT_SERVER_OPEN_RESULT_NOTSUPPORTED = 2
AINPUT_SERVER_OPEN_RESULT_OK = 0

# --- types declared in this header ---
AINPUT_SERVER_OPEN_RESULT = _types.AINPUT_SERVER_OPEN_RESULT
ainput_server_context = _types.ainput_server_context
psAInputChannelIdAssigned = _types.psAInputChannelIdAssigned
psAInputServerChannelHandle = _types.psAInputServerChannelHandle
psAInputServerClose = _types.psAInputServerClose
psAInputServerInitialize = _types.psAInputServerInitialize
psAInputServerIsOpen = _types.psAInputServerIsOpen
psAInputServerMouseEvent = _types.psAInputServerMouseEvent
psAInputServerOpen = _types.psAInputServerOpen
psAInputServerOpenResult = _types.psAInputServerOpenResult
psAInputServerPoll = _types.psAInputServerPoll
struct_s_ainput_server_context = _types.struct_s_ainput_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'ainput_server_context_free',  # void (ctypes.POINTER(ainput_server_context))
    'ainput_server_context_new',  # ctypes.POINTER(ainput_server_context) (HANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['AINPUT_SERVER_OPEN_RESULT', 'AINPUT_SERVER_OPEN_RESULT_CLOSED', 'AINPUT_SERVER_OPEN_RESULT_ERROR', 'AINPUT_SERVER_OPEN_RESULT_NOTSUPPORTED', 'AINPUT_SERVER_OPEN_RESULT_OK', 'FUNCTIONS', 'ainput_server_context', 'bind', 'psAInputChannelIdAssigned', 'psAInputServerChannelHandle', 'psAInputServerClose', 'psAInputServerInitialize', 'psAInputServerIsOpen', 'psAInputServerMouseEvent', 'psAInputServerOpen', 'psAInputServerOpenResult', 'psAInputServerPoll', 'struct_s_ainput_server_context']
