"""
Mirror of <freerdp/server/audin.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
audin_server_context = _types.audin_server_context
psAudinServerChannelClose = _types.psAudinServerChannelClose
psAudinServerChannelIdAssigned = _types.psAudinServerChannelIdAssigned
psAudinServerChannelIsOpen = _types.psAudinServerChannelIsOpen
psAudinServerChannelOpen = _types.psAudinServerChannelOpen
psAudinServerData = _types.psAudinServerData
psAudinServerFormatChange = _types.psAudinServerFormatChange
psAudinServerFormats = _types.psAudinServerFormats
psAudinServerIncomingData = _types.psAudinServerIncomingData
psAudinServerOpen = _types.psAudinServerOpen
psAudinServerOpenReply = _types.psAudinServerOpenReply
psAudinServerVersion = _types.psAudinServerVersion
struct_s_audin_server_context = _types.struct_s_audin_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'audin_server_context_free',  # void (ctypes.POINTER(audin_server_context))
    'audin_server_context_new',  # ctypes.POINTER(audin_server_context) (HANDLE)
    'audin_server_get_negotiated_format',  # ctypes.POINTER(AUDIO_FORMAT) (ctypes.POINTER(audin_server_context))
    'audin_server_set_formats',  # BOOL (ctypes.POINTER(audin_server_context), SSIZE_T, ctypes.POINTER(AUDIO_FORMAT))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'audin_server_context', 'bind', 'psAudinServerChannelClose', 'psAudinServerChannelIdAssigned', 'psAudinServerChannelIsOpen', 'psAudinServerChannelOpen', 'psAudinServerData', 'psAudinServerFormatChange', 'psAudinServerFormats', 'psAudinServerIncomingData', 'psAudinServerOpen', 'psAudinServerOpenReply', 'psAudinServerVersion', 'struct_s_audin_server_context']
