"""
Mirror of <freerdp/server/cliprdr.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
CliprdrServerContext = _types.CliprdrServerContext
psCliprdrCheckEventHandle = _types.psCliprdrCheckEventHandle
psCliprdrClientCapabilities = _types.psCliprdrClientCapabilities
psCliprdrClientFileContentsRequest = _types.psCliprdrClientFileContentsRequest
psCliprdrClientFileContentsResponse = _types.psCliprdrClientFileContentsResponse
psCliprdrClientFormatDataRequest = _types.psCliprdrClientFormatDataRequest
psCliprdrClientFormatDataResponse = _types.psCliprdrClientFormatDataResponse
psCliprdrClientFormatList = _types.psCliprdrClientFormatList
psCliprdrClientFormatListResponse = _types.psCliprdrClientFormatListResponse
psCliprdrClientLockClipboardData = _types.psCliprdrClientLockClipboardData
psCliprdrClientUnlockClipboardData = _types.psCliprdrClientUnlockClipboardData
psCliprdrClose = _types.psCliprdrClose
psCliprdrGetEventHandle = _types.psCliprdrGetEventHandle
psCliprdrMonitorReady = _types.psCliprdrMonitorReady
psCliprdrOpen = _types.psCliprdrOpen
psCliprdrServerCapabilities = _types.psCliprdrServerCapabilities
psCliprdrServerFileContentsRequest = _types.psCliprdrServerFileContentsRequest
psCliprdrServerFileContentsResponse = _types.psCliprdrServerFileContentsResponse
psCliprdrServerFormatDataRequest = _types.psCliprdrServerFormatDataRequest
psCliprdrServerFormatDataResponse = _types.psCliprdrServerFormatDataResponse
psCliprdrServerFormatList = _types.psCliprdrServerFormatList
psCliprdrServerFormatListResponse = _types.psCliprdrServerFormatListResponse
psCliprdrServerLockClipboardData = _types.psCliprdrServerLockClipboardData
psCliprdrServerUnlockClipboardData = _types.psCliprdrServerUnlockClipboardData
psCliprdrStart = _types.psCliprdrStart
psCliprdrStop = _types.psCliprdrStop
psCliprdrTempDirectory = _types.psCliprdrTempDirectory
struct_s_cliprdr_server_context = _types.struct_s_cliprdr_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'cliprdr_server_context_free',  # void (ctypes.POINTER(CliprdrServerContext))
    'cliprdr_server_context_new',  # ctypes.POINTER(CliprdrServerContext) (HANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['CliprdrServerContext', 'FUNCTIONS', 'bind', 'psCliprdrCheckEventHandle', 'psCliprdrClientCapabilities', 'psCliprdrClientFileContentsRequest', 'psCliprdrClientFileContentsResponse', 'psCliprdrClientFormatDataRequest', 'psCliprdrClientFormatDataResponse', 'psCliprdrClientFormatList', 'psCliprdrClientFormatListResponse', 'psCliprdrClientLockClipboardData', 'psCliprdrClientUnlockClipboardData', 'psCliprdrClose', 'psCliprdrGetEventHandle', 'psCliprdrMonitorReady', 'psCliprdrOpen', 'psCliprdrServerCapabilities', 'psCliprdrServerFileContentsRequest', 'psCliprdrServerFileContentsResponse', 'psCliprdrServerFormatDataRequest', 'psCliprdrServerFormatDataResponse', 'psCliprdrServerFormatList', 'psCliprdrServerFormatListResponse', 'psCliprdrServerLockClipboardData', 'psCliprdrServerUnlockClipboardData', 'psCliprdrStart', 'psCliprdrStop', 'psCliprdrTempDirectory', 'struct_s_cliprdr_server_context']
