"""
Mirror of <freerdp/server/disp.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
DispServerContext = _types.DispServerContext
DispServerPrivate = _types.DispServerPrivate
psDispCaps = _types.psDispCaps
psDispChannelIdAssigned = _types.psDispChannelIdAssigned
psDispClose = _types.psDispClose
psDispMonitorLayout = _types.psDispMonitorLayout
psDispOpen = _types.psDispOpen
struct_s_disp_server_context = _types.struct_s_disp_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'disp_server_context_free',  # void (ctypes.POINTER(DispServerContext))
    'disp_server_context_new',  # ctypes.POINTER(DispServerContext) (HANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['DispServerContext', 'DispServerPrivate', 'FUNCTIONS', 'bind', 'psDispCaps', 'psDispChannelIdAssigned', 'psDispClose', 'psDispMonitorLayout', 'psDispOpen', 'struct_s_disp_server_context']
