"""
Mirror of <freerdp/server/drdynvc.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
DrdynvcServerContext = _types.DrdynvcServerContext
DrdynvcServerPrivate = _types.DrdynvcServerPrivate
psDrdynvcStart = _types.psDrdynvcStart
psDrdynvcStop = _types.psDrdynvcStop
struct_s_drdynvc_server_context = _types.struct_s_drdynvc_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'drdynvc_server_context_free',  # void (ctypes.POINTER(DrdynvcServerContext))
    'drdynvc_server_context_new',  # ctypes.POINTER(DrdynvcServerContext) (HANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['DrdynvcServerContext', 'DrdynvcServerPrivate', 'FUNCTIONS', 'bind', 'psDrdynvcStart', 'psDrdynvcStop', 'struct_s_drdynvc_server_context']
