"""
Mirror of <freerdp/server/echo.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
ECHO_SERVER_OPEN_RESULT_CLOSED = 1
ECHO_SERVER_OPEN_RESULT_ERROR = 3
ECHO_SERVER_OPEN_RESULT_NOTSUPPORTED = 2
ECHO_SERVER_OPEN_RESULT_OK = 0

# --- types declared in this header ---
ECHO_SERVER_OPEN_RESULT = _types.ECHO_SERVER_OPEN_RESULT
echo_server_context = _types.echo_server_context
psEchoServerChannelIdAssigned = _types.psEchoServerChannelIdAssigned
psEchoServerClose = _types.psEchoServerClose
psEchoServerOpen = _types.psEchoServerOpen
psEchoServerOpenResult = _types.psEchoServerOpenResult
psEchoServerRequest = _types.psEchoServerRequest
psEchoServerResponse = _types.psEchoServerResponse
struct_s_echo_server_context = _types.struct_s_echo_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'echo_server_context_free',  # void (ctypes.POINTER(echo_server_context))
    'echo_server_context_new',  # ctypes.POINTER(echo_server_context) (HANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['ECHO_SERVER_OPEN_RESULT', 'ECHO_SERVER_OPEN_RESULT_CLOSED', 'ECHO_SERVER_OPEN_RESULT_ERROR', 'ECHO_SERVER_OPEN_RESULT_NOTSUPPORTED', 'ECHO_SERVER_OPEN_RESULT_OK', 'FUNCTIONS', 'bind', 'echo_server_context', 'psEchoServerChannelIdAssigned', 'psEchoServerClose', 'psEchoServerOpen', 'psEchoServerOpenResult', 'psEchoServerRequest', 'psEchoServerResponse', 'struct_s_echo_server_context']
