"""
Mirror of <freerdp/server/encomsp.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
EncomspServerContext = _types.EncomspServerContext
EncomspServerPrivate = _types.EncomspServerPrivate
psEncomspApplicationCreated = _types.psEncomspApplicationCreated
psEncomspApplicationRemoved = _types.psEncomspApplicationRemoved
psEncomspChangeParticipantControlLevel = _types.psEncomspChangeParticipantControlLevel
psEncomspFilterUpdated = _types.psEncomspFilterUpdated
psEncomspGraphicsStreamPaused = _types.psEncomspGraphicsStreamPaused
psEncomspGraphicsStreamResumed = _types.psEncomspGraphicsStreamResumed
psEncomspParticipantCreated = _types.psEncomspParticipantCreated
psEncomspParticipantRemoved = _types.psEncomspParticipantRemoved
psEncomspShowWindow = _types.psEncomspShowWindow
psEncomspStart = _types.psEncomspStart
psEncomspStop = _types.psEncomspStop
psEncomspWindowCreated = _types.psEncomspWindowCreated
psEncomspWindowRemoved = _types.psEncomspWindowRemoved
struct_s_encomsp_server_context = _types.struct_s_encomsp_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'encomsp_server_context_free',  # void (ctypes.POINTER(EncomspServerContext))
    'encomsp_server_context_new',  # ctypes.POINTER(EncomspServerContext) (HANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['EncomspServerContext', 'EncomspServerPrivate', 'FUNCTIONS', 'bind', 'psEncomspApplicationCreated', 'psEncomspApplicationRemoved', 'psEncomspChangeParticipantControlLevel', 'psEncomspFilterUpdated', 'psEncomspGraphicsStreamPaused', 'psEncomspGraphicsStreamResumed', 'psEncomspParticipantCreated', 'psEncomspParticipantRemoved', 'psEncomspShowWindow', 'psEncomspStart', 'psEncomspStop', 'psEncomspWindowCreated', 'psEncomspWindowRemoved', 'struct_s_encomsp_server_context']
