"""
Mirror of <freerdp/server/gfxredir.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
GfxRedirServerContext = _types.GfxRedirServerContext
GfxRedirServerPrivate = _types.GfxRedirServerPrivate
psGfxRedirClose = _types.psGfxRedirClose
psGfxRedirClosePool = _types.psGfxRedirClosePool
psGfxRedirCreateBuffer = _types.psGfxRedirCreateBuffer
psGfxRedirDestroyBuffer = _types.psGfxRedirDestroyBuffer
psGfxRedirError = _types.psGfxRedirError
psGfxRedirGraphicsRedirectionCapsAdvertise = _types.psGfxRedirGraphicsRedirectionCapsAdvertise
psGfxRedirGraphicsRedirectionCapsConfirm = _types.psGfxRedirGraphicsRedirectionCapsConfirm
psGfxRedirGraphicsRedirectionLegacyCaps = _types.psGfxRedirGraphicsRedirectionLegacyCaps
psGfxRedirOpen = _types.psGfxRedirOpen
psGfxRedirOpenPool = _types.psGfxRedirOpenPool
psGfxRedirPresentBuffer = _types.psGfxRedirPresentBuffer
psGfxRedirPresentBufferAck = _types.psGfxRedirPresentBufferAck
struct_s_gfxredir_server_context = _types.struct_s_gfxredir_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'gfxredir_server_context_free',  # void (ctypes.POINTER(GfxRedirServerContext))
    'gfxredir_server_context_new',  # ctypes.POINTER(GfxRedirServerContext) (HANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'GfxRedirServerContext', 'GfxRedirServerPrivate', 'bind', 'psGfxRedirClose', 'psGfxRedirClosePool', 'psGfxRedirCreateBuffer', 'psGfxRedirDestroyBuffer', 'psGfxRedirError', 'psGfxRedirGraphicsRedirectionCapsAdvertise', 'psGfxRedirGraphicsRedirectionCapsConfirm', 'psGfxRedirGraphicsRedirectionLegacyCaps', 'psGfxRedirOpen', 'psGfxRedirOpenPool', 'psGfxRedirPresentBuffer', 'psGfxRedirPresentBufferAck', 'struct_s_gfxredir_server_context']
