"""
Mirror of <freerdp/server/location.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
LocationServerContext = _types.LocationServerContext
psLocationServerBaseLocation3D = _types.psLocationServerBaseLocation3D
psLocationServerChannelHandle = _types.psLocationServerChannelHandle
psLocationServerChannelIdAssigned = _types.psLocationServerChannelIdAssigned
psLocationServerClientReady = _types.psLocationServerClientReady
psLocationServerClose = _types.psLocationServerClose
psLocationServerInitialize = _types.psLocationServerInitialize
psLocationServerLocation2DDelta = _types.psLocationServerLocation2DDelta
psLocationServerLocation3DDelta = _types.psLocationServerLocation3DDelta
psLocationServerOpen = _types.psLocationServerOpen
psLocationServerPoll = _types.psLocationServerPoll
psLocationServerServerReady = _types.psLocationServerServerReady
struct_s_location_server_context = _types.struct_s_location_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'location_server_context_free',  # void (ctypes.POINTER(LocationServerContext))
    'location_server_context_new',  # ctypes.POINTER(LocationServerContext) (HANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'LocationServerContext', 'bind', 'psLocationServerBaseLocation3D', 'psLocationServerChannelHandle', 'psLocationServerChannelIdAssigned', 'psLocationServerClientReady', 'psLocationServerClose', 'psLocationServerInitialize', 'psLocationServerLocation2DDelta', 'psLocationServerLocation3DDelta', 'psLocationServerOpen', 'psLocationServerPoll', 'psLocationServerServerReady', 'struct_s_location_server_context']
