"""
Mirror of <freerdp/server/rail.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
RailServerContext = _types.RailServerContext
RailServerPrivate = _types.RailServerPrivate
psRailClientActivate = _types.psRailClientActivate
psRailClientCaretBlinkRate = _types.psRailClientCaretBlinkRate
psRailClientClientStatus = _types.psRailClientClientStatus
psRailClientCloak = _types.psRailClientCloak
psRailClientCompartmentInfo = _types.psRailClientCompartmentInfo
psRailClientExec = _types.psRailClientExec
psRailClientGetAppidReq = _types.psRailClientGetAppidReq
psRailClientHandshake = _types.psRailClientHandshake
psRailClientLangbarInfo = _types.psRailClientLangbarInfo
psRailClientLanguageImeInfo = _types.psRailClientLanguageImeInfo
psRailClientNotifyEvent = _types.psRailClientNotifyEvent
psRailClientSnapArrange = _types.psRailClientSnapArrange
psRailClientSyscommand = _types.psRailClientSyscommand
psRailClientSysmenu = _types.psRailClientSysmenu
psRailClientSysparam = _types.psRailClientSysparam
psRailClientTextScale = _types.psRailClientTextScale
psRailClientWindowMove = _types.psRailClientWindowMove
psRailServerCloak = _types.psRailServerCloak
psRailServerExecResult = _types.psRailServerExecResult
psRailServerGetAppidResp = _types.psRailServerGetAppidResp
psRailServerGetAppidRespEx = _types.psRailServerGetAppidRespEx
psRailServerHandshake = _types.psRailServerHandshake
psRailServerHandshakeEx = _types.psRailServerHandshakeEx
psRailServerLangbarInfo = _types.psRailServerLangbarInfo
psRailServerLocalMoveSize = _types.psRailServerLocalMoveSize
psRailServerMinMaxInfo = _types.psRailServerMinMaxInfo
psRailServerPowerDisplayRequest = _types.psRailServerPowerDisplayRequest
psRailServerSysparam = _types.psRailServerSysparam
psRailServerTaskbarInfo = _types.psRailServerTaskbarInfo
psRailServerZOrderSync = _types.psRailServerZOrderSync
psRailStart = _types.psRailStart
psRailStop = _types.psRailStop
struct_s_rail_server_context = _types.struct_s_rail_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'rail_server_context_free',  # void (ctypes.POINTER(RailServerContext))
    'rail_server_context_new',  # ctypes.POINTER(RailServerContext) (HANDLE)
    'rail_server_handle_messages',  # UINT (ctypes.POINTER(RailServerContext))
    'rail_server_set_handshake_ex_flags',  # void (ctypes.POINTER(RailServerContext), DWORD)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'RailServerContext', 'RailServerPrivate', 'bind', 'psRailClientActivate', 'psRailClientCaretBlinkRate', 'psRailClientClientStatus', 'psRailClientCloak', 'psRailClientCompartmentInfo', 'psRailClientExec', 'psRailClientGetAppidReq', 'psRailClientHandshake', 'psRailClientLangbarInfo', 'psRailClientLanguageImeInfo', 'psRailClientNotifyEvent', 'psRailClientSnapArrange', 'psRailClientSyscommand', 'psRailClientSysmenu', 'psRailClientSysparam', 'psRailClientTextScale', 'psRailClientWindowMove', 'psRailServerCloak', 'psRailServerExecResult', 'psRailServerGetAppidResp', 'psRailServerGetAppidRespEx', 'psRailServerHandshake', 'psRailServerHandshakeEx', 'psRailServerLangbarInfo', 'psRailServerLocalMoveSize', 'psRailServerMinMaxInfo', 'psRailServerPowerDisplayRequest', 'psRailServerSysparam', 'psRailServerTaskbarInfo', 'psRailServerZOrderSync', 'psRailStart', 'psRailStop', 'struct_s_rail_server_context']
