"""
Mirror of <freerdp/server/rdpemsc.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
MouseCursorServerContext = _types.MouseCursorServerContext
psMouseCursorServerCapsAdvertise = _types.psMouseCursorServerCapsAdvertise
psMouseCursorServerCapsConfirm = _types.psMouseCursorServerCapsConfirm
psMouseCursorServerChannelHandle = _types.psMouseCursorServerChannelHandle
psMouseCursorServerChannelIdAssigned = _types.psMouseCursorServerChannelIdAssigned
psMouseCursorServerClose = _types.psMouseCursorServerClose
psMouseCursorServerInitialize = _types.psMouseCursorServerInitialize
psMouseCursorServerMouseptrUpdate = _types.psMouseCursorServerMouseptrUpdate
psMouseCursorServerOpen = _types.psMouseCursorServerOpen
psMouseCursorServerPoll = _types.psMouseCursorServerPoll
struct_s_mouse_cursor_server_context = _types.struct_s_mouse_cursor_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'mouse_cursor_server_context_free',  # void (ctypes.POINTER(MouseCursorServerContext))
    'mouse_cursor_server_context_new',  # ctypes.POINTER(MouseCursorServerContext) (HANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'MouseCursorServerContext', 'bind', 'psMouseCursorServerCapsAdvertise', 'psMouseCursorServerCapsConfirm', 'psMouseCursorServerChannelHandle', 'psMouseCursorServerChannelIdAssigned', 'psMouseCursorServerClose', 'psMouseCursorServerInitialize', 'psMouseCursorServerMouseptrUpdate', 'psMouseCursorServerOpen', 'psMouseCursorServerPoll', 'struct_s_mouse_cursor_server_context']
