"""
Mirror of <freerdp/server/rdpecam.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
CameraDeviceServerContext = _types.CameraDeviceServerContext
psCameraDeviceServerActivateDeviceRequest = _types.psCameraDeviceServerActivateDeviceRequest
psCameraDeviceServerChannelHandle = _types.psCameraDeviceServerChannelHandle
psCameraDeviceServerChannelIdAssigned = _types.psCameraDeviceServerChannelIdAssigned
psCameraDeviceServerClose = _types.psCameraDeviceServerClose
psCameraDeviceServerCurrentMediaTypeRequest = _types.psCameraDeviceServerCurrentMediaTypeRequest
psCameraDeviceServerCurrentMediaTypeResponse = _types.psCameraDeviceServerCurrentMediaTypeResponse
psCameraDeviceServerDeactivateDeviceRequest = _types.psCameraDeviceServerDeactivateDeviceRequest
psCameraDeviceServerErrorResponse = _types.psCameraDeviceServerErrorResponse
psCameraDeviceServerInitialize = _types.psCameraDeviceServerInitialize
psCameraDeviceServerMediaTypeListRequest = _types.psCameraDeviceServerMediaTypeListRequest
psCameraDeviceServerMediaTypeListResponse = _types.psCameraDeviceServerMediaTypeListResponse
psCameraDeviceServerOpen = _types.psCameraDeviceServerOpen
psCameraDeviceServerPoll = _types.psCameraDeviceServerPoll
psCameraDeviceServerPropertyListRequest = _types.psCameraDeviceServerPropertyListRequest
psCameraDeviceServerPropertyListResponse = _types.psCameraDeviceServerPropertyListResponse
psCameraDeviceServerPropertyValueRequest = _types.psCameraDeviceServerPropertyValueRequest
psCameraDeviceServerPropertyValueResponse = _types.psCameraDeviceServerPropertyValueResponse
psCameraDeviceServerSampleErrorResponse = _types.psCameraDeviceServerSampleErrorResponse
psCameraDeviceServerSampleRequest = _types.psCameraDeviceServerSampleRequest
psCameraDeviceServerSampleResponse = _types.psCameraDeviceServerSampleResponse
psCameraDeviceServerSetPropertyValueRequest = _types.psCameraDeviceServerSetPropertyValueRequest
psCameraDeviceServerStartStreamsRequest = _types.psCameraDeviceServerStartStreamsRequest
psCameraDeviceServerStopStreamsRequest = _types.psCameraDeviceServerStopStreamsRequest
psCameraDeviceServerStreamListRequest = _types.psCameraDeviceServerStreamListRequest
psCameraDeviceServerStreamListResponse = _types.psCameraDeviceServerStreamListResponse
psCameraDeviceServerSuccessResponse = _types.psCameraDeviceServerSuccessResponse
struct_camera_device_server_context = _types.struct_camera_device_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'camera_device_server_context_free',  # void (ctypes.POINTER(CameraDeviceServerContext))
    'camera_device_server_context_new',  # ctypes.POINTER(CameraDeviceServerContext) (HANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['CameraDeviceServerContext', 'FUNCTIONS', 'bind', 'psCameraDeviceServerActivateDeviceRequest', 'psCameraDeviceServerChannelHandle', 'psCameraDeviceServerChannelIdAssigned', 'psCameraDeviceServerClose', 'psCameraDeviceServerCurrentMediaTypeRequest', 'psCameraDeviceServerCurrentMediaTypeResponse', 'psCameraDeviceServerDeactivateDeviceRequest', 'psCameraDeviceServerErrorResponse', 'psCameraDeviceServerInitialize', 'psCameraDeviceServerMediaTypeListRequest', 'psCameraDeviceServerMediaTypeListResponse', 'psCameraDeviceServerOpen', 'psCameraDeviceServerPoll', 'psCameraDeviceServerPropertyListRequest', 'psCameraDeviceServerPropertyListResponse', 'psCameraDeviceServerPropertyValueRequest', 'psCameraDeviceServerPropertyValueResponse', 'psCameraDeviceServerSampleErrorResponse', 'psCameraDeviceServerSampleRequest', 'psCameraDeviceServerSampleResponse', 'psCameraDeviceServerSetPropertyValueRequest', 'psCameraDeviceServerStartStreamsRequest', 'psCameraDeviceServerStopStreamsRequest', 'psCameraDeviceServerStreamListRequest', 'psCameraDeviceServerStreamListResponse', 'psCameraDeviceServerSuccessResponse', 'struct_camera_device_server_context']
