"""
Mirror of <freerdp/server/rdpecam-enumerator.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
CamDevEnumServerContext = _types.CamDevEnumServerContext
psCamDevEnumServerServerChannelHandle = _types.psCamDevEnumServerServerChannelHandle
psCamDevEnumServerServerChannelIdAssigned = _types.psCamDevEnumServerServerChannelIdAssigned
psCamDevEnumServerServerClose = _types.psCamDevEnumServerServerClose
psCamDevEnumServerServerDeviceAddedNotification = _types.psCamDevEnumServerServerDeviceAddedNotification
psCamDevEnumServerServerDeviceRemovedNotification = _types.psCamDevEnumServerServerDeviceRemovedNotification
psCamDevEnumServerServerInitialize = _types.psCamDevEnumServerServerInitialize
psCamDevEnumServerServerOpen = _types.psCamDevEnumServerServerOpen
psCamDevEnumServerServerPoll = _types.psCamDevEnumServerServerPoll
psCamDevEnumServerServerSelectVersionRequest = _types.psCamDevEnumServerServerSelectVersionRequest
psCamDevEnumServerServerSelectVersionResponse = _types.psCamDevEnumServerServerSelectVersionResponse
struct_s_cam_dev_enum_server_context = _types.struct_s_cam_dev_enum_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'cam_dev_enum_server_context_free',  # void (ctypes.POINTER(CamDevEnumServerContext))
    'cam_dev_enum_server_context_new',  # ctypes.POINTER(CamDevEnumServerContext) (HANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['CamDevEnumServerContext', 'FUNCTIONS', 'bind', 'psCamDevEnumServerServerChannelHandle', 'psCamDevEnumServerServerChannelIdAssigned', 'psCamDevEnumServerServerClose', 'psCamDevEnumServerServerDeviceAddedNotification', 'psCamDevEnumServerServerDeviceRemovedNotification', 'psCamDevEnumServerServerInitialize', 'psCamDevEnumServerServerOpen', 'psCamDevEnumServerServerPoll', 'psCamDevEnumServerServerSelectVersionRequest', 'psCamDevEnumServerServerSelectVersionResponse', 'struct_s_cam_dev_enum_server_context']
