"""
Mirror of <freerdp/server/rdpei.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
RdpeiServerContext = _types.RdpeiServerContext
RdpeiServerPrivate = _types.RdpeiServerPrivate
psRdpeiServerClose = _types.psRdpeiServerClose
psRdpeiServerOpen = _types.psRdpeiServerOpen
struct_s_rdpei_server_context = _types.struct_s_rdpei_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'rdpei_server_context_free',  # void (ctypes.POINTER(RdpeiServerContext))
    'rdpei_server_context_new',  # ctypes.POINTER(RdpeiServerContext) (HANDLE)
    'rdpei_server_context_reset',  # void (ctypes.POINTER(RdpeiServerContext))
    'rdpei_server_get_event_handle',  # HANDLE (ctypes.POINTER(RdpeiServerContext))
    'rdpei_server_handle_messages',  # UINT (ctypes.POINTER(RdpeiServerContext))
    'rdpei_server_init',  # UINT (ctypes.POINTER(RdpeiServerContext))
    'rdpei_server_resume',  # UINT (ctypes.POINTER(RdpeiServerContext))
    'rdpei_server_send_sc_ready',  # UINT (ctypes.POINTER(RdpeiServerContext), UINT32, UINT32)
    'rdpei_server_suspend',  # UINT (ctypes.POINTER(RdpeiServerContext))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'RdpeiServerContext', 'RdpeiServerPrivate', 'bind', 'psRdpeiServerClose', 'psRdpeiServerOpen', 'struct_s_rdpei_server_context']
