"""
Mirror of <freerdp/server/rdpgfx.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
RdpgfxServerContext = _types.RdpgfxServerContext
RdpgfxServerPrivate = _types.RdpgfxServerPrivate
psRdpgfxCacheImportOffer = _types.psRdpgfxCacheImportOffer
psRdpgfxCacheImportReply = _types.psRdpgfxCacheImportReply
psRdpgfxCacheToSurface = _types.psRdpgfxCacheToSurface
psRdpgfxCapsAdvertise = _types.psRdpgfxCapsAdvertise
psRdpgfxCapsConfirm = _types.psRdpgfxCapsConfirm
psRdpgfxCreateSurface = _types.psRdpgfxCreateSurface
psRdpgfxDeleteEncodingContext = _types.psRdpgfxDeleteEncodingContext
psRdpgfxDeleteSurface = _types.psRdpgfxDeleteSurface
psRdpgfxEndFrame = _types.psRdpgfxEndFrame
psRdpgfxEvictCacheEntry = _types.psRdpgfxEvictCacheEntry
psRdpgfxFrameAcknowledge = _types.psRdpgfxFrameAcknowledge
psRdpgfxMapSurfaceToOutput = _types.psRdpgfxMapSurfaceToOutput
psRdpgfxMapSurfaceToScaledOutput = _types.psRdpgfxMapSurfaceToScaledOutput
psRdpgfxMapSurfaceToScaledWindow = _types.psRdpgfxMapSurfaceToScaledWindow
psRdpgfxMapSurfaceToWindow = _types.psRdpgfxMapSurfaceToWindow
psRdpgfxQoeFrameAcknowledge = _types.psRdpgfxQoeFrameAcknowledge
psRdpgfxResetGraphics = _types.psRdpgfxResetGraphics
psRdpgfxServerChannelIdAssigned = _types.psRdpgfxServerChannelIdAssigned
psRdpgfxServerClose = _types.psRdpgfxServerClose
psRdpgfxServerInitialize = _types.psRdpgfxServerInitialize
psRdpgfxServerOpen = _types.psRdpgfxServerOpen
psRdpgfxSolidFill = _types.psRdpgfxSolidFill
psRdpgfxStartFrame = _types.psRdpgfxStartFrame
psRdpgfxSurfaceCommand = _types.psRdpgfxSurfaceCommand
psRdpgfxSurfaceFrameCommand = _types.psRdpgfxSurfaceFrameCommand
psRdpgfxSurfaceToCache = _types.psRdpgfxSurfaceToCache
psRdpgfxSurfaceToSurface = _types.psRdpgfxSurfaceToSurface
struct_s_rdpgfx_server_context = _types.struct_s_rdpgfx_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'rdpgfx_server_context_free',  # void (ctypes.POINTER(RdpgfxServerContext))
    'rdpgfx_server_context_new',  # ctypes.POINTER(RdpgfxServerContext) (HANDLE)
    'rdpgfx_server_get_event_handle',  # HANDLE (ctypes.POINTER(RdpgfxServerContext))
    'rdpgfx_server_handle_messages',  # UINT (ctypes.POINTER(RdpgfxServerContext))
    'rdpgfx_server_set_own_thread',  # BOOL (ctypes.POINTER(RdpgfxServerContext), BOOL)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'RdpgfxServerContext', 'RdpgfxServerPrivate', 'bind', 'psRdpgfxCacheImportOffer', 'psRdpgfxCacheImportReply', 'psRdpgfxCacheToSurface', 'psRdpgfxCapsAdvertise', 'psRdpgfxCapsConfirm', 'psRdpgfxCreateSurface', 'psRdpgfxDeleteEncodingContext', 'psRdpgfxDeleteSurface', 'psRdpgfxEndFrame', 'psRdpgfxEvictCacheEntry', 'psRdpgfxFrameAcknowledge', 'psRdpgfxMapSurfaceToOutput', 'psRdpgfxMapSurfaceToScaledOutput', 'psRdpgfxMapSurfaceToScaledWindow', 'psRdpgfxMapSurfaceToWindow', 'psRdpgfxQoeFrameAcknowledge', 'psRdpgfxResetGraphics', 'psRdpgfxServerChannelIdAssigned', 'psRdpgfxServerClose', 'psRdpgfxServerInitialize', 'psRdpgfxServerOpen', 'psRdpgfxSolidFill', 'psRdpgfxStartFrame', 'psRdpgfxSurfaceCommand', 'psRdpgfxSurfaceFrameCommand', 'psRdpgfxSurfaceToCache', 'psRdpgfxSurfaceToSurface', 'struct_s_rdpgfx_server_context']
