"""
Mirror of <freerdp/server/rdpsnd.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
RdpsndServerContext = _types.RdpsndServerContext
RdpsndServerPrivate = _types.RdpsndServerPrivate
psRdpsndChannelIdAssigned = _types.psRdpsndChannelIdAssigned
psRdpsndServerActivated = _types.psRdpsndServerActivated
psRdpsndServerClose = _types.psRdpsndServerClose
psRdpsndServerConfirmBlock = _types.psRdpsndServerConfirmBlock
psRdpsndServerInitialize = _types.psRdpsndServerInitialize
psRdpsndServerSelectFormat = _types.psRdpsndServerSelectFormat
psRdpsndServerSendFormats = _types.psRdpsndServerSendFormats
psRdpsndServerSendSamples = _types.psRdpsndServerSendSamples
psRdpsndServerSendSamples2 = _types.psRdpsndServerSendSamples2
psRdpsndServerSetVolume = _types.psRdpsndServerSetVolume
psRdpsndServerTraining = _types.psRdpsndServerTraining
psRdpsndServerTrainingConfirm = _types.psRdpsndServerTrainingConfirm
psRdpsndStart = _types.psRdpsndStart
psRdpsndStop = _types.psRdpsndStop
rdpsnd_server_context = _types.rdpsnd_server_context
struct_s_rdpsnd_server_context = _types.struct_s_rdpsnd_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'rdpsnd_server_context_free',  # void (ctypes.POINTER(RdpsndServerContext))
    'rdpsnd_server_context_new',  # ctypes.POINTER(RdpsndServerContext) (HANDLE)
    'rdpsnd_server_context_reset',  # void (ctypes.POINTER(RdpsndServerContext))
    'rdpsnd_server_get_event_handle',  # HANDLE (ctypes.POINTER(RdpsndServerContext))
    'rdpsnd_server_handle_messages',  # UINT (ctypes.POINTER(RdpsndServerContext))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'RdpsndServerContext', 'RdpsndServerPrivate', 'bind', 'psRdpsndChannelIdAssigned', 'psRdpsndServerActivated', 'psRdpsndServerClose', 'psRdpsndServerConfirmBlock', 'psRdpsndServerInitialize', 'psRdpsndServerSelectFormat', 'psRdpsndServerSendFormats', 'psRdpsndServerSendSamples', 'psRdpsndServerSendSamples2', 'psRdpsndServerSetVolume', 'psRdpsndServerTraining', 'psRdpsndServerTrainingConfirm', 'psRdpsndStart', 'psRdpsndStop', 'rdpsnd_server_context', 'struct_s_rdpsnd_server_context']
