"""
Mirror of <freerdp/server/remdesk.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
RemdeskServerContext = _types.RemdeskServerContext
RemdeskServerPrivate = _types.RemdeskServerPrivate
psRemdeskStart = _types.psRemdeskStart
psRemdeskStop = _types.psRemdeskStop
struct_s_remdesk_server_context = _types.struct_s_remdesk_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'remdesk_server_context_free',  # void (ctypes.POINTER(RemdeskServerContext))
    'remdesk_server_context_new',  # ctypes.POINTER(RemdeskServerContext) (HANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'RemdeskServerContext', 'RemdeskServerPrivate', 'bind', 'psRemdeskStart', 'psRemdeskStop', 'struct_s_remdesk_server_context']
