"""
Mirror of <freerdp/server/server-common.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_server_warn_deprecated',  # void (ctypes.c_int, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_server_warn_experimental',  # void (ctypes.c_int, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_server_warn_unmaintained',  # void (ctypes.c_int, ctypes.POINTER(ctypes.c_char_p))
    'server_audin_get_formats',  # ctypes.c_size_t (ctypes.POINTER(ctypes.POINTER(AUDIO_FORMAT)))
    'server_rdpsnd_get_formats',  # ctypes.c_size_t (ctypes.POINTER(ctypes.POINTER(AUDIO_FORMAT)))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
