"""
Mirror of <freerdp/server/shadow.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
SHADOW_MSG_IN_REFRESH_REQUEST_ID = 0x3e9
SHADOW_MSG_OUT_AUDIO_OUT_SAMPLES_ID = 0x7d3
SHADOW_MSG_OUT_AUDIO_OUT_VOLUME_ID = 0x7d4
SHADOW_MSG_OUT_POINTER_ALPHA_UPDATE_ID = 0x7d2
SHADOW_MSG_OUT_POINTER_POSITION_UPDATE_ID = 0x7d1

# --- types declared in this header ---
MSG_OUT_FREE_FN = _types.MSG_OUT_FREE_FN
RDP_SHADOW_ENTRY_POINTS = _types.RDP_SHADOW_ENTRY_POINTS
SHADOW_MSG_OUT = _types.SHADOW_MSG_OUT
SHADOW_MSG_OUT_AUDIO_OUT_SAMPLES = _types.SHADOW_MSG_OUT_AUDIO_OUT_SAMPLES
SHADOW_MSG_OUT_AUDIO_OUT_VOLUME = _types.SHADOW_MSG_OUT_AUDIO_OUT_VOLUME
SHADOW_MSG_OUT_POINTER_ALPHA_UPDATE = _types.SHADOW_MSG_OUT_POINTER_ALPHA_UPDATE
SHADOW_MSG_OUT_POINTER_POSITION_UPDATE = _types.SHADOW_MSG_OUT_POINTER_POSITION_UPDATE
pfnShadowAuthenticate = _types.pfnShadowAuthenticate
pfnShadowChannelAudinServerReceiveSamples = _types.pfnShadowChannelAudinServerReceiveSamples
pfnShadowClientCapabilities = _types.pfnShadowClientCapabilities
pfnShadowClientConnect = _types.pfnShadowClientConnect
pfnShadowClientDisconnect = _types.pfnShadowClientDisconnect
pfnShadowEnumMonitors = _types.pfnShadowEnumMonitors
pfnShadowExtendedMouseEvent = _types.pfnShadowExtendedMouseEvent
pfnShadowKeyboardEvent = _types.pfnShadowKeyboardEvent
pfnShadowMouseEvent = _types.pfnShadowMouseEvent
pfnShadowRelMouseEvent = _types.pfnShadowRelMouseEvent
pfnShadowSubsystemEntry = _types.pfnShadowSubsystemEntry
pfnShadowSubsystemFree = _types.pfnShadowSubsystemFree
pfnShadowSubsystemInit = _types.pfnShadowSubsystemInit
pfnShadowSubsystemNew = _types.pfnShadowSubsystemNew
pfnShadowSubsystemStart = _types.pfnShadowSubsystemStart
pfnShadowSubsystemStop = _types.pfnShadowSubsystemStop
pfnShadowSubsystemUninit = _types.pfnShadowSubsystemUninit
pfnShadowSynchronizeEvent = _types.pfnShadowSynchronizeEvent
pfnShadowUnicodeKeyboardEvent = _types.pfnShadowUnicodeKeyboardEvent
rdpShadowCapture = _types.rdpShadowCapture
rdpShadowClient = _types.rdpShadowClient
rdpShadowEncoder = _types.rdpShadowEncoder
rdpShadowMultiClientEvent = _types.rdpShadowMultiClientEvent
rdpShadowScreen = _types.rdpShadowScreen
rdpShadowServer = _types.rdpShadowServer
rdpShadowSubsystem = _types.rdpShadowSubsystem
rdpShadowSurface = _types.rdpShadowSurface
struct_SHADOW_MSG_OUT_AUDIO_OUT_SAMPLES = _types.struct_SHADOW_MSG_OUT_AUDIO_OUT_SAMPLES
struct_SHADOW_MSG_OUT_AUDIO_OUT_VOLUME = _types.struct_SHADOW_MSG_OUT_AUDIO_OUT_VOLUME
struct_SHADOW_MSG_OUT_POINTER_ALPHA_UPDATE = _types.struct_SHADOW_MSG_OUT_POINTER_ALPHA_UPDATE
struct_SHADOW_MSG_OUT_POINTER_POSITION_UPDATE = _types.struct_SHADOW_MSG_OUT_POINTER_POSITION_UPDATE
struct_S_RDP_SHADOW_ENTRY_POINTS = _types.struct_S_RDP_SHADOW_ENTRY_POINTS
struct_S_SHADOW_MSG_OUT = _types.struct_S_SHADOW_MSG_OUT
struct_rdp_shadow_client = _types.struct_rdp_shadow_client
struct_rdp_shadow_server = _types.struct_rdp_shadow_server
struct_rdp_shadow_subsystem = _types.struct_rdp_shadow_subsystem
struct_rdp_shadow_surface = _types.struct_rdp_shadow_surface

# --- functions declared in this header ---
FUNCTIONS = (
    'shadow_capture_align_clip_rect',  # ctypes.c_int (ctypes.POINTER(RECTANGLE_16), ctypes.POINTER(RECTANGLE_16))
    'shadow_capture_compare',  # ctypes.c_int (ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, ctypes.POINTER(BYTE), UINT32, ctypes.POINTER(RECTANGLE_16))
    'shadow_capture_compare_with_format',  # ctypes.c_int (ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, UINT32, ctypes.POINTER(BYTE), UINT32, UINT32, ctypes.POINTER(RECTANGLE_16))
    'shadow_client_boardcast_msg',  # ctypes.c_int (ctypes.POINTER(rdpShadowServer), ctypes.c_void_p, UINT32, ctypes.POINTER(SHADOW_MSG_OUT), ctypes.c_void_p)
    'shadow_client_boardcast_quit',  # ctypes.c_int (ctypes.POINTER(rdpShadowServer), ctypes.c_int)
    'shadow_client_post_msg',  # BOOL (ctypes.POINTER(rdpShadowClient), ctypes.c_void_p, UINT32, ctypes.POINTER(SHADOW_MSG_OUT), ctypes.c_void_p)
    'shadow_encoder_inflight_frames',  # UINT32 (ctypes.POINTER(rdpShadowEncoder))
    'shadow_encoder_preferred_fps',  # UINT32 (ctypes.POINTER(rdpShadowEncoder))
    'shadow_enum_monitors',  # UINT32 (ctypes.POINTER(MONITOR_DEF), UINT32)
    'shadow_screen_resize',  # BOOL (ctypes.POINTER(rdpShadowScreen))
    'shadow_server_command_line_status_print',  # ctypes.c_int (ctypes.POINTER(rdpShadowServer), ctypes.c_int, ctypes.POINTER(ctypes.c_char_p), ctypes.c_int, ctypes.POINTER(COMMAND_LINE_ARGUMENT_A))
    'shadow_server_free',  # void (ctypes.POINTER(rdpShadowServer))
    'shadow_server_init',  # ctypes.c_int (ctypes.POINTER(rdpShadowServer))
    'shadow_server_new',  # ctypes.POINTER(rdpShadowServer) ()
    'shadow_server_parse_command_line',  # ctypes.c_int (ctypes.POINTER(rdpShadowServer), ctypes.c_int, ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(COMMAND_LINE_ARGUMENT_A))
    'shadow_server_start',  # ctypes.c_int (ctypes.POINTER(rdpShadowServer))
    'shadow_server_stop',  # ctypes.c_int (ctypes.POINTER(rdpShadowServer))
    'shadow_server_uninit',  # ctypes.c_int (ctypes.POINTER(rdpShadowServer))
    'shadow_subsystem_frame_update',  # void (ctypes.POINTER(rdpShadowSubsystem))
    'shadow_subsystem_pointer_convert_alpha_pointer_data',  # ctypes.c_int (ctypes.POINTER(BYTE), BOOL, UINT32, UINT32, ctypes.POINTER(SHADOW_MSG_OUT_POINTER_ALPHA_UPDATE))
    'shadow_subsystem_pointer_convert_alpha_pointer_data_to_format',  # ctypes.c_int (ctypes.POINTER(BYTE), UINT32, BOOL, UINT32, UINT32, ctypes.POINTER(SHADOW_MSG_OUT_POINTER_ALPHA_UPDATE))
    'shadow_subsystem_set_entry',  # void (pfnShadowSubsystemEntry)
    'shadow_subsystem_set_entry_builtin',  # void (ctypes.c_char_p)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'MSG_OUT_FREE_FN', 'RDP_SHADOW_ENTRY_POINTS', 'SHADOW_MSG_IN_REFRESH_REQUEST_ID', 'SHADOW_MSG_OUT', 'SHADOW_MSG_OUT_AUDIO_OUT_SAMPLES', 'SHADOW_MSG_OUT_AUDIO_OUT_SAMPLES_ID', 'SHADOW_MSG_OUT_AUDIO_OUT_VOLUME', 'SHADOW_MSG_OUT_AUDIO_OUT_VOLUME_ID', 'SHADOW_MSG_OUT_POINTER_ALPHA_UPDATE', 'SHADOW_MSG_OUT_POINTER_ALPHA_UPDATE_ID', 'SHADOW_MSG_OUT_POINTER_POSITION_UPDATE', 'SHADOW_MSG_OUT_POINTER_POSITION_UPDATE_ID', 'bind', 'pfnShadowAuthenticate', 'pfnShadowChannelAudinServerReceiveSamples', 'pfnShadowClientCapabilities', 'pfnShadowClientConnect', 'pfnShadowClientDisconnect', 'pfnShadowEnumMonitors', 'pfnShadowExtendedMouseEvent', 'pfnShadowKeyboardEvent', 'pfnShadowMouseEvent', 'pfnShadowRelMouseEvent', 'pfnShadowSubsystemEntry', 'pfnShadowSubsystemFree', 'pfnShadowSubsystemInit', 'pfnShadowSubsystemNew', 'pfnShadowSubsystemStart', 'pfnShadowSubsystemStop', 'pfnShadowSubsystemUninit', 'pfnShadowSynchronizeEvent', 'pfnShadowUnicodeKeyboardEvent', 'rdpShadowCapture', 'rdpShadowClient', 'rdpShadowEncoder', 'rdpShadowMultiClientEvent', 'rdpShadowScreen', 'rdpShadowServer', 'rdpShadowSubsystem', 'rdpShadowSurface', 'struct_SHADOW_MSG_OUT_AUDIO_OUT_SAMPLES', 'struct_SHADOW_MSG_OUT_AUDIO_OUT_VOLUME', 'struct_SHADOW_MSG_OUT_POINTER_ALPHA_UPDATE', 'struct_SHADOW_MSG_OUT_POINTER_POSITION_UPDATE', 'struct_S_RDP_SHADOW_ENTRY_POINTS', 'struct_S_SHADOW_MSG_OUT', 'struct_rdp_shadow_client', 'struct_rdp_shadow_server', 'struct_rdp_shadow_subsystem', 'struct_rdp_shadow_surface']
