"""
Mirror of <freerdp/server/telemetry.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
TelemetryServerContext = _types.TelemetryServerContext
psTelemetryServerChannelHandle = _types.psTelemetryServerChannelHandle
psTelemetryServerChannelIdAssigned = _types.psTelemetryServerChannelIdAssigned
psTelemetryServerClose = _types.psTelemetryServerClose
psTelemetryServerInitialize = _types.psTelemetryServerInitialize
psTelemetryServerOpen = _types.psTelemetryServerOpen
psTelemetryServerPoll = _types.psTelemetryServerPoll
psTelemetryServerRdpTelemetry = _types.psTelemetryServerRdpTelemetry
struct_s_telemetry_server_context = _types.struct_s_telemetry_server_context

# --- functions declared in this header ---
FUNCTIONS = (
    'telemetry_server_context_free',  # void (ctypes.POINTER(TelemetryServerContext))
    'telemetry_server_context_new',  # ctypes.POINTER(TelemetryServerContext) (HANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'TelemetryServerContext', 'bind', 'psTelemetryServerChannelHandle', 'psTelemetryServerChannelIdAssigned', 'psTelemetryServerClose', 'psTelemetryServerInitialize', 'psTelemetryServerOpen', 'psTelemetryServerPoll', 'psTelemetryServerRdpTelemetry', 'struct_s_telemetry_server_context']
