"""
Mirror of <freerdp/channels/ainput.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
AINPUT_CHANNEL_NAME = 'ainput'
AINPUT_DVC_CHANNEL_NAME = 'FreeRDP::Advanced::Input'
AINPUT_FLAGS_BUTTON1 = 0x1000
AINPUT_FLAGS_BUTTON2 = 0x2000
AINPUT_FLAGS_BUTTON3 = 0x4000
AINPUT_FLAGS_DOWN = 8
AINPUT_FLAGS_HAVE_REL = 0x20
AINPUT_FLAGS_MOVE = 4
AINPUT_FLAGS_REL = 0x10
AINPUT_FLAGS_WHEEL = 1
AINPUT_VERSION_MAJOR = 1
AINPUT_VERSION_MINOR = 0
AINPUT_XFLAGS_BUTTON1 = 0x100
AINPUT_XFLAGS_BUTTON2 = 0x200
MSG_AINPUT_MOUSE = 2
MSG_AINPUT_VERSION = 1

# --- types declared in this header ---
AInputClientContext = _types.AInputClientContext
AInputEventFlags = _types.AInputEventFlags
eAInputMsgType = _types.eAInputMsgType

__all__ = ['AINPUT_CHANNEL_NAME', 'AINPUT_DVC_CHANNEL_NAME', 'AINPUT_FLAGS_BUTTON1', 'AINPUT_FLAGS_BUTTON2', 'AINPUT_FLAGS_BUTTON3', 'AINPUT_FLAGS_DOWN', 'AINPUT_FLAGS_HAVE_REL', 'AINPUT_FLAGS_MOVE', 'AINPUT_FLAGS_REL', 'AINPUT_FLAGS_WHEEL', 'AINPUT_VERSION_MAJOR', 'AINPUT_VERSION_MINOR', 'AINPUT_XFLAGS_BUTTON1', 'AINPUT_XFLAGS_BUTTON2', 'AInputClientContext', 'AInputEventFlags', 'MSG_AINPUT_MOUSE', 'MSG_AINPUT_VERSION', 'eAInputMsgType']
