"""
Mirror of <freerdp/channels/channels.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
StaticClientChannelStat = _types.StaticClientChannelStat
StaticClientChannelStats = _types.StaticClientChannelStats
freerdp_channel_handle_fkt_t = _types.freerdp_channel_handle_fkt_t
struct_StaticClientChannelStat = _types.struct_StaticClientChannelStat
struct_StaticClientChannelStats = _types.struct_StaticClientChannelStats

# --- functions declared in this header ---
FUNCTIONS = (
    'FreeRDP_InitWtsApi',  # ctypes.POINTER(WtsApiFunctionTable) ()
    'freerdp_channel_client_stats_free',  # void (ctypes.POINTER(StaticClientChannelStats))
    'freerdp_channels_check_fds',  # BOOL (ctypes.POINTER(rdpChannels), ctypes.POINTER(freerdp))
    'freerdp_channels_client_load',  # ctypes.c_int (ctypes.POINTER(rdpChannels), ctypes.POINTER(rdpSettings), PVIRTUALCHANNELENTRY, ctypes.c_void_p)
    'freerdp_channels_client_load_ex',  # ctypes.c_int (ctypes.POINTER(rdpChannels), ctypes.POINTER(rdpSettings), PVIRTUALCHANNELENTRYEX, ctypes.c_void_p)
    'freerdp_channels_client_stats',  # ctypes.POINTER(StaticClientChannelStats) (ctypes.POINTER(rdpChannels))
    'freerdp_channels_data',  # BOOL (ctypes.POINTER(freerdp), UINT16, ctypes.POINTER(BYTE), ctypes.c_size_t, UINT32, ctypes.c_size_t)
    'freerdp_channels_get_event_handle',  # HANDLE (ctypes.POINTER(freerdp))
    'freerdp_channels_get_id_by_name',  # UINT16 (ctypes.POINTER(freerdp), ctypes.c_char_p)
    'freerdp_channels_get_name_by_id',  # ctypes.c_char_p (ctypes.POINTER(freerdp), UINT16)
    'freerdp_channels_get_static_channel_interface',  # ctypes.c_void_p (ctypes.POINTER(rdpChannels), ctypes.c_char_p)
    'freerdp_channels_load_plugin',  # ctypes.c_int (ctypes.POINTER(rdpChannels), ctypes.POINTER(rdpSettings), ctypes.c_char_p, ctypes.c_void_p)
    'freerdp_channels_process_pending_messages',  # ctypes.c_int (ctypes.POINTER(freerdp))
    'freerdp_client_channel_register',  # BOOL (ctypes.POINTER(rdpChannels), HANDLE, freerdp_channel_handle_fkt_t, ctypes.c_void_p)
    'freerdp_client_channel_unregister',  # BOOL (ctypes.POINTER(rdpChannels), HANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'StaticClientChannelStat', 'StaticClientChannelStats', 'bind', 'freerdp_channel_handle_fkt_t', 'struct_StaticClientChannelStat', 'struct_StaticClientChannelStats']
