"""
Mirror of <freerdp/channels/drdynvc.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
CAPABILITY_REQUEST_PDU = 5
CLOSE_REQUEST_PDU = 4
CREATE_REQUEST_PDU = 1
DATA_COMPRESSED_PDU = 7
DATA_FIRST_COMPRESSED_PDU = 6
DATA_FIRST_PDU = 2
DATA_PDU = 3
DRDYNVC_CHANNEL_NAME = 'drdynvc'
DRDYNVC_SVC_CHANNEL_NAME = 'drdynvc'
SOFT_SYNC_CHANNEL_LIST_PRESENT = 2
SOFT_SYNC_REQUEST_PDU = 8
SOFT_SYNC_RESPONSE_PDU = 9
SOFT_SYNC_TCP_FLUSHED = 1
TUNNELTYPE_UDPFECL = 3
TUNNELTYPE_UDPFECR = 1

# --- types declared in this header ---
DynamicChannelPDU = _types.DynamicChannelPDU

__all__ = ['CAPABILITY_REQUEST_PDU', 'CLOSE_REQUEST_PDU', 'CREATE_REQUEST_PDU', 'DATA_COMPRESSED_PDU', 'DATA_FIRST_COMPRESSED_PDU', 'DATA_FIRST_PDU', 'DATA_PDU', 'DRDYNVC_CHANNEL_NAME', 'DRDYNVC_SVC_CHANNEL_NAME', 'DynamicChannelPDU', 'SOFT_SYNC_CHANNEL_LIST_PRESENT', 'SOFT_SYNC_REQUEST_PDU', 'SOFT_SYNC_RESPONSE_PDU', 'SOFT_SYNC_TCP_FLUSHED', 'TUNNELTYPE_UDPFECL', 'TUNNELTYPE_UDPFECR']
