"""
Mirror of <freerdp/channels/echo.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

# --- #defines and enum members declared in this header ---
ECHO_CHANNEL_NAME = 'echo'
ECHO_DVC_CHANNEL_NAME = 'ECHO'

__all__ = ['ECHO_CHANNEL_NAME', 'ECHO_DVC_CHANNEL_NAME']
