"""
Mirror of <freerdp/channels/geometry.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
GEOMETRY_CHANNEL_NAME = 'geometry'
GEOMETRY_CLEAR = 2
GEOMETRY_DVC_CHANNEL_NAME = 'Microsoft::Windows::RDS::Geometry::v08.01'
GEOMETRY_UPDATE = 1
RDH_RECTANGLE = 1

# --- types declared in this header ---
FREERDP_RGNDATA = _types.FREERDP_RGNDATA
MAPPED_GEOMETRY_PACKET = _types.MAPPED_GEOMETRY_PACKET
struct_FREERDP_RGNDATA = _types.struct_FREERDP_RGNDATA
struct_MAPPED_GEOMETRY_PACKET = _types.struct_MAPPED_GEOMETRY_PACKET

__all__ = ['FREERDP_RGNDATA', 'GEOMETRY_CHANNEL_NAME', 'GEOMETRY_CLEAR', 'GEOMETRY_DVC_CHANNEL_NAME', 'GEOMETRY_UPDATE', 'MAPPED_GEOMETRY_PACKET', 'RDH_RECTANGLE', 'struct_FREERDP_RGNDATA', 'struct_MAPPED_GEOMETRY_PACKET']
