"""
Mirror of <freerdp/channels/rdp2tcp.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

# --- #defines and enum members declared in this header ---
RDP2TCP_DVC_CHANNEL_NAME = 'rdp2tcp'

__all__ = ['RDP2TCP_DVC_CHANNEL_NAME']
