"""
Mirror of <freerdp/channels/rdpear.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

# --- #defines and enum members declared in this header ---
RDPEAR_CHANNEL_NAME = 'rdpear'
RDPEAR_DVC_CHANNEL_NAME = 'Microsoft::Windows::RDS::AuthRedirection'

__all__ = ['RDPEAR_CHANNEL_NAME', 'RDPEAR_DVC_CHANNEL_NAME']
