"""
Mirror of <freerdp/channels/rdpewa.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

# --- #defines and enum members declared in this header ---
RDPEWA_CHANNEL_NAME = 'rdpewa'
RDPEWA_DVC_CHANNEL_NAME = 'WebAuthN_Channel'

__all__ = ['RDPEWA_CHANNEL_NAME', 'RDPEWA_DVC_CHANNEL_NAME']
