"""
Mirror of <freerdp/channels/rdpsnd.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

# --- #defines and enum members declared in this header ---
RDPSND_CHANNEL_NAME = 'rdpsnd'
RDPSND_DVC_CHANNEL_NAME = 'AUDIO_PLAYBACK_DVC'
RDPSND_LOSSY_DVC_CHANNEL_NAME = 'AUDIO_PLAYBACK_LOSSY_DVC'

__all__ = ['RDPSND_CHANNEL_NAME', 'RDPSND_DVC_CHANNEL_NAME', 'RDPSND_LOSSY_DVC_CHANNEL_NAME']
