"""
Mirror of <freerdp/channels/telemetry.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
TELEMETRY_CHANNEL_NAME = 'telemetry'
TELEMETRY_DVC_CHANNEL_NAME = 'Microsoft::Windows::RDS::Telemetry'

# --- types declared in this header ---
TELEMETRY_RDP_TELEMETRY_PDU = _types.TELEMETRY_RDP_TELEMETRY_PDU
struct_TELEMETRY_RDP_TELEMETRY_PDU = _types.struct_TELEMETRY_RDP_TELEMETRY_PDU

__all__ = ['TELEMETRY_CHANNEL_NAME', 'TELEMETRY_DVC_CHANNEL_NAME', 'TELEMETRY_RDP_TELEMETRY_PDU', 'struct_TELEMETRY_RDP_TELEMETRY_PDU']
