"""
Mirror of <freerdp/channels/tsmf.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

# --- #defines and enum members declared in this header ---
TSMF_CHANNEL_NAME = 'tsmf'
TSMF_DVC_CHANNEL_NAME = 'TSMF'

__all__ = ['TSMF_CHANNEL_NAME', 'TSMF_DVC_CHANNEL_NAME']
