"""
Mirror of <freerdp/channels/urbdrc.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

# --- #defines and enum members declared in this header ---
URBDRC_CHANNEL_NAME = 'urbdrc'
URBDRC_DVC_CHANNEL_NAME = 'urbdrc'

__all__ = ['URBDRC_CHANNEL_NAME', 'URBDRC_DVC_CHANNEL_NAME']
