"""
Mirror of <freerdp/channels/wtsvc.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
DRDYNVC_STATE_FAILED = 3
DRDYNVC_STATE_INITIALIZED = 1
DRDYNVC_STATE_NONE = 0
DRDYNVC_STATE_READY = 2

# --- types declared in this header ---
psDVCCreationStatusCallback = _types.psDVCCreationStatusCallback

# --- functions declared in this header ---
FUNCTIONS = (
    'WTSChannelGetHandleById',  # ctypes.c_void_p (ctypes.POINTER(freerdp_peer), UINT16)
    'WTSChannelGetHandleByName',  # ctypes.c_void_p (ctypes.POINTER(freerdp_peer), ctypes.c_char_p)
    'WTSChannelGetId',  # UINT16 (ctypes.POINTER(freerdp_peer), ctypes.c_char_p)
    'WTSChannelGetIdByHandle',  # UINT32 (HANDLE)
    'WTSChannelGetName',  # ctypes.c_char_p (ctypes.POINTER(freerdp_peer), UINT16)
    'WTSChannelGetOptions',  # INT64 (ctypes.POINTER(freerdp_peer), UINT16)
    'WTSChannelSetHandleById',  # BOOL (ctypes.POINTER(freerdp_peer), UINT16, ctypes.c_void_p)
    'WTSChannelSetHandleByName',  # BOOL (ctypes.POINTER(freerdp_peer), ctypes.c_char_p, ctypes.c_void_p)
    'WTSGetAcceptedChannelNames',  # ctypes.POINTER(ctypes.c_char_p) (ctypes.POINTER(freerdp_peer), ctypes.POINTER(ctypes.c_size_t))
    'WTSIsChannelJoinedById',  # BOOL (ctypes.POINTER(freerdp_peer), UINT16)
    'WTSIsChannelJoinedByName',  # BOOL (ctypes.POINTER(freerdp_peer), ctypes.c_char_p)
    'WTSVirtualChannelManagerCheckFileDescriptor',  # BOOL (HANDLE)
    'WTSVirtualChannelManagerCheckFileDescriptorEx',  # BOOL (HANDLE, BOOL)
    'WTSVirtualChannelManagerGetDrdynvcState',  # BYTE (HANDLE)
    'WTSVirtualChannelManagerGetEventHandle',  # HANDLE (HANDLE)
    'WTSVirtualChannelManagerIsChannelJoined',  # BOOL (HANDLE, ctypes.c_char_p)
    'WTSVirtualChannelManagerOpen',  # BOOL (HANDLE)
    'WTSVirtualChannelManagerSetDVCCreationCallback',  # void (HANDLE, psDVCCreationStatusCallback, ctypes.c_void_p)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['DRDYNVC_STATE_FAILED', 'DRDYNVC_STATE_INITIALIZED', 'DRDYNVC_STATE_NONE', 'DRDYNVC_STATE_READY', 'FUNCTIONS', 'bind', 'psDVCCreationStatusCallback']
