"""
Mirror of <freerdp/cache/persistent.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
PERSISTENT_CACHE_ENTRY = _types.PERSISTENT_CACHE_ENTRY
PERSISTENT_CACHE_ENTRY_V2 = _types.PERSISTENT_CACHE_ENTRY_V2
PERSISTENT_CACHE_ENTRY_V3 = _types.PERSISTENT_CACHE_ENTRY_V3
PERSISTENT_CACHE_HEADER_V3 = _types.PERSISTENT_CACHE_HEADER_V3
rdpPersistentCache = _types.rdpPersistentCache
struct_PERSISTENT_CACHE_ENTRY = _types.struct_PERSISTENT_CACHE_ENTRY
struct_PERSISTENT_CACHE_ENTRY_V2 = _types.struct_PERSISTENT_CACHE_ENTRY_V2
struct_PERSISTENT_CACHE_ENTRY_V3 = _types.struct_PERSISTENT_CACHE_ENTRY_V3
struct_PERSISTENT_CACHE_HEADER_V3 = _types.struct_PERSISTENT_CACHE_HEADER_V3

# --- functions declared in this header ---
FUNCTIONS = (
    'persistent_cache_close',  # ctypes.c_int (ctypes.POINTER(rdpPersistentCache))
    'persistent_cache_free',  # void (ctypes.POINTER(rdpPersistentCache))
    'persistent_cache_get_count',  # ctypes.c_int (ctypes.POINTER(rdpPersistentCache))
    'persistent_cache_get_version',  # ctypes.c_int (ctypes.POINTER(rdpPersistentCache))
    'persistent_cache_new',  # ctypes.POINTER(rdpPersistentCache) ()
    'persistent_cache_open',  # ctypes.c_int (ctypes.POINTER(rdpPersistentCache), ctypes.c_char_p, BOOL, UINT32)
    'persistent_cache_read_entry',  # ctypes.c_int (ctypes.POINTER(rdpPersistentCache), ctypes.POINTER(PERSISTENT_CACHE_ENTRY))
    'persistent_cache_write_entry',  # ctypes.c_int (ctypes.POINTER(rdpPersistentCache), ctypes.POINTER(PERSISTENT_CACHE_ENTRY))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'PERSISTENT_CACHE_ENTRY', 'PERSISTENT_CACHE_ENTRY_V2', 'PERSISTENT_CACHE_ENTRY_V3', 'PERSISTENT_CACHE_HEADER_V3', 'bind', 'rdpPersistentCache', 'struct_PERSISTENT_CACHE_ENTRY', 'struct_PERSISTENT_CACHE_ENTRY_V2', 'struct_PERSISTENT_CACHE_ENTRY_V3', 'struct_PERSISTENT_CACHE_HEADER_V3']
