"""
Mirror of <winpr/asn1.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
ER_TAG_APP = 0x60
ER_TAG_BIT_STRING = 3
ER_TAG_BOOLEAN = 1
ER_TAG_CONTEXTUAL = 0xa0
ER_TAG_ENUMERATED = 0xa
ER_TAG_GENERALIZED_TIME = 0x18
ER_TAG_GENERAL_STRING = 0x1b
ER_TAG_IA5STRING = 0x16
ER_TAG_INTEGER = 2
ER_TAG_NULL = 5
ER_TAG_OBJECT_IDENTIFIER = 6
ER_TAG_OCTET_STRING = 4
ER_TAG_PRINTABLE_STRING = 0x13
ER_TAG_SEQUENCE = 0x30
ER_TAG_SEQUENCE_OF = 0x30
ER_TAG_SET = 0x31
ER_TAG_SET_OF = 0x31
ER_TAG_UTCTIME = 0x17
ER_TAG_UTF8STRING = 0xc
WINPR_ASN1_BER = 0
WINPR_ASN1_DER = 1

# --- types declared in this header ---
WinPrAsn1Decoder = _types.WinPrAsn1Decoder
WinPrAsn1Encoder = _types.WinPrAsn1Encoder
WinPrAsn1EncodingRule = _types.WinPrAsn1EncodingRule
WinPrAsn1_BOOL = _types.WinPrAsn1_BOOL
WinPrAsn1_ENUMERATED = _types.WinPrAsn1_ENUMERATED
WinPrAsn1_IA5STRING = _types.WinPrAsn1_IA5STRING
WinPrAsn1_INTEGER = _types.WinPrAsn1_INTEGER
WinPrAsn1_MemoryChunk = _types.WinPrAsn1_MemoryChunk
WinPrAsn1_OID = _types.WinPrAsn1_OID
WinPrAsn1_OctetString = _types.WinPrAsn1_OctetString
WinPrAsn1_STRING = _types.WinPrAsn1_STRING
WinPrAsn1_UTCTIME = _types.WinPrAsn1_UTCTIME
WinPrAsn1_tag = _types.WinPrAsn1_tag
WinPrAsn1_tagId = _types.WinPrAsn1_tagId
struct_WinPrAsn1Decoder = _types.struct_WinPrAsn1Decoder
struct_WinPrAsn1_MemoryChunk = _types.struct_WinPrAsn1_MemoryChunk
struct_WinPrAsn1_UTCTIME = _types.struct_WinPrAsn1_UTCTIME

# --- functions declared in this header ---
FUNCTIONS = (
    'WinPrAsn1DecGetStream',  # wStream (ctypes.POINTER(WinPrAsn1Decoder))
    'WinPrAsn1DecPeekContextualTag',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_tagId), ctypes.POINTER(WinPrAsn1Decoder))
    'WinPrAsn1DecPeekTag',  # BOOL (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_tag))
    'WinPrAsn1DecPeekTagAndLen',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_tag), ctypes.POINTER(ctypes.c_size_t))
    'WinPrAsn1DecReadApp',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_tagId), ctypes.POINTER(WinPrAsn1Decoder))
    'WinPrAsn1DecReadBoolean',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_BOOL))
    'WinPrAsn1DecReadContextualBool',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), WinPrAsn1_tagId, ctypes.POINTER(BOOL), ctypes.POINTER(WinPrAsn1_BOOL))
    'WinPrAsn1DecReadContextualInteger',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), WinPrAsn1_tagId, ctypes.POINTER(BOOL), ctypes.POINTER(WinPrAsn1_INTEGER))
    'WinPrAsn1DecReadContextualOID',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), WinPrAsn1_tagId, ctypes.POINTER(BOOL), ctypes.POINTER(WinPrAsn1_OID), BOOL)
    'WinPrAsn1DecReadContextualOctetString',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), WinPrAsn1_tagId, ctypes.POINTER(BOOL), ctypes.POINTER(WinPrAsn1_OctetString), BOOL)
    'WinPrAsn1DecReadContextualSequence',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), WinPrAsn1_tagId, ctypes.POINTER(BOOL), ctypes.POINTER(WinPrAsn1Decoder))
    'WinPrAsn1DecReadContextualTag',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_tagId), ctypes.POINTER(WinPrAsn1Decoder))
    'WinPrAsn1DecReadEnumerated',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_ENUMERATED))
    'WinPrAsn1DecReadGeneralString',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_STRING))
    'WinPrAsn1DecReadIA5String',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_IA5STRING))
    'WinPrAsn1DecReadInteger',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_INTEGER))
    'WinPrAsn1DecReadNull',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder))
    'WinPrAsn1DecReadOID',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_OID), BOOL)
    'WinPrAsn1DecReadOctetString',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_OctetString), BOOL)
    'WinPrAsn1DecReadSequence',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1Decoder))
    'WinPrAsn1DecReadSet',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1Decoder))
    'WinPrAsn1DecReadTagAndLen',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_tag), ctypes.POINTER(ctypes.c_size_t))
    'WinPrAsn1DecReadTagLenValue',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_tag), ctypes.POINTER(ctypes.c_size_t), ctypes.POINTER(WinPrAsn1Decoder))
    'WinPrAsn1DecReadUtcTime',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Decoder), ctypes.POINTER(WinPrAsn1_UTCTIME))
    'WinPrAsn1Decoder_Init',  # void (ctypes.POINTER(WinPrAsn1Decoder), WinPrAsn1EncodingRule, ctypes.POINTER(wStream))
    'WinPrAsn1Decoder_InitMem',  # void (ctypes.POINTER(WinPrAsn1Decoder), WinPrAsn1EncodingRule, ctypes.POINTER(BYTE), ctypes.c_size_t)
    'WinPrAsn1EncAppContainer',  # BOOL (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_tagId)
    'WinPrAsn1EncBoolean',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_BOOL)
    'WinPrAsn1EncContextualBoolean',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_tagId, WinPrAsn1_BOOL)
    'WinPrAsn1EncContextualContainer',  # BOOL (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_tagId)
    'WinPrAsn1EncContextualEnumerated',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_tagId, WinPrAsn1_ENUMERATED)
    'WinPrAsn1EncContextualIA5String',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_tagId, WinPrAsn1_IA5STRING)
    'WinPrAsn1EncContextualInteger',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_tagId, WinPrAsn1_INTEGER)
    'WinPrAsn1EncContextualOID',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_tagId, ctypes.POINTER(WinPrAsn1_OID))
    'WinPrAsn1EncContextualOctetString',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_tagId, ctypes.POINTER(WinPrAsn1_OctetString))
    'WinPrAsn1EncContextualOctetStringContainer',  # BOOL (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_tagId)
    'WinPrAsn1EncContextualRawContent',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_tagId, ctypes.POINTER(WinPrAsn1_MemoryChunk))
    'WinPrAsn1EncContextualSeqContainer',  # BOOL (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_tagId)
    'WinPrAsn1EncContextualSetContainer',  # BOOL (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_tagId)
    'WinPrAsn1EncContextualUtcTime',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_tagId, ctypes.POINTER(WinPrAsn1_UTCTIME))
    'WinPrAsn1EncEndContainer',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder))
    'WinPrAsn1EncEnumerated',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_ENUMERATED)
    'WinPrAsn1EncGeneralString',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_STRING)
    'WinPrAsn1EncIA5String',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_IA5STRING)
    'WinPrAsn1EncInteger',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), WinPrAsn1_INTEGER)
    'WinPrAsn1EncOID',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), ctypes.POINTER(WinPrAsn1_OID))
    'WinPrAsn1EncOctetString',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), ctypes.POINTER(WinPrAsn1_OctetString))
    'WinPrAsn1EncOctetStringContainer',  # BOOL (ctypes.POINTER(WinPrAsn1Encoder))
    'WinPrAsn1EncRawContent',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), ctypes.POINTER(WinPrAsn1_MemoryChunk))
    'WinPrAsn1EncSeqContainer',  # BOOL (ctypes.POINTER(WinPrAsn1Encoder))
    'WinPrAsn1EncSetContainer',  # BOOL (ctypes.POINTER(WinPrAsn1Encoder))
    'WinPrAsn1EncStreamSize',  # BOOL (ctypes.POINTER(WinPrAsn1Encoder), ctypes.POINTER(ctypes.c_size_t))
    'WinPrAsn1EncToStream',  # BOOL (ctypes.POINTER(WinPrAsn1Encoder), ctypes.POINTER(wStream))
    'WinPrAsn1EncUtcTime',  # ctypes.c_size_t (ctypes.POINTER(WinPrAsn1Encoder), ctypes.POINTER(WinPrAsn1_UTCTIME))
    'WinPrAsn1Encoder_Free',  # void (ctypes.POINTER(ctypes.POINTER(WinPrAsn1Encoder)))
    'WinPrAsn1Encoder_FreeNoNull',  # void (ctypes.POINTER(WinPrAsn1Encoder))
    'WinPrAsn1Encoder_New',  # ctypes.POINTER(WinPrAsn1Encoder) (WinPrAsn1EncodingRule)
    'WinPrAsn1Encoder_Reset',  # void (ctypes.POINTER(WinPrAsn1Encoder))
    'WinPrAsn1FreeOID',  # void (ctypes.POINTER(WinPrAsn1_OID))
    'WinPrAsn1FreeOctetString',  # void (ctypes.POINTER(WinPrAsn1_OctetString))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['ER_TAG_APP', 'ER_TAG_BIT_STRING', 'ER_TAG_BOOLEAN', 'ER_TAG_CONTEXTUAL', 'ER_TAG_ENUMERATED', 'ER_TAG_GENERALIZED_TIME', 'ER_TAG_GENERAL_STRING', 'ER_TAG_IA5STRING', 'ER_TAG_INTEGER', 'ER_TAG_NULL', 'ER_TAG_OBJECT_IDENTIFIER', 'ER_TAG_OCTET_STRING', 'ER_TAG_PRINTABLE_STRING', 'ER_TAG_SEQUENCE', 'ER_TAG_SEQUENCE_OF', 'ER_TAG_SET', 'ER_TAG_SET_OF', 'ER_TAG_UTCTIME', 'ER_TAG_UTF8STRING', 'FUNCTIONS', 'WINPR_ASN1_BER', 'WINPR_ASN1_DER', 'WinPrAsn1Decoder', 'WinPrAsn1Encoder', 'WinPrAsn1EncodingRule', 'WinPrAsn1_BOOL', 'WinPrAsn1_ENUMERATED', 'WinPrAsn1_IA5STRING', 'WinPrAsn1_INTEGER', 'WinPrAsn1_MemoryChunk', 'WinPrAsn1_OID', 'WinPrAsn1_OctetString', 'WinPrAsn1_STRING', 'WinPrAsn1_UTCTIME', 'WinPrAsn1_tag', 'WinPrAsn1_tagId', 'bind', 'struct_WinPrAsn1Decoder', 'struct_WinPrAsn1_MemoryChunk', 'struct_WinPrAsn1_UTCTIME']
