"""
Mirror of <winpr/bitstream.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
BITDUMP_MSB_FIRST = 1
BITDUMP_STDERR = 2

# --- types declared in this header ---
struct_wBitStream = _types.struct_wBitStream
wBitStream = _types.wBitStream

# --- functions declared in this header ---
FUNCTIONS = (
    'BitDump',  # void (ctypes.c_char_p, UINT32, ctypes.POINTER(BYTE), UINT32, UINT32)
    'BitStream_Attach',  # void (ctypes.POINTER(wBitStream), ctypes.POINTER(BYTE), UINT32)
    'BitStream_Free',  # void (ctypes.POINTER(wBitStream))
    'BitStream_New',  # ctypes.POINTER(wBitStream) ()
    'ReverseBits32',  # UINT32 (UINT32, UINT32)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['BITDUMP_MSB_FIRST', 'BITDUMP_STDERR', 'FUNCTIONS', 'bind', 'struct_wBitStream', 'wBitStream']
