"""
Mirror of <winpr/buildflags.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

# --- #defines and enum members declared in this header ---
WINPR_BUILD_CONFIG = ''
WINPR_BUILD_TYPE = 'Release'
WINPR_CFLAGS = ' -fvisibility=hidden -fno-omit-frame-pointer -Wredundant-decls -fsigned-char -Wimplicit-function-declaration -Wno-jump-misses-init -fvisibility=hidden -O3 -DNDEBUG'
WINPR_COMPILER_ID = 'GNU'
WINPR_COMPILER_VERSION = '13.3.0'
WINPR_TARGET_ARCH = 'x64'

__all__ = ['WINPR_BUILD_CONFIG', 'WINPR_BUILD_TYPE', 'WINPR_CFLAGS', 'WINPR_COMPILER_ID', 'WINPR_COMPILER_VERSION', 'WINPR_TARGET_ARCH']
