"""
Mirror of <winpr/cast.h> (FreeRDP 3.32.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

# --- #defines and enum members declared in this header ---
WINPR_ARCH_SUPPORTED = 1

__all__ = ['WINPR_ARCH_SUPPORTED']
