"""
Mirror of <winpr/clipboard.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
CLIPBOARD_SYNTHESIZE_FN = _types.CLIPBOARD_SYNTHESIZE_FN
struct_s_wClipboardDelegate = _types.struct_s_wClipboardDelegate
struct_wClipboardFileRangeRequest = _types.struct_wClipboardFileRangeRequest
struct_wClipboardFileSizeRequest = _types.struct_wClipboardFileSizeRequest
wClipboard = _types.wClipboard
wClipboardDelegate = _types.wClipboardDelegate
wClipboardFileRangeRequest = _types.wClipboardFileRangeRequest
wClipboardFileSizeRequest = _types.wClipboardFileSizeRequest

# --- functions declared in this header ---
FUNCTIONS = (
    'ClipboardCountFormats',  # UINT32 (ctypes.POINTER(wClipboard))
    'ClipboardCountRegisteredFormats',  # UINT32 (ctypes.POINTER(wClipboard))
    'ClipboardCreate',  # ctypes.POINTER(wClipboard) ()
    'ClipboardDestroy',  # void (ctypes.POINTER(wClipboard))
    'ClipboardEmpty',  # BOOL (ctypes.POINTER(wClipboard))
    'ClipboardGetData',  # ctypes.c_void_p (ctypes.POINTER(wClipboard), UINT32, ctypes.POINTER(UINT32))
    'ClipboardGetDelegate',  # ctypes.POINTER(wClipboardDelegate) (ctypes.POINTER(wClipboard))
    'ClipboardGetFormatId',  # UINT32 (ctypes.POINTER(wClipboard), ctypes.c_char_p)
    'ClipboardGetFormatIdString',  # ctypes.c_char_p (UINT32)
    'ClipboardGetFormatIds',  # UINT32 (ctypes.POINTER(wClipboard), ctypes.POINTER(ctypes.POINTER(UINT32)))
    'ClipboardGetFormatName',  # ctypes.c_char_p (ctypes.POINTER(wClipboard), UINT32)
    'ClipboardGetOwner',  # UINT64 (ctypes.POINTER(wClipboard))
    'ClipboardGetRegisteredFormatIds',  # UINT32 (ctypes.POINTER(wClipboard), ctypes.POINTER(ctypes.POINTER(UINT32)))
    'ClipboardLock',  # void (ctypes.POINTER(wClipboard))
    'ClipboardRegisterFormat',  # UINT32 (ctypes.POINTER(wClipboard), ctypes.c_char_p)
    'ClipboardRegisterSynthesizer',  # BOOL (ctypes.POINTER(wClipboard), UINT32, UINT32, CLIPBOARD_SYNTHESIZE_FN)
    'ClipboardSetData',  # BOOL (ctypes.POINTER(wClipboard), UINT32, ctypes.c_void_p, UINT32)
    'ClipboardSetOwner',  # void (ctypes.POINTER(wClipboard), UINT64)
    'ClipboardUnlock',  # void (ctypes.POINTER(wClipboard))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['CLIPBOARD_SYNTHESIZE_FN', 'FUNCTIONS', 'bind', 'struct_s_wClipboardDelegate', 'struct_wClipboardFileRangeRequest', 'struct_wClipboardFileSizeRequest', 'wClipboard', 'wClipboardDelegate', 'wClipboardFileRangeRequest', 'wClipboardFileSizeRequest']
