"""
Mirror of <winpr/collections.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
MAX_EVENT_HANDLERS = 0x20
WMQ_QUIT = 0xffffffff

# --- types declared in this header ---
ArrayList_ForEachFkt = _types.ArrayList_ForEachFkt
HASH_TABLE_FOREACH_FN = _types.HASH_TABLE_FOREACH_FN
HASH_TABLE_HASH_FN = _types.HASH_TABLE_HASH_FN
MESSAGE_FREE_FN = _types.MESSAGE_FREE_FN
OBJECT_EQUALS_FN = _types.OBJECT_EQUALS_FN
OBJECT_FREE_FN = _types.OBJECT_FREE_FN
OBJECT_INIT_FN = _types.OBJECT_INIT_FN
OBJECT_NEW_FN = _types.OBJECT_NEW_FN
OBJECT_UNINIT_FN = _types.OBJECT_UNINIT_FN
pEventHandler = _types.pEventHandler
struct_s_wMessage = _types.struct_s_wMessage
struct_wEventArgs = _types.struct_wEventArgs
struct_wEventType = _types.struct_wEventType
struct_wMessagePipe = _types.struct_wMessagePipe
struct_wObject = _types.struct_wObject
wArrayList = _types.wArrayList
wBufferPool = _types.wBufferPool
wCountdownEvent = _types.wCountdownEvent
wEventArgs = _types.wEventArgs
wEventType = _types.wEventType
wHashTable = _types.wHashTable
wLinkedList = _types.wLinkedList
wListDictionary = _types.wListDictionary
wMessage = _types.wMessage
wMessagePipe = _types.wMessagePipe
wMessageQueue = _types.wMessageQueue
wObject = _types.wObject
wObjectPool = _types.wObjectPool
wPubSub = _types.wPubSub
wQueue = _types.wQueue
wStack = _types.wStack

# --- functions declared in this header ---
FUNCTIONS = (
    'ArrayList_Append',  # BOOL (ctypes.POINTER(wArrayList), ctypes.c_void_p)
    'ArrayList_Capacity',  # ctypes.c_size_t (ctypes.POINTER(wArrayList))
    'ArrayList_Clear',  # void (ctypes.POINTER(wArrayList))
    'ArrayList_Contains',  # BOOL (ctypes.POINTER(wArrayList), ctypes.c_void_p)
    'ArrayList_Count',  # ctypes.c_size_t (ctypes.POINTER(wArrayList))
    'ArrayList_ForEach',  # BOOL (ctypes.POINTER(wArrayList), ArrayList_ForEachFkt, ...)
    'ArrayList_ForEachAP',  # BOOL (ctypes.POINTER(wArrayList), ArrayList_ForEachFkt, ctypes.c_void_p)
    'ArrayList_Free',  # void (ctypes.POINTER(wArrayList))
    'ArrayList_GetItem',  # ctypes.c_void_p (ctypes.POINTER(wArrayList), ctypes.c_size_t)
    'ArrayList_IndexOf',  # SSIZE_T (ctypes.POINTER(wArrayList), ctypes.c_void_p, SSIZE_T, SSIZE_T)
    'ArrayList_Insert',  # BOOL (ctypes.POINTER(wArrayList), ctypes.c_size_t, ctypes.c_void_p)
    'ArrayList_IsFixedSized',  # BOOL (ctypes.POINTER(wArrayList))
    'ArrayList_IsReadOnly',  # BOOL (ctypes.POINTER(wArrayList))
    'ArrayList_IsSynchronized',  # BOOL (ctypes.POINTER(wArrayList))
    'ArrayList_Items',  # ctypes.c_size_t (ctypes.POINTER(wArrayList), ctypes.POINTER(ctypes.POINTER(ULONG_PTR)))
    'ArrayList_LastIndexOf',  # SSIZE_T (ctypes.POINTER(wArrayList), ctypes.c_void_p, SSIZE_T, SSIZE_T)
    'ArrayList_Lock',  # void (ctypes.POINTER(wArrayList))
    'ArrayList_New',  # ctypes.POINTER(wArrayList) (BOOL)
    'ArrayList_Object',  # ctypes.POINTER(wObject) (ctypes.POINTER(wArrayList))
    'ArrayList_Remove',  # BOOL (ctypes.POINTER(wArrayList), ctypes.c_void_p)
    'ArrayList_RemoveAt',  # BOOL (ctypes.POINTER(wArrayList), ctypes.c_size_t)
    'ArrayList_SetItem',  # BOOL (ctypes.POINTER(wArrayList), ctypes.c_size_t, ctypes.c_void_p)
    'ArrayList_Unlock',  # void (ctypes.POINTER(wArrayList))
    'BufferPool_Clear',  # void (ctypes.POINTER(wBufferPool))
    'BufferPool_Free',  # void (ctypes.POINTER(wBufferPool))
    'BufferPool_GetBufferSize',  # SSIZE_T (ctypes.POINTER(wBufferPool), ctypes.c_void_p)
    'BufferPool_GetPoolSize',  # SSIZE_T (ctypes.POINTER(wBufferPool))
    'BufferPool_New',  # ctypes.POINTER(wBufferPool) (BOOL, SSIZE_T, DWORD)
    'BufferPool_Return',  # BOOL (ctypes.POINTER(wBufferPool), ctypes.c_void_p)
    'BufferPool_Take',  # ctypes.c_void_p (ctypes.POINTER(wBufferPool), SSIZE_T)
    'CountdownEvent_AddCount',  # void (ctypes.POINTER(wCountdownEvent), ctypes.c_size_t)
    'CountdownEvent_CurrentCount',  # ctypes.c_size_t (ctypes.POINTER(wCountdownEvent))
    'CountdownEvent_Free',  # void (ctypes.POINTER(wCountdownEvent))
    'CountdownEvent_InitialCount',  # ctypes.c_size_t (ctypes.POINTER(wCountdownEvent))
    'CountdownEvent_IsSet',  # BOOL (ctypes.POINTER(wCountdownEvent))
    'CountdownEvent_New',  # ctypes.POINTER(wCountdownEvent) (ctypes.c_size_t)
    'CountdownEvent_Reset',  # void (ctypes.POINTER(wCountdownEvent), ctypes.c_size_t)
    'CountdownEvent_Signal',  # BOOL (ctypes.POINTER(wCountdownEvent), ctypes.c_size_t)
    'CountdownEvent_WaitHandle',  # HANDLE (ctypes.POINTER(wCountdownEvent))
    'HashTable_Clear',  # void (ctypes.POINTER(wHashTable))
    'HashTable_Contains',  # BOOL (ctypes.POINTER(wHashTable), ctypes.c_void_p)
    'HashTable_ContainsKey',  # BOOL (ctypes.POINTER(wHashTable), ctypes.c_void_p)
    'HashTable_ContainsValue',  # BOOL (ctypes.POINTER(wHashTable), ctypes.c_void_p)
    'HashTable_Count',  # ctypes.c_size_t (ctypes.POINTER(wHashTable))
    'HashTable_Foreach',  # BOOL (ctypes.POINTER(wHashTable), HASH_TABLE_FOREACH_FN, ctypes.c_void_p)
    'HashTable_Free',  # void (ctypes.POINTER(wHashTable))
    'HashTable_GetItemValue',  # ctypes.c_void_p (ctypes.POINTER(wHashTable), ctypes.c_void_p)
    'HashTable_GetKeys',  # ctypes.c_size_t (ctypes.POINTER(wHashTable), ctypes.POINTER(ctypes.POINTER(ULONG_PTR)))
    'HashTable_Insert',  # BOOL (ctypes.POINTER(wHashTable), ctypes.c_void_p, ctypes.c_void_p)
    'HashTable_KeyObject',  # ctypes.POINTER(wObject) (ctypes.POINTER(wHashTable))
    'HashTable_Lock',  # void (ctypes.POINTER(wHashTable))
    'HashTable_New',  # ctypes.POINTER(wHashTable) (BOOL)
    'HashTable_PointerCompare',  # BOOL (ctypes.c_void_p, ctypes.c_void_p)
    'HashTable_PointerHash',  # UINT32 (ctypes.c_void_p)
    'HashTable_Remove',  # BOOL (ctypes.POINTER(wHashTable), ctypes.c_void_p)
    'HashTable_SetHashFunction',  # BOOL (ctypes.POINTER(wHashTable), HASH_TABLE_HASH_FN)
    'HashTable_SetItemValue',  # BOOL (ctypes.POINTER(wHashTable), ctypes.c_void_p, ctypes.c_void_p)
    'HashTable_SetupForStringData',  # BOOL (ctypes.POINTER(wHashTable), BOOL)
    'HashTable_StringClone',  # ctypes.c_void_p (ctypes.c_void_p)
    'HashTable_StringCompare',  # BOOL (ctypes.c_void_p, ctypes.c_void_p)
    'HashTable_StringFree',  # void (ctypes.c_void_p)
    'HashTable_StringHash',  # UINT32 (ctypes.c_void_p)
    'HashTable_Unlock',  # void (ctypes.POINTER(wHashTable))
    'HashTable_ValueObject',  # ctypes.POINTER(wObject) (ctypes.POINTER(wHashTable))
    'LinkedList_AddFirst',  # BOOL (ctypes.POINTER(wLinkedList), ctypes.c_void_p)
    'LinkedList_AddLast',  # BOOL (ctypes.POINTER(wLinkedList), ctypes.c_void_p)
    'LinkedList_Clear',  # void (ctypes.POINTER(wLinkedList))
    'LinkedList_Contains',  # BOOL (ctypes.POINTER(wLinkedList), ctypes.c_void_p)
    'LinkedList_Count',  # ctypes.c_size_t (ctypes.POINTER(wLinkedList))
    'LinkedList_Enumerator_Current',  # ctypes.c_void_p (ctypes.POINTER(wLinkedList))
    'LinkedList_Enumerator_MoveNext',  # BOOL (ctypes.POINTER(wLinkedList))
    'LinkedList_Enumerator_Reset',  # void (ctypes.POINTER(wLinkedList))
    'LinkedList_First',  # ctypes.c_void_p (ctypes.POINTER(wLinkedList))
    'LinkedList_Free',  # void (ctypes.POINTER(wLinkedList))
    'LinkedList_Last',  # ctypes.c_void_p (ctypes.POINTER(wLinkedList))
    'LinkedList_New',  # ctypes.POINTER(wLinkedList) ()
    'LinkedList_Object',  # ctypes.POINTER(wObject) (ctypes.POINTER(wLinkedList))
    'LinkedList_Remove',  # BOOL (ctypes.POINTER(wLinkedList), ctypes.c_void_p)
    'LinkedList_RemoveFirst',  # void (ctypes.POINTER(wLinkedList))
    'LinkedList_RemoveLast',  # void (ctypes.POINTER(wLinkedList))
    'ListDictionary_Add',  # BOOL (ctypes.POINTER(wListDictionary), ctypes.c_void_p, ctypes.c_void_p)
    'ListDictionary_Clear',  # void (ctypes.POINTER(wListDictionary))
    'ListDictionary_Contains',  # BOOL (ctypes.POINTER(wListDictionary), ctypes.c_void_p)
    'ListDictionary_Count',  # ctypes.c_size_t (ctypes.POINTER(wListDictionary))
    'ListDictionary_Free',  # void (ctypes.POINTER(wListDictionary))
    'ListDictionary_GetItemValue',  # ctypes.c_void_p (ctypes.POINTER(wListDictionary), ctypes.c_void_p)
    'ListDictionary_GetKeys',  # ctypes.c_size_t (ctypes.POINTER(wListDictionary), ctypes.POINTER(ctypes.POINTER(ULONG_PTR)))
    'ListDictionary_KeyObject',  # ctypes.POINTER(wObject) (ctypes.POINTER(wListDictionary))
    'ListDictionary_Lock',  # void (ctypes.POINTER(wListDictionary))
    'ListDictionary_New',  # ctypes.POINTER(wListDictionary) (BOOL)
    'ListDictionary_Remove',  # void (ctypes.POINTER(wListDictionary), ctypes.c_void_p)
    'ListDictionary_Remove_Head',  # void (ctypes.POINTER(wListDictionary))
    'ListDictionary_SetItemValue',  # BOOL (ctypes.POINTER(wListDictionary), ctypes.c_void_p, ctypes.c_void_p)
    'ListDictionary_Take',  # ctypes.c_void_p (ctypes.POINTER(wListDictionary), ctypes.c_void_p)
    'ListDictionary_Take_Head',  # ctypes.c_void_p (ctypes.POINTER(wListDictionary))
    'ListDictionary_Unlock',  # void (ctypes.POINTER(wListDictionary))
    'ListDictionary_ValueObject',  # ctypes.POINTER(wObject) (ctypes.POINTER(wListDictionary))
    'MessagePipe_Free',  # void (ctypes.POINTER(wMessagePipe))
    'MessagePipe_New',  # ctypes.POINTER(wMessagePipe) ()
    'MessagePipe_PostQuit',  # void (ctypes.POINTER(wMessagePipe), ctypes.c_int)
    'MessageQueue_Capacity',  # ctypes.c_size_t (ctypes.POINTER(wMessageQueue))
    'MessageQueue_Clear',  # ctypes.c_int (ctypes.POINTER(wMessageQueue))
    'MessageQueue_Dispatch',  # BOOL (ctypes.POINTER(wMessageQueue), ctypes.POINTER(wMessage))
    'MessageQueue_Event',  # HANDLE (ctypes.POINTER(wMessageQueue))
    'MessageQueue_Free',  # void (ctypes.POINTER(wMessageQueue))
    'MessageQueue_Get',  # ctypes.c_int (ctypes.POINTER(wMessageQueue), ctypes.POINTER(wMessage))
    'MessageQueue_New',  # ctypes.POINTER(wMessageQueue) (ctypes.POINTER(wObject))
    'MessageQueue_Object',  # ctypes.POINTER(wObject) (ctypes.POINTER(wMessageQueue))
    'MessageQueue_Peek',  # ctypes.c_int (ctypes.POINTER(wMessageQueue), ctypes.POINTER(wMessage), BOOL)
    'MessageQueue_Post',  # BOOL (ctypes.POINTER(wMessageQueue), ctypes.c_void_p, UINT32, ctypes.c_void_p, ctypes.c_void_p)
    'MessageQueue_PostQuit',  # BOOL (ctypes.POINTER(wMessageQueue), ctypes.c_int)
    'MessageQueue_Size',  # ctypes.c_size_t (ctypes.POINTER(wMessageQueue))
    'MessageQueue_Wait',  # BOOL (ctypes.POINTER(wMessageQueue))
    'ObjectPool_Clear',  # void (ctypes.POINTER(wObjectPool))
    'ObjectPool_Free',  # void (ctypes.POINTER(wObjectPool))
    'ObjectPool_New',  # ctypes.POINTER(wObjectPool) (BOOL)
    'ObjectPool_Object',  # ctypes.POINTER(wObject) (ctypes.POINTER(wObjectPool))
    'ObjectPool_Return',  # void (ctypes.POINTER(wObjectPool), ctypes.c_void_p)
    'ObjectPool_Take',  # ctypes.c_void_p (ctypes.POINTER(wObjectPool))
    'PubSub_AddEventTypes',  # void (ctypes.POINTER(wPubSub), ctypes.POINTER(wEventType), ctypes.c_size_t)
    'PubSub_FindEventType',  # ctypes.POINTER(wEventType) (ctypes.POINTER(wPubSub), ctypes.c_char_p)
    'PubSub_Free',  # void (ctypes.POINTER(wPubSub))
    'PubSub_GetEventTypes',  # ctypes.POINTER(wEventType) (ctypes.POINTER(wPubSub), ctypes.POINTER(ctypes.c_size_t))
    'PubSub_Lock',  # void (ctypes.POINTER(wPubSub))
    'PubSub_New',  # ctypes.POINTER(wPubSub) (BOOL)
    'PubSub_OnEvent',  # ctypes.c_int (ctypes.POINTER(wPubSub), ctypes.c_char_p, ctypes.c_void_p, ctypes.POINTER(wEventArgs))
    'PubSub_Subscribe',  # ctypes.c_int (ctypes.POINTER(wPubSub), ctypes.c_char_p, ...)
    'PubSub_Unlock',  # void (ctypes.POINTER(wPubSub))
    'PubSub_Unsubscribe',  # ctypes.c_int (ctypes.POINTER(wPubSub), ctypes.c_char_p, ...)
    'Queue_Capacity',  # ctypes.c_size_t (ctypes.POINTER(wQueue))
    'Queue_Clear',  # void (ctypes.POINTER(wQueue))
    'Queue_Contains',  # BOOL (ctypes.POINTER(wQueue), ctypes.c_void_p)
    'Queue_Count',  # ctypes.c_size_t (ctypes.POINTER(wQueue))
    'Queue_Dequeue',  # ctypes.c_void_p (ctypes.POINTER(wQueue))
    'Queue_Discard',  # void (ctypes.POINTER(wQueue))
    'Queue_Enqueue',  # BOOL (ctypes.POINTER(wQueue), ctypes.c_void_p)
    'Queue_Event',  # HANDLE (ctypes.POINTER(wQueue))
    'Queue_Free',  # void (ctypes.POINTER(wQueue))
    'Queue_Lock',  # void (ctypes.POINTER(wQueue))
    'Queue_New',  # ctypes.POINTER(wQueue) (BOOL, SSIZE_T, SSIZE_T)
    'Queue_Object',  # ctypes.POINTER(wObject) (ctypes.POINTER(wQueue))
    'Queue_Peek',  # ctypes.c_void_p (ctypes.POINTER(wQueue))
    'Queue_Unlock',  # void (ctypes.POINTER(wQueue))
    'Stack_Clear',  # void (ctypes.POINTER(wStack))
    'Stack_Contains',  # BOOL (ctypes.POINTER(wStack), ctypes.c_void_p)
    'Stack_Count',  # ctypes.c_size_t (ctypes.POINTER(wStack))
    'Stack_Free',  # void (ctypes.POINTER(wStack))
    'Stack_IsSynchronized',  # BOOL (ctypes.POINTER(wStack))
    'Stack_New',  # ctypes.POINTER(wStack) (BOOL)
    'Stack_Object',  # ctypes.POINTER(wObject) (ctypes.POINTER(wStack))
    'Stack_Peek',  # ctypes.c_void_p (ctypes.POINTER(wStack))
    'Stack_Pop',  # ctypes.c_void_p (ctypes.POINTER(wStack))
    'Stack_Push',  # void (ctypes.POINTER(wStack), ctypes.c_void_p)
    'winpr_ObjectStringClone',  # ctypes.c_void_p (ctypes.c_void_p)
    'winpr_ObjectStringFree',  # void (ctypes.c_void_p)
    'winpr_ObjectWStringClone',  # ctypes.c_void_p (ctypes.c_void_p)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['ArrayList_ForEachFkt', 'FUNCTIONS', 'HASH_TABLE_FOREACH_FN', 'HASH_TABLE_HASH_FN', 'MAX_EVENT_HANDLERS', 'MESSAGE_FREE_FN', 'OBJECT_EQUALS_FN', 'OBJECT_FREE_FN', 'OBJECT_INIT_FN', 'OBJECT_NEW_FN', 'OBJECT_UNINIT_FN', 'WMQ_QUIT', 'bind', 'pEventHandler', 'struct_s_wMessage', 'struct_wEventArgs', 'struct_wEventType', 'struct_wMessagePipe', 'struct_wObject', 'wArrayList', 'wBufferPool', 'wCountdownEvent', 'wEventArgs', 'wEventType', 'wHashTable', 'wLinkedList', 'wListDictionary', 'wMessage', 'wMessagePipe', 'wMessageQueue', 'wObject', 'wObjectPool', 'wPubSub', 'wQueue', 'wStack']
