"""
Mirror of <winpr/cred.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
BinaryBlobCredential = 3
BinaryBlobForSystem = 5
CERT_HASH_LENGTH = 0x14
CertCredential = 1
CredForSystemProtection = 3
CredTrustedProtection = 2
CredUnprotected = 0
CredUserProtection = 1
UsernameForPackedCredentials = 4
UsernameTargetCredential = 2

# --- types declared in this header ---
CERT_CREDENTIAL_INFO = _types.CERT_CREDENTIAL_INFO
CREDENTIALA = _types.CREDENTIALA
CREDENTIALW = _types.CREDENTIALW
CREDENTIAL_ATTRIBUTEA = _types.CREDENTIAL_ATTRIBUTEA
CREDENTIAL_ATTRIBUTEW = _types.CREDENTIAL_ATTRIBUTEW
CREDENTIAL_TARGET_INFORMATIONA = _types.CREDENTIAL_TARGET_INFORMATIONA
CREDENTIAL_TARGET_INFORMATIONW = _types.CREDENTIAL_TARGET_INFORMATIONW
CRED_MARSHAL_TYPE = _types.CRED_MARSHAL_TYPE
CRED_PROTECTION_TYPE = _types.CRED_PROTECTION_TYPE
PCERT_CREDENTIAL_INFO = _types.PCERT_CREDENTIAL_INFO
PCREDENTIALA = _types.PCREDENTIALA
PCREDENTIALW = _types.PCREDENTIALW
PCREDENTIAL_ATTRIBUTEA = _types.PCREDENTIAL_ATTRIBUTEA
PCREDENTIAL_ATTRIBUTEW = _types.PCREDENTIAL_ATTRIBUTEW
PCREDENTIAL_TARGET_INFORMATIONA = _types.PCREDENTIAL_TARGET_INFORMATIONA
PCREDENTIAL_TARGET_INFORMATIONW = _types.PCREDENTIAL_TARGET_INFORMATIONW
PCRED_MARSHAL_TYPE = _types.PCRED_MARSHAL_TYPE
PCRED_PROTECTION_TYPE = _types.PCRED_PROTECTION_TYPE
struct_CERT_CREDENTIAL_INFO = _types.struct_CERT_CREDENTIAL_INFO
struct_CREDENTIALA = _types.struct_CREDENTIALA
struct_CREDENTIALW = _types.struct_CREDENTIALW
struct_CREDENTIAL_ATTRIBUTEA = _types.struct_CREDENTIAL_ATTRIBUTEA
struct_CREDENTIAL_ATTRIBUTEW = _types.struct_CREDENTIAL_ATTRIBUTEW
struct_CREDENTIAL_TARGET_INFORMATIONA = _types.struct_CREDENTIAL_TARGET_INFORMATIONA
struct_CREDENTIAL_TARGET_INFORMATIONW = _types.struct_CREDENTIAL_TARGET_INFORMATIONW

# --- functions declared in this header ---
FUNCTIONS = (
    'CredFree',  # void (PVOID)
    'CredIsMarshaledCredentialA',  # BOOL (LPCSTR)
    'CredIsMarshaledCredentialW',  # BOOL (LPCWSTR)
    'CredMarshalCredentialA',  # BOOL (CRED_MARSHAL_TYPE, PVOID, ctypes.POINTER(LPSTR))
    'CredMarshalCredentialW',  # BOOL (CRED_MARSHAL_TYPE, PVOID, ctypes.POINTER(LPWSTR))
    'CredUnmarshalCredentialA',  # BOOL (LPCSTR, PCRED_MARSHAL_TYPE, ctypes.POINTER(PVOID))
    'CredUnmarshalCredentialW',  # BOOL (LPCWSTR, PCRED_MARSHAL_TYPE, ctypes.POINTER(PVOID))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['BinaryBlobCredential', 'BinaryBlobForSystem', 'CERT_CREDENTIAL_INFO', 'CERT_HASH_LENGTH', 'CREDENTIALA', 'CREDENTIALW', 'CREDENTIAL_ATTRIBUTEA', 'CREDENTIAL_ATTRIBUTEW', 'CREDENTIAL_TARGET_INFORMATIONA', 'CREDENTIAL_TARGET_INFORMATIONW', 'CRED_MARSHAL_TYPE', 'CRED_PROTECTION_TYPE', 'CertCredential', 'CredForSystemProtection', 'CredTrustedProtection', 'CredUnprotected', 'CredUserProtection', 'FUNCTIONS', 'PCERT_CREDENTIAL_INFO', 'PCREDENTIALA', 'PCREDENTIALW', 'PCREDENTIAL_ATTRIBUTEA', 'PCREDENTIAL_ATTRIBUTEW', 'PCREDENTIAL_TARGET_INFORMATIONA', 'PCREDENTIAL_TARGET_INFORMATIONW', 'PCRED_MARSHAL_TYPE', 'PCRED_PROTECTION_TYPE', 'UsernameForPackedCredentials', 'UsernameTargetCredential', 'bind', 'struct_CERT_CREDENTIAL_INFO', 'struct_CREDENTIALA', 'struct_CREDENTIALW', 'struct_CREDENTIAL_ATTRIBUTEA', 'struct_CREDENTIAL_ATTRIBUTEW', 'struct_CREDENTIAL_TARGET_INFORMATIONA', 'struct_CREDENTIAL_TARGET_INFORMATIONW']
