"""
Mirror of <winpr/crt.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
errno_t = _types.errno_t

# --- functions declared in this header ---
FUNCTIONS = (
    'SecureZeroMemory',  # PVOID (PVOID, ctypes.c_size_t)
    '_itoa_s',  # errno_t (ctypes.c_int, ctypes.c_char_p, ctypes.c_size_t, ctypes.c_int)
    'memmove_s',  # errno_t (ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t)
    'winpr_aligned_calloc',  # ctypes.c_void_p (ctypes.c_size_t, ctypes.c_size_t, ctypes.c_size_t)
    'winpr_aligned_free',  # void (ctypes.c_void_p)
    'winpr_aligned_malloc',  # ctypes.c_void_p (ctypes.c_size_t, ctypes.c_size_t)
    'winpr_aligned_msize',  # ctypes.c_size_t (ctypes.c_void_p, ctypes.c_size_t, ctypes.c_size_t)
    'winpr_aligned_offset_malloc',  # ctypes.c_void_p (ctypes.c_size_t, ctypes.c_size_t, ctypes.c_size_t)
    'winpr_aligned_offset_realloc',  # ctypes.c_void_p (ctypes.c_void_p, ctypes.c_size_t, ctypes.c_size_t, ctypes.c_size_t)
    'winpr_aligned_offset_recalloc',  # ctypes.c_void_p (ctypes.c_void_p, ctypes.c_size_t, ctypes.c_size_t, ctypes.c_size_t, ctypes.c_size_t)
    'winpr_aligned_realloc',  # ctypes.c_void_p (ctypes.c_void_p, ctypes.c_size_t, ctypes.c_size_t)
    'winpr_aligned_recalloc',  # ctypes.c_void_p (ctypes.c_void_p, ctypes.c_size_t, ctypes.c_size_t, ctypes.c_size_t)
    'wmemmove_s',  # errno_t (ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'errno_t']
