"""
Mirror of <winpr/debug.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'winpr_backtrace',  # ctypes.c_void_p (DWORD)
    'winpr_backtrace_free',  # void (ctypes.c_void_p)
    'winpr_backtrace_symbols',  # ctypes.POINTER(ctypes.c_char_p) (ctypes.c_void_p, ctypes.POINTER(ctypes.c_size_t))
    'winpr_backtrace_symbols_fd',  # void (ctypes.c_void_p, ctypes.c_int)
    'winpr_log_backtrace',  # void (ctypes.c_char_p, DWORD, DWORD)
    'winpr_log_backtrace_ex',  # void (ctypes.POINTER(wLog), DWORD, DWORD)
    'winpr_strerror',  # ctypes.c_char_p (INT32, ctypes.c_char_p, ctypes.c_size_t)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
