"""
Mirror of <winpr/environment.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'EnvironmentBlockToEnvpA',  # ctypes.POINTER(ctypes.c_char_p) (LPCH)
    'ExpandEnvironmentStringsA',  # DWORD (LPCSTR, LPSTR, DWORD)
    'ExpandEnvironmentStringsW',  # DWORD (LPCWSTR, LPWSTR, DWORD)
    'FreeEnvironmentStringsA',  # BOOL (LPCH)
    'FreeEnvironmentStringsW',  # BOOL (LPWCH)
    'GetCommandLineA',  # LPSTR ()
    'GetCommandLineW',  # LPWSTR ()
    'GetCurrentDirectoryA',  # DWORD (DWORD, LPSTR)
    'GetCurrentDirectoryW',  # DWORD (DWORD, LPWSTR)
    'GetEnvAlloc',  # ctypes.c_char_p (LPCSTR)
    'GetEnvironmentStrings',  # LPCH ()
    'GetEnvironmentStringsW',  # LPWCH ()
    'GetEnvironmentVariableA',  # DWORD (LPCSTR, LPSTR, DWORD)
    'GetEnvironmentVariableEBA',  # DWORD (LPCSTR, LPCSTR, LPSTR, DWORD)
    'GetEnvironmentVariableW',  # DWORD (LPCWSTR, LPWSTR, DWORD)
    'GetEnvironmentVariableX',  # DWORD (ctypes.c_char_p, ctypes.c_char_p, DWORD)
    'MergeEnvironmentStrings',  # LPCH (PCSTR, PCSTR)
    'NeedCurrentDirectoryForExePathA',  # BOOL (LPCSTR)
    'NeedCurrentDirectoryForExePathW',  # BOOL (LPCWSTR)
    'SearchPathA',  # DWORD (LPCSTR, LPCSTR, LPCSTR, DWORD, LPSTR, ctypes.POINTER(LPSTR))
    'SearchPathW',  # DWORD (LPCWSTR, LPCWSTR, LPCWSTR, DWORD, LPWSTR, ctypes.POINTER(LPWSTR))
    'SetCurrentDirectoryA',  # BOOL (LPCSTR)
    'SetCurrentDirectoryW',  # BOOL (LPCWSTR)
    'SetEnvironmentStringsA',  # BOOL (LPCH)
    'SetEnvironmentStringsW',  # BOOL (LPWCH)
    'SetEnvironmentVariableA',  # BOOL (LPCSTR, LPCSTR)
    'SetEnvironmentVariableEBA',  # BOOL (ctypes.POINTER(LPSTR), LPCSTR, LPCSTR)
    'SetEnvironmentVariableW',  # BOOL (LPCWSTR, LPCWSTR)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
