"""
Mirror of <winpr/handle.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
DUPLICATE_CLOSE_SOURCE = 1
DUPLICATE_SAME_ACCESS = 2
HANDLE_FLAG_INHERIT = 1
HANDLE_FLAG_PROTECT_FROM_CLOSE = 2
WINPR_FD_READ = 1
WINPR_FD_READ_BIT = 0
WINPR_FD_WRITE = 2
WINPR_FD_WRITE_BIT = 1

# --- functions declared in this header ---
FUNCTIONS = (
    'CloseHandle',  # BOOL (HANDLE)
    'DuplicateHandle',  # BOOL (HANDLE, HANDLE, HANDLE, LPHANDLE, DWORD, BOOL, DWORD)
    'GetHandleInformation',  # BOOL (HANDLE, LPDWORD)
    'SetHandleInformation',  # BOOL (HANDLE, DWORD, DWORD)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['DUPLICATE_CLOSE_SOURCE', 'DUPLICATE_SAME_ACCESS', 'FUNCTIONS', 'HANDLE_FLAG_INHERIT', 'HANDLE_FLAG_PROTECT_FROM_CLOSE', 'WINPR_FD_READ', 'WINPR_FD_READ_BIT', 'WINPR_FD_WRITE', 'WINPR_FD_WRITE_BIT', 'bind']
