"""
Mirror of <winpr/image.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
WINPR_IMAGE_BITMAP = 0
WINPR_IMAGE_BMP_HEADER_LEN = 0x36
WINPR_IMAGE_CMP_FUZZY = 4
WINPR_IMAGE_CMP_IGNORE_ALPHA = 2
WINPR_IMAGE_CMP_IGNORE_DEPTH = 1
WINPR_IMAGE_CMP_NO_FLAGS = 0
WINPR_IMAGE_JPEG = 2
WINPR_IMAGE_PNG = 1
WINPR_IMAGE_WEBP = 3

# --- types declared in this header ---
WINPR_BITMAP_CORE_HEADER = _types.WINPR_BITMAP_CORE_HEADER
WINPR_BITMAP_FILE_HEADER = _types.WINPR_BITMAP_FILE_HEADER
WINPR_BITMAP_INFO_HEADER = _types.WINPR_BITMAP_INFO_HEADER
struct_WINPR_BITMAP_CORE_HEADER = _types.struct_WINPR_BITMAP_CORE_HEADER
struct_WINPR_BITMAP_FILE_HEADER = _types.struct_WINPR_BITMAP_FILE_HEADER
struct_WINPR_BITMAP_INFO_HEADER = _types.struct_WINPR_BITMAP_INFO_HEADER
struct_wImage = _types.struct_wImage
wImage = _types.wImage
wImageFlags = _types.wImageFlags

# --- functions declared in this header ---
FUNCTIONS = (
    'winpr_bitmap_construct_header',  # ctypes.POINTER(BYTE) (ctypes.c_size_t, ctypes.c_size_t, ctypes.c_size_t)
    'winpr_bitmap_write',  # ctypes.c_int (ctypes.c_char_p, ctypes.POINTER(BYTE), ctypes.c_size_t, ctypes.c_size_t, ctypes.c_size_t)
    'winpr_bitmap_write_ex',  # ctypes.c_int (ctypes.c_char_p, ctypes.POINTER(BYTE), ctypes.c_size_t, ctypes.c_size_t, ctypes.c_size_t, ctypes.c_size_t)
    'winpr_image_equal',  # BOOL (ctypes.POINTER(wImage), ctypes.POINTER(wImage), UINT32)
    'winpr_image_format_extension',  # ctypes.c_char_p (UINT32)
    'winpr_image_format_is_supported',  # BOOL (UINT32)
    'winpr_image_format_mime',  # ctypes.c_char_p (UINT32)
    'winpr_image_free',  # void (ctypes.POINTER(wImage), BOOL)
    'winpr_image_new',  # ctypes.POINTER(wImage) ()
    'winpr_image_read',  # ctypes.c_int (ctypes.POINTER(wImage), ctypes.c_char_p)
    'winpr_image_read_buffer',  # ctypes.c_int (ctypes.POINTER(wImage), ctypes.POINTER(BYTE), ctypes.c_size_t)
    'winpr_image_write',  # ctypes.c_int (ctypes.POINTER(wImage), ctypes.c_char_p)
    'winpr_image_write_buffer',  # ctypes.c_void_p (ctypes.POINTER(wImage), UINT32, ctypes.POINTER(ctypes.c_size_t))
    'winpr_image_write_ex',  # ctypes.c_int (ctypes.POINTER(wImage), UINT32, ctypes.c_char_p)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'WINPR_BITMAP_CORE_HEADER', 'WINPR_BITMAP_FILE_HEADER', 'WINPR_BITMAP_INFO_HEADER', 'WINPR_IMAGE_BITMAP', 'WINPR_IMAGE_BMP_HEADER_LEN', 'WINPR_IMAGE_CMP_FUZZY', 'WINPR_IMAGE_CMP_IGNORE_ALPHA', 'WINPR_IMAGE_CMP_IGNORE_DEPTH', 'WINPR_IMAGE_CMP_NO_FLAGS', 'WINPR_IMAGE_JPEG', 'WINPR_IMAGE_PNG', 'WINPR_IMAGE_WEBP', 'bind', 'struct_WINPR_BITMAP_CORE_HEADER', 'struct_WINPR_BITMAP_FILE_HEADER', 'struct_WINPR_BITMAP_INFO_HEADER', 'struct_wImage', 'wImage', 'wImageFlags']
