"""
Mirror of <winpr/ini.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
wIniFile = _types.wIniFile

# --- functions declared in this header ---
FUNCTIONS = (
    'IniFile_Clone',  # ctypes.POINTER(wIniFile) (ctypes.POINTER(wIniFile))
    'IniFile_Free',  # void (ctypes.POINTER(wIniFile))
    'IniFile_GetKeyValueInt',  # ctypes.c_int (ctypes.POINTER(wIniFile), ctypes.c_char_p, ctypes.c_char_p)
    'IniFile_GetKeyValueString',  # ctypes.c_char_p (ctypes.POINTER(wIniFile), ctypes.c_char_p, ctypes.c_char_p)
    'IniFile_GetSectionKeyNames',  # ctypes.POINTER(ctypes.c_char_p) (ctypes.POINTER(wIniFile), ctypes.c_char_p, ctypes.POINTER(ctypes.c_size_t))
    'IniFile_GetSectionNames',  # ctypes.POINTER(ctypes.c_char_p) (ctypes.POINTER(wIniFile), ctypes.POINTER(ctypes.c_size_t))
    'IniFile_New',  # ctypes.POINTER(wIniFile) ()
    'IniFile_ReadBuffer',  # ctypes.c_int (ctypes.POINTER(wIniFile), ctypes.c_char_p)
    'IniFile_ReadFile',  # ctypes.c_int (ctypes.POINTER(wIniFile), ctypes.c_char_p)
    'IniFile_SetKeyValueInt',  # ctypes.c_int (ctypes.POINTER(wIniFile), ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int)
    'IniFile_SetKeyValueString',  # ctypes.c_int (ctypes.POINTER(wIniFile), ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p)
    'IniFile_WriteBuffer',  # ctypes.c_char_p (ctypes.POINTER(wIniFile))
    'IniFile_WriteFile',  # ctypes.c_int (ctypes.POINTER(wIniFile), ctypes.c_char_p)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'wIniFile']
