"""
Mirror of <winpr/interlocked.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
WINPR_INTERLOCKED_COMPARE_EXCHANGE64 = 1

# --- types declared in this header ---
WINPR_LIST_ENTRY = _types.WINPR_LIST_ENTRY
WINPR_LIST_ENTRY32 = _types.WINPR_LIST_ENTRY32
WINPR_LIST_ENTRY64 = _types.WINPR_LIST_ENTRY64
WINPR_PLIST_ENTRY = _types.WINPR_PLIST_ENTRY
WINPR_PLIST_ENTRY32 = _types.WINPR_PLIST_ENTRY32
WINPR_PLIST_ENTRY64 = _types.WINPR_PLIST_ENTRY64
WINPR_PSINGLE_LIST_ENTRY = _types.WINPR_PSINGLE_LIST_ENTRY
WINPR_PSLIST_HEADER = _types.WINPR_PSLIST_HEADER
WINPR_SINGLE_LIST_ENTRY = _types.WINPR_SINGLE_LIST_ENTRY
WINPR_SLIST_HEADER = _types.WINPR_SLIST_HEADER
_anon_16 = _types._anon_16
struct_S_WINPR_LIST_ENTRY = _types.struct_S_WINPR_LIST_ENTRY
struct_S_WINPR_SINGLE_LIST_ENTRY = _types.struct_S_WINPR_SINGLE_LIST_ENTRY
struct_WINPR_LIST_ENTRY32 = _types.struct_WINPR_LIST_ENTRY32
struct_WINPR_LIST_ENTRY64 = _types.struct_WINPR_LIST_ENTRY64
struct_WINPR_SLIST_HEADER = _types.struct_WINPR_SLIST_HEADER

# --- functions declared in this header ---
FUNCTIONS = (
    'AppendTailList',  # void (WINPR_PLIST_ENTRY, WINPR_PLIST_ENTRY)
    'InitializeListHead',  # void (WINPR_PLIST_ENTRY)
    'InitializeSListHead',  # void (WINPR_PSLIST_HEADER)
    'InsertHeadList',  # void (WINPR_PLIST_ENTRY, WINPR_PLIST_ENTRY)
    'InsertTailList',  # void (WINPR_PLIST_ENTRY, WINPR_PLIST_ENTRY)
    'InterlockedCompareExchange',  # LONG (ctypes.POINTER(LONG), LONG, LONG)
    'InterlockedCompareExchange64',  # LONGLONG (ctypes.POINTER(LONGLONG), LONGLONG, LONGLONG)
    'InterlockedCompareExchangePointer',  # PVOID (ctypes.POINTER(PVOID), PVOID, PVOID)
    'InterlockedDecrement',  # LONG (ctypes.POINTER(LONG))
    'InterlockedExchange',  # LONG (ctypes.POINTER(LONG), LONG)
    'InterlockedExchangeAdd',  # LONG (ctypes.POINTER(LONG), LONG)
    'InterlockedFlushSList',  # WINPR_PSINGLE_LIST_ENTRY (WINPR_PSLIST_HEADER)
    'InterlockedIncrement',  # LONG (ctypes.POINTER(LONG))
    'InterlockedPopEntrySList',  # WINPR_PSINGLE_LIST_ENTRY (WINPR_PSLIST_HEADER)
    'InterlockedPushEntrySList',  # WINPR_PSINGLE_LIST_ENTRY (WINPR_PSLIST_HEADER, WINPR_PSINGLE_LIST_ENTRY)
    'InterlockedPushListSListEx',  # WINPR_PSINGLE_LIST_ENTRY (WINPR_PSLIST_HEADER, WINPR_PSINGLE_LIST_ENTRY, WINPR_PSINGLE_LIST_ENTRY, ULONG)
    'IsListEmpty',  # BOOL (ctypes.POINTER(WINPR_LIST_ENTRY))
    'PopEntryList',  # WINPR_PSINGLE_LIST_ENTRY (WINPR_PSINGLE_LIST_ENTRY)
    'PushEntryList',  # void (WINPR_PSINGLE_LIST_ENTRY, WINPR_PSINGLE_LIST_ENTRY)
    'QueryDepthSList',  # USHORT (WINPR_PSLIST_HEADER)
    'RemoveEntryList',  # BOOL (WINPR_PLIST_ENTRY)
    'RemoveHeadList',  # WINPR_PLIST_ENTRY (WINPR_PLIST_ENTRY)
    'RemoveTailList',  # WINPR_PLIST_ENTRY (WINPR_PLIST_ENTRY)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'WINPR_INTERLOCKED_COMPARE_EXCHANGE64', 'WINPR_LIST_ENTRY', 'WINPR_LIST_ENTRY32', 'WINPR_LIST_ENTRY64', 'WINPR_PLIST_ENTRY', 'WINPR_PLIST_ENTRY32', 'WINPR_PLIST_ENTRY64', 'WINPR_PSINGLE_LIST_ENTRY', 'WINPR_PSLIST_HEADER', 'WINPR_SINGLE_LIST_ENTRY', 'WINPR_SLIST_HEADER', '_anon_16', 'bind', 'struct_S_WINPR_LIST_ENTRY', 'struct_S_WINPR_SINGLE_LIST_ENTRY', 'struct_WINPR_LIST_ENTRY32', 'struct_WINPR_LIST_ENTRY64', 'struct_WINPR_SLIST_HEADER']
