"""
Mirror of <winpr/json.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
WINPR_JSON = _types.WINPR_JSON

# --- functions declared in this header ---
FUNCTIONS = (
    'WINPR_JSON_AddArrayToObject',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(WINPR_JSON), ctypes.c_char_p)
    'WINPR_JSON_AddBoolToObject',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(WINPR_JSON), ctypes.c_char_p, BOOL)
    'WINPR_JSON_AddFalseToObject',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(WINPR_JSON), ctypes.c_char_p)
    'WINPR_JSON_AddIntegerToObject',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(WINPR_JSON), ctypes.c_char_p, ctypes.c_int64)
    'WINPR_JSON_AddItemToArray',  # BOOL (ctypes.POINTER(WINPR_JSON), ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_AddNullToObject',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(WINPR_JSON), ctypes.c_char_p)
    'WINPR_JSON_AddNumberToObject',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(WINPR_JSON), ctypes.c_char_p, ctypes.c_double)
    'WINPR_JSON_AddObjectToObject',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(WINPR_JSON), ctypes.c_char_p)
    'WINPR_JSON_AddStringToObject',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(WINPR_JSON), ctypes.c_char_p, ctypes.c_char_p)
    'WINPR_JSON_AddTrueToObject',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(WINPR_JSON), ctypes.c_char_p)
    'WINPR_JSON_CreateArray',  # ctypes.POINTER(WINPR_JSON) ()
    'WINPR_JSON_CreateBool',  # ctypes.POINTER(WINPR_JSON) (BOOL)
    'WINPR_JSON_CreateFalse',  # ctypes.POINTER(WINPR_JSON) ()
    'WINPR_JSON_CreateNull',  # ctypes.POINTER(WINPR_JSON) ()
    'WINPR_JSON_CreateNumber',  # ctypes.POINTER(WINPR_JSON) (ctypes.c_double)
    'WINPR_JSON_CreateObject',  # ctypes.POINTER(WINPR_JSON) ()
    'WINPR_JSON_CreateString',  # ctypes.POINTER(WINPR_JSON) (ctypes.c_char_p)
    'WINPR_JSON_CreateTrue',  # ctypes.POINTER(WINPR_JSON) ()
    'WINPR_JSON_Delete',  # void (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_GetArrayItem',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(WINPR_JSON), ctypes.c_size_t)
    'WINPR_JSON_GetArraySize',  # ctypes.c_size_t (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_GetErrorPtr',  # ctypes.c_char_p ()
    'WINPR_JSON_GetNumberValue',  # ctypes.c_double (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_GetObjectItem',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(WINPR_JSON), ctypes.c_char_p)
    'WINPR_JSON_GetObjectItemCaseSensitive',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(WINPR_JSON), ctypes.c_char_p)
    'WINPR_JSON_GetStringValue',  # ctypes.c_char_p (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_HasObjectItem',  # BOOL (ctypes.POINTER(WINPR_JSON), ctypes.c_char_p)
    'WINPR_JSON_IsArray',  # BOOL (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_IsBool',  # BOOL (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_IsFalse',  # BOOL (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_IsInvalid',  # BOOL (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_IsNull',  # BOOL (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_IsNumber',  # BOOL (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_IsObject',  # BOOL (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_IsString',  # BOOL (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_IsTrue',  # BOOL (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_Parse',  # ctypes.POINTER(WINPR_JSON) (ctypes.c_char_p)
    'WINPR_JSON_ParseFromFile',  # ctypes.POINTER(WINPR_JSON) (ctypes.c_char_p)
    'WINPR_JSON_ParseFromFileFP',  # ctypes.POINTER(WINPR_JSON) (ctypes.c_void_p)
    'WINPR_JSON_ParseWithLength',  # ctypes.POINTER(WINPR_JSON) (ctypes.c_char_p, ctypes.c_size_t)
    'WINPR_JSON_Print',  # ctypes.c_char_p (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_PrintUnformatted',  # ctypes.c_char_p (ctypes.POINTER(WINPR_JSON))
    'WINPR_JSON_version',  # ctypes.c_int (ctypes.c_char_p, ctypes.c_size_t)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'WINPR_JSON', 'bind']
