"""
Mirror of <winpr/library.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
DONT_RESOLVE_DLL_REFERENCES = 1
LOAD_IGNORE_CODE_AUTHZ_LEVEL = 0x10
LOAD_LIBRARY_AS_DATAFILE = 2
LOAD_LIBRARY_AS_DATAFILE_EXCLUSIVE = 0x40
LOAD_LIBRARY_AS_IMAGE_RESOURCE = 0x20
LOAD_LIBRARY_SEARCH_APPLICATION_DIR = 0x200
LOAD_LIBRARY_SEARCH_DEFAULT_DIRS = 0x1000
LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR = 0x100
LOAD_LIBRARY_SEARCH_SYSTEM32 = 0x800
LOAD_LIBRARY_SEARCH_USER_DIRS = 0x400
LOAD_WITH_ALTERED_SEARCH_PATH = 8

# --- types declared in this header ---
DLL_DIRECTORY_COOKIE = _types.DLL_DIRECTORY_COOKIE

# --- functions declared in this header ---
FUNCTIONS = (
    'AddDllDirectory',  # DLL_DIRECTORY_COOKIE (PCWSTR)
    'FreeLibrary',  # BOOL (HMODULE)
    'GetModuleFileNameA',  # DWORD (HMODULE, LPSTR, DWORD)
    'GetModuleFileNameW',  # DWORD (HMODULE, LPWSTR, DWORD)
    'GetModuleHandleA',  # HMODULE (LPCSTR)
    'GetModuleHandleW',  # HMODULE (LPCWSTR)
    'GetProcAddress',  # FARPROC (HMODULE, LPCSTR)
    'LoadLibraryA',  # HMODULE (LPCSTR)
    'LoadLibraryExA',  # HMODULE (LPCSTR, HANDLE, DWORD)
    'LoadLibraryExW',  # HMODULE (LPCWSTR, HANDLE, DWORD)
    'LoadLibraryExX',  # HMODULE (LPCSTR, HANDLE, DWORD)
    'LoadLibraryW',  # HMODULE (LPCWSTR)
    'LoadLibraryX',  # HMODULE (LPCSTR)
    'RemoveDllDirectory',  # BOOL (DLL_DIRECTORY_COOKIE)
    'SetDefaultDllDirectories',  # BOOL (DWORD)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['DLL_DIRECTORY_COOKIE', 'DONT_RESOLVE_DLL_REFERENCES', 'FUNCTIONS', 'LOAD_IGNORE_CODE_AUTHZ_LEVEL', 'LOAD_LIBRARY_AS_DATAFILE', 'LOAD_LIBRARY_AS_DATAFILE_EXCLUSIVE', 'LOAD_LIBRARY_AS_IMAGE_RESOURCE', 'LOAD_LIBRARY_SEARCH_APPLICATION_DIR', 'LOAD_LIBRARY_SEARCH_DEFAULT_DIRS', 'LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR', 'LOAD_LIBRARY_SEARCH_SYSTEM32', 'LOAD_LIBRARY_SEARCH_USER_DIRS', 'LOAD_WITH_ALTERED_SEARCH_PATH', 'bind']
