"""
Mirror of <winpr/memory.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'CreateFileMappingA',  # HANDLE (HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCSTR)
    'CreateFileMappingW',  # HANDLE (HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCWSTR)
    'FlushViewOfFile',  # BOOL (LPCVOID, ctypes.c_size_t)
    'MapViewOfFile',  # LPVOID (HANDLE, DWORD, DWORD, DWORD, ctypes.c_size_t)
    'MapViewOfFileEx',  # LPVOID (HANDLE, DWORD, DWORD, DWORD, ctypes.c_size_t, LPVOID)
    'OpenFileMappingA',  # HANDLE (DWORD, BOOL, LPCSTR)
    'OpenFileMappingW',  # HANDLE (DWORD, BOOL, LPCWSTR)
    'UnmapViewOfFile',  # BOOL (LPCVOID)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
