"""
Mirror of <winpr/ncrypt.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
MS_SCARD_PROV_A = 'Microsoft Base Smart Card Crypto Provider'
NCRYPT_MACHINE_KEY_FLAG = 0x20
NCRYPT_SILENT_FLAG = 0x40

# --- types declared in this header ---
NCRYPT_HANDLE = _types.NCRYPT_HANDLE
NCRYPT_KEY_HANDLE = _types.NCRYPT_KEY_HANDLE
NCRYPT_PROV_HANDLE = _types.NCRYPT_PROV_HANDLE
NCryptKeyName = _types.NCryptKeyName
NCryptProviderName = _types.NCryptProviderName
struct_NCryptKeyName = _types.struct_NCryptKeyName
struct_NCryptProviderName = _types.struct_NCryptProviderName

# --- functions declared in this header ---
FUNCTIONS = (
    'NCryptEnumKeys',  # SECURITY_STATUS (NCRYPT_PROV_HANDLE, LPCWSTR, ctypes.POINTER(ctypes.POINTER(NCryptKeyName)), ctypes.POINTER(PVOID), DWORD)
    'NCryptEnumStorageProviders',  # SECURITY_STATUS (ctypes.POINTER(DWORD), ctypes.POINTER(ctypes.POINTER(NCryptProviderName)), DWORD)
    'NCryptFreeBuffer',  # SECURITY_STATUS (PVOID)
    'NCryptFreeObject',  # SECURITY_STATUS (NCRYPT_HANDLE)
    'NCryptGetProperty',  # SECURITY_STATUS (NCRYPT_HANDLE, LPCWSTR, PBYTE, DWORD, ctypes.POINTER(DWORD), DWORD)
    'NCryptOpenKey',  # SECURITY_STATUS (NCRYPT_PROV_HANDLE, ctypes.POINTER(NCRYPT_KEY_HANDLE), LPCWSTR, DWORD, DWORD)
    'NCryptOpenStorageProvider',  # SECURITY_STATUS (ctypes.POINTER(NCRYPT_PROV_HANDLE), LPCWSTR, DWORD)
    'winpr_NCryptGetModulePath',  # ctypes.c_char_p (NCRYPT_PROV_HANDLE)
    'winpr_NCryptOpenStorageProviderEx',  # SECURITY_STATUS (ctypes.POINTER(NCRYPT_PROV_HANDLE), LPCWSTR, DWORD, ctypes.POINTER(LPCSTR))
    'winpr_NCryptSecurityStatusError',  # ctypes.c_char_p (SECURITY_STATUS)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'MS_SCARD_PROV_A', 'NCRYPT_HANDLE', 'NCRYPT_KEY_HANDLE', 'NCRYPT_MACHINE_KEY_FLAG', 'NCRYPT_PROV_HANDLE', 'NCRYPT_SILENT_FLAG', 'NCryptKeyName', 'NCryptProviderName', 'bind', 'struct_NCryptKeyName', 'struct_NCryptProviderName']
