"""
Mirror of <winpr/ntlm.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
psPeerComputeNtlmHash = _types.psPeerComputeNtlmHash

# --- functions declared in this header ---
FUNCTIONS = (
    'NTOWFv1A',  # BOOL (LPCSTR, UINT32, ctypes.POINTER(BYTE))
    'NTOWFv1W',  # BOOL (LPCWSTR, UINT32, ctypes.POINTER(BYTE))
    'NTOWFv2A',  # BOOL (LPCSTR, UINT32, LPCSTR, UINT32, LPCSTR, UINT32, ctypes.POINTER(BYTE))
    'NTOWFv2FromHashA',  # BOOL (ctypes.POINTER(BYTE), LPCSTR, UINT32, LPCSTR, UINT32, ctypes.POINTER(BYTE))
    'NTOWFv2FromHashW',  # BOOL (ctypes.POINTER(BYTE), LPCWSTR, UINT32, LPCWSTR, UINT32, ctypes.POINTER(BYTE))
    'NTOWFv2W',  # BOOL (LPCWSTR, UINT32, LPCWSTR, UINT32, LPCWSTR, UINT32, ctypes.POINTER(BYTE))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'psPeerComputeNtlmHash']
