"""
Mirror of <winpr/Pathcch.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
PATHCCH_ALLOW_LONG_PATHS = 1
PATHCCH_MAX_CCH = 0x8000
VOLUME_PREFIX = '\\\\\\\\?\\\\Volume'

# --- functions declared in this header ---
FUNCTIONS = (
    'PathAllocCanonicalizeA',  # HRESULT (PCSTR, ctypes.c_ulong, ctypes.POINTER(PSTR))
    'PathAllocCanonicalizeW',  # HRESULT (PCWSTR, ctypes.c_ulong, ctypes.POINTER(PWSTR))
    'PathAllocCombineA',  # HRESULT (PCSTR, PCSTR, ctypes.c_ulong, ctypes.POINTER(PSTR))
    'PathAllocCombineW',  # HRESULT (PCWSTR, PCWSTR, ctypes.c_ulong, ctypes.POINTER(PWSTR))
    'PathCchAddBackslashA',  # HRESULT (PSTR, ctypes.c_size_t)
    'PathCchAddBackslashExA',  # HRESULT (PSTR, ctypes.c_size_t, ctypes.POINTER(PSTR), ctypes.POINTER(ctypes.c_size_t))
    'PathCchAddBackslashExW',  # HRESULT (PWSTR, ctypes.c_size_t, ctypes.POINTER(PWSTR), ctypes.POINTER(ctypes.c_size_t))
    'PathCchAddBackslashW',  # HRESULT (PWSTR, ctypes.c_size_t)
    'PathCchAddExtensionA',  # HRESULT (PSTR, ctypes.c_size_t, PCSTR)
    'PathCchAddExtensionW',  # HRESULT (PWSTR, ctypes.c_size_t, PCWSTR)
    'PathCchAppendA',  # HRESULT (PSTR, ctypes.c_size_t, PCSTR)
    'PathCchAppendExA',  # HRESULT (PSTR, ctypes.c_size_t, PCSTR, ctypes.c_ulong)
    'PathCchAppendExW',  # HRESULT (PWSTR, ctypes.c_size_t, PCWSTR, ctypes.c_ulong)
    'PathCchAppendW',  # HRESULT (PWSTR, ctypes.c_size_t, PCWSTR)
    'PathCchCanonicalizeA',  # HRESULT (PSTR, ctypes.c_size_t, PCSTR)
    'PathCchCanonicalizeExA',  # HRESULT (PSTR, ctypes.c_size_t, PCSTR, ctypes.c_ulong)
    'PathCchCanonicalizeExW',  # HRESULT (PWSTR, ctypes.c_size_t, PCWSTR, ctypes.c_ulong)
    'PathCchCanonicalizeW',  # HRESULT (PWSTR, ctypes.c_size_t, PCWSTR)
    'PathCchCombineA',  # HRESULT (PSTR, ctypes.c_size_t, PCSTR, PCSTR)
    'PathCchCombineExA',  # HRESULT (PSTR, ctypes.c_size_t, PCSTR, PCSTR, ctypes.c_ulong)
    'PathCchCombineExW',  # HRESULT (PWSTR, ctypes.c_size_t, PCWSTR, PCWSTR, ctypes.c_ulong)
    'PathCchCombineW',  # HRESULT (PWSTR, ctypes.c_size_t, PCWSTR, PCWSTR)
    'PathCchFindExtensionA',  # HRESULT (PCSTR, ctypes.c_size_t, ctypes.POINTER(PCSTR))
    'PathCchFindExtensionW',  # HRESULT (PCWSTR, ctypes.c_size_t, ctypes.POINTER(PCWSTR))
    'PathCchIsRootA',  # BOOL (PCSTR)
    'PathCchIsRootW',  # BOOL (PCWSTR)
    'PathCchRemoveBackslashA',  # HRESULT (PSTR, ctypes.c_size_t)
    'PathCchRemoveBackslashExA',  # HRESULT (PSTR, ctypes.c_size_t, ctypes.POINTER(PSTR), ctypes.POINTER(ctypes.c_size_t))
    'PathCchRemoveBackslashExW',  # HRESULT (PWSTR, ctypes.c_size_t, ctypes.POINTER(PWSTR), ctypes.POINTER(ctypes.c_size_t))
    'PathCchRemoveBackslashW',  # HRESULT (PWSTR, ctypes.c_size_t)
    'PathCchRemoveExtensionA',  # HRESULT (PSTR, ctypes.c_size_t)
    'PathCchRemoveExtensionW',  # HRESULT (PWSTR, ctypes.c_size_t)
    'PathCchRemoveFileSpecA',  # HRESULT (PSTR, ctypes.c_size_t)
    'PathCchRemoveFileSpecW',  # HRESULT (PWSTR, ctypes.c_size_t)
    'PathCchRenameExtensionA',  # HRESULT (PSTR, ctypes.c_size_t, PCSTR)
    'PathCchRenameExtensionW',  # HRESULT (PWSTR, ctypes.c_size_t, PCWSTR)
    'PathCchSkipRootA',  # HRESULT (PCSTR, ctypes.POINTER(PCSTR))
    'PathCchSkipRootW',  # HRESULT (PCWSTR, ctypes.POINTER(PCWSTR))
    'PathCchStripPrefixA',  # HRESULT (PSTR, ctypes.c_size_t)
    'PathCchStripPrefixW',  # HRESULT (PWSTR, ctypes.c_size_t)
    'PathCchStripToRootA',  # HRESULT (PSTR, ctypes.c_size_t)
    'PathCchStripToRootW',  # HRESULT (PWSTR, ctypes.c_size_t)
    'PathIsUNCExA',  # BOOL (PCSTR, ctypes.POINTER(PCSTR))
    'PathIsUNCExW',  # BOOL (PCWSTR, ctypes.POINTER(PCWSTR))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'PATHCCH_ALLOW_LONG_PATHS', 'PATHCCH_MAX_CCH', 'VOLUME_PREFIX', 'bind']
