"""
Mirror of <winpr/path.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
KNOWN_PATH_HOME = 1
KNOWN_PATH_SYSTEM_CONFIG_HOME = 7
KNOWN_PATH_TEMP = 2
KNOWN_PATH_XDG_CACHE_HOME = 5
KNOWN_PATH_XDG_CONFIG_HOME = 4
KNOWN_PATH_XDG_DATA_HOME = 3
KNOWN_PATH_XDG_RUNTIME_DIR = 6
PATH_SHARED_LIB_EXT_APPLE_SO = 2
PATH_SHARED_LIB_EXT_EXPLICIT = 0x80000000
PATH_SHARED_LIB_EXT_EXPLICIT_DLL = 0x80000001
PATH_SHARED_LIB_EXT_EXPLICIT_DYLIB = 0x80000003
PATH_SHARED_LIB_EXT_EXPLICIT_SO = 0x80000002
PATH_SHARED_LIB_EXT_WITH_DOT = 1
PATH_STYLE_NATIVE = 3
PATH_STYLE_UNIX = 2
PATH_STYLE_WINDOWS = 1

# --- types declared in this header ---
eKnownPathTypes = _types.eKnownPathTypes

# --- functions declared in this header ---
FUNCTIONS = (
    'GetCombinedPath',  # ctypes.c_char_p (ctypes.c_char_p, ctypes.c_char_p)
    'GetCombinedPathV',  # ctypes.c_char_p (ctypes.c_char_p, ctypes.c_char_p, ...)
    'GetCombinedPathVA',  # ctypes.c_char_p (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_void_p)
    'GetEnvironmentPath',  # ctypes.c_char_p (ctypes.c_char_p)
    'GetEnvironmentSubPath',  # ctypes.c_char_p (ctypes.c_char_p, ctypes.c_char_p)
    'GetEnvironmentSubPathV',  # ctypes.c_char_p (ctypes.c_char_p, ctypes.c_char_p, ...)
    'GetEnvironmentSubPathVA',  # ctypes.c_char_p (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_void_p)
    'GetKnownPath',  # ctypes.c_char_p (eKnownPathTypes)
    'GetKnownPathIdString',  # ctypes.c_char_p (ctypes.c_int)
    'GetKnownSubPath',  # ctypes.c_char_p (eKnownPathTypes, ctypes.c_char_p)
    'GetKnownSubPathV',  # ctypes.c_char_p (eKnownPathTypes, ctypes.c_char_p, ...)
    'GetKnownSubPathVA',  # ctypes.c_char_p (eKnownPathTypes, ctypes.c_char_p, ctypes.c_void_p)
    'NativePathAllocCombineA',  # HRESULT (PCSTR, PCSTR, ctypes.c_ulong, ctypes.POINTER(PSTR))
    'NativePathAllocCombineW',  # HRESULT (PCWSTR, PCWSTR, ctypes.c_ulong, ctypes.POINTER(PWSTR))
    'NativePathCchAddExtensionA',  # HRESULT (PSTR, ctypes.c_size_t, PCSTR)
    'NativePathCchAddExtensionW',  # HRESULT (PWSTR, ctypes.c_size_t, PCWSTR)
    'NativePathCchAppendA',  # HRESULT (PSTR, ctypes.c_size_t, PCSTR)
    'NativePathCchAppendW',  # HRESULT (PWSTR, ctypes.c_size_t, PCWSTR)
    'PathCchAddSeparatorA',  # HRESULT (PSTR, ctypes.c_size_t)
    'PathCchAddSeparatorExA',  # HRESULT (PSTR, ctypes.c_size_t, ctypes.POINTER(PSTR), ctypes.POINTER(ctypes.c_size_t))
    'PathCchAddSeparatorExW',  # HRESULT (PWSTR, ctypes.c_size_t, ctypes.POINTER(PWSTR), ctypes.POINTER(ctypes.c_size_t))
    'PathCchAddSeparatorW',  # HRESULT (PWSTR, ctypes.c_size_t)
    'PathCchAddSlashA',  # HRESULT (PSTR, ctypes.c_size_t)
    'PathCchAddSlashExA',  # HRESULT (PSTR, ctypes.c_size_t, ctypes.POINTER(PSTR), ctypes.POINTER(ctypes.c_size_t))
    'PathCchAddSlashExW',  # HRESULT (PWSTR, ctypes.c_size_t, ctypes.POINTER(PWSTR), ctypes.POINTER(ctypes.c_size_t))
    'PathCchAddSlashW',  # HRESULT (PWSTR, ctypes.c_size_t)
    'PathCchConvertStyleA',  # HRESULT (PSTR, ctypes.c_size_t, ctypes.c_ulong)
    'PathCchConvertStyleW',  # HRESULT (PWSTR, ctypes.c_size_t, ctypes.c_ulong)
    'PathFileExistsA',  # BOOL (LPCSTR)
    'PathFileExistsW',  # BOOL (LPCWSTR)
    'PathGetSeparatorA',  # ctypes.c_char (ctypes.c_ulong)
    'PathGetSeparatorW',  # WCHAR (ctypes.c_ulong)
    'PathGetSharedLibraryExtensionA',  # PCSTR (ctypes.c_ulong)
    'PathGetSharedLibraryExtensionW',  # PCWSTR (ctypes.c_ulong)
    'PathIsDirectoryEmptyA',  # BOOL (LPCSTR)
    'PathIsDirectoryEmptyW',  # BOOL (LPCWSTR)
    'PathIsRelativeA',  # BOOL (LPCSTR)
    'PathIsRelativeW',  # BOOL (LPCWSTR)
    'PathMakePathA',  # BOOL (LPCSTR, LPSECURITY_ATTRIBUTES)
    'PathMakePathW',  # BOOL (LPCWSTR, LPSECURITY_ATTRIBUTES)
    'UnixPathAllocCombineA',  # HRESULT (PCSTR, PCSTR, ctypes.c_ulong, ctypes.POINTER(PSTR))
    'UnixPathAllocCombineW',  # HRESULT (PCWSTR, PCWSTR, ctypes.c_ulong, ctypes.POINTER(PWSTR))
    'UnixPathCchAddExtensionA',  # HRESULT (PSTR, ctypes.c_size_t, PCSTR)
    'UnixPathCchAddExtensionW',  # HRESULT (PWSTR, ctypes.c_size_t, PCWSTR)
    'UnixPathCchAppendA',  # HRESULT (PSTR, ctypes.c_size_t, PCSTR)
    'UnixPathCchAppendW',  # HRESULT (PWSTR, ctypes.c_size_t, PCWSTR)
    'winpr_DeleteFile',  # BOOL (ctypes.c_char_p)
    'winpr_GetConfigFilePath',  # ctypes.c_char_p (BOOL, ctypes.c_char_p)
    'winpr_GetConfigFilePathV',  # ctypes.c_char_p (BOOL, ctypes.c_char_p, ...)
    'winpr_GetConfigFilePathVA',  # ctypes.c_char_p (BOOL, ctypes.c_char_p, ctypes.c_void_p)
    'winpr_MoveFile',  # BOOL (LPCSTR, LPCSTR)
    'winpr_MoveFileEx',  # BOOL (LPCSTR, LPCSTR, DWORD)
    'winpr_PathFileExists',  # BOOL (ctypes.c_char_p)
    'winpr_PathMakePath',  # BOOL (ctypes.c_char_p, LPSECURITY_ATTRIBUTES)
    'winpr_RemoveDirectory',  # BOOL (LPCSTR)
    'winpr_RemoveDirectory_RecursiveA',  # BOOL (LPCSTR)
    'winpr_RemoveDirectory_RecursiveW',  # BOOL (LPCWSTR)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'KNOWN_PATH_HOME', 'KNOWN_PATH_SYSTEM_CONFIG_HOME', 'KNOWN_PATH_TEMP', 'KNOWN_PATH_XDG_CACHE_HOME', 'KNOWN_PATH_XDG_CONFIG_HOME', 'KNOWN_PATH_XDG_DATA_HOME', 'KNOWN_PATH_XDG_RUNTIME_DIR', 'PATH_SHARED_LIB_EXT_APPLE_SO', 'PATH_SHARED_LIB_EXT_EXPLICIT', 'PATH_SHARED_LIB_EXT_EXPLICIT_DLL', 'PATH_SHARED_LIB_EXT_EXPLICIT_DYLIB', 'PATH_SHARED_LIB_EXT_EXPLICIT_SO', 'PATH_SHARED_LIB_EXT_WITH_DOT', 'PATH_STYLE_NATIVE', 'PATH_STYLE_UNIX', 'PATH_STYLE_WINDOWS', 'bind', 'eKnownPathTypes']
