"""
Mirror of <winpr/platform.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

# --- #defines and enum members declared in this header ---
nullptr = 0

__all__ = ['nullptr']
