"""
Mirror of <winpr/pool.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
WINPR_CALLBACK_ENVIRON = 1
WINPR_THREAD_POOL = 1

# --- types declared in this header ---
PTP_CALLBACK_ENVIRON = _types.PTP_CALLBACK_ENVIRON
PTP_CALLBACK_INSTANCE = _types.PTP_CALLBACK_INSTANCE
PTP_CLEANUP_GROUP = _types.PTP_CLEANUP_GROUP
PTP_CLEANUP_GROUP_CANCEL_CALLBACK = _types.PTP_CLEANUP_GROUP_CANCEL_CALLBACK
PTP_IO = _types.PTP_IO
PTP_POOL = _types.PTP_POOL
PTP_POOL_STACK_INFORMATION = _types.PTP_POOL_STACK_INFORMATION
PTP_SIMPLE_CALLBACK = _types.PTP_SIMPLE_CALLBACK
PTP_TIMER = _types.PTP_TIMER
PTP_TIMER_CALLBACK = _types.PTP_TIMER_CALLBACK
PTP_VERSION = _types.PTP_VERSION
PTP_WAIT = _types.PTP_WAIT
PTP_WAIT_CALLBACK = _types.PTP_WAIT_CALLBACK
PTP_WIN32_IO_CALLBACK = _types.PTP_WIN32_IO_CALLBACK
PTP_WORK = _types.PTP_WORK
PTP_WORK_CALLBACK = _types.PTP_WORK_CALLBACK
TP_CALLBACK_ENVIRON = _types.TP_CALLBACK_ENVIRON
TP_CALLBACK_ENVIRON_V1 = _types.TP_CALLBACK_ENVIRON_V1
TP_CALLBACK_INSTANCE = _types.TP_CALLBACK_INSTANCE
TP_CLEANUP_GROUP = _types.TP_CLEANUP_GROUP
TP_IO = _types.TP_IO
TP_POOL = _types.TP_POOL
TP_POOL_STACK_INFORMATION = _types.TP_POOL_STACK_INFORMATION
TP_TIMER = _types.TP_TIMER
TP_VERSION = _types.TP_VERSION
TP_WAIT = _types.TP_WAIT
TP_WAIT_RESULT = _types.TP_WAIT_RESULT
TP_WORK = _types.TP_WORK
_anon_25 = _types._anon_25
_anon_26 = _types._anon_26
struct_TP_CALLBACK_ENVIRON_V1 = _types.struct_TP_CALLBACK_ENVIRON_V1
struct_TP_POOL_STACK_INFORMATION = _types.struct_TP_POOL_STACK_INFORMATION

# --- functions declared in this header ---
FUNCTIONS = (
    'winpr_CallbackMayRunLong',  # BOOL (PTP_CALLBACK_INSTANCE)
    'winpr_CancelThreadpoolIo',  # void (PTP_IO)
    'winpr_CloseThreadpool',  # void (PTP_POOL)
    'winpr_CloseThreadpoolCleanupGroup',  # void (PTP_CLEANUP_GROUP)
    'winpr_CloseThreadpoolCleanupGroupMembers',  # void (PTP_CLEANUP_GROUP, BOOL, PVOID)
    'winpr_CloseThreadpoolIo',  # void (PTP_IO)
    'winpr_CloseThreadpoolTimer',  # void (PTP_TIMER)
    'winpr_CloseThreadpoolWait',  # void (PTP_WAIT)
    'winpr_CloseThreadpoolWork',  # void (PTP_WORK)
    'winpr_CreateThreadpool',  # PTP_POOL (PVOID)
    'winpr_CreateThreadpoolCleanupGroup',  # PTP_CLEANUP_GROUP ()
    'winpr_CreateThreadpoolIo',  # PTP_IO (HANDLE, PTP_WIN32_IO_CALLBACK, PVOID, PTP_CALLBACK_ENVIRON)
    'winpr_CreateThreadpoolTimer',  # PTP_TIMER (PTP_TIMER_CALLBACK, PVOID, PTP_CALLBACK_ENVIRON)
    'winpr_CreateThreadpoolWait',  # PTP_WAIT (PTP_WAIT_CALLBACK, PVOID, PTP_CALLBACK_ENVIRON)
    'winpr_CreateThreadpoolWork',  # PTP_WORK (PTP_WORK_CALLBACK, PVOID, PTP_CALLBACK_ENVIRON)
    'winpr_DisassociateCurrentThreadFromCallback',  # void (PTP_CALLBACK_INSTANCE)
    'winpr_FreeLibraryWhenCallbackReturns',  # void (PTP_CALLBACK_INSTANCE, HMODULE)
    'winpr_IsThreadpoolTimerSet',  # BOOL (PTP_TIMER)
    'winpr_LeaveCriticalSectionWhenCallbackReturns',  # void (PTP_CALLBACK_INSTANCE, PCRITICAL_SECTION)
    'winpr_ReleaseMutexWhenCallbackReturns',  # void (PTP_CALLBACK_INSTANCE, HANDLE)
    'winpr_ReleaseSemaphoreWhenCallbackReturns',  # void (PTP_CALLBACK_INSTANCE, HANDLE, DWORD)
    'winpr_SetEventWhenCallbackReturns',  # void (PTP_CALLBACK_INSTANCE, HANDLE)
    'winpr_SetThreadpoolCallbackCleanupGroup',  # void (PTP_CALLBACK_ENVIRON, PTP_CLEANUP_GROUP, PTP_CLEANUP_GROUP_CANCEL_CALLBACK)
    'winpr_SetThreadpoolThreadMaximum',  # void (PTP_POOL, DWORD)
    'winpr_SetThreadpoolThreadMinimum',  # BOOL (PTP_POOL, DWORD)
    'winpr_SetThreadpoolTimer',  # void (PTP_TIMER, PFILETIME, DWORD, DWORD)
    'winpr_SetThreadpoolWait',  # void (PTP_WAIT, HANDLE, PFILETIME)
    'winpr_StartThreadpoolIo',  # void (PTP_IO)
    'winpr_SubmitThreadpoolWork',  # void (PTP_WORK)
    'winpr_TrySubmitThreadpoolCallback',  # BOOL (PTP_SIMPLE_CALLBACK, PVOID, PTP_CALLBACK_ENVIRON)
    'winpr_WaitForThreadpoolIoCallbacks',  # void (PTP_IO, BOOL)
    'winpr_WaitForThreadpoolTimerCallbacks',  # void (PTP_TIMER, BOOL)
    'winpr_WaitForThreadpoolWaitCallbacks',  # void (PTP_WAIT, BOOL)
    'winpr_WaitForThreadpoolWorkCallbacks',  # void (PTP_WORK, BOOL)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'PTP_CALLBACK_ENVIRON', 'PTP_CALLBACK_INSTANCE', 'PTP_CLEANUP_GROUP', 'PTP_CLEANUP_GROUP_CANCEL_CALLBACK', 'PTP_IO', 'PTP_POOL', 'PTP_POOL_STACK_INFORMATION', 'PTP_SIMPLE_CALLBACK', 'PTP_TIMER', 'PTP_TIMER_CALLBACK', 'PTP_VERSION', 'PTP_WAIT', 'PTP_WAIT_CALLBACK', 'PTP_WIN32_IO_CALLBACK', 'PTP_WORK', 'PTP_WORK_CALLBACK', 'TP_CALLBACK_ENVIRON', 'TP_CALLBACK_ENVIRON_V1', 'TP_CALLBACK_INSTANCE', 'TP_CLEANUP_GROUP', 'TP_IO', 'TP_POOL', 'TP_POOL_STACK_INFORMATION', 'TP_TIMER', 'TP_VERSION', 'TP_WAIT', 'TP_WAIT_RESULT', 'TP_WORK', 'WINPR_CALLBACK_ENVIRON', 'WINPR_THREAD_POOL', '_anon_25', '_anon_26', 'bind', 'struct_TP_CALLBACK_ENVIRON_V1', 'struct_TP_POOL_STACK_INFORMATION']
