"""
Mirror of <winpr/print.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
WINPR_HEXDUMP_LINE_LENGTH = 0x10

# --- functions declared in this header ---
FUNCTIONS = (
    'winpr_BinToHexString',  # ctypes.c_char_p (ctypes.c_void_p, ctypes.c_size_t, BOOL)
    'winpr_BinToHexStringBuffer',  # ctypes.c_size_t (ctypes.c_void_p, ctypes.c_size_t, ctypes.c_char_p, ctypes.c_size_t, BOOL)
    'winpr_CArrayDump',  # void (ctypes.c_char_p, UINT32, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_size_t)
    'winpr_HexDump',  # void (ctypes.c_char_p, UINT32, ctypes.c_void_p, ctypes.c_size_t)
    'winpr_HexLogDump',  # void (ctypes.POINTER(wLog), UINT32, ctypes.c_void_p, ctypes.c_size_t)
    'winpr_HexStringToBinBuffer',  # ctypes.c_size_t (ctypes.c_char_p, ctypes.c_size_t, ctypes.POINTER(BYTE), ctypes.c_size_t)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'WINPR_HEXDUMP_LINE_LENGTH', 'bind']
