"""
Mirror of <winpr/sam.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
WINPR_SAM = _types.WINPR_SAM
WINPR_SAM_ENTRY = _types.WINPR_SAM_ENTRY
struct_winpr_sam_entry = _types.struct_winpr_sam_entry

# --- functions declared in this header ---
FUNCTIONS = (
    'SamClose',  # void (ctypes.POINTER(WINPR_SAM))
    'SamFreeEntry',  # void (ctypes.POINTER(WINPR_SAM), ctypes.POINTER(WINPR_SAM_ENTRY))
    'SamLookupUserA',  # ctypes.POINTER(WINPR_SAM_ENTRY) (ctypes.POINTER(WINPR_SAM), LPCSTR, UINT32, LPCSTR, UINT32)
    'SamLookupUserW',  # ctypes.POINTER(WINPR_SAM_ENTRY) (ctypes.POINTER(WINPR_SAM), LPCWSTR, UINT32, LPCWSTR, UINT32)
    'SamOpen',  # ctypes.POINTER(WINPR_SAM) (ctypes.c_char_p, BOOL)
    'SamResetEntry',  # void (ctypes.POINTER(WINPR_SAM_ENTRY))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'WINPR_SAM', 'WINPR_SAM_ENTRY', 'bind', 'struct_winpr_sam_entry']
