"""
Mirror of <winpr/shell.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
FD_ACCESSTIME = 0x10
FD_ATTRIBUTES = 4
FD_CLSID = 1
FD_CREATETIME = 8
FD_FILESIZE = 0x40
FD_LINKUI = 0x8000
FD_PROGRESSUI = 0x4000
FD_SIZEPOINT = 2
FD_UNICODE = 0x80000000
FD_WRITESTIME = 0x20

# --- types declared in this header ---
FD_FLAGS = _types.FD_FLAGS
FILEDESCRIPTOR = _types.FILEDESCRIPTOR
FILEDESCRIPTORW = _types.FILEDESCRIPTORW
struct_FILEDESCRIPTOR = _types.struct_FILEDESCRIPTOR
struct_FILEDESCRIPTORW = _types.struct_FILEDESCRIPTORW

# --- functions declared in this header ---
FUNCTIONS = (
    'GetUserProfileDirectoryA',  # BOOL (HANDLE, LPSTR, LPDWORD)
    'GetUserProfileDirectoryW',  # BOOL (HANDLE, LPWSTR, LPDWORD)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FD_ACCESSTIME', 'FD_ATTRIBUTES', 'FD_CLSID', 'FD_CREATETIME', 'FD_FILESIZE', 'FD_FLAGS', 'FD_LINKUI', 'FD_PROGRESSUI', 'FD_SIZEPOINT', 'FD_UNICODE', 'FD_WRITESTIME', 'FILEDESCRIPTOR', 'FILEDESCRIPTORW', 'FUNCTIONS', 'bind', 'struct_FILEDESCRIPTOR', 'struct_FILEDESCRIPTORW']
