"""
Mirror of <winpr/spec.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

# --- #defines and enum members declared in this header ---
MAXBYTE = 0xff
MAXCHAR = 0x7f
MAXDWORD = 0xffffffff
MAXLONG = 0x7fffffff
MAXSHORT = 0x7fff
MAXWORD = 0xffff
MEMORY_ALLOCATION_ALIGNMENT = 0x10
MINCHAR = 0x80
MINLONG = 0x80000000
MINSHORT = 0x8000

__all__ = ['MAXBYTE', 'MAXCHAR', 'MAXDWORD', 'MAXLONG', 'MAXSHORT', 'MAXWORD', 'MEMORY_ALLOCATION_ALIGNMENT', 'MINCHAR', 'MINLONG', 'MINSHORT']
