"""
Mirror of <winpr/ssl.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
WINPR_SSL_CLEANUP_GLOBAL = 1
WINPR_SSL_CLEANUP_THREAD = 2
WINPR_SSL_INIT_ALREADY_INITIALIZED = 1
WINPR_SSL_INIT_DEFAULT = 0
WINPR_SSL_INIT_ENABLE_FIPS = 4
WINPR_SSL_INIT_ENABLE_LOCKING = 2

# --- functions declared in this header ---
FUNCTIONS = (
    'winpr_CleanupSSL',  # BOOL (DWORD)
    'winpr_FIPSMode',  # BOOL ()
    'winpr_InitializeSSL',  # BOOL (DWORD)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'WINPR_SSL_CLEANUP_GLOBAL', 'WINPR_SSL_CLEANUP_THREAD', 'WINPR_SSL_INIT_ALREADY_INITIALIZED', 'WINPR_SSL_INIT_DEFAULT', 'WINPR_SSL_INIT_ENABLE_FIPS', 'WINPR_SSL_INIT_ENABLE_LOCKING', 'bind']
