"""
Mirror of <winpr/sspicli.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
LOGON32_LOGON_BATCH = 4
LOGON32_LOGON_INTERACTIVE = 2
LOGON32_LOGON_NETWORK = 3
LOGON32_LOGON_NETWORK_CLEARTEXT = 8
LOGON32_LOGON_NEW_CREDENTIALS = 9
LOGON32_LOGON_SERVICE = 5
LOGON32_LOGON_UNLOCK = 7
LOGON32_PROVIDER_DEFAULT = 0
LOGON32_PROVIDER_VIRTUAL = 4
LOGON32_PROVIDER_WINNT35 = 1
LOGON32_PROVIDER_WINNT40 = 2
LOGON32_PROVIDER_WINNT50 = 3
NameCanonical = 7
NameCanonicalEx = 9
NameDisplay = 3
NameDnsDomain = 0xc
NameFullyQualifiedDN = 1
NameSamCompatible = 2
NameServicePrincipal = 0xa
NameUniqueId = 6
NameUnknown = 0
NameUserPrincipal = 8

# --- types declared in this header ---
EXTENDED_NAME_FORMAT = _types.EXTENDED_NAME_FORMAT
PEXTENDED_NAME_FORMAT = _types.PEXTENDED_NAME_FORMAT
PQUOTA_LIMITS = _types.PQUOTA_LIMITS
QUOTA_LIMITS = _types.QUOTA_LIMITS
struct_QUOTA_LIMITS = _types.struct_QUOTA_LIMITS

# --- functions declared in this header ---
FUNCTIONS = (
    'GetUserNameExA',  # BOOL (EXTENDED_NAME_FORMAT, LPSTR, PULONG)
    'GetUserNameExW',  # BOOL (EXTENDED_NAME_FORMAT, LPWSTR, PULONG)
    'LogonUserA',  # BOOL (LPCSTR, LPCSTR, LPCSTR, DWORD, DWORD, PHANDLE)
    'LogonUserExA',  # BOOL (LPCSTR, LPCSTR, LPCSTR, DWORD, DWORD, PHANDLE, ctypes.POINTER(PSID), ctypes.POINTER(PVOID), LPDWORD, PQUOTA_LIMITS)
    'LogonUserExW',  # BOOL (LPCWSTR, LPCWSTR, LPCWSTR, DWORD, DWORD, PHANDLE, ctypes.POINTER(PSID), ctypes.POINTER(PVOID), LPDWORD, PQUOTA_LIMITS)
    'LogonUserW',  # BOOL (LPCWSTR, LPCWSTR, LPCWSTR, DWORD, DWORD, PHANDLE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['EXTENDED_NAME_FORMAT', 'FUNCTIONS', 'LOGON32_LOGON_BATCH', 'LOGON32_LOGON_INTERACTIVE', 'LOGON32_LOGON_NETWORK', 'LOGON32_LOGON_NETWORK_CLEARTEXT', 'LOGON32_LOGON_NEW_CREDENTIALS', 'LOGON32_LOGON_SERVICE', 'LOGON32_LOGON_UNLOCK', 'LOGON32_PROVIDER_DEFAULT', 'LOGON32_PROVIDER_VIRTUAL', 'LOGON32_PROVIDER_WINNT35', 'LOGON32_PROVIDER_WINNT40', 'LOGON32_PROVIDER_WINNT50', 'NameCanonical', 'NameCanonicalEx', 'NameDisplay', 'NameDnsDomain', 'NameFullyQualifiedDN', 'NameSamCompatible', 'NameServicePrincipal', 'NameUniqueId', 'NameUnknown', 'NameUserPrincipal', 'PEXTENDED_NAME_FORMAT', 'PQUOTA_LIMITS', 'QUOTA_LIMITS', 'bind', 'struct_QUOTA_LIMITS']
