"""
Mirror of <winpr/stream.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
struct_wStream = _types.struct_wStream
wStream = _types.wStream
wStreamPool = _types.wStreamPool

# --- functions declared in this header ---
FUNCTIONS = (
    'StreamPool_Clear',  # void (ctypes.POINTER(wStreamPool))
    'StreamPool_Find',  # ctypes.POINTER(wStream) (ctypes.POINTER(wStreamPool), ctypes.POINTER(BYTE))
    'StreamPool_Free',  # void (ctypes.POINTER(wStreamPool))
    'StreamPool_GetStatistics',  # ctypes.c_char_p (ctypes.POINTER(wStreamPool), ctypes.c_char_p, ctypes.c_size_t)
    'StreamPool_New',  # ctypes.POINTER(wStreamPool) (BOOL, ctypes.c_size_t)
    'StreamPool_Return',  # void (ctypes.POINTER(wStreamPool), ctypes.POINTER(wStream))
    'StreamPool_Take',  # ctypes.POINTER(wStream) (ctypes.POINTER(wStreamPool), ctypes.c_size_t)
    'StreamPool_UsedCount',  # ctypes.c_size_t (ctypes.POINTER(wStreamPool))
    'StreamPool_WaitForReturn',  # BOOL (ctypes.POINTER(wStreamPool), UINT32)
    'Stream_AddRef',  # void (ctypes.POINTER(wStream))
    'Stream_CheckAndLogRequiredCapacityEx',  # BOOL (ctypes.c_char_p, DWORD, ctypes.POINTER(wStream), ctypes.c_size_t, ctypes.c_size_t, ctypes.c_char_p, ...)
    'Stream_CheckAndLogRequiredCapacityExVa',  # BOOL (ctypes.c_char_p, DWORD, ctypes.POINTER(wStream), ctypes.c_size_t, ctypes.c_size_t, ctypes.c_char_p, ctypes.c_void_p)
    'Stream_CheckAndLogRequiredCapacityWLogEx',  # BOOL (ctypes.POINTER(wLog), DWORD, ctypes.POINTER(wStream), ctypes.c_size_t, ctypes.c_size_t, ctypes.c_char_p, ...)
    'Stream_CheckAndLogRequiredCapacityWLogExVa',  # BOOL (ctypes.POINTER(wLog), DWORD, ctypes.POINTER(wStream), ctypes.c_size_t, ctypes.c_size_t, ctypes.c_char_p, ctypes.c_void_p)
    'Stream_CheckAndLogRequiredLengthEx',  # BOOL (ctypes.c_char_p, DWORD, ctypes.POINTER(wStream), ctypes.c_size_t, ctypes.c_size_t, ctypes.c_char_p, ...)
    'Stream_CheckAndLogRequiredLengthExVa',  # BOOL (ctypes.c_char_p, DWORD, ctypes.POINTER(wStream), ctypes.c_size_t, ctypes.c_size_t, ctypes.c_char_p, ctypes.c_void_p)
    'Stream_CheckAndLogRequiredLengthWLogEx',  # BOOL (ctypes.POINTER(wLog), DWORD, ctypes.POINTER(wStream), ctypes.c_size_t, ctypes.c_size_t, ctypes.c_char_p, ...)
    'Stream_CheckAndLogRequiredLengthWLogExVa',  # BOOL (ctypes.POINTER(wLog), DWORD, ctypes.POINTER(wStream), ctypes.c_size_t, ctypes.c_size_t, ctypes.c_char_p, ctypes.c_void_p)
    'Stream_EnsureCapacity',  # BOOL (ctypes.POINTER(wStream), ctypes.c_size_t)
    'Stream_EnsureRemainingCapacity',  # BOOL (ctypes.POINTER(wStream), ctypes.c_size_t)
    'Stream_Free',  # void (ctypes.POINTER(wStream), BOOL)
    'Stream_GetRemainingCapacity',  # ctypes.c_size_t (ctypes.POINTER(wStream))
    'Stream_GetRemainingLength',  # ctypes.c_size_t (ctypes.POINTER(wStream))
    'Stream_New',  # ctypes.POINTER(wStream) (ctypes.POINTER(BYTE), ctypes.c_size_t)
    'Stream_Read_UTF16_String',  # BOOL (ctypes.POINTER(wStream), ctypes.c_void_p, ctypes.c_size_t)
    'Stream_Read_UTF16_String_As_UTF8',  # ctypes.c_char_p (ctypes.POINTER(wStream), ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t))
    'Stream_Read_UTF16_String_As_UTF8_Buffer',  # SSIZE_T (ctypes.POINTER(wStream), ctypes.c_size_t, ctypes.c_char_p, ctypes.c_size_t)
    'Stream_Release',  # void (ctypes.POINTER(wStream))
    'Stream_SafeSeekEx',  # BOOL (ctypes.POINTER(wStream), ctypes.c_size_t, ctypes.c_char_p, ctypes.c_size_t, ctypes.c_char_p)
    'Stream_SafeZeroEx',  # BOOL (ctypes.POINTER(wStream), ctypes.c_size_t, ctypes.c_char_p, ctypes.c_size_t, ctypes.c_char_p)
    'Stream_SealLength',  # void (ctypes.POINTER(wStream))
    'Stream_SetLength',  # BOOL (ctypes.POINTER(wStream), ctypes.c_size_t)
    'Stream_SetPosition',  # BOOL (ctypes.POINTER(wStream), ctypes.c_size_t)
    'Stream_StaticConstInit',  # ctypes.POINTER(wStream) (ctypes.POINTER(wStream), ctypes.POINTER(BYTE), ctypes.c_size_t)
    'Stream_StaticInit',  # ctypes.POINTER(wStream) (ctypes.POINTER(wStream), ctypes.POINTER(BYTE), ctypes.c_size_t)
    'Stream_Write_UTF16_String',  # BOOL (ctypes.POINTER(wStream), ctypes.c_void_p, ctypes.c_size_t)
    'Stream_Write_UTF16_String_From_UTF8',  # SSIZE_T (ctypes.POINTER(wStream), ctypes.c_size_t, ctypes.c_char_p, ctypes.c_size_t, BOOL)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'struct_wStream', 'wStream', 'wStreamPool']
