"""
Mirror of <winpr/string.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
CP_ACP = 0
CP_MACCP = 2
CP_OEMCP = 1
CP_SYMBOL = 0x2a
CP_THREAD_ACP = 3
CP_UTF7 = 0xfde8
CP_UTF8 = 0xfde9
CSTR_EQUAL = 2
CSTR_GREATER_THAN = 3
CSTR_LESS_THAN = 1
MB_COMPOSITE = 2
MB_ERR_INVALID_CHARS = 8
MB_PRECOMPOSED = 1
MB_USEGLYPHCHARS = 4

# --- functions declared in this header ---
FUNCTIONS = (
    'ByteSwapUnicode',  # ctypes.c_void_p (ctypes.c_void_p, ctypes.c_size_t)
    'CharLowerA',  # LPSTR (LPSTR)
    'CharLowerBuffA',  # DWORD (LPSTR, DWORD)
    'CharLowerBuffW',  # DWORD (LPWSTR, DWORD)
    'CharLowerW',  # LPWSTR (LPWSTR)
    'CharUpperA',  # LPSTR (LPSTR)
    'CharUpperBuffA',  # DWORD (LPSTR, DWORD)
    'CharUpperBuffW',  # DWORD (LPWSTR, DWORD)
    'CharUpperW',  # LPWSTR (LPWSTR)
    'ConvertLineEndingToCRLF',  # ctypes.c_char_p (ctypes.c_char_p, ctypes.POINTER(ctypes.c_size_t))
    'ConvertLineEndingToLF',  # ctypes.c_size_t (ctypes.c_char_p, ctypes.c_size_t)
    'ConvertMszUtf8NToWChar',  # SSIZE_T (ctypes.c_char_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t)
    'ConvertMszUtf8NToWCharAlloc',  # ctypes.c_void_p (ctypes.c_char_p, ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t))
    'ConvertMszWCharNToUtf8',  # SSIZE_T (ctypes.c_void_p, ctypes.c_size_t, ctypes.c_char_p, ctypes.c_size_t)
    'ConvertMszWCharNToUtf8Alloc',  # ctypes.c_char_p (ctypes.c_void_p, ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t))
    'ConvertUtf8NToWChar',  # SSIZE_T (ctypes.c_char_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t)
    'ConvertUtf8NToWCharAlloc',  # ctypes.c_void_p (ctypes.c_char_p, ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t))
    'ConvertUtf8ToWChar',  # SSIZE_T (ctypes.c_char_p, ctypes.c_void_p, ctypes.c_size_t)
    'ConvertUtf8ToWCharAlloc',  # ctypes.c_void_p (ctypes.c_char_p, ctypes.POINTER(ctypes.c_size_t))
    'ConvertWCharNToUtf8',  # SSIZE_T (ctypes.c_void_p, ctypes.c_size_t, ctypes.c_char_p, ctypes.c_size_t)
    'ConvertWCharNToUtf8Alloc',  # ctypes.c_char_p (ctypes.c_void_p, ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t))
    'ConvertWCharToUtf8',  # SSIZE_T (ctypes.c_void_p, ctypes.c_char_p, ctypes.c_size_t)
    'ConvertWCharToUtf8Alloc',  # ctypes.c_char_p (ctypes.c_void_p, ctypes.POINTER(ctypes.c_size_t))
    'GetLine',  # INT64 (ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(ctypes.c_size_t), ctypes.c_void_p)
    'InitializeConstWCharFromUtf8',  # ctypes.c_void_p (ctypes.c_char_p, ctypes.c_void_p, ctypes.c_size_t)
    'IsCharAlphaA',  # BOOL (CHAR)
    'IsCharAlphaNumericA',  # BOOL (CHAR)
    'IsCharAlphaNumericW',  # BOOL (WCHAR)
    'IsCharAlphaW',  # BOOL (WCHAR)
    'IsCharLowerA',  # BOOL (CHAR)
    'IsCharLowerW',  # BOOL (WCHAR)
    'IsCharUpperA',  # BOOL (CHAR)
    'IsCharUpperW',  # BOOL (WCHAR)
    'StrSep',  # ctypes.c_char_p (ctypes.POINTER(ctypes.c_char_p), ctypes.c_char_p)
    '_strdup',  # ctypes.c_char_p (ctypes.c_char_p)
    '_stricmp',  # ctypes.c_int (ctypes.c_char_p, ctypes.c_char_p)
    '_strnicmp',  # ctypes.c_int (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_size_t)
    '_wcschr',  # ctypes.c_void_p (ctypes.c_void_p, WCHAR)
    '_wcscmp',  # ctypes.c_int (ctypes.c_void_p, ctypes.c_void_p)
    '_wcsdup',  # ctypes.c_void_p (ctypes.c_void_p)
    '_wcslen',  # ctypes.c_size_t (ctypes.c_void_p)
    '_wcsncat',  # ctypes.c_void_p (ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t)
    '_wcsncmp',  # ctypes.c_int (ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t)
    '_wcsnlen',  # ctypes.c_size_t (ctypes.c_void_p, ctypes.c_size_t)
    '_wcsrchr',  # ctypes.c_void_p (ctypes.c_void_p, WCHAR)
    '_wcsstr',  # ctypes.c_void_p (ctypes.c_void_p, ctypes.c_void_p)
    'strtok_s',  # ctypes.c_char_p (ctypes.c_char_p, ctypes.c_char_p, ctypes.POINTER(ctypes.c_char_p))
    'wcsndup',  # ctypes.c_void_p (ctypes.c_void_p, ctypes.c_size_t)
    'wcstok_s',  # ctypes.c_void_p (ctypes.c_void_p, ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p))
    'winpr_asprintf',  # ctypes.c_int (ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(ctypes.c_size_t), ctypes.c_char_p, ...)
    'winpr_str_append',  # BOOL (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_size_t, ctypes.c_char_p)
    'winpr_str_has_newlines',  # BOOL (ctypes.c_char_p)
    'winpr_str_is_valid_url',  # BOOL (ctypes.c_char_p)
    'winpr_str_is_valid_urlN',  # BOOL (ctypes.c_char_p, ctypes.c_size_t)
    'winpr_str_url_decode',  # ctypes.c_char_p (ctypes.c_char_p, ctypes.c_size_t)
    'winpr_str_url_encode',  # ctypes.c_char_p (ctypes.c_char_p, ctypes.c_size_t)
    'winpr_strnstr',  # ctypes.c_char_p (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_size_t)
    'winpr_vasprintf',  # ctypes.c_int (ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(ctypes.c_size_t), ctypes.c_char_p, ctypes.c_void_p)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['CP_ACP', 'CP_MACCP', 'CP_OEMCP', 'CP_SYMBOL', 'CP_THREAD_ACP', 'CP_UTF7', 'CP_UTF8', 'CSTR_EQUAL', 'CSTR_GREATER_THAN', 'CSTR_LESS_THAN', 'FUNCTIONS', 'MB_COMPOSITE', 'MB_ERR_INVALID_CHARS', 'MB_PRECOMPOSED', 'MB_USEGLYPHCHARS', 'bind']
