"""
Mirror of <winpr/strlst.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'string_list_copy',  # ctypes.POINTER(ctypes.c_char_p) (ctypes.POINTER(ctypes.c_char_p))
    'string_list_free',  # void (ctypes.POINTER(ctypes.c_char_p))
    'string_list_length',  # ctypes.c_int (ctypes.POINTER(ctypes.c_char_p))
    'string_list_print',  # void (ctypes.c_void_p, ctypes.POINTER(ctypes.c_char_p))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
