"""
Mirror of <winpr/tchar.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
TCHAR = _types.TCHAR

__all__ = ['TCHAR']
