"""
Mirror of <winpr/timezone.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
TIME_ZONE_ID_DAYLIGHT = 2
TIME_ZONE_ID_STANDARD = 1
TIME_ZONE_ID_UNKNOWN = 0

# --- types declared in this header ---
DYNAMIC_TIME_ZONE_INFORMATION = _types.DYNAMIC_TIME_ZONE_INFORMATION
LPDYNAMIC_TIME_ZONE_INFORMATION = _types.LPDYNAMIC_TIME_ZONE_INFORMATION
LPTIME_ZONE_INFORMATION = _types.LPTIME_ZONE_INFORMATION
PDYNAMIC_TIME_ZONE_INFORMATION = _types.PDYNAMIC_TIME_ZONE_INFORMATION
PTIME_ZONE_INFORMATION = _types.PTIME_ZONE_INFORMATION
TIME_ZONE_INFORMATION = _types.TIME_ZONE_INFORMATION
struct_DYNAMIC_TIME_ZONE_INFORMATION = _types.struct_DYNAMIC_TIME_ZONE_INFORMATION
struct_TIME_ZONE_INFORMATION = _types.struct_TIME_ZONE_INFORMATION

# --- functions declared in this header ---
FUNCTIONS = (
    'EnumDynamicTimeZoneInformation',  # DWORD (DWORD, PDYNAMIC_TIME_ZONE_INFORMATION)
    'FileTimeToSystemTime',  # BOOL (ctypes.POINTER(FILETIME), LPSYSTEMTIME)
    'GetDynamicTimeZoneInformation',  # DWORD (PDYNAMIC_TIME_ZONE_INFORMATION)
    'GetDynamicTimeZoneInformationEffectiveYears',  # DWORD (ctypes.POINTER(DYNAMIC_TIME_ZONE_INFORMATION), LPDWORD, LPDWORD)
    'GetTimeZoneInformation',  # DWORD (LPTIME_ZONE_INFORMATION)
    'GetTimeZoneInformationForYear',  # BOOL (USHORT, PDYNAMIC_TIME_ZONE_INFORMATION, LPTIME_ZONE_INFORMATION)
    'SetDynamicTimeZoneInformation',  # BOOL (ctypes.POINTER(DYNAMIC_TIME_ZONE_INFORMATION))
    'SetTimeZoneInformation',  # BOOL (ctypes.POINTER(TIME_ZONE_INFORMATION))
    'SystemTimeToFileTime',  # BOOL (ctypes.POINTER(SYSTEMTIME), LPFILETIME)
    'SystemTimeToTzSpecificLocalTime',  # BOOL (LPTIME_ZONE_INFORMATION, LPSYSTEMTIME, LPSYSTEMTIME)
    'SystemTimeToTzSpecificLocalTimeEx',  # BOOL (ctypes.POINTER(DYNAMIC_TIME_ZONE_INFORMATION), ctypes.POINTER(SYSTEMTIME), LPSYSTEMTIME)
    'TzSpecificLocalTimeToSystemTime',  # BOOL (LPTIME_ZONE_INFORMATION, LPSYSTEMTIME, LPSYSTEMTIME)
    'TzSpecificLocalTimeToSystemTimeEx',  # BOOL (ctypes.POINTER(DYNAMIC_TIME_ZONE_INFORMATION), ctypes.POINTER(SYSTEMTIME), LPSYSTEMTIME)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['DYNAMIC_TIME_ZONE_INFORMATION', 'FUNCTIONS', 'LPDYNAMIC_TIME_ZONE_INFORMATION', 'LPTIME_ZONE_INFORMATION', 'PDYNAMIC_TIME_ZONE_INFORMATION', 'PTIME_ZONE_INFORMATION', 'TIME_ZONE_ID_DAYLIGHT', 'TIME_ZONE_ID_STANDARD', 'TIME_ZONE_ID_UNKNOWN', 'TIME_ZONE_INFORMATION', 'bind', 'struct_DYNAMIC_TIME_ZONE_INFORMATION', 'struct_TIME_ZONE_INFORMATION']
