"""
Mirror of <winpr/version.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

# --- #defines and enum members declared in this header ---
WINPR_API_VERSION = '3'
WINPR_GIT_REVISION = 'n/a'
WINPR_VERSION = '3.31.1'
WINPR_VERSION_FULL = '3.31.1'
WINPR_VERSION_MAJOR = 3
WINPR_VERSION_MINOR = 0x1f
WINPR_VERSION_REVISION = 1
WINPR_VERSION_SUFFIX = ''

__all__ = ['WINPR_API_VERSION', 'WINPR_GIT_REVISION', 'WINPR_VERSION', 'WINPR_VERSION_FULL', 'WINPR_VERSION_MAJOR', 'WINPR_VERSION_MINOR', 'WINPR_VERSION_REVISION', 'WINPR_VERSION_SUFFIX']
