"""
Mirror of <winpr/winpr.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'winpr_getApplicationDetailsProduct',  # ctypes.c_char_p ()
    'winpr_getApplicationDetailsVendor',  # ctypes.c_char_p ()
    'winpr_getApplicationDetailsVersion',  # SSIZE_T ()
    'winpr_get_build_config',  # ctypes.c_char_p ()
    'winpr_get_build_revision',  # ctypes.c_char_p ()
    'winpr_get_version',  # void (ctypes.POINTER(ctypes.c_int), ctypes.POINTER(ctypes.c_int), ctypes.POINTER(ctypes.c_int))
    'winpr_get_version_string',  # ctypes.c_char_p ()
    'winpr_setApplicationDetails',  # BOOL (ctypes.c_char_p, ctypes.c_char_p, SSIZE_T)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
