"""
Mirror of <winpr/winsock.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
FD_ACCEPT = 8
FD_ACCEPT_BIT = 3
FD_ADDRESS_LIST_CHANGE = 0x200
FD_ADDRESS_LIST_CHANGE_BIT = 9
FD_ALL_EVENTS = 0x3ff
FD_CLOSE = 0x20
FD_CLOSE_BIT = 5
FD_CONNECT = 0x10
FD_CONNECT_BIT = 4
FD_GROUP_QOS = 0x80
FD_GROUP_QOS_BIT = 7
FD_MAX_EVENTS = 0xa
FD_OOB = 4
FD_OOB_BIT = 2
FD_QOS = 0x40
FD_QOS_BIT = 6
FD_READ = 1
FD_READ_BIT = 0
FD_ROUTING_INTERFACE_CHANGE = 0x100
FD_ROUTING_INTERFACE_CHANGE_BIT = 8
FD_WRITE = 2
FD_WRITE_BIT = 1
MAX_PROTOCOL_CHAIN = 7
SD_BOTH = 2
SD_RECEIVE = 0
SD_SEND = 1
SG_CONSTRAINED_GROUP = 2
SG_UNCONSTRAINED_GROUP = 1
SOCKET_ERROR = -1
WSADESCRIPTION_LEN = 0x100
WSAPROTOCOL_LEN = 0xff
WSASYS_STATUS_LEN = 0x80

# --- types declared in this header ---
GROUP = _types.GROUP
IN6_ADDR = _types.IN6_ADDR
INTERFACE_INFO = _types.INTERFACE_INFO
LPIN6_ADDR = _types.LPIN6_ADDR
LPINTERFACE_INFO = _types.LPINTERFACE_INFO
LPWSADATA = _types.LPWSADATA
LPWSAOVERLAPPED = _types.LPWSAOVERLAPPED
LPWSAOVERLAPPED_COMPLETION_ROUTINE = _types.LPWSAOVERLAPPED_COMPLETION_ROUTINE
LPWSAPROTOCOLCHAIN = _types.LPWSAPROTOCOLCHAIN
LPWSAPROTOCOL_INFOA = _types.LPWSAPROTOCOL_INFOA
LPWSAPROTOCOL_INFOW = _types.LPWSAPROTOCOL_INFOW
PIN6_ADDR = _types.PIN6_ADDR
SOCKADDR_STORAGE = _types.SOCKADDR_STORAGE
SOCKET = _types.SOCKET
WSADATA = _types.WSADATA
WSAPROTOCOLCHAIN = _types.WSAPROTOCOLCHAIN
WSAPROTOCOL_INFOA = _types.WSAPROTOCOL_INFOA
WSAPROTOCOL_INFOW = _types.WSAPROTOCOL_INFOW
sockaddr_gen = _types.sockaddr_gen
struct_INTERFACE_INFO = _types.struct_INTERFACE_INFO
struct_WSAData = _types.struct_WSAData
struct_WSAPROTOCOLCHAIN = _types.struct_WSAPROTOCOLCHAIN
struct_WSAPROTOCOL_INFOA = _types.struct_WSAPROTOCOL_INFOA
struct_WSAPROTOCOL_INFOW = _types.struct_WSAPROTOCOL_INFOW
struct_sockaddr_gen = _types.struct_sockaddr_gen
struct_sockaddr_in6_old = _types.struct_sockaddr_in6_old

# --- functions declared in this header ---
FUNCTIONS = (
    'WSACleanup',  # ctypes.c_int ()
    'WSACloseEvent',  # BOOL (HANDLE)
    'WSACreateEvent',  # HANDLE ()
    'WSAEventSelect',  # ctypes.c_int (SOCKET, HANDLE, LONG)
    'WSAGetLastError',  # ctypes.c_int ()
    'WSAIoctl',  # ctypes.c_int (SOCKET, DWORD, LPVOID, DWORD, LPVOID, DWORD, LPDWORD, LPWSAOVERLAPPED, LPWSAOVERLAPPED_COMPLETION_ROUTINE)
    'WSAResetEvent',  # BOOL (HANDLE)
    'WSASetEvent',  # BOOL (HANDLE)
    'WSASetLastError',  # void (ctypes.c_int)
    'WSASocketA',  # SOCKET (ctypes.c_int, ctypes.c_int, ctypes.c_int, LPWSAPROTOCOL_INFOA, GROUP, DWORD)
    'WSASocketW',  # SOCKET (ctypes.c_int, ctypes.c_int, ctypes.c_int, LPWSAPROTOCOL_INFOW, GROUP, DWORD)
    'WSAStartup',  # ctypes.c_int (WORD, LPWSADATA)
    'WSAWaitForMultipleEvents',  # DWORD (DWORD, ctypes.POINTER(HANDLE), BOOL, DWORD, BOOL)
    '_accept',  # SOCKET (SOCKET, ctypes.POINTER(struct_sockaddr), ctypes.POINTER(ctypes.c_int))
    '_bind',  # ctypes.c_int (SOCKET, ctypes.POINTER(struct_sockaddr), ctypes.c_int)
    '_connect',  # ctypes.c_int (SOCKET, ctypes.POINTER(struct_sockaddr), ctypes.c_int)
    '_gethostbyaddr',  # ctypes.POINTER(struct_hostent) (ctypes.c_char_p, ctypes.c_int, ctypes.c_int)
    '_gethostbyname',  # ctypes.POINTER(struct_hostent) (ctypes.c_char_p)
    '_gethostname',  # ctypes.c_int (ctypes.c_char_p, ctypes.c_int)
    '_getpeername',  # ctypes.c_int (SOCKET, ctypes.POINTER(struct_sockaddr), ctypes.POINTER(ctypes.c_int))
    '_getprotobyname',  # ctypes.POINTER(struct_protoent) (ctypes.c_char_p)
    '_getprotobynumber',  # ctypes.POINTER(struct_protoent) (ctypes.c_int)
    '_getservbyname',  # ctypes.POINTER(struct_servent) (ctypes.c_char_p, ctypes.c_char_p)
    '_getservbyport',  # ctypes.POINTER(struct_servent) (ctypes.c_int, ctypes.c_char_p)
    '_getsockname',  # ctypes.c_int (SOCKET, ctypes.POINTER(struct_sockaddr), ctypes.POINTER(ctypes.c_int))
    '_getsockopt',  # ctypes.c_int (SOCKET, ctypes.c_int, ctypes.c_int, ctypes.c_char_p, ctypes.POINTER(ctypes.c_int))
    '_htonl',  # u_long (u_long)
    '_htons',  # u_short (u_short)
    '_inet_addr',  # ctypes.c_ulong (ctypes.c_char_p)
    '_inet_ntoa',  # ctypes.c_char_p (struct_in_addr)
    '_ioctlsocket',  # ctypes.c_int (SOCKET, ctypes.c_long, ctypes.POINTER(u_long))
    '_listen',  # ctypes.c_int (SOCKET, ctypes.c_int)
    '_ntohl',  # u_long (u_long)
    '_ntohs',  # u_short (u_short)
    '_recv',  # ctypes.c_int (SOCKET, ctypes.c_char_p, ctypes.c_int, ctypes.c_int)
    '_recvfrom',  # ctypes.c_int (SOCKET, ctypes.c_char_p, ctypes.c_int, ctypes.c_int, ctypes.POINTER(struct_sockaddr), ctypes.POINTER(ctypes.c_int))
    '_select',  # ctypes.c_int (ctypes.c_int, ctypes.POINTER(fd_set), ctypes.POINTER(fd_set), ctypes.POINTER(fd_set), ctypes.POINTER(struct_timeval))
    '_send',  # ctypes.c_int (SOCKET, ctypes.c_char_p, ctypes.c_int, ctypes.c_int)
    '_sendto',  # ctypes.c_int (SOCKET, ctypes.c_char_p, ctypes.c_int, ctypes.c_int, ctypes.POINTER(struct_sockaddr), ctypes.c_int)
    '_setsockopt',  # ctypes.c_int (SOCKET, ctypes.c_int, ctypes.c_int, ctypes.c_char_p, ctypes.c_int)
    '_shutdown',  # ctypes.c_int (SOCKET, ctypes.c_int)
    '_socket',  # SOCKET (ctypes.c_int, ctypes.c_int, ctypes.c_int)
    'closesocket',  # ctypes.c_int (SOCKET)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FD_ACCEPT', 'FD_ACCEPT_BIT', 'FD_ADDRESS_LIST_CHANGE', 'FD_ADDRESS_LIST_CHANGE_BIT', 'FD_ALL_EVENTS', 'FD_CLOSE', 'FD_CLOSE_BIT', 'FD_CONNECT', 'FD_CONNECT_BIT', 'FD_GROUP_QOS', 'FD_GROUP_QOS_BIT', 'FD_MAX_EVENTS', 'FD_OOB', 'FD_OOB_BIT', 'FD_QOS', 'FD_QOS_BIT', 'FD_READ', 'FD_READ_BIT', 'FD_ROUTING_INTERFACE_CHANGE', 'FD_ROUTING_INTERFACE_CHANGE_BIT', 'FD_WRITE', 'FD_WRITE_BIT', 'FUNCTIONS', 'GROUP', 'IN6_ADDR', 'INTERFACE_INFO', 'LPIN6_ADDR', 'LPINTERFACE_INFO', 'LPWSADATA', 'LPWSAOVERLAPPED', 'LPWSAOVERLAPPED_COMPLETION_ROUTINE', 'LPWSAPROTOCOLCHAIN', 'LPWSAPROTOCOL_INFOA', 'LPWSAPROTOCOL_INFOW', 'MAX_PROTOCOL_CHAIN', 'PIN6_ADDR', 'SD_BOTH', 'SD_RECEIVE', 'SD_SEND', 'SG_CONSTRAINED_GROUP', 'SG_UNCONSTRAINED_GROUP', 'SOCKADDR_STORAGE', 'SOCKET', 'SOCKET_ERROR', 'WSADATA', 'WSADESCRIPTION_LEN', 'WSAPROTOCOLCHAIN', 'WSAPROTOCOL_INFOA', 'WSAPROTOCOL_INFOW', 'WSAPROTOCOL_LEN', 'WSASYS_STATUS_LEN', 'bind', 'sockaddr_gen', 'struct_INTERFACE_INFO', 'struct_WSAData', 'struct_WSAPROTOCOLCHAIN', 'struct_WSAPROTOCOL_INFOA', 'struct_WSAPROTOCOL_INFOW', 'struct_sockaddr_gen', 'struct_sockaddr_in6_old']
