"""
Mirror of <winpr/wlog.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
WLOG_APPENDER_BINARY = 2
WLOG_APPENDER_CALLBACK = 3
WLOG_APPENDER_CONSOLE = 0
WLOG_APPENDER_FILE = 1
WLOG_APPENDER_JOURNALD = 5
WLOG_APPENDER_SYSLOG = 4
WLOG_APPENDER_UDP = 6
WLOG_DEBUG = 1
WLOG_ERROR = 4
WLOG_FATAL = 5
WLOG_INFO = 2
WLOG_LEVEL_INHERIT = 0xffff
WLOG_MESSAGE_DATA = 1
WLOG_MESSAGE_IMAGE = 2
WLOG_MESSAGE_PACKET = 3
WLOG_MESSAGE_TEXT = 0
WLOG_OFF = 6
WLOG_PACKET_INBOUND = 1
WLOG_PACKET_OUTBOUND = 2
WLOG_TRACE = 0
WLOG_WARN = 3

# --- types declared in this header ---
struct_wLogCallbacks = _types.struct_wLogCallbacks
struct_wLogCallbacksEx = _types.struct_wLogCallbacksEx
struct_wLogMessage = _types.struct_wLogMessage
wLog = _types.wLog
wLogAppender = _types.wLogAppender
wLogAppenderType = _types.wLogAppenderType
wLogCallbackData_t = _types.wLogCallbackData_t
wLogCallbackImage_t = _types.wLogCallbackImage_t
wLogCallbackMessageEx_t = _types.wLogCallbackMessageEx_t
wLogCallbackMessage_t = _types.wLogCallbackMessage_t
wLogCallbackPackage_t = _types.wLogCallbackPackage_t
wLogCallbacks = _types.wLogCallbacks
wLogCallbacksEx = _types.wLogCallbacksEx
wLogLayout = _types.wLogLayout
wLogLevel = _types.wLogLevel
wLogMessage = _types.wLogMessage
wLogMessageType = _types.wLogMessageType

# --- functions declared in this header ---
FUNCTIONS = (
    'WLog_AddStringLogFilters',  # BOOL (LPCSTR)
    'WLog_CloseAppender',  # BOOL (ctypes.POINTER(wLog))
    'WLog_ConfigureAppender',  # BOOL (ctypes.POINTER(wLogAppender), ctypes.c_char_p, ctypes.c_void_p)
    'WLog_Create',  # ctypes.POINTER(wLog) (LPCSTR, ctypes.POINTER(wLog))
    'WLog_Discard',  # void (ctypes.POINTER(wLog))
    'WLog_Get',  # ctypes.POINTER(wLog) (LPCSTR)
    'WLog_GetAppenderContext',  # ctypes.c_void_p (ctypes.POINTER(wLogAppender), wLogMessageType)
    'WLog_GetLogAppender',  # ctypes.POINTER(wLogAppender) (ctypes.POINTER(wLog))
    'WLog_GetLogLayout',  # ctypes.POINTER(wLogLayout) (ctypes.POINTER(wLog))
    'WLog_GetLogLevel',  # DWORD (ctypes.POINTER(wLog))
    'WLog_GetRoot',  # ctypes.POINTER(wLog) ()
    'WLog_IsLevelActive',  # BOOL (ctypes.POINTER(wLog), DWORD)
    'WLog_Layout_SetPrefixFormat',  # BOOL (ctypes.POINTER(wLog), ctypes.POINTER(wLogLayout), ctypes.c_char_p)
    'WLog_OpenAppender',  # BOOL (ctypes.POINTER(wLog))
    'WLog_PrintMessage',  # BOOL (ctypes.POINTER(wLog), DWORD, DWORD, ctypes.c_size_t, ctypes.c_char_p, ctypes.c_char_p, ...)
    'WLog_PrintMessageVA',  # BOOL (ctypes.POINTER(wLog), DWORD, DWORD, ctypes.c_size_t, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_void_p)
    'WLog_PrintTextMessage',  # BOOL (ctypes.POINTER(wLog), DWORD, ctypes.c_size_t, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p, ...)
    'WLog_PrintTextMessageVA',  # BOOL (ctypes.POINTER(wLog), DWORD, ctypes.c_size_t, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_void_p)
    'WLog_SetAppenderContext',  # BOOL (ctypes.POINTER(wLogAppender), wLogMessageType, ctypes.c_void_p)
    'WLog_SetContext',  # BOOL (ctypes.POINTER(wLog), ctypes.CFUNCTYPE(ctypes.c_char_p, ctypes.c_void_p), ctypes.c_void_p)
    'WLog_SetGlobalContext',  # BOOL (ctypes.c_char_p)
    'WLog_SetLogAppenderType',  # BOOL (ctypes.POINTER(wLog), DWORD)
    'WLog_SetLogLevel',  # BOOL (ctypes.POINTER(wLog), DWORD)
    'WLog_SetStringLogLevel',  # BOOL (ctypes.POINTER(wLog), LPCSTR)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'WLOG_APPENDER_BINARY', 'WLOG_APPENDER_CALLBACK', 'WLOG_APPENDER_CONSOLE', 'WLOG_APPENDER_FILE', 'WLOG_APPENDER_JOURNALD', 'WLOG_APPENDER_SYSLOG', 'WLOG_APPENDER_UDP', 'WLOG_DEBUG', 'WLOG_ERROR', 'WLOG_FATAL', 'WLOG_INFO', 'WLOG_LEVEL_INHERIT', 'WLOG_MESSAGE_DATA', 'WLOG_MESSAGE_IMAGE', 'WLOG_MESSAGE_PACKET', 'WLOG_MESSAGE_TEXT', 'WLOG_OFF', 'WLOG_PACKET_INBOUND', 'WLOG_PACKET_OUTBOUND', 'WLOG_TRACE', 'WLOG_WARN', 'bind', 'struct_wLogCallbacks', 'struct_wLogCallbacksEx', 'struct_wLogMessage', 'wLog', 'wLogAppender', 'wLogAppenderType', 'wLogCallbackData_t', 'wLogCallbackImage_t', 'wLogCallbackMessageEx_t', 'wLogCallbackMessage_t', 'wLogCallbackPackage_t', 'wLogCallbacks', 'wLogCallbacksEx', 'wLogLayout', 'wLogLevel', 'wLogMessage', 'wLogMessageType']
