"""
Mirror of <freerdp/addin.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
FREERDP_ADDIN_CHANNEL_DEVICE = 0x4000
FREERDP_ADDIN_CHANNEL_DYNAMIC = 0x2000
FREERDP_ADDIN_CHANNEL_ENTRYEX = 0x8000
FREERDP_ADDIN_CHANNEL_STATIC = 0x1000
FREERDP_ADDIN_CLIENT = 1
FREERDP_ADDIN_DYNAMIC = 0x20
FREERDP_ADDIN_NAME = 0x100
FREERDP_ADDIN_SERVER = 2
FREERDP_ADDIN_STATIC = 0x10
FREERDP_ADDIN_SUBSYSTEM = 0x200
FREERDP_ADDIN_TYPE = 0x400

# --- types declared in this header ---
FREERDP_ADDIN = _types.FREERDP_ADDIN
FREERDP_LOAD_CHANNEL_ADDIN_ENTRY_FN = _types.FREERDP_LOAD_CHANNEL_ADDIN_ENTRY_FN
struct_FREERDP_ADDIN = _types.struct_FREERDP_ADDIN

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_get_current_addin_provider',  # FREERDP_LOAD_CHANNEL_ADDIN_ENTRY_FN ()
    'freerdp_get_dynamic_addin_install_path',  # LPSTR ()
    'freerdp_get_library_install_path',  # LPSTR ()
    'freerdp_load_channel_addin_entry',  # PVIRTUALCHANNELENTRY (LPCSTR, LPCSTR, LPCSTR, DWORD)
    'freerdp_load_dynamic_addin',  # PVIRTUALCHANNELENTRY (LPCSTR, LPCSTR, LPCSTR)
    'freerdp_load_dynamic_channel_addin_entry',  # PVIRTUALCHANNELENTRY (LPCSTR, LPCSTR, LPCSTR, DWORD)
    'freerdp_register_addin_provider',  # ctypes.c_int (FREERDP_LOAD_CHANNEL_ADDIN_ENTRY_FN, DWORD)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FREERDP_ADDIN', 'FREERDP_ADDIN_CHANNEL_DEVICE', 'FREERDP_ADDIN_CHANNEL_DYNAMIC', 'FREERDP_ADDIN_CHANNEL_ENTRYEX', 'FREERDP_ADDIN_CHANNEL_STATIC', 'FREERDP_ADDIN_CLIENT', 'FREERDP_ADDIN_DYNAMIC', 'FREERDP_ADDIN_NAME', 'FREERDP_ADDIN_SERVER', 'FREERDP_ADDIN_STATIC', 'FREERDP_ADDIN_SUBSYSTEM', 'FREERDP_ADDIN_TYPE', 'FREERDP_LOAD_CHANNEL_ADDIN_ENTRY_FN', 'FUNCTIONS', 'bind', 'struct_FREERDP_ADDIN']
