"""
Mirror of <freerdp/assistance.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
rdpAssistanceFile = _types.rdpAssistanceFile

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_assistance_bin_to_hex_string',  # ctypes.c_char_p (ctypes.c_void_p, ctypes.c_size_t)
    'freerdp_assistance_construct_expert_blob',  # ctypes.c_char_p (ctypes.c_char_p, ctypes.c_char_p)
    'freerdp_assistance_encrypt_pass_stub',  # ctypes.POINTER(BYTE) (ctypes.c_char_p, ctypes.c_char_p, ctypes.POINTER(ctypes.c_size_t))
    'freerdp_assistance_file_free',  # void (ctypes.POINTER(rdpAssistanceFile))
    'freerdp_assistance_file_new',  # ctypes.POINTER(rdpAssistanceFile) ()
    'freerdp_assistance_generate_pass_stub',  # ctypes.c_char_p (DWORD)
    'freerdp_assistance_get_encrypted_pass_stub',  # BOOL (ctypes.POINTER(rdpAssistanceFile), ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(ctypes.c_size_t))
    'freerdp_assistance_hex_string_to_bin',  # ctypes.POINTER(BYTE) (ctypes.c_void_p, ctypes.POINTER(ctypes.c_size_t))
    'freerdp_assistance_parse_file',  # ctypes.c_int (ctypes.POINTER(rdpAssistanceFile), ctypes.c_char_p, ctypes.c_char_p)
    'freerdp_assistance_parse_file_buffer',  # ctypes.c_int (ctypes.POINTER(rdpAssistanceFile), ctypes.c_char_p, ctypes.c_size_t, ctypes.c_char_p)
    'freerdp_assistance_populate_settings_from_assistance_file',  # BOOL (ctypes.POINTER(rdpAssistanceFile), ctypes.POINTER(rdpSettings))
    'freerdp_assistance_print_file',  # void (ctypes.POINTER(rdpAssistanceFile), ctypes.POINTER(wLog), DWORD)
    'freerdp_assistance_set_connection_string2',  # ctypes.c_int (ctypes.POINTER(rdpAssistanceFile), ctypes.c_char_p, ctypes.c_char_p)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'rdpAssistanceFile']
