"""
Mirror of <freerdp/autodetect.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
FREERDP_AUTODETECT_STATE_COMPLETE = 3
FREERDP_AUTODETECT_STATE_FAIL = 4
FREERDP_AUTODETECT_STATE_INITIAL = 0
FREERDP_AUTODETECT_STATE_REQUEST = 1
FREERDP_AUTODETECT_STATE_RESPONSE = 2
RDP_BW_RESULTS_RESPONSE_TYPE_CONNECTTIME = 3
RDP_BW_RESULTS_RESPONSE_TYPE_CONTINUOUS = 0xb
RDP_NETCHAR_RESERVED = 0
RDP_NETCHAR_RESULT_TYPE_BASE_RTT_AVG_RTT = 0x840
RDP_NETCHAR_RESULT_TYPE_BASE_RTT_BW_AVG_RTT = 0x8c0
RDP_NETCHAR_RESULT_TYPE_BW_AVG_RTT = 0x880

# --- types declared in this header ---
FREERDP_AUTODETECT_STATE = _types.FREERDP_AUTODETECT_STATE
RDP_BW_RESULTS_RESPONSE_TYPE = _types.RDP_BW_RESULTS_RESPONSE_TYPE
RDP_NETCHAR_RESULT_TYPE = _types.RDP_NETCHAR_RESULT_TYPE
pBandwidthMeasurePayload = _types.pBandwidthMeasurePayload
pBandwidthMeasureResults = _types.pBandwidthMeasureResults
pBandwidthMeasureStart = _types.pBandwidthMeasureStart
pBandwidthMeasureStop = _types.pBandwidthMeasureStop
pClientBandwidthMeasureResult = _types.pClientBandwidthMeasureResult
pNetworkCharacteristicsResult = _types.pNetworkCharacteristicsResult
pNetworkCharacteristicsSync = _types.pNetworkCharacteristicsSync
pOnConnectTimeAutoDetect = _types.pOnConnectTimeAutoDetect
pRTTMeasureRequest = _types.pRTTMeasureRequest
pRTTMeasureResponse = _types.pRTTMeasureResponse
pRxTxReceived = _types.pRxTxReceived
rdpAutoDetect = _types.rdpAutoDetect
rdpNetworkCharacteristicsResult = _types.rdpNetworkCharacteristicsResult
struct_rdp_autodetect = _types.struct_rdp_autodetect
struct_rdp_network_characteristics_result = _types.struct_rdp_network_characteristics_result

# --- functions declared in this header ---
FUNCTIONS = (
    'autodetect_get',  # ctypes.POINTER(rdpAutoDetect) (ctypes.POINTER(rdpContext))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FREERDP_AUTODETECT_STATE', 'FREERDP_AUTODETECT_STATE_COMPLETE', 'FREERDP_AUTODETECT_STATE_FAIL', 'FREERDP_AUTODETECT_STATE_INITIAL', 'FREERDP_AUTODETECT_STATE_REQUEST', 'FREERDP_AUTODETECT_STATE_RESPONSE', 'FUNCTIONS', 'RDP_BW_RESULTS_RESPONSE_TYPE', 'RDP_BW_RESULTS_RESPONSE_TYPE_CONNECTTIME', 'RDP_BW_RESULTS_RESPONSE_TYPE_CONTINUOUS', 'RDP_NETCHAR_RESERVED', 'RDP_NETCHAR_RESULT_TYPE', 'RDP_NETCHAR_RESULT_TYPE_BASE_RTT_AVG_RTT', 'RDP_NETCHAR_RESULT_TYPE_BASE_RTT_BW_AVG_RTT', 'RDP_NETCHAR_RESULT_TYPE_BW_AVG_RTT', 'bind', 'pBandwidthMeasurePayload', 'pBandwidthMeasureResults', 'pBandwidthMeasureStart', 'pBandwidthMeasureStop', 'pClientBandwidthMeasureResult', 'pNetworkCharacteristicsResult', 'pNetworkCharacteristicsSync', 'pOnConnectTimeAutoDetect', 'pRTTMeasureRequest', 'pRTTMeasureResponse', 'pRxTxReceived', 'rdpAutoDetect', 'rdpNetworkCharacteristicsResult', 'struct_rdp_autodetect', 'struct_rdp_network_characteristics_result']
