"""
Mirror of <freerdp/codecs.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
FREERDP_CODEC_ALL = 0x7fffffff
FREERDP_CODEC_ALPHACODEC = 0x20
FREERDP_CODEC_AVC420 = 0x80
FREERDP_CODEC_AVC444 = 0x100
FREERDP_CODEC_CLEARCODEC = 0x10
FREERDP_CODEC_INTERLEAVED = 1
FREERDP_CODEC_NSCODEC = 4
FREERDP_CODEC_PLANAR = 2
FREERDP_CODEC_PROGRESSIVE = 0x40
FREERDP_CODEC_REMOTEFX = 8

# --- types declared in this header ---
FreeRDP_CodecFlags = _types.FreeRDP_CodecFlags
rdpCodecs = _types.rdpCodecs
struct_rdp_codecs = _types.struct_rdp_codecs

# --- functions declared in this header ---
FUNCTIONS = (
    'codecs_free',  # void (ctypes.POINTER(rdpCodecs))
    'codecs_new',  # ctypes.POINTER(rdpCodecs) (ctypes.POINTER(rdpContext))
    'freerdp_client_codecs_free',  # void (ctypes.POINTER(rdpCodecs))
    'freerdp_client_codecs_new',  # ctypes.POINTER(rdpCodecs) (UINT32)
    'freerdp_client_codecs_prepare',  # BOOL (ctypes.POINTER(rdpCodecs), UINT32, UINT32, UINT32)
    'freerdp_client_codecs_reset',  # BOOL (ctypes.POINTER(rdpCodecs), UINT32, UINT32, UINT32)
    'freerdp_codec_id_to_str',  # ctypes.c_char_p (UINT32)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FREERDP_CODEC_ALL', 'FREERDP_CODEC_ALPHACODEC', 'FREERDP_CODEC_AVC420', 'FREERDP_CODEC_AVC444', 'FREERDP_CODEC_CLEARCODEC', 'FREERDP_CODEC_INTERLEAVED', 'FREERDP_CODEC_NSCODEC', 'FREERDP_CODEC_PLANAR', 'FREERDP_CODEC_PROGRESSIVE', 'FREERDP_CODEC_REMOTEFX', 'FUNCTIONS', 'FreeRDP_CodecFlags', 'bind', 'rdpCodecs', 'struct_rdp_codecs']
