"""
Mirror of <freerdp/dvc.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
IDRDYNVC_ENTRY_POINTS = _types.IDRDYNVC_ENTRY_POINTS
IWTSListener = _types.IWTSListener
IWTSListenerCallback = _types.IWTSListenerCallback
IWTSPlugin = _types.IWTSPlugin
IWTSVirtualChannel = _types.IWTSVirtualChannel
IWTSVirtualChannelCallback = _types.IWTSVirtualChannelCallback
IWTSVirtualChannelManager = _types.IWTSVirtualChannelManager
PDVC_PLUGIN_ENTRY = _types.PDVC_PLUGIN_ENTRY
rdpContext = _types.rdpContext
struct_S_IDRDYNVC_ENTRY_POINTS = _types.struct_S_IDRDYNVC_ENTRY_POINTS
struct_s_IWTSListener = _types.struct_s_IWTSListener
struct_s_IWTSListenerCallback = _types.struct_s_IWTSListenerCallback
struct_s_IWTSPlugin = _types.struct_s_IWTSPlugin
struct_s_IWTSVirtualChannel = _types.struct_s_IWTSVirtualChannel
struct_s_IWTSVirtualChannelCallback = _types.struct_s_IWTSVirtualChannelCallback
struct_s_IWTSVirtualChannelManager = _types.struct_s_IWTSVirtualChannelManager

# --- functions declared in this header ---
FUNCTIONS = (
    'add_callback_by_name',  # void (ctypes.c_char_p, ctypes.c_void_p, ctypes.c_void_p)
    'get_callback_by_name',  # ctypes.c_void_p (ctypes.c_char_p, ctypes.POINTER(ctypes.c_void_p))
    'remove_callback_by_name',  # void (ctypes.c_char_p, ctypes.c_void_p)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'IDRDYNVC_ENTRY_POINTS', 'IWTSListener', 'IWTSListenerCallback', 'IWTSPlugin', 'IWTSVirtualChannel', 'IWTSVirtualChannelCallback', 'IWTSVirtualChannelManager', 'PDVC_PLUGIN_ENTRY', 'bind', 'rdpContext', 'struct_S_IDRDYNVC_ENTRY_POINTS', 'struct_s_IWTSListener', 'struct_s_IWTSListenerCallback', 'struct_s_IWTSPlugin', 'struct_s_IWTSVirtualChannel', 'struct_s_IWTSVirtualChannelCallback', 'struct_s_IWTSVirtualChannelManager']
