"""
Mirror of <freerdp/freerdp.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
ACCESS_TOKEN_TYPE_AAD = 0
ACCESS_TOKEN_TYPE_AVD = 1
AUTH_FIDO_PIN = 8
AUTH_NLA = 0
AUTH_RDP = 2
AUTH_RDSTLS = 7
AUTH_SMARTCARD_PIN = 6
AUTH_TLS = 1
Disconnect_Ultimatum_channel_purged = 4
Disconnect_Ultimatum_domain_disconnected = 0
Disconnect_Ultimatum_provider_initiated = 1
Disconnect_Ultimatum_token_purged = 2
Disconnect_Ultimatum_user_requested = 3
GATEWAY_MESSAGE_CONSENT = 1
GATEWAY_MESSAGE_SERVICE = 2
GW_AUTH_HTTP = 3
GW_AUTH_RDG = 4
GW_AUTH_RPC = 5
MCS_BASE_CHANNEL_ID = 0x3e9
MCS_GLOBAL_CHANNEL_ID = 0x3eb
VERIFY_CERT_FLAG_CHANGED = 0x40
VERIFY_CERT_FLAG_FP_IS_PEM = 0x200
VERIFY_CERT_FLAG_GATEWAY = 0x20
VERIFY_CERT_FLAG_LEGACY = 2
VERIFY_CERT_FLAG_MATCH_LEGACY_SHA1 = 0x100
VERIFY_CERT_FLAG_MISMATCH = 0x80
VERIFY_CERT_FLAG_NONE = 0
VERIFY_CERT_FLAG_REDIRECT = 0x10

# --- types declared in this header ---
AccessTokenType = _types.AccessTokenType
RDP_CLIENT_ENTRY_POINTS = _types.RDP_CLIENT_ENTRY_POINTS
RDP_CLIENT_ENTRY_POINTS_V1 = _types.RDP_CLIENT_ENTRY_POINTS_V1
freerdp = _types.freerdp
pAuthenticate = _types.pAuthenticate
pAuthenticateEx = _types.pAuthenticateEx
pChooseSmartcard = _types.pChooseSmartcard
pConnectCallback = _types.pConnectCallback
pContextFree = _types.pContextFree
pContextNew = _types.pContextNew
pGetAccessToken = _types.pGetAccessToken
pGetCommonAccessToken = _types.pGetCommonAccessToken
pLogonErrorInfo = _types.pLogonErrorInfo
pPostDisconnect = _types.pPostDisconnect
pPresentGatewayMessage = _types.pPresentGatewayMessage
pReceiveChannelData = _types.pReceiveChannelData
pRetryDialog = _types.pRetryDialog
pSendChannelData = _types.pSendChannelData
pSendChannelPacket = _types.pSendChannelPacket
pVerifyCertificate = _types.pVerifyCertificate
pVerifyCertificateEx = _types.pVerifyCertificateEx
pVerifyChangedCertificate = _types.pVerifyChangedCertificate
pVerifyChangedCertificateEx = _types.pVerifyChangedCertificateEx
pVerifyX509Certificate = _types.pVerifyX509Certificate
rdpCache = _types.rdpCache
rdpChannelHandles = _types.rdpChannelHandles
rdpClientContext = _types.rdpClientContext
rdpContext = _types.rdpContext
rdpRail = _types.rdpRail
rdpRdp = _types.rdpRdp
rdp_auth_reason = _types.rdp_auth_reason
struct_rdp_channel_handles = _types.struct_rdp_channel_handles
struct_rdp_context = _types.struct_rdp_context
struct_rdp_freerdp = _types.struct_rdp_freerdp

# --- functions declared in this header ---
FUNCTIONS = (
    'checkChannelErrorEvent',  # BOOL (ctypes.POINTER(rdpContext))
    'clearChannelError',  # void (ctypes.POINTER(rdpContext))
    'freerdp_abort_connect',  # BOOL (ctypes.POINTER(freerdp))
    'freerdp_abort_connect_context',  # BOOL (ctypes.POINTER(rdpContext))
    'freerdp_abort_event',  # HANDLE (ctypes.POINTER(rdpContext))
    'freerdp_channels_attach',  # UINT (ctypes.POINTER(freerdp))
    'freerdp_channels_detach',  # UINT (ctypes.POINTER(freerdp))
    'freerdp_channels_from_mcs',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.POINTER(rdpContext))
    'freerdp_check_event_handles',  # BOOL (ctypes.POINTER(rdpContext))
    'freerdp_check_fds',  # BOOL (ctypes.POINTER(freerdp))
    'freerdp_connect',  # BOOL (ctypes.POINTER(freerdp))
    'freerdp_context_free',  # void (ctypes.POINTER(freerdp))
    'freerdp_context_new',  # BOOL (ctypes.POINTER(freerdp))
    'freerdp_context_new_ex',  # BOOL (ctypes.POINTER(freerdp), ctypes.POINTER(rdpSettings))
    'freerdp_context_reset',  # BOOL (ctypes.POINTER(freerdp))
    'freerdp_disconnect',  # BOOL (ctypes.POINTER(freerdp))
    'freerdp_disconnect_before_reconnect',  # BOOL (ctypes.POINTER(freerdp))
    'freerdp_disconnect_before_reconnect_context',  # BOOL (ctypes.POINTER(rdpContext))
    'freerdp_disconnect_reason_string',  # ctypes.c_char_p (ctypes.c_int)
    'freerdp_error_info',  # UINT32 (ctypes.POINTER(freerdp))
    'freerdp_focus_required',  # BOOL (ctypes.POINTER(freerdp))
    'freerdp_free',  # void (ctypes.POINTER(freerdp))
    'freerdp_get_build_config',  # ctypes.c_char_p ()
    'freerdp_get_build_revision',  # ctypes.c_char_p ()
    'freerdp_get_common_access_token',  # pGetCommonAccessToken (ctypes.POINTER(rdpContext))
    'freerdp_get_disconnect_ultimatum',  # ctypes.c_int (ctypes.POINTER(rdpContext))
    'freerdp_get_event_handles',  # DWORD (ctypes.POINTER(rdpContext), ctypes.POINTER(HANDLE), DWORD)
    'freerdp_get_last_error',  # UINT32 (ctypes.POINTER(rdpContext))
    'freerdp_get_last_error_category',  # ctypes.c_char_p (UINT32)
    'freerdp_get_last_error_name',  # ctypes.c_char_p (UINT32)
    'freerdp_get_last_error_string',  # ctypes.c_char_p (UINT32)
    'freerdp_get_logon_error_info_data',  # ctypes.c_char_p (UINT32)
    'freerdp_get_logon_error_info_data_ex',  # ctypes.c_char_p (UINT32, ctypes.c_char_p, ctypes.c_size_t)
    'freerdp_get_logon_error_info_type',  # ctypes.c_char_p (UINT32)
    'freerdp_get_logon_error_info_type_ex',  # ctypes.c_char_p (UINT32, ctypes.c_char_p, ctypes.c_size_t)
    'freerdp_get_message_queue',  # ctypes.POINTER(wMessageQueue) (ctypes.POINTER(freerdp), DWORD)
    'freerdp_get_message_queue_event_handle',  # HANDLE (ctypes.POINTER(freerdp), DWORD)
    'freerdp_get_nla_sspi_error',  # UINT32 (ctypes.POINTER(rdpContext))
    'freerdp_get_state',  # CONNECTION_STATE (ctypes.POINTER(rdpContext))
    'freerdp_get_stats',  # BOOL (ctypes.POINTER(rdpRdp), ctypes.POINTER(UINT64), ctypes.POINTER(UINT64), ctypes.POINTER(UINT64), ctypes.POINTER(UINT64))
    'freerdp_get_transport_sent',  # ULONG (ctypes.POINTER(rdpContext), BOOL)
    'freerdp_get_version',  # void (ctypes.POINTER(ctypes.c_int), ctypes.POINTER(ctypes.c_int), ctypes.POINTER(ctypes.c_int))
    'freerdp_get_version_string',  # ctypes.c_char_p ()
    'freerdp_is_active_state',  # BOOL (ctypes.POINTER(rdpContext))
    'freerdp_is_valid_mcs_create_request',  # BOOL (ctypes.POINTER(BYTE), ctypes.c_size_t)
    'freerdp_is_valid_mcs_create_response',  # BOOL (ctypes.POINTER(BYTE), ctypes.c_size_t)
    'freerdp_message_queue_process_message',  # ctypes.c_int (ctypes.POINTER(freerdp), DWORD, ctypes.POINTER(wMessage))
    'freerdp_message_queue_process_pending_messages',  # ctypes.c_int (ctypes.POINTER(freerdp), DWORD)
    'freerdp_nego_get_routing_token',  # ctypes.c_char_p (ctypes.POINTER(rdpContext), ctypes.POINTER(DWORD))
    'freerdp_new',  # ctypes.POINTER(freerdp) ()
    'freerdp_nla_FreeContextBuffer',  # SECURITY_STATUS (ctypes.POINTER(rdpContext), PVOID)
    'freerdp_nla_QueryContextAttributes',  # SECURITY_STATUS (ctypes.POINTER(rdpContext), DWORD, PVOID)
    'freerdp_nla_decrypt',  # BOOL (ctypes.POINTER(rdpContext), ctypes.POINTER(SecBuffer), ctypes.POINTER(SecBuffer))
    'freerdp_nla_encrypt',  # BOOL (ctypes.POINTER(rdpContext), ctypes.POINTER(SecBuffer), ctypes.POINTER(SecBuffer))
    'freerdp_nla_impersonate',  # BOOL (ctypes.POINTER(rdpContext))
    'freerdp_nla_revert_to_self',  # BOOL (ctypes.POINTER(rdpContext))
    'freerdp_persist_credentials',  # BOOL (ctypes.POINTER(rdpContext))
    'freerdp_reconnect',  # BOOL (ctypes.POINTER(freerdp))
    'freerdp_send_error_info',  # BOOL (ctypes.POINTER(rdpRdp))
    'freerdp_set_common_access_token',  # BOOL (ctypes.POINTER(rdpContext), pGetCommonAccessToken)
    'freerdp_set_error_info',  # void (ctypes.POINTER(rdpRdp), UINT32)
    'freerdp_set_focus',  # void (ctypes.POINTER(freerdp))
    'freerdp_set_last_error_ex',  # void (ctypes.POINTER(rdpContext), UINT32, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int)
    'freerdp_shall_disconnect',  # BOOL (ctypes.POINTER(freerdp))
    'freerdp_shall_disconnect_context',  # BOOL (ctypes.POINTER(rdpContext))
    'freerdp_state_string',  # ctypes.c_char_p (CONNECTION_STATE)
    'getChannelError',  # UINT (ctypes.POINTER(rdpContext))
    'getChannelErrorDescription',  # ctypes.c_char_p (ctypes.POINTER(rdpContext))
    'getChannelErrorEventHandle',  # HANDLE (ctypes.POINTER(rdpContext))
    'setChannelError',  # void (ctypes.POINTER(rdpContext), UINT, ctypes.c_char_p, ...)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['ACCESS_TOKEN_TYPE_AAD', 'ACCESS_TOKEN_TYPE_AVD', 'AUTH_FIDO_PIN', 'AUTH_NLA', 'AUTH_RDP', 'AUTH_RDSTLS', 'AUTH_SMARTCARD_PIN', 'AUTH_TLS', 'AccessTokenType', 'Disconnect_Ultimatum_channel_purged', 'Disconnect_Ultimatum_domain_disconnected', 'Disconnect_Ultimatum_provider_initiated', 'Disconnect_Ultimatum_token_purged', 'Disconnect_Ultimatum_user_requested', 'FUNCTIONS', 'GATEWAY_MESSAGE_CONSENT', 'GATEWAY_MESSAGE_SERVICE', 'GW_AUTH_HTTP', 'GW_AUTH_RDG', 'GW_AUTH_RPC', 'MCS_BASE_CHANNEL_ID', 'MCS_GLOBAL_CHANNEL_ID', 'RDP_CLIENT_ENTRY_POINTS', 'RDP_CLIENT_ENTRY_POINTS_V1', 'VERIFY_CERT_FLAG_CHANGED', 'VERIFY_CERT_FLAG_FP_IS_PEM', 'VERIFY_CERT_FLAG_GATEWAY', 'VERIFY_CERT_FLAG_LEGACY', 'VERIFY_CERT_FLAG_MATCH_LEGACY_SHA1', 'VERIFY_CERT_FLAG_MISMATCH', 'VERIFY_CERT_FLAG_NONE', 'VERIFY_CERT_FLAG_REDIRECT', 'bind', 'freerdp', 'pAuthenticate', 'pAuthenticateEx', 'pChooseSmartcard', 'pConnectCallback', 'pContextFree', 'pContextNew', 'pGetAccessToken', 'pGetCommonAccessToken', 'pLogonErrorInfo', 'pPostDisconnect', 'pPresentGatewayMessage', 'pReceiveChannelData', 'pRetryDialog', 'pSendChannelData', 'pSendChannelPacket', 'pVerifyCertificate', 'pVerifyCertificateEx', 'pVerifyChangedCertificate', 'pVerifyChangedCertificateEx', 'pVerifyX509Certificate', 'rdpCache', 'rdpChannelHandles', 'rdpClientContext', 'rdpContext', 'rdpRail', 'rdpRdp', 'rdp_auth_reason', 'struct_rdp_channel_handles', 'struct_rdp_context', 'struct_rdp_freerdp']
