"""
Mirror of <freerdp/graphics.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
pBitmap_Decompress = _types.pBitmap_Decompress
pBitmap_Free = _types.pBitmap_Free
pBitmap_New = _types.pBitmap_New
pBitmap_Paint = _types.pBitmap_Paint
pBitmap_SetSurface = _types.pBitmap_SetSurface
pGlyph_BeginDraw = _types.pGlyph_BeginDraw
pGlyph_Draw = _types.pGlyph_Draw
pGlyph_EndDraw = _types.pGlyph_EndDraw
pGlyph_Free = _types.pGlyph_Free
pGlyph_New = _types.pGlyph_New
pGlyph_SetBounds = _types.pGlyph_SetBounds
pPointer_Free = _types.pPointer_Free
pPointer_New = _types.pPointer_New
pPointer_Set = _types.pPointer_Set
pPointer_SetDefault = _types.pPointer_SetDefault
pPointer_SetNull = _types.pPointer_SetNull
pPointer_SetPosition = _types.pPointer_SetPosition
rdpBitmap = _types.rdpBitmap
rdpGlyph = _types.rdpGlyph
rdpGraphics = _types.rdpGraphics
rdpPointer = _types.rdpPointer
struct_rdp_bitmap = _types.struct_rdp_bitmap
struct_rdp_glyph = _types.struct_rdp_glyph
struct_rdp_graphics = _types.struct_rdp_graphics
struct_rdp_pointer = _types.struct_rdp_pointer

# --- functions declared in this header ---
FUNCTIONS = (
    'Bitmap_Alloc',  # ctypes.POINTER(rdpBitmap) (ctypes.POINTER(rdpContext))
    'Bitmap_SetDimensions',  # BOOL (ctypes.POINTER(rdpBitmap), UINT16, UINT16)
    'Bitmap_SetRectangle',  # BOOL (ctypes.POINTER(rdpBitmap), UINT16, UINT16, UINT16, UINT16)
    'Glyph_Alloc',  # ctypes.POINTER(rdpGlyph) (ctypes.POINTER(rdpContext), INT32, INT32, UINT32, UINT32, UINT32, ctypes.POINTER(BYTE))
    'Pointer_Alloc',  # ctypes.POINTER(rdpPointer) (ctypes.POINTER(rdpContext))
    'graphics_free',  # void (ctypes.POINTER(rdpGraphics))
    'graphics_new',  # ctypes.POINTER(rdpGraphics) (ctypes.POINTER(rdpContext))
    'graphics_register_bitmap',  # void (ctypes.POINTER(rdpGraphics), ctypes.POINTER(rdpBitmap))
    'graphics_register_glyph',  # void (ctypes.POINTER(rdpGraphics), ctypes.POINTER(rdpGlyph))
    'graphics_register_pointer',  # void (ctypes.POINTER(rdpGraphics), ctypes.POINTER(rdpPointer))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'pBitmap_Decompress', 'pBitmap_Free', 'pBitmap_New', 'pBitmap_Paint', 'pBitmap_SetSurface', 'pGlyph_BeginDraw', 'pGlyph_Draw', 'pGlyph_EndDraw', 'pGlyph_Free', 'pGlyph_New', 'pGlyph_SetBounds', 'pPointer_Free', 'pPointer_New', 'pPointer_Set', 'pPointer_SetDefault', 'pPointer_SetNull', 'pPointer_SetPosition', 'rdpBitmap', 'rdpGlyph', 'rdpGraphics', 'rdpPointer', 'struct_rdp_bitmap', 'struct_rdp_glyph', 'struct_rdp_graphics', 'struct_rdp_pointer']
