"""
Mirror of <freerdp/heartbeat.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
pServerHeartbeat = _types.pServerHeartbeat
rdpHeartbeat = _types.rdpHeartbeat
struct_rdp_heartbeat = _types.struct_rdp_heartbeat

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_heartbeat_send_heartbeat_pdu',  # BOOL (ctypes.POINTER(freerdp_peer), BYTE, BYTE, BYTE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'pServerHeartbeat', 'rdpHeartbeat', 'struct_rdp_heartbeat']
