"""
Mirror of <freerdp/input.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
KBD_FLAGS_DOWN = 0x4000
KBD_FLAGS_EXTENDED = 0x100
KBD_FLAGS_EXTENDED1 = 0x200
KBD_FLAGS_RELEASE = 0x8000
KBD_SYNC_CAPS_LOCK = 4
KBD_SYNC_KANA_LOCK = 8
KBD_SYNC_NUM_LOCK = 2
KBD_SYNC_SCROLL_LOCK = 1
PTR_FLAGS_BUTTON1 = 0x1000
PTR_FLAGS_BUTTON2 = 0x2000
PTR_FLAGS_BUTTON3 = 0x4000
PTR_FLAGS_DOWN = 0x8000
PTR_FLAGS_HWHEEL = 0x400
PTR_FLAGS_MOVE = 0x800
PTR_FLAGS_WHEEL = 0x200
PTR_FLAGS_WHEEL_NEGATIVE = 0x100
PTR_XFLAGS_BUTTON1 = 1
PTR_XFLAGS_BUTTON2 = 2
PTR_XFLAGS_DOWN = 0x8000
RDP_CLIENT_INPUT_PDU_HEADER_LENGTH = 4
WheelRotationMask = 0x1ff

# --- types declared in this header ---
pExtendedMouseEvent = _types.pExtendedMouseEvent
pFocusInEvent = _types.pFocusInEvent
pKeyboardEvent = _types.pKeyboardEvent
pKeyboardPauseEvent = _types.pKeyboardPauseEvent
pMouseEvent = _types.pMouseEvent
pQoEEvent = _types.pQoEEvent
pRelMouseEvent = _types.pRelMouseEvent
pSynchronizeEvent = _types.pSynchronizeEvent
pUnicodeKeyboardEvent = _types.pUnicodeKeyboardEvent
rdpInput = _types.rdpInput
rdpInputProxy = _types.rdpInputProxy
struct_rdp_input = _types.struct_rdp_input

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_input_keyboard_flags_string',  # ctypes.c_char_p (ctypes.c_uint32, ctypes.c_char_p, ctypes.c_size_t)
    'freerdp_input_keypress_flags_string',  # ctypes.c_char_p (ctypes.c_uint32, ctypes.c_char_p, ctypes.c_size_t)
    'freerdp_input_mouse_flags_string',  # ctypes.c_char_p (ctypes.c_uint32, ctypes.c_bool, ctypes.c_char_p, ctypes.c_size_t)
    'freerdp_input_send_extended_mouse_event',  # BOOL (ctypes.POINTER(rdpInput), UINT16, UINT16, UINT16)
    'freerdp_input_send_focus_in_event',  # BOOL (ctypes.POINTER(rdpInput), UINT16)
    'freerdp_input_send_keyboard_event',  # BOOL (ctypes.POINTER(rdpInput), UINT16, UINT8)
    'freerdp_input_send_keyboard_event_ex',  # BOOL (ctypes.POINTER(rdpInput), BOOL, BOOL, UINT32)
    'freerdp_input_send_keyboard_pause_event',  # BOOL (ctypes.POINTER(rdpInput))
    'freerdp_input_send_mouse_event',  # BOOL (ctypes.POINTER(rdpInput), UINT16, UINT16, UINT16)
    'freerdp_input_send_qoe_timestamp',  # BOOL (ctypes.POINTER(rdpInput), UINT32)
    'freerdp_input_send_rel_mouse_event',  # BOOL (ctypes.POINTER(rdpInput), UINT16, INT16, INT16)
    'freerdp_input_send_synchronize_event',  # BOOL (ctypes.POINTER(rdpInput), UINT32)
    'freerdp_input_send_unicode_keyboard_event',  # BOOL (ctypes.POINTER(rdpInput), UINT16, UINT16)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'KBD_FLAGS_DOWN', 'KBD_FLAGS_EXTENDED', 'KBD_FLAGS_EXTENDED1', 'KBD_FLAGS_RELEASE', 'KBD_SYNC_CAPS_LOCK', 'KBD_SYNC_KANA_LOCK', 'KBD_SYNC_NUM_LOCK', 'KBD_SYNC_SCROLL_LOCK', 'PTR_FLAGS_BUTTON1', 'PTR_FLAGS_BUTTON2', 'PTR_FLAGS_BUTTON3', 'PTR_FLAGS_DOWN', 'PTR_FLAGS_HWHEEL', 'PTR_FLAGS_MOVE', 'PTR_FLAGS_WHEEL', 'PTR_FLAGS_WHEEL_NEGATIVE', 'PTR_XFLAGS_BUTTON1', 'PTR_XFLAGS_BUTTON2', 'PTR_XFLAGS_DOWN', 'RDP_CLIENT_INPUT_PDU_HEADER_LENGTH', 'WheelRotationMask', 'bind', 'pExtendedMouseEvent', 'pFocusInEvent', 'pKeyboardEvent', 'pKeyboardPauseEvent', 'pMouseEvent', 'pQoEEvent', 'pRelMouseEvent', 'pSynchronizeEvent', 'pUnicodeKeyboardEvent', 'rdpInput', 'rdpInputProxy', 'struct_rdp_input']
