"""
Mirror of <freerdp/license.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
LICENSE_STATE_ABORTED = 7
LICENSE_STATE_COMPLETED = 6
LICENSE_STATE_CONFIGURED = 1
LICENSE_STATE_INITIAL = 0
LICENSE_STATE_NEW_REQUEST = 3
LICENSE_STATE_PLATFORM_CHALLENGE = 4
LICENSE_STATE_PLATFORM_CHALLENGE_RESPONSE = 5
LICENSE_STATE_REQUEST = 2
LICENSE_TYPE_INVALID = 0
LICENSE_TYPE_ISSUED = 2
LICENSE_TYPE_NONE = 1

# --- types declared in this header ---
LICENSE_STATE = _types.LICENSE_STATE
LICENSE_TYPE = _types.LICENSE_TYPE
rdpLicense = _types.rdpLicense

# --- functions declared in this header ---
FUNCTIONS = (
    'license_get',  # ctypes.POINTER(rdpLicense) (ctypes.POINTER(rdpContext))
    'license_get_state',  # LICENSE_STATE (ctypes.POINTER(rdpLicense))
    'license_get_type',  # LICENSE_TYPE (ctypes.POINTER(rdpLicense))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'LICENSE_STATE', 'LICENSE_STATE_ABORTED', 'LICENSE_STATE_COMPLETED', 'LICENSE_STATE_CONFIGURED', 'LICENSE_STATE_INITIAL', 'LICENSE_STATE_NEW_REQUEST', 'LICENSE_STATE_PLATFORM_CHALLENGE', 'LICENSE_STATE_PLATFORM_CHALLENGE_RESPONSE', 'LICENSE_STATE_REQUEST', 'LICENSE_TYPE', 'LICENSE_TYPE_INVALID', 'LICENSE_TYPE_ISSUED', 'LICENSE_TYPE_NONE', 'bind', 'rdpLicense']
