"""
Mirror of <freerdp/listener.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
freerdp_listener = _types.freerdp_listener
psListenerCheckFileDescriptor = _types.psListenerCheckFileDescriptor
psListenerClose = _types.psListenerClose
psListenerGetEventHandles = _types.psListenerGetEventHandles
psListenerOpen = _types.psListenerOpen
psListenerOpenFromSocket = _types.psListenerOpenFromSocket
psListenerOpenLocal = _types.psListenerOpenLocal
psPeerAccepted = _types.psPeerAccepted
struct_rdp_freerdp_listener = _types.struct_rdp_freerdp_listener

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_listener_free',  # void (ctypes.POINTER(freerdp_listener))
    'freerdp_listener_new',  # ctypes.POINTER(freerdp_listener) ()
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'freerdp_listener', 'psListenerCheckFileDescriptor', 'psListenerClose', 'psListenerGetEventHandles', 'psListenerOpen', 'psListenerOpenFromSocket', 'psListenerOpenLocal', 'psPeerAccepted', 'struct_rdp_freerdp_listener']
