"""
Mirror of <freerdp/metrics.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
rdpMetrics = _types.rdpMetrics
struct_rdp_metrics = _types.struct_rdp_metrics

# --- functions declared in this header ---
FUNCTIONS = (
    'metrics_free',  # void (ctypes.POINTER(rdpMetrics))
    'metrics_new',  # ctypes.POINTER(rdpMetrics) (ctypes.POINTER(rdpContext))
    'metrics_write_bytes',  # ctypes.c_double (ctypes.POINTER(rdpMetrics), UINT32, UINT32)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'rdpMetrics', 'struct_rdp_metrics']
