"""
Mirror of <freerdp/peer.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
LICENSE_CB_ABORT = 1
LICENSE_CB_COMPLETED = 3
LICENSE_CB_INTERNAL_ERROR = 0
LICENSE_CB_IN_PROGRESS = 2

# --- types declared in this header ---
LicenseCallbackResult = _types.LicenseCallbackResult
freerdp_peer = _types.freerdp_peer
psPeerActivate = _types.psPeerActivate
psPeerAdjustMonitorsLayout = _types.psPeerAdjustMonitorsLayout
psPeerCapabilities = _types.psPeerCapabilities
psPeerCheckFileDescriptor = _types.psPeerCheckFileDescriptor
psPeerClientCapabilities = _types.psPeerClientCapabilities
psPeerClose = _types.psPeerClose
psPeerContextFree = _types.psPeerContextFree
psPeerContextNew = _types.psPeerContextNew
psPeerDisconnect = _types.psPeerDisconnect
psPeerDrainOutputBuffer = _types.psPeerDrainOutputBuffer
psPeerGetEventHandle = _types.psPeerGetEventHandle
psPeerGetEventHandles = _types.psPeerGetEventHandles
psPeerGetReceiveEventHandle = _types.psPeerGetReceiveEventHandle
psPeerHasMoreToRead = _types.psPeerHasMoreToRead
psPeerInitialize = _types.psPeerInitialize
psPeerIsWriteBlocked = _types.psPeerIsWriteBlocked
psPeerLicenseCallback = _types.psPeerLicenseCallback
psPeerLogon = _types.psPeerLogon
psPeerPostConnect = _types.psPeerPostConnect
psPeerReachedState = _types.psPeerReachedState
psPeerReceiveChannelData = _types.psPeerReceiveChannelData
psPeerRemoteCredentials = _types.psPeerRemoteCredentials
psPeerSendChannelData = _types.psPeerSendChannelData
psPeerSendChannelPacket = _types.psPeerSendChannelPacket
psPeerSendServerRedirection = _types.psPeerSendServerRedirection
psPeerSetState = _types.psPeerSetState
psPeerVirtualChannelClose = _types.psPeerVirtualChannelClose
psPeerVirtualChannelGetData = _types.psPeerVirtualChannelGetData
psPeerVirtualChannelOpen = _types.psPeerVirtualChannelOpen
psPeerVirtualChannelRead = _types.psPeerVirtualChannelRead
psPeerVirtualChannelSetData = _types.psPeerVirtualChannelSetData
psPeerVirtualChannelWrite = _types.psPeerVirtualChannelWrite
struct_rdp_freerdp_peer = _types.struct_rdp_freerdp_peer

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_peer_context_free',  # void (ctypes.POINTER(freerdp_peer))
    'freerdp_peer_context_new',  # BOOL (ctypes.POINTER(freerdp_peer))
    'freerdp_peer_context_new_ex',  # BOOL (ctypes.POINTER(freerdp_peer), ctypes.POINTER(rdpSettings))
    'freerdp_peer_free',  # void (ctypes.POINTER(freerdp_peer))
    'freerdp_peer_new',  # ctypes.POINTER(freerdp_peer) (ctypes.c_int)
    'freerdp_peer_os_major_type_string',  # ctypes.c_char_p (ctypes.POINTER(freerdp_peer))
    'freerdp_peer_os_minor_type_string',  # ctypes.c_char_p (ctypes.POINTER(freerdp_peer))
    'freerdp_peer_set_local_and_hostname',  # BOOL (ctypes.POINTER(freerdp_peer), ctypes.POINTER(struct_sockaddr_storage))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'LICENSE_CB_ABORT', 'LICENSE_CB_COMPLETED', 'LICENSE_CB_INTERNAL_ERROR', 'LICENSE_CB_IN_PROGRESS', 'LicenseCallbackResult', 'bind', 'freerdp_peer', 'psPeerActivate', 'psPeerAdjustMonitorsLayout', 'psPeerCapabilities', 'psPeerCheckFileDescriptor', 'psPeerClientCapabilities', 'psPeerClose', 'psPeerContextFree', 'psPeerContextNew', 'psPeerDisconnect', 'psPeerDrainOutputBuffer', 'psPeerGetEventHandle', 'psPeerGetEventHandles', 'psPeerGetReceiveEventHandle', 'psPeerHasMoreToRead', 'psPeerInitialize', 'psPeerIsWriteBlocked', 'psPeerLicenseCallback', 'psPeerLogon', 'psPeerPostConnect', 'psPeerReachedState', 'psPeerReceiveChannelData', 'psPeerRemoteCredentials', 'psPeerSendChannelData', 'psPeerSendChannelPacket', 'psPeerSendServerRedirection', 'psPeerSetState', 'psPeerVirtualChannelClose', 'psPeerVirtualChannelGetData', 'psPeerVirtualChannelOpen', 'psPeerVirtualChannelRead', 'psPeerVirtualChannelSetData', 'psPeerVirtualChannelWrite', 'struct_rdp_freerdp_peer']
