"""
Mirror of <freerdp/pointer.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
PTR_MSG_TYPE_CACHED = 7
PTR_MSG_TYPE_COLOR = 6
PTR_MSG_TYPE_POINTER = 8
PTR_MSG_TYPE_POINTER_LARGE = 9
PTR_MSG_TYPE_POSITION = 3
PTR_MSG_TYPE_SYSTEM = 1
SYSPTR_DEFAULT = 0x7f00
SYSPTR_NULL = 0

# --- types declared in this header ---
POINTER_CACHED_UPDATE = _types.POINTER_CACHED_UPDATE
POINTER_COLOR_UPDATE = _types.POINTER_COLOR_UPDATE
POINTER_LARGE_UPDATE = _types.POINTER_LARGE_UPDATE
POINTER_NEW_UPDATE = _types.POINTER_NEW_UPDATE
POINTER_POSITION_UPDATE = _types.POINTER_POSITION_UPDATE
POINTER_SYSTEM_UPDATE = _types.POINTER_SYSTEM_UPDATE
pPointerCached = _types.pPointerCached
pPointerColor = _types.pPointerColor
pPointerLarge = _types.pPointerLarge
pPointerNew = _types.pPointerNew
pPointerPosition = _types.pPointerPosition
pPointerSystem = _types.pPointerSystem
rdpPointerUpdate = _types.rdpPointerUpdate
struct_POINTER_CACHED_UPDATE = _types.struct_POINTER_CACHED_UPDATE
struct_POINTER_COLOR_UPDATE = _types.struct_POINTER_COLOR_UPDATE
struct_POINTER_LARGE_UPDATE = _types.struct_POINTER_LARGE_UPDATE
struct_POINTER_NEW_UPDATE = _types.struct_POINTER_NEW_UPDATE
struct_POINTER_POSITION_UPDATE = _types.struct_POINTER_POSITION_UPDATE
struct_POINTER_SYSTEM_UPDATE = _types.struct_POINTER_SYSTEM_UPDATE
struct_rdp_pointer_update = _types.struct_rdp_pointer_update

__all__ = ['POINTER_CACHED_UPDATE', 'POINTER_COLOR_UPDATE', 'POINTER_LARGE_UPDATE', 'POINTER_NEW_UPDATE', 'POINTER_POSITION_UPDATE', 'POINTER_SYSTEM_UPDATE', 'PTR_MSG_TYPE_CACHED', 'PTR_MSG_TYPE_COLOR', 'PTR_MSG_TYPE_POINTER', 'PTR_MSG_TYPE_POINTER_LARGE', 'PTR_MSG_TYPE_POSITION', 'PTR_MSG_TYPE_SYSTEM', 'SYSPTR_DEFAULT', 'SYSPTR_NULL', 'pPointerCached', 'pPointerColor', 'pPointerLarge', 'pPointerNew', 'pPointerPosition', 'pPointerSystem', 'rdpPointerUpdate', 'struct_POINTER_CACHED_UPDATE', 'struct_POINTER_COLOR_UPDATE', 'struct_POINTER_LARGE_UPDATE', 'struct_POINTER_NEW_UPDATE', 'struct_POINTER_POSITION_UPDATE', 'struct_POINTER_SYSTEM_UPDATE', 'struct_rdp_pointer_update']
