"""
Mirror of <freerdp/primitives.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
AVC444_CHROMAv1 = 1
AVC444_CHROMAv2 = 2
AVC444_LUMA = 0
PRIMITIVES_AUTODETECT = 3
PRIMITIVES_ONLY_CPU = 1
PRIMITIVES_ONLY_GPU = 2
PRIMITIVES_PURE_SOFT = 0
PRIMITIVES_SUCCESS = 0
PRIM_ARM_FPA_AVAILABLE = 0x10
PRIM_ARM_FPE_AVAILABLE = 0x20
PRIM_ARM_IWMMXT_AVAILABLE = 0x40
PRIM_ARM_NEON_AVAILABLE = 0x80
PRIM_ARM_VFP1_AVAILABLE = 1
PRIM_ARM_VFP2_AVAILABLE = 2
PRIM_ARM_VFP3_AVAILABLE = 4
PRIM_ARM_VFP4_AVAILABLE = 8
PRIM_FLAGS_HAVE_EXTCPU = 1
PRIM_FLAGS_HAVE_EXTGPU = 2
PRIM_X86_3DNOW_AVAILABLE = 2
PRIM_X86_3DNOW_PREFETCH_AVAILABLE = 4
PRIM_X86_AVX2_AVAILABLE = 0x1000
PRIM_X86_AVX_AES_AVAILABLE = 0x800
PRIM_X86_AVX_AVAILABLE = 0x200
PRIM_X86_FMA_AVAILABLE = 0x400
PRIM_X86_MMX_AVAILABLE = 1
PRIM_X86_SSE2_AVAILABLE = 0x10
PRIM_X86_SSE3_AVAILABLE = 0x20
PRIM_X86_SSE41_AVAILABLE = 0x80
PRIM_X86_SSE42_AVAILABLE = 0x100
PRIM_X86_SSE_AVAILABLE = 8
PRIM_X86_SSSE3_AVAILABLE = 0x40

# --- types declared in this header ---
avc444_frame_type = _types.avc444_frame_type
fn_RGB565ToARGB_16u32u_C3C4_t = _types.fn_RGB565ToARGB_16u32u_C3C4_t
fn_RGBToAVC444YUV_t = _types.fn_RGBToAVC444YUV_t
fn_RGBToRGB_16s8u_P3AC4R_t = _types.fn_RGBToRGB_16s8u_P3AC4R_t
fn_RGBToYCbCr_16s16s_P3P3_t = _types.fn_RGBToYCbCr_16s16s_P3P3_t
fn_RGBToYUV420_8u_P3AC4R_t = _types.fn_RGBToYUV420_8u_P3AC4R_t
fn_RGBToYUV444_8u_P3AC4R_t = _types.fn_RGBToYUV444_8u_P3AC4R_t
fn_YCoCgToRGB_8u_AC4R_t = _types.fn_YCoCgToRGB_8u_AC4R_t
fn_YUV420CombineToYUV444_t = _types.fn_YUV420CombineToYUV444_t
fn_YUV420ToRGB_8u_P3AC4R_t = _types.fn_YUV420ToRGB_8u_P3AC4R_t
fn_YUV444SplitToYUV420_t = _types.fn_YUV444SplitToYUV420_t
fn_YUV444ToRGB_8u_P3AC4R_t = _types.fn_YUV444ToRGB_8u_P3AC4R_t
fn_add_16s_inplace_t = _types.fn_add_16s_inplace_t
fn_add_16s_t = _types.fn_add_16s_t
fn_alphaComp_argb_t = _types.fn_alphaComp_argb_t
fn_andC_32u_t = _types.fn_andC_32u_t
fn_copy_8u_AC4r_t = _types.fn_copy_8u_AC4r_t
fn_copy_8u_t = _types.fn_copy_8u_t
fn_copy_no_overlap_t = _types.fn_copy_no_overlap_t
fn_copy_t = _types.fn_copy_t
fn_lShiftC_16s_inplace_t = _types.fn_lShiftC_16s_inplace_t
fn_lShiftC_16s_t = _types.fn_lShiftC_16s_t
fn_lShiftC_16u_t = _types.fn_lShiftC_16u_t
fn_orC_32u_t = _types.fn_orC_32u_t
fn_rShiftC_16s_t = _types.fn_rShiftC_16s_t
fn_rShiftC_16u_t = _types.fn_rShiftC_16u_t
fn_set_32s_t = _types.fn_set_32s_t
fn_set_32u_t = _types.fn_set_32u_t
fn_set_8u_t = _types.fn_set_8u_t
fn_shiftC_16s_t = _types.fn_shiftC_16s_t
fn_shiftC_16u_t = _types.fn_shiftC_16u_t
fn_sign_16s_t = _types.fn_sign_16s_t
fn_yCbCrToRGB_16s16s_P3P3_t = _types.fn_yCbCrToRGB_16s16s_P3P3_t
fn_yCbCrToRGB_16s8u_P3AC4R_t = _types.fn_yCbCrToRGB_16s8u_P3AC4R_t
fn_zero_t = _types.fn_zero_t
prim_size_t = _types.prim_size_t
primitive_hints = _types.primitive_hints
primitives_t = _types.primitives_t
primitives_uninit_t = _types.primitives_uninit_t
pstatus_t = _types.pstatus_t
struct_prim_size_t = _types.struct_prim_size_t
struct_primitives_t = _types.struct_primitives_t

# --- functions declared in this header ---
FUNCTIONS = (
    'primitives_avc444_frame_type_str',  # ctypes.c_char_p (avc444_frame_type)
    'primitives_flags',  # DWORD (ctypes.POINTER(primitives_t))
    'primitives_get',  # ctypes.POINTER(primitives_t) ()
    'primitives_get_by_type',  # ctypes.POINTER(primitives_t) (primitive_hints)
    'primitives_get_generic',  # ctypes.POINTER(primitives_t) ()
    'primitives_get_hints',  # primitive_hints ()
    'primitives_init',  # BOOL (ctypes.POINTER(primitives_t), primitive_hints)
    'primitives_set_hints',  # void (primitive_hints)
    'primitives_uninit',  # void ()
    'primtives_hint_str',  # ctypes.c_char_p (primitive_hints)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['AVC444_CHROMAv1', 'AVC444_CHROMAv2', 'AVC444_LUMA', 'FUNCTIONS', 'PRIMITIVES_AUTODETECT', 'PRIMITIVES_ONLY_CPU', 'PRIMITIVES_ONLY_GPU', 'PRIMITIVES_PURE_SOFT', 'PRIMITIVES_SUCCESS', 'PRIM_ARM_FPA_AVAILABLE', 'PRIM_ARM_FPE_AVAILABLE', 'PRIM_ARM_IWMMXT_AVAILABLE', 'PRIM_ARM_NEON_AVAILABLE', 'PRIM_ARM_VFP1_AVAILABLE', 'PRIM_ARM_VFP2_AVAILABLE', 'PRIM_ARM_VFP3_AVAILABLE', 'PRIM_ARM_VFP4_AVAILABLE', 'PRIM_FLAGS_HAVE_EXTCPU', 'PRIM_FLAGS_HAVE_EXTGPU', 'PRIM_X86_3DNOW_AVAILABLE', 'PRIM_X86_3DNOW_PREFETCH_AVAILABLE', 'PRIM_X86_AVX2_AVAILABLE', 'PRIM_X86_AVX_AES_AVAILABLE', 'PRIM_X86_AVX_AVAILABLE', 'PRIM_X86_FMA_AVAILABLE', 'PRIM_X86_MMX_AVAILABLE', 'PRIM_X86_SSE2_AVAILABLE', 'PRIM_X86_SSE3_AVAILABLE', 'PRIM_X86_SSE41_AVAILABLE', 'PRIM_X86_SSE42_AVAILABLE', 'PRIM_X86_SSE_AVAILABLE', 'PRIM_X86_SSSE3_AVAILABLE', 'avc444_frame_type', 'bind', 'fn_RGB565ToARGB_16u32u_C3C4_t', 'fn_RGBToAVC444YUV_t', 'fn_RGBToRGB_16s8u_P3AC4R_t', 'fn_RGBToYCbCr_16s16s_P3P3_t', 'fn_RGBToYUV420_8u_P3AC4R_t', 'fn_RGBToYUV444_8u_P3AC4R_t', 'fn_YCoCgToRGB_8u_AC4R_t', 'fn_YUV420CombineToYUV444_t', 'fn_YUV420ToRGB_8u_P3AC4R_t', 'fn_YUV444SplitToYUV420_t', 'fn_YUV444ToRGB_8u_P3AC4R_t', 'fn_add_16s_inplace_t', 'fn_add_16s_t', 'fn_alphaComp_argb_t', 'fn_andC_32u_t', 'fn_copy_8u_AC4r_t', 'fn_copy_8u_t', 'fn_copy_no_overlap_t', 'fn_copy_t', 'fn_lShiftC_16s_inplace_t', 'fn_lShiftC_16s_t', 'fn_lShiftC_16u_t', 'fn_orC_32u_t', 'fn_rShiftC_16s_t', 'fn_rShiftC_16u_t', 'fn_set_32s_t', 'fn_set_32u_t', 'fn_set_8u_t', 'fn_shiftC_16s_t', 'fn_shiftC_16u_t', 'fn_sign_16s_t', 'fn_yCbCrToRGB_16s16s_P3P3_t', 'fn_yCbCrToRGB_16s8u_P3AC4R_t', 'fn_zero_t', 'prim_size_t', 'primitive_hints', 'primitives_t', 'primitives_uninit_t', 'pstatus_t', 'struct_prim_size_t', 'struct_primitives_t']
