"""
Mirror of <freerdp/primary.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
BACKMODE_OPAQUE = 2
BACKMODE_TRANSPARENT = 1

# --- types declared in this header ---
DELTA_POINT = _types.DELTA_POINT
DELTA_RECT = _types.DELTA_RECT
DRAW_NINE_GRID_ORDER = _types.DRAW_NINE_GRID_ORDER
DSTBLT_ORDER = _types.DSTBLT_ORDER
ELLIPSE_CB_ORDER = _types.ELLIPSE_CB_ORDER
ELLIPSE_SC_ORDER = _types.ELLIPSE_SC_ORDER
FAST_GLYPH_ORDER = _types.FAST_GLYPH_ORDER
FAST_INDEX_ORDER = _types.FAST_INDEX_ORDER
GLYPH_DATA = _types.GLYPH_DATA
GLYPH_DATA_V2 = _types.GLYPH_DATA_V2
GLYPH_FRAGMENT = _types.GLYPH_FRAGMENT
GLYPH_FRAGMENT_INDEX = _types.GLYPH_FRAGMENT_INDEX
GLYPH_INDEX_ORDER = _types.GLYPH_INDEX_ORDER
LINE_TO_ORDER = _types.LINE_TO_ORDER
MEM3BLT_ORDER = _types.MEM3BLT_ORDER
MEMBLT_ORDER = _types.MEMBLT_ORDER
MULTI_DRAW_NINE_GRID_ORDER = _types.MULTI_DRAW_NINE_GRID_ORDER
MULTI_DSTBLT_ORDER = _types.MULTI_DSTBLT_ORDER
MULTI_OPAQUE_RECT_ORDER = _types.MULTI_OPAQUE_RECT_ORDER
MULTI_PATBLT_ORDER = _types.MULTI_PATBLT_ORDER
MULTI_SCRBLT_ORDER = _types.MULTI_SCRBLT_ORDER
OPAQUE_RECT_ORDER = _types.OPAQUE_RECT_ORDER
ORDER_INFO = _types.ORDER_INFO
PATBLT_ORDER = _types.PATBLT_ORDER
POLYGON_CB_ORDER = _types.POLYGON_CB_ORDER
POLYGON_SC_ORDER = _types.POLYGON_SC_ORDER
POLYLINE_ORDER = _types.POLYLINE_ORDER
SAVE_BITMAP_ORDER = _types.SAVE_BITMAP_ORDER
SCRBLT_ORDER = _types.SCRBLT_ORDER
pDrawNineGrid = _types.pDrawNineGrid
pDstBlt = _types.pDstBlt
pEllipseCB = _types.pEllipseCB
pEllipseSC = _types.pEllipseSC
pFastGlyph = _types.pFastGlyph
pFastIndex = _types.pFastIndex
pGlyphIndex = _types.pGlyphIndex
pLineTo = _types.pLineTo
pMem3Blt = _types.pMem3Blt
pMemBlt = _types.pMemBlt
pMultiDrawNineGrid = _types.pMultiDrawNineGrid
pMultiDstBlt = _types.pMultiDstBlt
pMultiOpaqueRect = _types.pMultiOpaqueRect
pMultiPatBlt = _types.pMultiPatBlt
pMultiScrBlt = _types.pMultiScrBlt
pOpaqueRect = _types.pOpaqueRect
pOrderInfo = _types.pOrderInfo
pPatBlt = _types.pPatBlt
pPolygonCB = _types.pPolygonCB
pPolygonSC = _types.pPolygonSC
pPolyline = _types.pPolyline
pSaveBitmap = _types.pSaveBitmap
pScrBlt = _types.pScrBlt
rdpBounds = _types.rdpBounds
rdpBrush = _types.rdpBrush
rdpPrimaryUpdate = _types.rdpPrimaryUpdate
struct_DELTA_POINT = _types.struct_DELTA_POINT
struct_DELTA_RECT = _types.struct_DELTA_RECT
struct_DRAW_NINE_GRID_ORDER = _types.struct_DRAW_NINE_GRID_ORDER
struct_DSTBLT_ORDER = _types.struct_DSTBLT_ORDER
struct_ELLIPSE_CB_ORDER = _types.struct_ELLIPSE_CB_ORDER
struct_ELLIPSE_SC_ORDER = _types.struct_ELLIPSE_SC_ORDER
struct_FAST_GLYPH_ORDER = _types.struct_FAST_GLYPH_ORDER
struct_FAST_INDEX_ORDER = _types.struct_FAST_INDEX_ORDER
struct_GLYPH_DATA = _types.struct_GLYPH_DATA
struct_GLYPH_DATA_V2 = _types.struct_GLYPH_DATA_V2
struct_GLYPH_FRAGMENT = _types.struct_GLYPH_FRAGMENT
struct_GLYPH_FRAGMENT_INDEX = _types.struct_GLYPH_FRAGMENT_INDEX
struct_GLYPH_INDEX_ORDER = _types.struct_GLYPH_INDEX_ORDER
struct_LINE_TO_ORDER = _types.struct_LINE_TO_ORDER
struct_MEM3BLT_ORDER = _types.struct_MEM3BLT_ORDER
struct_MEMBLT_ORDER = _types.struct_MEMBLT_ORDER
struct_MULTI_DRAW_NINE_GRID_ORDER = _types.struct_MULTI_DRAW_NINE_GRID_ORDER
struct_MULTI_DSTBLT_ORDER = _types.struct_MULTI_DSTBLT_ORDER
struct_MULTI_OPAQUE_RECT_ORDER = _types.struct_MULTI_OPAQUE_RECT_ORDER
struct_MULTI_PATBLT_ORDER = _types.struct_MULTI_PATBLT_ORDER
struct_MULTI_SCRBLT_ORDER = _types.struct_MULTI_SCRBLT_ORDER
struct_OPAQUE_RECT_ORDER = _types.struct_OPAQUE_RECT_ORDER
struct_ORDER_INFO = _types.struct_ORDER_INFO
struct_PATBLT_ORDER = _types.struct_PATBLT_ORDER
struct_POLYGON_CB_ORDER = _types.struct_POLYGON_CB_ORDER
struct_POLYGON_SC_ORDER = _types.struct_POLYGON_SC_ORDER
struct_POLYLINE_ORDER = _types.struct_POLYLINE_ORDER
struct_SAVE_BITMAP_ORDER = _types.struct_SAVE_BITMAP_ORDER
struct_SCRBLT_ORDER = _types.struct_SCRBLT_ORDER
struct_rdp_bounds = _types.struct_rdp_bounds
struct_rdp_brush = _types.struct_rdp_brush
struct_rdp_primary_update = _types.struct_rdp_primary_update

__all__ = ['BACKMODE_OPAQUE', 'BACKMODE_TRANSPARENT', 'DELTA_POINT', 'DELTA_RECT', 'DRAW_NINE_GRID_ORDER', 'DSTBLT_ORDER', 'ELLIPSE_CB_ORDER', 'ELLIPSE_SC_ORDER', 'FAST_GLYPH_ORDER', 'FAST_INDEX_ORDER', 'GLYPH_DATA', 'GLYPH_DATA_V2', 'GLYPH_FRAGMENT', 'GLYPH_FRAGMENT_INDEX', 'GLYPH_INDEX_ORDER', 'LINE_TO_ORDER', 'MEM3BLT_ORDER', 'MEMBLT_ORDER', 'MULTI_DRAW_NINE_GRID_ORDER', 'MULTI_DSTBLT_ORDER', 'MULTI_OPAQUE_RECT_ORDER', 'MULTI_PATBLT_ORDER', 'MULTI_SCRBLT_ORDER', 'OPAQUE_RECT_ORDER', 'ORDER_INFO', 'PATBLT_ORDER', 'POLYGON_CB_ORDER', 'POLYGON_SC_ORDER', 'POLYLINE_ORDER', 'SAVE_BITMAP_ORDER', 'SCRBLT_ORDER', 'pDrawNineGrid', 'pDstBlt', 'pEllipseCB', 'pEllipseSC', 'pFastGlyph', 'pFastIndex', 'pGlyphIndex', 'pLineTo', 'pMem3Blt', 'pMemBlt', 'pMultiDrawNineGrid', 'pMultiDstBlt', 'pMultiOpaqueRect', 'pMultiPatBlt', 'pMultiScrBlt', 'pOpaqueRect', 'pOrderInfo', 'pPatBlt', 'pPolygonCB', 'pPolygonSC', 'pPolyline', 'pSaveBitmap', 'pScrBlt', 'rdpBounds', 'rdpBrush', 'rdpPrimaryUpdate', 'struct_DELTA_POINT', 'struct_DELTA_RECT', 'struct_DRAW_NINE_GRID_ORDER', 'struct_DSTBLT_ORDER', 'struct_ELLIPSE_CB_ORDER', 'struct_ELLIPSE_SC_ORDER', 'struct_FAST_GLYPH_ORDER', 'struct_FAST_INDEX_ORDER', 'struct_GLYPH_DATA', 'struct_GLYPH_DATA_V2', 'struct_GLYPH_FRAGMENT', 'struct_GLYPH_FRAGMENT_INDEX', 'struct_GLYPH_INDEX_ORDER', 'struct_LINE_TO_ORDER', 'struct_MEM3BLT_ORDER', 'struct_MEMBLT_ORDER', 'struct_MULTI_DRAW_NINE_GRID_ORDER', 'struct_MULTI_DSTBLT_ORDER', 'struct_MULTI_OPAQUE_RECT_ORDER', 'struct_MULTI_PATBLT_ORDER', 'struct_MULTI_SCRBLT_ORDER', 'struct_OPAQUE_RECT_ORDER', 'struct_ORDER_INFO', 'struct_PATBLT_ORDER', 'struct_POLYGON_CB_ORDER', 'struct_POLYGON_SC_ORDER', 'struct_POLYLINE_ORDER', 'struct_SAVE_BITMAP_ORDER', 'struct_SCRBLT_ORDER', 'struct_rdp_bounds', 'struct_rdp_brush', 'struct_rdp_primary_update']
