"""
Mirror of <freerdp/redirection.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
ENCODING_TYPE_ASN1_DER = 1
LB_CLIENT_TSV_URL = 0x1000
LB_DOMAIN = 8
LB_DONTSTOREUSERNAME = 0x20
LB_LOAD_BALANCE_INFO = 2
LB_NOREDIRECT = 0x80
LB_PASSWORD = 0x10
LB_PASSWORD_IS_PK_ENCRYPTED = 0x4000
LB_PASSWORD_MAX_LENGTH = 0x200
LB_REDIRECTION_GUID = 0x8000
LB_SERVER_TSV_CAPABLE = 0x2000
LB_SMARTCARD_LOGON = 0x40
LB_TARGET_CERTIFICATE = 0x10000
LB_TARGET_FQDN = 0x100
LB_TARGET_NETBIOS_NAME = 0x200
LB_TARGET_NET_ADDRESS = 1
LB_TARGET_NET_ADDRESSES = 0x800
LB_USERNAME = 4

# --- types declared in this header ---
rdpRedirection = _types.rdpRedirection

# --- functions declared in this header ---
FUNCTIONS = (
    'redirection_free',  # void (ctypes.POINTER(rdpRedirection))
    'redirection_new',  # ctypes.POINTER(rdpRedirection) ()
    'redirection_set_array_option',  # BOOL (ctypes.POINTER(rdpRedirection), UINT32, ctypes.POINTER(ctypes.c_char_p), ctypes.c_size_t)
    'redirection_set_byte_option',  # BOOL (ctypes.POINTER(rdpRedirection), UINT32, ctypes.POINTER(BYTE), ctypes.c_size_t)
    'redirection_set_flags',  # BOOL (ctypes.POINTER(rdpRedirection), UINT32)
    'redirection_set_session_id',  # BOOL (ctypes.POINTER(rdpRedirection), UINT32)
    'redirection_set_string_option',  # BOOL (ctypes.POINTER(rdpRedirection), UINT32, ctypes.c_char_p)
    'redirection_settings_are_valid',  # BOOL (ctypes.POINTER(rdpRedirection), ctypes.POINTER(UINT32))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['ENCODING_TYPE_ASN1_DER', 'FUNCTIONS', 'LB_CLIENT_TSV_URL', 'LB_DOMAIN', 'LB_DONTSTOREUSERNAME', 'LB_LOAD_BALANCE_INFO', 'LB_NOREDIRECT', 'LB_PASSWORD', 'LB_PASSWORD_IS_PK_ENCRYPTED', 'LB_PASSWORD_MAX_LENGTH', 'LB_REDIRECTION_GUID', 'LB_SERVER_TSV_CAPABLE', 'LB_SMARTCARD_LOGON', 'LB_TARGET_CERTIFICATE', 'LB_TARGET_FQDN', 'LB_TARGET_NETBIOS_NAME', 'LB_TARGET_NET_ADDRESS', 'LB_TARGET_NET_ADDRESSES', 'LB_USERNAME', 'bind', 'rdpRedirection']
