"""
Mirror of <freerdp/session.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
INFO_TYPE_LOGON = 0
INFO_TYPE_LOGON_EXTENDED_INF = 3
INFO_TYPE_LOGON_LONG = 1
INFO_TYPE_LOGON_PLAIN_NOTIFY = 2

# --- types declared in this header ---
RDP_LOGON_INFO_TYPE = _types.RDP_LOGON_INFO_TYPE
logon_info = _types.logon_info
logon_info_ex = _types.logon_info_ex
struct_rdp_logon_info = _types.struct_rdp_logon_info
struct_rdp_logon_info_ex = _types.struct_rdp_logon_info_ex

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_session_logon_type_data_str',  # ctypes.c_char_p (ctypes.c_uint32, ctypes.c_void_p, ctypes.c_char_p, ctypes.c_size_t)
    'freerdp_session_logon_type_str',  # ctypes.c_char_p (ctypes.c_uint32)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'INFO_TYPE_LOGON', 'INFO_TYPE_LOGON_EXTENDED_INF', 'INFO_TYPE_LOGON_LONG', 'INFO_TYPE_LOGON_PLAIN_NOTIFY', 'RDP_LOGON_INFO_TYPE', 'bind', 'logon_info', 'logon_info_ex', 'struct_rdp_logon_info', 'struct_rdp_logon_info_ex']
