"""
Mirror of <freerdp/settings.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
FREERDP_SETTINGS_REMOTE_MODE = 2
FREERDP_SETTINGS_SERVER_MODE = 1

# --- types declared in this header ---
rdpSettings = _types.rdpSettings

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_addin_argv_add_argument',  # BOOL (ctypes.POINTER(ADDIN_ARGV), ctypes.c_char_p)
    'freerdp_addin_argv_add_argument_ex',  # BOOL (ctypes.POINTER(ADDIN_ARGV), ctypes.c_char_p, ctypes.c_size_t)
    'freerdp_addin_argv_clone',  # ctypes.POINTER(ADDIN_ARGV) (ctypes.POINTER(ADDIN_ARGV))
    'freerdp_addin_argv_del_argument',  # BOOL (ctypes.POINTER(ADDIN_ARGV), ctypes.c_char_p)
    'freerdp_addin_argv_free',  # void (ctypes.POINTER(ADDIN_ARGV))
    'freerdp_addin_argv_new',  # ctypes.POINTER(ADDIN_ARGV) (ctypes.c_size_t, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_addin_replace_argument',  # ctypes.c_int (ctypes.POINTER(ADDIN_ARGV), ctypes.c_char_p, ctypes.c_char_p)
    'freerdp_addin_replace_argument_value',  # ctypes.c_int (ctypes.POINTER(ADDIN_ARGV), ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p)
    'freerdp_addin_set_argument',  # ctypes.c_int (ctypes.POINTER(ADDIN_ARGV), ctypes.c_char_p)
    'freerdp_addin_set_argument_value',  # ctypes.c_int (ctypes.POINTER(ADDIN_ARGV), ctypes.c_char_p, ctypes.c_char_p)
    'freerdp_capability_buffer_copy',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.POINTER(rdpSettings))
    'freerdp_capability_buffer_free',  # void (ctypes.POINTER(rdpSettings))
    'freerdp_device_clone',  # ctypes.POINTER(RDPDR_DEVICE) (ctypes.POINTER(RDPDR_DEVICE))
    'freerdp_device_collection_add',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.POINTER(RDPDR_DEVICE))
    'freerdp_device_collection_del',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.POINTER(RDPDR_DEVICE))
    'freerdp_device_collection_find',  # ctypes.POINTER(RDPDR_DEVICE) (ctypes.POINTER(rdpSettings), ctypes.c_char_p)
    'freerdp_device_collection_find_type',  # ctypes.POINTER(RDPDR_DEVICE) (ctypes.POINTER(rdpSettings), UINT32)
    'freerdp_device_collection_free',  # void (ctypes.POINTER(rdpSettings))
    'freerdp_device_equal',  # BOOL (ctypes.POINTER(RDPDR_DEVICE), ctypes.POINTER(RDPDR_DEVICE))
    'freerdp_device_free',  # void (ctypes.POINTER(RDPDR_DEVICE))
    'freerdp_device_get_args',  # ctypes.POINTER(ADDIN_ARGV) (ctypes.POINTER(RDPDR_DEVICE))
    'freerdp_device_new',  # ctypes.POINTER(RDPDR_DEVICE) (UINT32, ctypes.c_size_t, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_dynamic_channel_collection_add',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.POINTER(ADDIN_ARGV))
    'freerdp_dynamic_channel_collection_del',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.c_char_p)
    'freerdp_dynamic_channel_collection_find',  # ctypes.POINTER(ADDIN_ARGV) (ctypes.POINTER(rdpSettings), ctypes.c_char_p)
    'freerdp_dynamic_channel_collection_free',  # void (ctypes.POINTER(rdpSettings))
    'freerdp_encryption_level_string',  # ctypes.c_char_p (UINT32)
    'freerdp_encryption_methods_string',  # ctypes.c_char_p (UINT32, ctypes.c_char_p, ctypes.c_size_t)
    'freerdp_get_gateway_usage_method',  # UINT32 (ctypes.POINTER(rdpSettings))
    'freerdp_performance_flags_make',  # void (ctypes.POINTER(rdpSettings))
    'freerdp_performance_flags_split',  # void (ctypes.POINTER(rdpSettings))
    'freerdp_rail_support_flags_to_string',  # ctypes.c_char_p (UINT32, ctypes.c_char_p, ctypes.c_size_t)
    'freerdp_rdp_version_string',  # ctypes.c_char_p (UINT32)
    'freerdp_rdpdr_dtyp_string',  # ctypes.c_char_p (UINT32)
    'freerdp_server_license_issuers_copy',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.POINTER(ctypes.c_char_p), UINT32)
    'freerdp_server_license_issuers_free',  # void (ctypes.POINTER(rdpSettings))
    'freerdp_set_gateway_usage_method',  # BOOL (ctypes.POINTER(rdpSettings), UINT32)
    'freerdp_settings_append_string',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_String, ctypes.c_char_p, ctypes.c_char_p)
    'freerdp_settings_are_valid',  # BOOL (ctypes.POINTER(rdpSettings))
    'freerdp_settings_clone',  # ctypes.POINTER(rdpSettings) (ctypes.POINTER(rdpSettings))
    'freerdp_settings_copy',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.POINTER(rdpSettings))
    'freerdp_settings_copy_item',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.POINTER(rdpSettings), SSIZE_T)
    'freerdp_settings_deserialize',  # ctypes.POINTER(rdpSettings) (ctypes.c_char_p, ctypes.c_size_t)
    'freerdp_settings_dump',  # void (ctypes.POINTER(wLog), DWORD, ctypes.POINTER(rdpSettings))
    'freerdp_settings_free',  # void (ctypes.POINTER(rdpSettings))
    'freerdp_settings_get_bool',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Bool)
    'freerdp_settings_get_codecs_flags',  # UINT32 (ctypes.POINTER(rdpSettings))
    'freerdp_settings_get_config_path',  # ctypes.c_char_p ()
    'freerdp_settings_get_int16',  # INT16 (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Int16)
    'freerdp_settings_get_int32',  # INT32 (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Int32)
    'freerdp_settings_get_int64',  # INT64 (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Int64)
    'freerdp_settings_get_key_for_name',  # SSIZE_T (ctypes.c_char_p)
    'freerdp_settings_get_name_for_key',  # ctypes.c_char_p (SSIZE_T)
    'freerdp_settings_get_pointer',  # ctypes.c_void_p (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Pointer)
    'freerdp_settings_get_pointer_array',  # ctypes.c_void_p (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Pointer, ctypes.c_size_t)
    'freerdp_settings_get_pointer_array_writable',  # ctypes.c_void_p (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Pointer, ctypes.c_size_t)
    'freerdp_settings_get_pointer_writable',  # ctypes.c_void_p (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Pointer)
    'freerdp_settings_get_server_name',  # ctypes.c_char_p (ctypes.POINTER(rdpSettings))
    'freerdp_settings_get_string',  # ctypes.c_char_p (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_String)
    'freerdp_settings_get_string_as_utf16',  # ctypes.c_void_p (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_String, ctypes.POINTER(ctypes.c_size_t))
    'freerdp_settings_get_string_writable',  # ctypes.c_char_p (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_String)
    'freerdp_settings_get_type_for_key',  # SSIZE_T (SSIZE_T)
    'freerdp_settings_get_type_for_name',  # SSIZE_T (ctypes.c_char_p)
    'freerdp_settings_get_type_name_for_key',  # ctypes.c_char_p (SSIZE_T)
    'freerdp_settings_get_type_name_for_type',  # ctypes.c_char_p (SSIZE_T)
    'freerdp_settings_get_uint16',  # UINT16 (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_UInt16)
    'freerdp_settings_get_uint32',  # UINT32 (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_UInt32)
    'freerdp_settings_get_uint64',  # UINT64 (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_UInt64)
    'freerdp_settings_new',  # ctypes.POINTER(rdpSettings) (DWORD)
    'freerdp_settings_print_diff',  # BOOL (ctypes.POINTER(wLog), DWORD, ctypes.POINTER(rdpSettings), ctypes.POINTER(rdpSettings))
    'freerdp_settings_serialize',  # ctypes.c_char_p (ctypes.POINTER(rdpSettings), BOOL, ctypes.POINTER(ctypes.c_size_t))
    'freerdp_settings_set_bool',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Bool, BOOL)
    'freerdp_settings_set_int16',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Int16, INT16)
    'freerdp_settings_set_int32',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Int32, INT32)
    'freerdp_settings_set_int64',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Int64, INT64)
    'freerdp_settings_set_monitor_def_array_sorted',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.POINTER(rdpMonitor), ctypes.c_size_t)
    'freerdp_settings_set_pointer',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Pointer, ctypes.c_void_p)
    'freerdp_settings_set_pointer_array',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Pointer, ctypes.c_size_t, ctypes.c_void_p)
    'freerdp_settings_set_pointer_len',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_Pointer, ctypes.c_void_p, ctypes.c_size_t)
    'freerdp_settings_set_string',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_String, ctypes.c_char_p)
    'freerdp_settings_set_string_from_utf16',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_String, ctypes.c_void_p)
    'freerdp_settings_set_string_from_utf16N',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_String, ctypes.c_void_p, ctypes.c_size_t)
    'freerdp_settings_set_string_len',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_String, ctypes.c_char_p, ctypes.c_size_t)
    'freerdp_settings_set_uint16',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_UInt16, UINT16)
    'freerdp_settings_set_uint32',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_UInt32, UINT32)
    'freerdp_settings_set_uint64',  # BOOL (ctypes.POINTER(rdpSettings), FreeRDP_Settings_Keys_UInt64, UINT64)
    'freerdp_settings_set_value_for_name',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.c_char_p, ctypes.c_char_p)
    'freerdp_settings_update_from_caps',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.POINTER(BYTE), ctypes.POINTER(ctypes.POINTER(BYTE)), ctypes.POINTER(UINT32), UINT32, BOOL)
    'freerdp_static_channel_collection_add',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.POINTER(ADDIN_ARGV))
    'freerdp_static_channel_collection_del',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.c_char_p)
    'freerdp_static_channel_collection_find',  # ctypes.POINTER(ADDIN_ARGV) (ctypes.POINTER(rdpSettings), ctypes.c_char_p)
    'freerdp_static_channel_collection_free',  # void (ctypes.POINTER(rdpSettings))
    'freerdp_supported_color_depths_string',  # ctypes.c_char_p (UINT16, ctypes.c_char_p, ctypes.c_size_t)
    'freerdp_target_net_addresses_copy',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.POINTER(ctypes.c_char_p), UINT32)
    'freerdp_target_net_addresses_free',  # void (ctypes.POINTER(rdpSettings))
    'freerdp_update_gateway_usage_method',  # void (ctypes.POINTER(rdpSettings), UINT32, UINT32)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FREERDP_SETTINGS_REMOTE_MODE', 'FREERDP_SETTINGS_SERVER_MODE', 'FUNCTIONS', 'bind', 'rdpSettings']
