"""
Mirror of <freerdp/streamdump.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
STREAM_MSG_SRV_RX = 1
STREAM_MSG_SRV_TX = 2

# --- types declared in this header ---
StreamDumpDirection = _types.StreamDumpDirection
rdpStreamDumpContext = _types.rdpStreamDumpContext

# --- functions declared in this header ---
FUNCTIONS = (
    'stream_dump_append',  # SSIZE_T (ctypes.POINTER(rdpContext), UINT32, ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_size_t))
    'stream_dump_free',  # void (ctypes.POINTER(rdpStreamDumpContext))
    'stream_dump_get',  # SSIZE_T (ctypes.POINTER(rdpContext), ctypes.POINTER(UINT32), ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_size_t), ctypes.POINTER(UINT64))
    'stream_dump_new',  # ctypes.POINTER(rdpStreamDumpContext) ()
    'stream_dump_register_handlers',  # BOOL (ctypes.POINTER(rdpContext), CONNECTION_STATE, BOOL)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'STREAM_MSG_SRV_RX', 'STREAM_MSG_SRV_TX', 'StreamDumpDirection', 'bind', 'rdpStreamDumpContext']
