"""
Mirror of <freerdp/timer.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
FreeRDP_TimerCallback = _types.FreeRDP_TimerCallback
FreeRDP_TimerID = _types.FreeRDP_TimerID

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_timer_add',  # FreeRDP_TimerID (ctypes.POINTER(rdpContext), ctypes.c_uint64, FreeRDP_TimerCallback, ctypes.c_void_p, ctypes.c_bool)
    'freerdp_timer_remove',  # ctypes.c_bool (ctypes.POINTER(rdpContext), FreeRDP_TimerID)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'FreeRDP_TimerCallback', 'FreeRDP_TimerID', 'bind']
