"""
Mirror of <freerdp/transport_io.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
pTCPConnect = _types.pTCPConnect
pTransportAttach = _types.pTransportAttach
pTransportAttachLayer = _types.pTransportAttachLayer
pTransportConnectLayer = _types.pTransportConnectLayer
pTransportFkt = _types.pTransportFkt
pTransportGetPublicKey = _types.pTransportGetPublicKey
pTransportLayerFkt = _types.pTransportLayerFkt
pTransportLayerGetEvent = _types.pTransportLayerGetEvent
pTransportLayerRead = _types.pTransportLayerRead
pTransportLayerWait = _types.pTransportLayerWait
pTransportLayerWrite = _types.pTransportLayerWrite
pTransportRWFkt = _types.pTransportRWFkt
pTransportRead = _types.pTransportRead
pTransportSetBlockingMode = _types.pTransportSetBlockingMode
rdpTransportIo = _types.rdpTransportIo
rdpTransportLayer = _types.rdpTransportLayer
struct_rdpTransportLayer = _types.struct_rdpTransportLayer
struct_rdp_transport_io = _types.struct_rdp_transport_io

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_get_io_callback_context',  # ctypes.c_void_p (ctypes.POINTER(rdpContext))
    'freerdp_get_io_callbacks',  # ctypes.POINTER(rdpTransportIo) (ctypes.POINTER(rdpContext))
    'freerdp_get_transport',  # ctypes.POINTER(rdpTransport) (ctypes.POINTER(rdpContext))
    'freerdp_io_callback_set_event',  # BOOL (ctypes.POINTER(rdpContext), BOOL)
    'freerdp_set_io_callback_context',  # BOOL (ctypes.POINTER(rdpContext), ctypes.c_void_p)
    'freerdp_set_io_callbacks',  # BOOL (ctypes.POINTER(rdpContext), ctypes.POINTER(rdpTransportIo))
    'transport_get_context',  # ctypes.POINTER(rdpContext) (ctypes.POINTER(rdpTransport))
    'transport_layer_free',  # void (ctypes.POINTER(rdpTransportLayer))
    'transport_layer_new',  # ctypes.POINTER(rdpTransportLayer) (ctypes.POINTER(rdpTransport), ctypes.c_size_t)
    'transport_parse_pdu',  # SSIZE_T (ctypes.POINTER(rdpTransport), ctypes.POINTER(wStream), ctypes.POINTER(BOOL))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'pTCPConnect', 'pTransportAttach', 'pTransportAttachLayer', 'pTransportConnectLayer', 'pTransportFkt', 'pTransportGetPublicKey', 'pTransportLayerFkt', 'pTransportLayerGetEvent', 'pTransportLayerRead', 'pTransportLayerWait', 'pTransportLayerWrite', 'pTransportRWFkt', 'pTransportRead', 'pTransportSetBlockingMode', 'rdpTransportIo', 'rdpTransportLayer', 'struct_rdpTransportLayer', 'struct_rdp_transport_io']
