"""
Mirror of <freerdp/update.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from .._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
CMDTYPE_FRAME_MARKER = 4
CMDTYPE_SET_SURFACE_BITS = 1
CMDTYPE_STREAM_SURFACE_BITS = 6
EX_COMPRESSED_BITMAP_HEADER_PRESENT = 1
SURFACECMD_FRAMEACTION_BEGIN = 0
SURFACECMD_FRAMEACTION_END = 1
TS_STATUS_BRINGING_SESSION_ONLINE = 0x403
TS_STATUS_FINDING_DESTINATION = 0x401
TS_STATUS_LOADING_DESTINATION = 0x402
TS_STATUS_REDIRECTING_TO_DESTINATION = 0x404
TS_STATUS_VM_LOADING = 0x501
TS_STATUS_VM_RETRYING_MONITORING = 0x505
TS_STATUS_VM_STARTING = 0x503
TS_STATUS_VM_STARTING_MONITORING = 0x504
TS_STATUS_VM_WAKING = 0x502

# --- types declared in this header ---
BITMAP_DATA = _types.BITMAP_DATA
BITMAP_UPDATE = _types.BITMAP_UPDATE
PALETTE_UPDATE = _types.PALETTE_UPDATE
PLAY_SOUND_UPDATE = _types.PLAY_SOUND_UPDATE
SURFACE_BITS_COMMAND = _types.SURFACE_BITS_COMMAND
SURFACE_FRAME = _types.SURFACE_FRAME
SURFACE_FRAME_MARKER = _types.SURFACE_FRAME_MARKER
TS_BITMAP_DATA_EX = _types.TS_BITMAP_DATA_EX
TS_COMPRESSED_BITMAP_HEADER_EX = _types.TS_COMPRESSED_BITMAP_HEADER_EX
pBeginPaint = _types.pBeginPaint
pBitmapUpdate = _types.pBitmapUpdate
pDesktopResize = _types.pDesktopResize
pEndPaint = _types.pEndPaint
pPalette = _types.pPalette
pPlaySound = _types.pPlaySound
pRefreshRect = _types.pRefreshRect
pRemoteMonitors = _types.pRemoteMonitors
pSaveSessionInfo = _types.pSaveSessionInfo
pServerStatusInfo = _types.pServerStatusInfo
pSetBounds = _types.pSetBounds
pSetKeyboardImeStatus = _types.pSetKeyboardImeStatus
pSetKeyboardIndicators = _types.pSetKeyboardIndicators
pSuppressOutput = _types.pSuppressOutput
pSurfaceBits = _types.pSurfaceBits
pSurfaceCommand = _types.pSurfaceCommand
pSurfaceFrameAcknowledge = _types.pSurfaceFrameAcknowledge
pSurfaceFrameBits = _types.pSurfaceFrameBits
pSurfaceFrameMarker = _types.pSurfaceFrameMarker
pSynchronize = _types.pSynchronize
rdpUpdate = _types.rdpUpdate
rdpUpdateProxy = _types.rdpUpdateProxy
struct_BITMAP_DATA = _types.struct_BITMAP_DATA
struct_BITMAP_UPDATE = _types.struct_BITMAP_UPDATE
struct_PALETTE_UPDATE = _types.struct_PALETTE_UPDATE
struct_PLAY_SOUND_UPDATE = _types.struct_PLAY_SOUND_UPDATE
struct_SURFACE_BITS_COMMAND = _types.struct_SURFACE_BITS_COMMAND
struct_SURFACE_FRAME = _types.struct_SURFACE_FRAME
struct_SURFACE_FRAME_MARKER = _types.struct_SURFACE_FRAME_MARKER
struct_TS_BITMAP_DATA_EX = _types.struct_TS_BITMAP_DATA_EX
struct_TS_COMPRESSED_BITMAP_HEADER_EX = _types.struct_TS_COMPRESSED_BITMAP_HEADER_EX
struct_rdp_update = _types.struct_rdp_update

# --- functions declared in this header ---
FUNCTIONS = (
    'rdp_stats_max_index',  # ctypes.c_size_t ()
    'rdp_stats_name_for_index',  # ctypes.c_char_p (ctypes.c_size_t)
    'rdp_stats_value_for_index',  # ctypes.c_uint64 (ctypes.POINTER(rdpUpdate), ctypes.c_size_t)
    'rdp_update_lock',  # void (ctypes.POINTER(rdpUpdate))
    'rdp_update_unlock',  # void (ctypes.POINTER(rdpUpdate))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['BITMAP_DATA', 'BITMAP_UPDATE', 'CMDTYPE_FRAME_MARKER', 'CMDTYPE_SET_SURFACE_BITS', 'CMDTYPE_STREAM_SURFACE_BITS', 'EX_COMPRESSED_BITMAP_HEADER_PRESENT', 'FUNCTIONS', 'PALETTE_UPDATE', 'PLAY_SOUND_UPDATE', 'SURFACECMD_FRAMEACTION_BEGIN', 'SURFACECMD_FRAMEACTION_END', 'SURFACE_BITS_COMMAND', 'SURFACE_FRAME', 'SURFACE_FRAME_MARKER', 'TS_BITMAP_DATA_EX', 'TS_COMPRESSED_BITMAP_HEADER_EX', 'TS_STATUS_BRINGING_SESSION_ONLINE', 'TS_STATUS_FINDING_DESTINATION', 'TS_STATUS_LOADING_DESTINATION', 'TS_STATUS_REDIRECTING_TO_DESTINATION', 'TS_STATUS_VM_LOADING', 'TS_STATUS_VM_RETRYING_MONITORING', 'TS_STATUS_VM_STARTING', 'TS_STATUS_VM_STARTING_MONITORING', 'TS_STATUS_VM_WAKING', 'bind', 'pBeginPaint', 'pBitmapUpdate', 'pDesktopResize', 'pEndPaint', 'pPalette', 'pPlaySound', 'pRefreshRect', 'pRemoteMonitors', 'pSaveSessionInfo', 'pServerStatusInfo', 'pSetBounds', 'pSetKeyboardImeStatus', 'pSetKeyboardIndicators', 'pSuppressOutput', 'pSurfaceBits', 'pSurfaceCommand', 'pSurfaceFrameAcknowledge', 'pSurfaceFrameBits', 'pSurfaceFrameMarker', 'pSynchronize', 'rdpUpdate', 'rdpUpdateProxy', 'struct_BITMAP_DATA', 'struct_BITMAP_UPDATE', 'struct_PALETTE_UPDATE', 'struct_PLAY_SOUND_UPDATE', 'struct_SURFACE_BITS_COMMAND', 'struct_SURFACE_FRAME', 'struct_SURFACE_FRAME_MARKER', 'struct_TS_BITMAP_DATA_EX', 'struct_TS_COMPRESSED_BITMAP_HEADER_EX', 'struct_rdp_update']
