"""
Mirror of <freerdp/gdi/bitmap.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
p_BitBlt = _types.p_BitBlt

# --- functions declared in this header ---
FUNCTIONS = (
    'gdi_BitBlt',  # BOOL (HGDI_DC, INT32, INT32, INT32, INT32, HGDI_DC, INT32, INT32, DWORD, ctypes.POINTER(gdiPalette))
    'gdi_CreateBitmap',  # HGDI_BITMAP (UINT32, UINT32, UINT32, ctypes.POINTER(BYTE))
    'gdi_CreateBitmapEx',  # HGDI_BITMAP (UINT32, UINT32, UINT32, UINT32, ctypes.POINTER(BYTE), ctypes.CFUNCTYPE(None, ctypes.c_void_p))
    'gdi_CreateCompatibleBitmap',  # HGDI_BITMAP (HGDI_DC, UINT32, UINT32)
    'gdi_GetPixel',  # UINT32 (HGDI_DC, UINT32, UINT32)
    'gdi_GetPointer',  # ctypes.POINTER(BYTE) (HGDI_BITMAP, UINT32, UINT32)
    'gdi_SetPixel',  # UINT32 (HGDI_DC, UINT32, UINT32, UINT32)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'p_BitBlt']
