"""
Mirror of <freerdp/gdi/dc.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'gdi_CreateCompatibleDC',  # HGDI_DC (HGDI_DC)
    'gdi_CreateDC',  # HGDI_DC (UINT32)
    'gdi_DeleteDC',  # BOOL (HGDI_DC)
    'gdi_DeleteObject',  # BOOL (HGDIOBJECT)
    'gdi_GetDC',  # HGDI_DC ()
    'gdi_SelectObject',  # HGDIOBJECT (HGDI_DC, HGDIOBJECT)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
