"""
Mirror of <freerdp/gdi/gfx.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
gdiGfxCacheEntry = _types.gdiGfxCacheEntry
gdiGfxSurface = _types.gdiGfxSurface
struct_gdi_gfx_cache_entry = _types.struct_gdi_gfx_cache_entry
struct_gdi_gfx_surface = _types.struct_gdi_gfx_surface

# --- functions declared in this header ---
FUNCTIONS = (
    'gdi_graphics_pipeline_init',  # BOOL (ctypes.POINTER(rdpGdi), ctypes.POINTER(RdpgfxClientContext))
    'gdi_graphics_pipeline_init_ex',  # BOOL (ctypes.POINTER(rdpGdi), ctypes.POINTER(RdpgfxClientContext), pcRdpgfxMapWindowForSurface, pcRdpgfxUnmapWindowForSurface, pcRdpgfxUpdateSurfaceArea)
    'gdi_graphics_pipeline_uninit',  # void (ctypes.POINTER(rdpGdi), ctypes.POINTER(RdpgfxClientContext))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'gdiGfxCacheEntry', 'gdiGfxSurface', 'struct_gdi_gfx_cache_entry', 'struct_gdi_gfx_surface']
