"""
Mirror of <freerdp/gdi/region.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'gdi_CRectToCRgn',  # BOOL (INT32, INT32, INT32, INT32, ctypes.POINTER(INT32), ctypes.POINTER(INT32), ctypes.POINTER(INT32), ctypes.POINTER(INT32))
    'gdi_CRectToRgn',  # BOOL (INT32, INT32, INT32, INT32, HGDI_RGN)
    'gdi_CRgnToCRect',  # BOOL (INT32, INT32, INT32, INT32, ctypes.POINTER(INT32), ctypes.POINTER(INT32), ctypes.POINTER(INT32), ctypes.POINTER(INT32))
    'gdi_CRgnToRect',  # BOOL (INT64, INT64, INT32, INT32, ctypes.POINTER(GDI_RECT))
    'gdi_CopyOverlap',  # BOOL (INT32, INT32, INT32, INT32, INT32, INT32)
    'gdi_CopyRect',  # BOOL (ctypes.POINTER(GDI_RECT), ctypes.POINTER(GDI_RECT))
    'gdi_CreateRect',  # ctypes.POINTER(GDI_RECT) (INT32, INT32, INT32, INT32)
    'gdi_CreateRectRgn',  # HGDI_RGN (INT32, INT32, INT32, INT32)
    'gdi_EqualRgn',  # BOOL (ctypes.POINTER(GDI_RGN), ctypes.POINTER(GDI_RGN))
    'gdi_InvalidateRegion',  # BOOL (HGDI_DC, INT32, INT32, INT32, INT32)
    'gdi_PtInRect',  # BOOL (ctypes.POINTER(GDI_RECT), INT32, INT32)
    'gdi_RectToCRgn',  # BOOL (ctypes.POINTER(GDI_RECT), ctypes.POINTER(INT32), ctypes.POINTER(INT32), ctypes.POINTER(INT32), ctypes.POINTER(INT32))
    'gdi_RectToRgn',  # BOOL (ctypes.POINTER(GDI_RECT), HGDI_RGN)
    'gdi_RgnToCRect',  # BOOL (ctypes.POINTER(GDI_RGN), ctypes.POINTER(INT32), ctypes.POINTER(INT32), ctypes.POINTER(INT32), ctypes.POINTER(INT32))
    'gdi_RgnToRect',  # BOOL (ctypes.POINTER(GDI_RGN), ctypes.POINTER(GDI_RECT))
    'gdi_SetRect',  # BOOL (ctypes.POINTER(GDI_RECT), INT32, INT32, INT32, INT32)
    'gdi_SetRectRgn',  # BOOL (HGDI_RGN, INT32, INT32, INT32, INT32)
    'gdi_SetRgn',  # BOOL (HGDI_RGN, INT32, INT32, INT32, INT32)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
