"""
Mirror of <freerdp/gdi/shape.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'gdi_Ellipse',  # BOOL (HGDI_DC, ctypes.c_int, ctypes.c_int, ctypes.c_int, ctypes.c_int)
    'gdi_FillRect',  # BOOL (HGDI_DC, ctypes.POINTER(GDI_RECT), HGDI_BRUSH)
    'gdi_PolyPolygon',  # BOOL (HGDI_DC, ctypes.POINTER(GDI_POINT), ctypes.POINTER(ctypes.c_int), ctypes.c_int)
    'gdi_Polygon',  # BOOL (HGDI_DC, ctypes.POINTER(GDI_POINT), ctypes.c_int)
    'gdi_Rectangle',  # BOOL (HGDI_DC, INT32, INT32, INT32, INT32)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
