"""
Mirror of <freerdp/gdi/video.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
gdiVideoContext = _types.gdiVideoContext

# --- functions declared in this header ---
FUNCTIONS = (
    'gdi_video_control_init',  # void (ctypes.POINTER(rdpGdi), ctypes.POINTER(VideoClientContext))
    'gdi_video_control_uninit',  # void (ctypes.POINTER(rdpGdi), ctypes.POINTER(VideoClientContext))
    'gdi_video_data_init',  # void (ctypes.POINTER(rdpGdi), ctypes.POINTER(VideoClientContext))
    'gdi_video_data_uninit',  # void (ctypes.POINTER(rdpGdi), ctypes.POINTER(VideoClientContext))
    'gdi_video_free',  # void (ctypes.POINTER(gdiVideoContext))
    'gdi_video_geometry_init',  # void (ctypes.POINTER(rdpGdi), ctypes.POINTER(GeometryClientContext))
    'gdi_video_geometry_uninit',  # void (ctypes.POINTER(rdpGdi), ctypes.POINTER(GeometryClientContext))
    'gdi_video_new',  # ctypes.POINTER(gdiVideoContext) (ctypes.POINTER(rdpGdi))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'gdiVideoContext']
