"""
Mirror of <freerdp/server/proxy/proxy_config.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ...._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
proxyConfig = _types.proxyConfig
struct_proxy_config = _types.struct_proxy_config

# --- functions declared in this header ---
FUNCTIONS = (
    'pf_config_clone',  # BOOL (ctypes.POINTER(ctypes.POINTER(proxyConfig)), ctypes.POINTER(proxyConfig))
    'pf_config_get',  # ctypes.c_char_p (ctypes.POINTER(proxyConfig), ctypes.c_char_p, ctypes.c_char_p)
    'pf_config_modules',  # ctypes.POINTER(ctypes.c_char_p) (ctypes.POINTER(proxyConfig))
    'pf_config_modules_count',  # ctypes.c_size_t (ctypes.POINTER(proxyConfig))
    'pf_config_plugin',  # BOOL (ctypes.POINTER(proxyPluginsManager), ctypes.c_void_p)
    'pf_config_required_plugin',  # ctypes.c_char_p (ctypes.POINTER(proxyConfig), ctypes.c_size_t)
    'pf_config_required_plugins_count',  # ctypes.c_size_t (ctypes.POINTER(proxyConfig))
    'pf_server_config_dump',  # BOOL (ctypes.c_char_p)
    'pf_server_config_free',  # void (ctypes.POINTER(proxyConfig))
    'pf_server_config_load_buffer',  # ctypes.POINTER(proxyConfig) (ctypes.c_char_p)
    'pf_server_config_load_file',  # ctypes.POINTER(proxyConfig) (ctypes.c_char_p)
    'pf_server_config_print',  # void (ctypes.POINTER(proxyConfig))
    'server_config_load_ini',  # ctypes.POINTER(proxyConfig) (ctypes.POINTER(wIniFile))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'proxyConfig', 'struct_proxy_config']
