"""
Mirror of <freerdp/server/proxy/proxy_server.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ...._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
proxyServer = _types.proxyServer

# --- functions declared in this header ---
FUNCTIONS = (
    'pf_server_add_module',  # BOOL (ctypes.POINTER(proxyServer), proxyModuleEntryPoint, ctypes.c_void_p)
    'pf_server_free',  # void (ctypes.POINTER(proxyServer))
    'pf_server_new',  # ctypes.POINTER(proxyServer) (ctypes.POINTER(proxyConfig))
    'pf_server_run',  # BOOL (ctypes.POINTER(proxyServer))
    'pf_server_start',  # BOOL (ctypes.POINTER(proxyServer))
    'pf_server_start_from_socket',  # BOOL (ctypes.POINTER(proxyServer), ctypes.c_int)
    'pf_server_start_with_peer_socket',  # BOOL (ctypes.POINTER(proxyServer), ctypes.c_int)
    'pf_server_stop',  # void (ctypes.POINTER(proxyServer))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'proxyServer']
