"""
Mirror of <freerdp/server/proxy/proxy_config.h> (FreeRDP 3.32.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ...._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
FREERDP_PROXY_CERT_POLICY_ALLOW = 1
FREERDP_PROXY_CERT_POLICY_DENY = 0
FREERDP_PROXY_CERT_POLICY_PINNED = 2

# --- types declared in this header ---
FreeRDP_ProxyCertPolicy = _types.FreeRDP_ProxyCertPolicy
proxyConfig = _types.proxyConfig
struct_proxy_config = _types.struct_proxy_config

# --- functions declared in this header ---
FUNCTIONS = (
    'pf_config_clone',  # BOOL (ctypes.POINTER(ctypes.POINTER(proxyConfig)), ctypes.POINTER(proxyConfig))
    'pf_config_get',  # ctypes.c_char_p (ctypes.POINTER(proxyConfig), ctypes.c_char_p, ctypes.c_char_p)
    'pf_config_modules',  # ctypes.POINTER(ctypes.c_char_p) (ctypes.POINTER(proxyConfig))
    'pf_config_modules_count',  # ctypes.c_size_t (ctypes.POINTER(proxyConfig))
    'pf_config_plugin',  # BOOL (ctypes.POINTER(proxyPluginsManager), ctypes.c_void_p)
    'pf_config_policy_from_str',  # FreeRDP_ProxyCertPolicy (ctypes.c_char_p)
    'pf_config_policy_to_str',  # ctypes.c_char_p (FreeRDP_ProxyCertPolicy)
    'pf_config_required_plugin',  # ctypes.c_char_p (ctypes.POINTER(proxyConfig), ctypes.c_size_t)
    'pf_config_required_plugins_count',  # ctypes.c_size_t (ctypes.POINTER(proxyConfig))
    'pf_server_config_dump',  # BOOL (ctypes.c_char_p)
    'pf_server_config_free',  # void (ctypes.POINTER(proxyConfig))
    'pf_server_config_load_buffer',  # ctypes.POINTER(proxyConfig) (ctypes.c_char_p)
    'pf_server_config_load_file',  # ctypes.POINTER(proxyConfig) (ctypes.c_char_p)
    'pf_server_config_print',  # void (ctypes.POINTER(proxyConfig))
    'server_config_load_ini',  # ctypes.POINTER(proxyConfig) (ctypes.POINTER(wIniFile))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FREERDP_PROXY_CERT_POLICY_ALLOW', 'FREERDP_PROXY_CERT_POLICY_DENY', 'FREERDP_PROXY_CERT_POLICY_PINNED', 'FUNCTIONS', 'FreeRDP_ProxyCertPolicy', 'bind', 'proxyConfig', 'struct_proxy_config']
