"""
Mirror of <freerdp/server/proxy/proxy_modules_api.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ...._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
proxyChannelDataEventInfo = _types.proxyChannelDataEventInfo
proxyChannelToInterceptData = _types.proxyChannelToInterceptData
proxyData = _types.proxyData
proxyDynChannelInterceptData = _types.proxyDynChannelInterceptData
proxyFetchTargetEventInfo = _types.proxyFetchTargetEventInfo
proxyFilterFn = _types.proxyFilterFn
proxyHookFn = _types.proxyHookFn
proxyKeyboardEventInfo = _types.proxyKeyboardEventInfo
proxyModule = _types.proxyModule
proxyModuleEntryPoint = _types.proxyModuleEntryPoint
proxyMouseEventInfo = _types.proxyMouseEventInfo
proxyMouseExEventInfo = _types.proxyMouseExEventInfo
proxyPlugin = _types.proxyPlugin
proxyPluginsManager = _types.proxyPluginsManager
proxyServerPeerLogon = _types.proxyServerPeerLogon
proxyUnicodeEventInfo = _types.proxyUnicodeEventInfo
struct_dyn_channel_intercept_data = _types.struct_dyn_channel_intercept_data
struct_dyn_channel_to_intercept_data = _types.struct_dyn_channel_to_intercept_data
struct_proxyChannelDataEventInfo = _types.struct_proxyChannelDataEventInfo
struct_proxyFetchTargetEventInfo = _types.struct_proxyFetchTargetEventInfo
struct_proxy_keyboard_event_info = _types.struct_proxy_keyboard_event_info
struct_proxy_mouse_event_info = _types.struct_proxy_mouse_event_info
struct_proxy_mouse_ex_event_info = _types.struct_proxy_mouse_ex_event_info
struct_proxy_plugin = _types.struct_proxy_plugin
struct_proxy_plugins_manager = _types.struct_proxy_plugins_manager
struct_proxy_unicode_event_info = _types.struct_proxy_unicode_event_info
struct_server_peer_logon = _types.struct_server_peer_logon

__all__ = ['proxyChannelDataEventInfo', 'proxyChannelToInterceptData', 'proxyData', 'proxyDynChannelInterceptData', 'proxyFetchTargetEventInfo', 'proxyFilterFn', 'proxyHookFn', 'proxyKeyboardEventInfo', 'proxyModule', 'proxyModuleEntryPoint', 'proxyMouseEventInfo', 'proxyMouseExEventInfo', 'proxyPlugin', 'proxyPluginsManager', 'proxyServerPeerLogon', 'proxyUnicodeEventInfo', 'struct_dyn_channel_intercept_data', 'struct_dyn_channel_to_intercept_data', 'struct_proxyChannelDataEventInfo', 'struct_proxyFetchTargetEventInfo', 'struct_proxy_keyboard_event_info', 'struct_proxy_mouse_event_info', 'struct_proxy_mouse_ex_event_info', 'struct_proxy_plugin', 'struct_proxy_plugins_manager', 'struct_proxy_unicode_event_info', 'struct_server_peer_logon']
