"""
Mirror of <freerdp/server/proxy/proxy_context.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ...._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
PROXY_SESSION_ID_LENGTH = 0x20

# --- types declared in this header ---
InterceptContextMapEntry = _types.InterceptContextMapEntry
pClientContext = _types.pClientContext
pServerContext = _types.pServerContext
pServerStaticChannelContext = _types.pServerStaticChannelContext
proxyChannelContextDtor = _types.proxyChannelContextDtor
proxyChannelDataFn = _types.proxyChannelDataFn
proxyData = _types.proxyData
proxyModule = _types.proxyModule
struct_p_server_static_channel_context = _types.struct_p_server_static_channel_context
struct_proxy_data = _types.struct_proxy_data
struct_s_InterceptContextMapEntry = _types.struct_s_InterceptContextMapEntry

# --- functions declared in this header ---
FUNCTIONS = (
    'StaticChannelContext_free',  # void (ctypes.POINTER(pServerStaticChannelContext))
    'StaticChannelContext_new',  # ctypes.POINTER(pServerStaticChannelContext) (ctypes.POINTER(pServerContext), ctypes.c_char_p, UINT32)
    'intercept_context_entry_free',  # void (ctypes.c_void_p)
    'pf_context_copy_settings',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.POINTER(rdpSettings))
    'pf_context_create_client_context',  # ctypes.POINTER(pClientContext) (ctypes.POINTER(rdpSettings))
    'pf_context_init_server_context',  # BOOL (ctypes.POINTER(freerdp_peer))
    'proxy_data_abort_connect',  # void (ctypes.POINTER(proxyData))
    'proxy_data_free',  # void (ctypes.POINTER(proxyData))
    'proxy_data_get_client_context',  # ctypes.POINTER(pClientContext) (ctypes.POINTER(proxyData))
    'proxy_data_get_server_context',  # ctypes.POINTER(pServerContext) (ctypes.POINTER(proxyData))
    'proxy_data_new',  # ctypes.POINTER(proxyData) ()
    'proxy_data_set_client_context',  # void (ctypes.POINTER(proxyData), ctypes.POINTER(pClientContext))
    'proxy_data_set_server_context',  # void (ctypes.POINTER(proxyData), ctypes.POINTER(pServerContext))
    'proxy_data_shall_disconnect',  # BOOL (ctypes.POINTER(proxyData))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'InterceptContextMapEntry', 'PROXY_SESSION_ID_LENGTH', 'bind', 'pClientContext', 'pServerContext', 'pServerStaticChannelContext', 'proxyChannelContextDtor', 'proxyChannelDataFn', 'proxyData', 'proxyModule', 'struct_p_server_static_channel_context', 'struct_proxy_data', 'struct_s_InterceptContextMapEntry']
