"""
Mirror of <freerdp/server/proxy/proxy_types.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ...._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
PF_CHANNEL_RESULT_DROP = 1
PF_CHANNEL_RESULT_ERROR = 2
PF_CHANNEL_RESULT_PASS = 0
PF_UTILS_CHANNEL_BLOCK = 1
PF_UTILS_CHANNEL_INTERCEPT = 3
PF_UTILS_CHANNEL_NOT_HANDLED = 0
PF_UTILS_CHANNEL_PASSTHROUGH = 2
PROXY_FETCH_TARGET_METHOD_CONFIG = 1
PROXY_FETCH_TARGET_METHOD_DEFAULT = 0
PROXY_FETCH_TARGET_METHOD_LOAD_BALANCE_INFO = 2
PROXY_FETCH_TARGET_USE_CUSTOM_ADDR = 3

# --- types declared in this header ---
PfChannelResult = _types.PfChannelResult
ProxyFetchTargetMethod = _types.ProxyFetchTargetMethod
pf_utils_channel_mode = _types.pf_utils_channel_mode

__all__ = ['PF_CHANNEL_RESULT_DROP', 'PF_CHANNEL_RESULT_ERROR', 'PF_CHANNEL_RESULT_PASS', 'PF_UTILS_CHANNEL_BLOCK', 'PF_UTILS_CHANNEL_INTERCEPT', 'PF_UTILS_CHANNEL_NOT_HANDLED', 'PF_UTILS_CHANNEL_PASSTHROUGH', 'PROXY_FETCH_TARGET_METHOD_CONFIG', 'PROXY_FETCH_TARGET_METHOD_DEFAULT', 'PROXY_FETCH_TARGET_METHOD_LOAD_BALANCE_INFO', 'PROXY_FETCH_TARGET_USE_CUSTOM_ADDR', 'PfChannelResult', 'ProxyFetchTargetMethod', 'pf_utils_channel_mode']
