"""
Mirror of <freerdp/utils/aad.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
AAD_WELLKNOWN_authorization_endpoint = 0xb
AAD_WELLKNOWN_claims_supported = 0x10
AAD_WELLKNOWN_cloud_graph_host_name = 0x14
AAD_WELLKNOWN_cloud_instance_name = 0x13
AAD_WELLKNOWN_device_authorization_endpoint = 0xc
AAD_WELLKNOWN_end_session_endpoint = 0xf
AAD_WELLKNOWN_frontchannel_logout_supported = 0xe
AAD_WELLKNOWN_http_logout_supported = 0xd
AAD_WELLKNOWN_id_token_signing_alg_values_supported = 5
AAD_WELLKNOWN_issuer = 8
AAD_WELLKNOWN_jwks_uri = 2
AAD_WELLKNOWN_kerberos_endpoint = 0x11
AAD_WELLKNOWN_msgraph_host = 0x15
AAD_WELLKNOWN_rbac_url = 0x16
AAD_WELLKNOWN_request_uri_parameter_supported = 9
AAD_WELLKNOWN_response_modes_supported = 3
AAD_WELLKNOWN_response_types_supported = 6
AAD_WELLKNOWN_scopes_supported = 7
AAD_WELLKNOWN_subject_types_supported = 4
AAD_WELLKNOWN_tenant_region_scope = 0x12
AAD_WELLKNOWN_token_endpoint = 0
AAD_WELLKNOWN_token_endpoint_auth_methods_supported = 1
AAD_WELLKNOWN_userinfo_endpoint = 0xa

# --- types declared in this header ---
AAD_WELLKNOWN_VALUES = _types.AAD_WELLKNOWN_VALUES

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_utils_aad_get_access_token',  # ctypes.c_char_p (ctypes.POINTER(wLog), ctypes.c_char_p, ctypes.c_size_t)
    'freerdp_utils_aad_get_wellknown',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(wLog), ctypes.c_char_p, ctypes.c_char_p)
    'freerdp_utils_aad_get_wellknown_custom_object',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(rdpContext), ctypes.c_char_p)
    'freerdp_utils_aad_get_wellknown_custom_string',  # ctypes.c_char_p (ctypes.POINTER(rdpContext), ctypes.c_char_p)
    'freerdp_utils_aad_get_wellknown_object',  # ctypes.POINTER(WINPR_JSON) (ctypes.POINTER(rdpContext), AAD_WELLKNOWN_VALUES)
    'freerdp_utils_aad_get_wellknown_string',  # ctypes.c_char_p (ctypes.POINTER(rdpContext), AAD_WELLKNOWN_VALUES)
    'freerdp_utils_aad_wellknwon_value_name',  # ctypes.c_char_p (AAD_WELLKNOWN_VALUES)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['AAD_WELLKNOWN_VALUES', 'AAD_WELLKNOWN_authorization_endpoint', 'AAD_WELLKNOWN_claims_supported', 'AAD_WELLKNOWN_cloud_graph_host_name', 'AAD_WELLKNOWN_cloud_instance_name', 'AAD_WELLKNOWN_device_authorization_endpoint', 'AAD_WELLKNOWN_end_session_endpoint', 'AAD_WELLKNOWN_frontchannel_logout_supported', 'AAD_WELLKNOWN_http_logout_supported', 'AAD_WELLKNOWN_id_token_signing_alg_values_supported', 'AAD_WELLKNOWN_issuer', 'AAD_WELLKNOWN_jwks_uri', 'AAD_WELLKNOWN_kerberos_endpoint', 'AAD_WELLKNOWN_msgraph_host', 'AAD_WELLKNOWN_rbac_url', 'AAD_WELLKNOWN_request_uri_parameter_supported', 'AAD_WELLKNOWN_response_modes_supported', 'AAD_WELLKNOWN_response_types_supported', 'AAD_WELLKNOWN_scopes_supported', 'AAD_WELLKNOWN_subject_types_supported', 'AAD_WELLKNOWN_tenant_region_scope', 'AAD_WELLKNOWN_token_endpoint', 'AAD_WELLKNOWN_token_endpoint_auth_methods_supported', 'AAD_WELLKNOWN_userinfo_endpoint', 'FUNCTIONS', 'bind']
