"""
Mirror of <freerdp/utils/channel_pdu_tracker.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
ChannelPduTracker = _types.ChannelPduTracker

# --- functions declared in this header ---
FUNCTIONS = (
    'ChannelPduTracker_free',  # void (ctypes.POINTER(ChannelPduTracker))
    'ChannelPduTracker_new',  # ctypes.POINTER(ChannelPduTracker) (HANDLE)
    'ChannelPduTracker_poll',  # ctypes.POINTER(wStream) (ctypes.POINTER(ChannelPduTracker), ctypes.POINTER(BOOL))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['ChannelPduTracker', 'FUNCTIONS', 'bind']
