"""
Mirror of <freerdp/utils/cliprdr_utils.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'cliprdr_parse_file_list',  # UINT (ctypes.POINTER(BYTE), UINT32, ctypes.POINTER(ctypes.POINTER(FILEDESCRIPTORW)), ctypes.POINTER(UINT32))
    'cliprdr_read_filedescriptor',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(FILEDESCRIPTORW))
    'cliprdr_serialize_file_list',  # UINT (ctypes.POINTER(FILEDESCRIPTORW), UINT32, ctypes.POINTER(ctypes.POINTER(BYTE)), ctypes.POINTER(UINT32))
    'cliprdr_serialize_file_list_ex',  # UINT (UINT32, ctypes.POINTER(FILEDESCRIPTORW), UINT32, ctypes.POINTER(ctypes.POINTER(BYTE)), ctypes.POINTER(UINT32))
    'cliprdr_write_filedescriptor',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(FILEDESCRIPTORW))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
