"""
Mirror of <freerdp/utils/encoded_types.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
FREERDP_FOUR_BYTE_FLOAT_MAX = 0x3ffffff
FREERDP_FOUR_BYTE_FLOAT_MIN = -67108863
FREERDP_FOUR_BYTE_SIGNED_INT_MAX = 0x1fffffff
FREERDP_FOUR_BYTE_SIGNED_INT_MIN = -536870911

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_read_four_byte_float',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_double))
    'freerdp_read_four_byte_float_exp',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_double), ctypes.POINTER(BYTE))
    'freerdp_read_four_byte_signed_integer',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(INT32))
    'freerdp_write_four_byte_float',  # BOOL (ctypes.POINTER(wStream), ctypes.c_double)
    'freerdp_write_four_byte_signed_integer',  # BOOL (ctypes.POINTER(wStream), INT32)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FREERDP_FOUR_BYTE_FLOAT_MAX', 'FREERDP_FOUR_BYTE_FLOAT_MIN', 'FREERDP_FOUR_BYTE_SIGNED_INT_MAX', 'FREERDP_FOUR_BYTE_SIGNED_INT_MIN', 'FUNCTIONS', 'bind']
