"""
Mirror of <freerdp/utils/gfx.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'rdpgfx_caps_flag_str',  # ctypes.c_char_p (UINT32)
    'rdpgfx_caps_flags_str',  # ctypes.c_char_p (UINT32, ctypes.c_char_p, ctypes.c_size_t)
    'rdpgfx_caps_version_str',  # ctypes.c_char_p (UINT32)
    'rdpgfx_get_cmd_id_string',  # ctypes.c_char_p (UINT16)
    'rdpgfx_get_codec_id_string',  # ctypes.c_char_p (UINT16)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
