"""
Mirror of <freerdp/utils/helpers.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_GetConfigFilePath',  # ctypes.c_char_p (BOOL, ctypes.c_char_p)
    'freerdp_GetJSONConfigFile',  # ctypes.POINTER(WINPR_JSON) (BOOL, ctypes.c_char_p)
    'freerdp_getApplicationDetailsProduct',  # ctypes.c_char_p ()
    'freerdp_getApplicationDetailsString',  # ctypes.c_char_p ()
    'freerdp_getApplicationDetailsStringW',  # ctypes.c_void_p ()
    'freerdp_getApplicationDetailsVendor',  # ctypes.c_char_p ()
    'freerdp_getApplicationDetailsVersion',  # SSIZE_T ()
    'freerdp_setApplicationDetails',  # BOOL (ctypes.c_char_p, ctypes.c_char_p, SSIZE_T)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
