"""
Mirror of <freerdp/utils/passphrase.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_interruptible_get_line',  # SSIZE_T (ctypes.POINTER(rdpContext), ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(ctypes.c_size_t), ctypes.c_void_p)
    'freerdp_interruptible_getc',  # ctypes.c_int (ctypes.POINTER(rdpContext), ctypes.c_void_p)
    'freerdp_passphrase_from_env',  # ctypes.c_char_p (ctypes.POINTER(rdpContext), ctypes.c_char_p, ctypes.c_char_p, ctypes.c_size_t)
    'freerdp_passphrase_read',  # ctypes.c_char_p (ctypes.POINTER(rdpContext), ctypes.c_char_p, ctypes.c_char_p, ctypes.c_size_t, ctypes.c_int)
    'freerdp_passphrase_read_tty',  # ctypes.c_char_p (ctypes.POINTER(rdpContext), ctypes.c_char_p, ctypes.c_char_p, ctypes.c_size_t, ctypes.c_int)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
