"""
Mirror of <freerdp/utils/pcap.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
_anon_14 = _types._anon_14
pcap_header = _types.pcap_header
pcap_record = _types.pcap_record
pcap_record_header = _types.pcap_record_header
rdpPcap = _types.rdpPcap
struct_pcap_header = _types.struct_pcap_header
struct_pcap_record_header = _types.struct_pcap_record_header
struct_s_pcap_record = _types.struct_s_pcap_record

# --- functions declared in this header ---
FUNCTIONS = (
    'pcap_add_record',  # BOOL (ctypes.POINTER(rdpPcap), ctypes.c_void_p, ctypes.c_size_t)
    'pcap_close',  # void (ctypes.POINTER(rdpPcap))
    'pcap_flush',  # void (ctypes.POINTER(rdpPcap))
    'pcap_get_next_record',  # BOOL (ctypes.POINTER(rdpPcap), ctypes.POINTER(pcap_record))
    'pcap_get_next_record_content',  # BOOL (ctypes.POINTER(rdpPcap), ctypes.POINTER(pcap_record))
    'pcap_get_next_record_header',  # BOOL (ctypes.POINTER(rdpPcap), ctypes.POINTER(pcap_record))
    'pcap_has_next_record',  # BOOL (ctypes.POINTER(rdpPcap))
    'pcap_open',  # ctypes.POINTER(rdpPcap) (ctypes.c_char_p, BOOL)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', '_anon_14', 'bind', 'pcap_header', 'pcap_record', 'pcap_record_header', 'rdpPcap', 'struct_pcap_header', 'struct_pcap_record_header', 'struct_s_pcap_record']
