"""
Mirror of <freerdp/utils/profiler.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
PROFILER = _types.PROFILER

# --- functions declared in this header ---
FUNCTIONS = (
    'profiler_create',  # ctypes.POINTER(PROFILER) (ctypes.c_char_p)
    'profiler_enter',  # void (ctypes.POINTER(PROFILER))
    'profiler_exit',  # void (ctypes.POINTER(PROFILER))
    'profiler_free',  # void (ctypes.POINTER(PROFILER))
    'profiler_print',  # void (ctypes.POINTER(PROFILER))
    'profiler_print_footer',  # void ()
    'profiler_print_header',  # void ()
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'PROFILER', 'bind']
