"""
Mirror of <freerdp/utils/rdpdr_utils.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
RDPDR_CAPABILITY_HEADER = _types.RDPDR_CAPABILITY_HEADER
RdpdrDevice = _types.RdpdrDevice
struct_RDPDR_CAPABILITY_HEADER = _types.struct_RDPDR_CAPABILITY_HEADER
struct_RdpdrDevice = _types.struct_RdpdrDevice

# --- functions declared in this header ---
FUNCTIONS = (
    'rdpdr_cap_type_string',  # ctypes.c_char_p (UINT16)
    'rdpdr_component_string',  # ctypes.c_char_p (UINT16)
    'rdpdr_device_type_string',  # ctypes.c_char_p (UINT32)
    'rdpdr_dump_received_packet',  # void (ctypes.POINTER(wLog), DWORD, ctypes.POINTER(wStream), ctypes.c_char_p)
    'rdpdr_dump_send_packet',  # void (ctypes.POINTER(wLog), DWORD, ctypes.POINTER(wStream), ctypes.c_char_p)
    'rdpdr_irp_mask2str',  # ctypes.c_char_p (UINT32, ctypes.c_char_p, ctypes.c_size_t)
    'rdpdr_irp_string',  # ctypes.c_char_p (UINT32)
    'rdpdr_irp_val2str',  # ctypes.c_char_p (UINT32)
    'rdpdr_packetid_string',  # ctypes.c_char_p (UINT16)
    'rdpdr_read_capset_header',  # UINT (ctypes.POINTER(wLog), ctypes.POINTER(wStream), ctypes.POINTER(RDPDR_CAPABILITY_HEADER))
    'rdpdr_write_capset_header',  # UINT (ctypes.POINTER(wLog), ctypes.POINTER(wStream), ctypes.POINTER(RDPDR_CAPABILITY_HEADER))
    'rdpdr_write_iocompletion_header',  # BOOL (ctypes.POINTER(wStream), UINT32, UINT32, NTSTATUS)
    'scard_get_ioctl_string',  # ctypes.c_char_p (UINT32, BOOL)
    'scard_log_status_error',  # LONG (ctypes.c_char_p, ctypes.c_char_p, LONG)
    'scard_log_status_error_wlog',  # LONG (ctypes.POINTER(wLog), ctypes.c_char_p, LONG, ...)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'RDPDR_CAPABILITY_HEADER', 'RdpdrDevice', 'bind', 'struct_RDPDR_CAPABILITY_HEADER', 'struct_RdpdrDevice']
