"""
Mirror of <freerdp/utils/ringbuffer.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
DataChunk = _types.DataChunk
RingBuffer = _types.RingBuffer
struct_DataChunk = _types.struct_DataChunk
struct_RingBuffer = _types.struct_RingBuffer

# --- functions declared in this header ---
FUNCTIONS = (
    'ringbuffer_capacity',  # ctypes.c_size_t (ctypes.POINTER(RingBuffer))
    'ringbuffer_commit_read_bytes',  # void (ctypes.POINTER(RingBuffer), ctypes.c_size_t)
    'ringbuffer_commit_written_bytes',  # BOOL (ctypes.POINTER(RingBuffer), ctypes.c_size_t)
    'ringbuffer_destroy',  # void (ctypes.POINTER(RingBuffer))
    'ringbuffer_ensure_linear_write',  # ctypes.POINTER(BYTE) (ctypes.POINTER(RingBuffer), ctypes.c_size_t)
    'ringbuffer_init',  # BOOL (ctypes.POINTER(RingBuffer), ctypes.c_size_t)
    'ringbuffer_peek',  # ctypes.c_int (ctypes.POINTER(RingBuffer), (DataChunk * 2), ctypes.c_size_t)
    'ringbuffer_used',  # ctypes.c_size_t (ctypes.POINTER(RingBuffer))
    'ringbuffer_write',  # BOOL (ctypes.POINTER(RingBuffer), ctypes.POINTER(BYTE), ctypes.c_size_t)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['DataChunk', 'FUNCTIONS', 'RingBuffer', 'bind', 'struct_DataChunk', 'struct_RingBuffer']
