"""
Mirror of <freerdp/utils/signal.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
freerdp_signal_handler_t = _types.freerdp_signal_handler_t

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_add_signal_cleanup_handler',  # BOOL (ctypes.c_void_p, freerdp_signal_handler_t)
    'freerdp_del_signal_cleanup_handler',  # BOOL (ctypes.c_void_p, freerdp_signal_handler_t)
    'freerdp_handle_signals',  # ctypes.c_int ()
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'freerdp_signal_handler_t']
