"""
Mirror of <freerdp/utils/smartcard_pack.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
SMARTCARD_COMMON_TYPE_HEADER_LENGTH = 8
SMARTCARD_PRIVATE_TYPE_HEADER_LENGTH = 8

# --- functions declared in this header ---
FUNCTIONS = (
    'smartcard_pack_common_type_header',  # void (ctypes.POINTER(wStream))
    'smartcard_pack_connect_a_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ConnectA_Call))
    'smartcard_pack_connect_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Connect_Return))
    'smartcard_pack_connect_w_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ConnectW_Call))
    'smartcard_pack_context_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Context_Call), ctypes.c_char_p)
    'smartcard_pack_control_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Control_Call))
    'smartcard_pack_control_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Control_Return))
    'smartcard_pack_device_type_id_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetDeviceTypeId_Return))
    'smartcard_pack_establish_context_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(EstablishContext_Call))
    'smartcard_pack_establish_context_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(EstablishContext_Return))
    'smartcard_pack_get_attrib_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetAttrib_Call))
    'smartcard_pack_get_attrib_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetAttrib_Return), DWORD, DWORD)
    'smartcard_pack_get_reader_icon_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetReaderIcon_Return))
    'smartcard_pack_get_status_change_a_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetStatusChangeA_Call))
    'smartcard_pack_get_status_change_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetStatusChange_Return), BOOL)
    'smartcard_pack_get_status_change_w_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetStatusChangeW_Call))
    'smartcard_pack_get_transmit_count_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetTransmitCount_Return))
    'smartcard_pack_hcard_and_disposition_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(HCardAndDisposition_Call), ctypes.c_char_p)
    'smartcard_pack_list_reader_groups_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ListReaderGroups_Call), BOOL)
    'smartcard_pack_list_reader_groups_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ListReaderGroups_Return), BOOL)
    'smartcard_pack_list_readers_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ListReaders_Call), BOOL)
    'smartcard_pack_list_readers_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ListReaders_Return), BOOL)
    'smartcard_pack_locate_cards_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(LocateCards_Return))
    'smartcard_pack_locate_cards_w_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(LocateCards_Return))
    'smartcard_pack_private_type_header',  # void (ctypes.POINTER(wStream), UINT32)
    'smartcard_pack_read_cache_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ReadCache_Return))
    'smartcard_pack_reconnect_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Reconnect_Call))
    'smartcard_pack_reconnect_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Reconnect_Return))
    'smartcard_pack_set_attrib_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(SetAttrib_Call))
    'smartcard_pack_state_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(State_Return))
    'smartcard_pack_status_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Status_Call), BOOL)
    'smartcard_pack_status_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Status_Return), BOOL)
    'smartcard_pack_transmit_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Transmit_Call))
    'smartcard_pack_transmit_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Transmit_Return))
    'smartcard_pack_write_size_align',  # LONG (ctypes.POINTER(wStream), ctypes.c_size_t, UINT32)
    'smartcard_scard_context_native_from_redir',  # SCARDCONTEXT (ctypes.POINTER(REDIR_SCARDCONTEXT))
    'smartcard_scard_context_native_to_redir',  # void (ctypes.POINTER(REDIR_SCARDCONTEXT), SCARDCONTEXT)
    'smartcard_scard_handle_native_from_redir',  # SCARDHANDLE (ctypes.POINTER(REDIR_SCARDHANDLE))
    'smartcard_scard_handle_native_to_redir',  # void (ctypes.POINTER(REDIR_SCARDHANDLE), SCARDHANDLE)
    'smartcard_trace_long_return',  # void (ctypes.POINTER(Long_Return), ctypes.c_char_p)
    'smartcard_unpack_common_type_header',  # LONG (ctypes.POINTER(wStream))
    'smartcard_unpack_connect_a_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ConnectA_Call))
    'smartcard_unpack_connect_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Connect_Return))
    'smartcard_unpack_connect_w_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ConnectW_Call))
    'smartcard_unpack_context_and_string_a_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ContextAndStringA_Call))
    'smartcard_unpack_context_and_string_w_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ContextAndStringW_Call))
    'smartcard_unpack_context_and_two_strings_a_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ContextAndTwoStringA_Call))
    'smartcard_unpack_context_and_two_strings_w_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ContextAndTwoStringW_Call))
    'smartcard_unpack_context_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Context_Call), ctypes.c_char_p)
    'smartcard_unpack_control_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Control_Call))
    'smartcard_unpack_control_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Control_Return))
    'smartcard_unpack_establish_context_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(EstablishContext_Call))
    'smartcard_unpack_establish_context_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(EstablishContext_Return))
    'smartcard_unpack_get_attrib_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetAttrib_Call))
    'smartcard_unpack_get_attrib_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetAttrib_Return))
    'smartcard_unpack_get_device_type_id_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetDeviceTypeId_Call))
    'smartcard_unpack_get_reader_icon_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetReaderIcon_Call))
    'smartcard_unpack_get_status_change_a_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetStatusChangeA_Call))
    'smartcard_unpack_get_status_change_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetStatusChange_Return), BOOL)
    'smartcard_unpack_get_status_change_w_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetStatusChangeW_Call))
    'smartcard_unpack_get_transmit_count_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(GetTransmitCount_Call))
    'smartcard_unpack_hcard_and_disposition_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(HCardAndDisposition_Call), ctypes.c_char_p)
    'smartcard_unpack_list_reader_groups_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ListReaderGroups_Call), BOOL)
    'smartcard_unpack_list_reader_groups_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ListReaderGroups_Return), BOOL)
    'smartcard_unpack_list_readers_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ListReaders_Call), BOOL)
    'smartcard_unpack_list_readers_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ListReaders_Return), BOOL)
    'smartcard_unpack_locate_cards_a_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(LocateCardsA_Call))
    'smartcard_unpack_locate_cards_by_atr_a_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(LocateCardsByATRA_Call))
    'smartcard_unpack_locate_cards_by_atr_w_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(LocateCardsByATRW_Call))
    'smartcard_unpack_locate_cards_w_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(LocateCardsW_Call))
    'smartcard_unpack_private_type_header',  # LONG (ctypes.POINTER(wStream))
    'smartcard_unpack_read_cache_a_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ReadCacheA_Call))
    'smartcard_unpack_read_cache_w_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(ReadCacheW_Call))
    'smartcard_unpack_read_size_align',  # LONG (ctypes.POINTER(wStream), ctypes.c_size_t, UINT32)
    'smartcard_unpack_reconnect_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Reconnect_Call))
    'smartcard_unpack_reconnect_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Reconnect_Return))
    'smartcard_unpack_set_attrib_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(SetAttrib_Call))
    'smartcard_unpack_state_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(State_Call))
    'smartcard_unpack_status_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Status_Call), BOOL)
    'smartcard_unpack_status_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Status_Return), BOOL)
    'smartcard_unpack_transmit_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Transmit_Call))
    'smartcard_unpack_transmit_return',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(Transmit_Return))
    'smartcard_unpack_write_cache_a_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(WriteCacheA_Call))
    'smartcard_unpack_write_cache_w_call',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(WriteCacheW_Call))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'SMARTCARD_COMMON_TYPE_HEADER_LENGTH', 'SMARTCARD_PRIVATE_TYPE_HEADER_LENGTH', 'bind']
