"""
Mirror of <freerdp/utils/smartcardlogon.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
SmartcardCertInfo = _types.SmartcardCertInfo
SmartcardKeyInfo = _types.SmartcardKeyInfo
struct_SmartcardCertInfo_st = _types.struct_SmartcardCertInfo_st

# --- functions declared in this header ---
FUNCTIONS = (
    'smartcardCertInfo_Free',  # void (ctypes.POINTER(SmartcardCertInfo))
    'smartcardCertList_Free',  # void (ctypes.POINTER(ctypes.POINTER(SmartcardCertInfo)), ctypes.c_size_t)
    'smartcard_enumerateCerts',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.POINTER(ctypes.POINTER(ctypes.POINTER(SmartcardCertInfo))), ctypes.POINTER(ctypes.c_size_t), BOOL)
    'smartcard_getCert',  # BOOL (ctypes.POINTER(rdpContext), ctypes.POINTER(ctypes.POINTER(SmartcardCertInfo)), BOOL)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'SmartcardCertInfo', 'SmartcardKeyInfo', 'bind', 'struct_SmartcardCertInfo_st']
