"""
Mirror of <freerdp/utils/smartcard_call.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
scard_call_context = _types.scard_call_context

# --- functions declared in this header ---
FUNCTIONS = (
    'smarcard_call_set_callbacks',  # BOOL (ctypes.POINTER(scard_call_context), ctypes.c_void_p, ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.c_void_p, SCARDCONTEXT), ctypes.CFUNCTYPE(None, ctypes.c_void_p))
    'smartcard_call_cancel_all_context',  # BOOL (ctypes.POINTER(scard_call_context))
    'smartcard_call_cancel_context',  # BOOL (ctypes.POINTER(scard_call_context), SCARDCONTEXT)
    'smartcard_call_context_add',  # BOOL (ctypes.POINTER(scard_call_context), ctypes.c_char_p)
    'smartcard_call_context_free',  # void (ctypes.POINTER(scard_call_context))
    'smartcard_call_context_new',  # ctypes.POINTER(scard_call_context) (ctypes.POINTER(rdpSettings))
    'smartcard_call_context_new_with_context',  # ctypes.POINTER(scard_call_context) (ctypes.POINTER(rdpContext))
    'smartcard_call_context_signal_stop',  # BOOL (ctypes.POINTER(scard_call_context), BOOL)
    'smartcard_call_get_context',  # ctypes.c_void_p (ctypes.POINTER(scard_call_context), SCARDCONTEXT)
    'smartcard_call_is_configured',  # BOOL (ctypes.POINTER(scard_call_context))
    'smartcard_call_release_context',  # BOOL (ctypes.POINTER(scard_call_context), SCARDCONTEXT)
    'smartcard_irp_device_control_call',  # LONG (ctypes.POINTER(scard_call_context), ctypes.POINTER(wStream), ctypes.POINTER(NTSTATUS), ctypes.POINTER(SMARTCARD_OPERATION))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'scard_call_context']
