"""
Mirror of <freerdp/utils/smartcard_operations.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
SMARTCARD_OPERATION = _types.SMARTCARD_OPERATION
_anon_23 = _types._anon_23
_anon_24 = _types._anon_24
struct_SMARTCARD_OPERATION = _types.struct_SMARTCARD_OPERATION

# --- functions declared in this header ---
FUNCTIONS = (
    'smartcard_irp_device_control_decode',  # LONG (ctypes.POINTER(wStream), UINT32, UINT32, ctypes.POINTER(SMARTCARD_OPERATION))
    'smartcard_irp_device_control_decode_request',  # LONG (ctypes.POINTER(wStream), UINT32, UINT32, ctypes.POINTER(SMARTCARD_OPERATION))
    'smartcard_irp_device_control_decode_response',  # LONG (ctypes.POINTER(wStream), UINT32, ctypes.POINTER(SMARTCARD_OPERATION))
    'smartcard_irp_device_control_encode_request',  # LONG (ctypes.POINTER(wStream), ctypes.POINTER(SMARTCARD_OPERATION))
    'smartcard_operation_free',  # void (ctypes.POINTER(SMARTCARD_OPERATION), BOOL)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'SMARTCARD_OPERATION', '_anon_23', '_anon_24', 'bind', 'struct_SMARTCARD_OPERATION']
