"""
Mirror of <freerdp/utils/stopwatch.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
STOPWATCH = _types.STOPWATCH
struct_STOPWATCH = _types.struct_STOPWATCH

# --- functions declared in this header ---
FUNCTIONS = (
    'stopwatch_create',  # ctypes.POINTER(STOPWATCH) ()
    'stopwatch_free',  # void (ctypes.POINTER(STOPWATCH))
    'stopwatch_get_elapsed_time_in_seconds',  # ctypes.c_double (ctypes.POINTER(STOPWATCH))
    'stopwatch_get_elapsed_time_in_useconds',  # void (ctypes.POINTER(STOPWATCH), ctypes.POINTER(UINT32), ctypes.POINTER(UINT32))
    'stopwatch_reset',  # void (ctypes.POINTER(STOPWATCH))
    'stopwatch_start',  # void (ctypes.POINTER(STOPWATCH))
    'stopwatch_stop',  # void (ctypes.POINTER(STOPWATCH))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'STOPWATCH', 'bind', 'struct_STOPWATCH']
