"""
Mirror of <freerdp/utils/string.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_desktop_rotation_flags_to_string',  # ctypes.c_char_p (UINT32)
    'freerdp_extract_key_value',  # BOOL (ctypes.c_char_p, ctypes.POINTER(UINT32), ctypes.POINTER(UINT32))
    'freerdp_input_touch_state_string',  # ctypes.c_char_p (DWORD)
    'freerdp_order_support_flags_string',  # ctypes.c_char_p (UINT8)
    'rdp_cluster_info_flags_to_string',  # ctypes.c_char_p (UINT32, ctypes.c_char_p, ctypes.c_size_t)
    'rdp_redirection_flags_to_string',  # ctypes.c_char_p (UINT32, ctypes.c_char_p, ctypes.c_size_t)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
