"""
Mirror of <freerdp/client.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
FREERDP_CLIENT_AAD_AUTH_REQUEST = 0
FREERDP_CLIENT_AAD_AVD_AUTH_REQUEST = 2
FREERDP_CLIENT_AAD_AVD_TOKEN_REQUEST = 3
FREERDP_CLIENT_AAD_TOKEN_REQUEST = 1
FREERDP_MAX_PEN_DEVICES = 0xa
FREERDP_MAX_TOUCH_CONTACTS = 0xa
FREERDP_PEN_BARREL_PRESSED = 0x20
FREERDP_PEN_ERASER_PRESSED = 2
FREERDP_PEN_HAS_PRESSURE = 0x40
FREERDP_PEN_HAS_ROTATION = 0x80
FREERDP_PEN_HAS_TILTX = 0x100
FREERDP_PEN_HAS_TILTY = 0x200
FREERDP_PEN_IS_INVERTED = 0x400
FREERDP_PEN_MOTION = 8
FREERDP_PEN_PRESS = 4
FREERDP_PEN_REGISTER = 1
FREERDP_PEN_RELEASE = 0x10
FREERDP_TOUCH_CANCEL = 8
FREERDP_TOUCH_DOWN = 1
FREERDP_TOUCH_HAS_PRESSURE = 0x100
FREERDP_TOUCH_MOTION = 4
FREERDP_TOUCH_UP = 2
RDP_CLIENT_ENTRY_POINT_NAME = 'RdpClientEntry'
RDP_CLIENT_INTERFACE_VERSION = 1

# --- types declared in this header ---
FreeRDPPenEventType = _types.FreeRDPPenEventType
FreeRDPTouchEventType = _types.FreeRDPTouchEventType
FreeRDP_PenDevice = _types.FreeRDP_PenDevice
FreeRDP_TouchContact = _types.FreeRDP_TouchContact
MIBClientWrapper = _types.MIBClientWrapper
RDP_CLIENT_ENTRY_POINTS_V1 = _types.RDP_CLIENT_ENTRY_POINTS_V1
freerdp_client_aad_type = _types.freerdp_client_aad_type
pRdpClientEntry = _types.pRdpClientEntry
pRdpClientFree = _types.pRdpClientFree
pRdpClientNew = _types.pRdpClientNew
pRdpClientStart = _types.pRdpClientStart
pRdpClientStop = _types.pRdpClientStop
pRdpGlobalInit = _types.pRdpGlobalInit
pRdpGlobalUninit = _types.pRdpGlobalUninit
rdpClientContext = _types.rdpClientContext
struct_FreeRDP_TouchContact = _types.struct_FreeRDP_TouchContact
struct_pen_device = _types.struct_pen_device
struct_rdp_client_context = _types.struct_rdp_client_context
struct_rdp_client_entry_points_v1 = _types.struct_rdp_client_entry_points_v1

# --- functions declared in this header ---
FUNCTIONS = (
    'client_auto_reconnect',  # BOOL (ctypes.POINTER(freerdp))
    'client_auto_reconnect_ex',  # BOOL (ctypes.POINTER(freerdp), ctypes.CFUNCTYPE(BOOL, ctypes.POINTER(freerdp)))
    'client_cli_authenticate_ex',  # BOOL (ctypes.POINTER(freerdp), ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(ctypes.c_char_p), rdp_auth_reason)
    'client_cli_choose_smartcard',  # BOOL (ctypes.POINTER(freerdp), ctypes.POINTER(ctypes.POINTER(SmartcardCertInfo)), DWORD, ctypes.POINTER(DWORD), BOOL)
    'client_cli_get_access_token',  # BOOL (ctypes.POINTER(freerdp), AccessTokenType, ctypes.POINTER(ctypes.c_char_p), ctypes.c_size_t, ...)
    'client_cli_logon_error_info',  # ctypes.c_int (ctypes.POINTER(freerdp), UINT32, UINT32)
    'client_cli_present_gateway_message',  # BOOL (ctypes.POINTER(freerdp), UINT32, BOOL, BOOL, ctypes.c_size_t, ctypes.c_void_p)
    'client_cli_verify_certificate_ex',  # DWORD (ctypes.POINTER(freerdp), ctypes.c_char_p, UINT16, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p, DWORD)
    'client_cli_verify_changed_certificate_ex',  # DWORD (ctypes.POINTER(freerdp), ctypes.c_char_p, UINT16, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p, DWORD)
    'client_common_get_access_token',  # BOOL (ctypes.POINTER(freerdp), ctypes.c_char_p, ctypes.POINTER(ctypes.c_char_p))
    'client_common_retry_dialog',  # SSIZE_T (ctypes.POINTER(freerdp), ctypes.c_char_p, ctypes.c_size_t, ctypes.c_void_p)
    'client_common_save_session_info',  # BOOL (ctypes.POINTER(rdpContext), UINT32, ctypes.c_void_p)
    'freerdp_client_OnChannelConnectedEventHandler',  # void (ctypes.c_void_p, ctypes.POINTER(ChannelConnectedEventArgs))
    'freerdp_client_OnChannelDisconnectedEventHandler',  # void (ctypes.c_void_p, ctypes.POINTER(ChannelDisconnectedEventArgs))
    'freerdp_client_common_stop',  # ctypes.c_int (ctypes.POINTER(rdpContext))
    'freerdp_client_context_free',  # void (ctypes.POINTER(rdpContext))
    'freerdp_client_context_new',  # ctypes.POINTER(rdpContext) (ctypes.POINTER(RDP_CLIENT_ENTRY_POINTS))
    'freerdp_client_encomsp_set_control',  # BOOL (ctypes.POINTER(EncomspClientContext), BOOL)
    'freerdp_client_encomsp_toggle_control',  # BOOL (ctypes.POINTER(EncomspClientContext))
    'freerdp_client_get_aad_url',  # ctypes.c_char_p (ctypes.POINTER(rdpClientContext), freerdp_client_aad_type, ...)
    'freerdp_client_get_instance',  # ctypes.POINTER(freerdp) (ctypes.POINTER(rdpContext))
    'freerdp_client_get_thread',  # HANDLE (ctypes.POINTER(rdpContext))
    'freerdp_client_handle_pen',  # BOOL (ctypes.POINTER(rdpClientContext), UINT32, INT32, ...)
    'freerdp_client_handle_touch',  # BOOL (ctypes.POINTER(rdpClientContext), UINT32, INT32, UINT32, INT32, INT32)
    'freerdp_client_is_pen',  # BOOL (ctypes.POINTER(rdpClientContext), INT32)
    'freerdp_client_load_channels',  # BOOL (ctypes.POINTER(freerdp))
    'freerdp_client_pen_cancel_all',  # BOOL (ctypes.POINTER(rdpClientContext))
    'freerdp_client_send_button_event',  # BOOL (ctypes.POINTER(rdpClientContext), BOOL, UINT16, INT32, INT32)
    'freerdp_client_send_extended_button_event',  # BOOL (ctypes.POINTER(rdpClientContext), BOOL, UINT16, INT32, INT32)
    'freerdp_client_send_wheel_event',  # BOOL (ctypes.POINTER(rdpClientContext), UINT16)
    'freerdp_client_settings_parse_assistance_file',  # ctypes.c_int (ctypes.POINTER(rdpSettings), ctypes.c_int, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_client_settings_parse_command_line',  # ctypes.c_int (ctypes.POINTER(rdpSettings), ctypes.c_int, ctypes.POINTER(ctypes.c_char_p), BOOL)
    'freerdp_client_settings_parse_command_line_ex',  # ctypes.c_int (ctypes.POINTER(rdpSettings), ctypes.c_int, ctypes.POINTER(ctypes.c_char_p), BOOL, ctypes.POINTER(COMMAND_LINE_ARGUMENT_A), ctypes.c_size_t, freerdp_command_line_handle_option_t, ctypes.c_void_p)
    'freerdp_client_settings_parse_connection_file',  # ctypes.c_int (ctypes.POINTER(rdpSettings), ctypes.c_char_p)
    'freerdp_client_settings_parse_connection_file_buffer',  # ctypes.c_int (ctypes.POINTER(rdpSettings), ctypes.POINTER(BYTE), ctypes.c_size_t)
    'freerdp_client_settings_write_connection_file',  # ctypes.c_int (ctypes.POINTER(rdpSettings), ctypes.c_char_p, BOOL)
    'freerdp_client_start',  # ctypes.c_int (ctypes.POINTER(rdpContext))
    'freerdp_client_stop',  # ctypes.c_int (ctypes.POINTER(rdpContext))
    'freerdp_client_use_relative_mouse_events',  # BOOL (ctypes.POINTER(rdpClientContext))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FREERDP_CLIENT_AAD_AUTH_REQUEST', 'FREERDP_CLIENT_AAD_AVD_AUTH_REQUEST', 'FREERDP_CLIENT_AAD_AVD_TOKEN_REQUEST', 'FREERDP_CLIENT_AAD_TOKEN_REQUEST', 'FREERDP_MAX_PEN_DEVICES', 'FREERDP_MAX_TOUCH_CONTACTS', 'FREERDP_PEN_BARREL_PRESSED', 'FREERDP_PEN_ERASER_PRESSED', 'FREERDP_PEN_HAS_PRESSURE', 'FREERDP_PEN_HAS_ROTATION', 'FREERDP_PEN_HAS_TILTX', 'FREERDP_PEN_HAS_TILTY', 'FREERDP_PEN_IS_INVERTED', 'FREERDP_PEN_MOTION', 'FREERDP_PEN_PRESS', 'FREERDP_PEN_REGISTER', 'FREERDP_PEN_RELEASE', 'FREERDP_TOUCH_CANCEL', 'FREERDP_TOUCH_DOWN', 'FREERDP_TOUCH_HAS_PRESSURE', 'FREERDP_TOUCH_MOTION', 'FREERDP_TOUCH_UP', 'FUNCTIONS', 'FreeRDPPenEventType', 'FreeRDPTouchEventType', 'FreeRDP_PenDevice', 'FreeRDP_TouchContact', 'MIBClientWrapper', 'RDP_CLIENT_ENTRY_POINTS_V1', 'RDP_CLIENT_ENTRY_POINT_NAME', 'RDP_CLIENT_INTERFACE_VERSION', 'bind', 'freerdp_client_aad_type', 'pRdpClientEntry', 'pRdpClientFree', 'pRdpClientNew', 'pRdpClientStart', 'pRdpClientStop', 'pRdpGlobalInit', 'pRdpGlobalUninit', 'rdpClientContext', 'struct_FreeRDP_TouchContact', 'struct_pen_device', 'struct_rdp_client_context', 'struct_rdp_client_entry_points_v1']
