"""
Mirror of <freerdp/client/aad_helper.h> (FreeRDP 3.32.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
AAD_AUTH_HELPER_NAVIGATE_CANCELLED = 2
AAD_AUTH_HELPER_NAVIGATE_ERROR = 4
AAD_AUTH_HELPER_NAVIGATE_OK = 1
AAD_AUTH_HELPER_NAVIGATE_TIMEOUT = 3

# --- types declared in this header ---
AadAuthHelper = _types.AadAuthHelper
AadAuthHelperNavigateStatus = _types.AadAuthHelperNavigateStatus

# --- functions declared in this header ---
FUNCTIONS = (
    'aad_auth_helper_get_access_token',  # BOOL (ctypes.POINTER(AadAuthHelper), AccessTokenType, ctypes.POINTER(ctypes.c_char_p), ctypes.c_size_t, ...)
    'aad_auth_helper_get_access_token_v',  # BOOL (ctypes.POINTER(AadAuthHelper), AccessTokenType, ctypes.POINTER(ctypes.c_char_p), ctypes.c_size_t, ctypes.c_void_p)
    'aad_auth_helper_start',  # ctypes.POINTER(AadAuthHelper) (ctypes.POINTER(rdpClientContext))
    'aad_auth_helper_stop',  # void (ctypes.POINTER(AadAuthHelper))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['AAD_AUTH_HELPER_NAVIGATE_CANCELLED', 'AAD_AUTH_HELPER_NAVIGATE_ERROR', 'AAD_AUTH_HELPER_NAVIGATE_OK', 'AAD_AUTH_HELPER_NAVIGATE_TIMEOUT', 'AadAuthHelper', 'AadAuthHelperNavigateStatus', 'FUNCTIONS', 'bind']
