"""
Mirror of <freerdp/client/ainput.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
AInputClientContext = _types.AInputClientContext
pcAInputSendInputEvent = _types.pcAInputSendInputEvent
struct_ainput_client_context = _types.struct_ainput_client_context

__all__ = ['AInputClientContext', 'pcAInputSendInputEvent', 'struct_ainput_client_context']
