"""
Mirror of <freerdp/client/audin.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
AUDIN_DEVICE_EXPORT_FUNC_NAME = 'freerdp_audin_client_subsystem_entry'

# --- types declared in this header ---
AudinReceive = _types.AudinReceive
FREERDP_AUDIN_DEVICE_ENTRY_POINTS = _types.FREERDP_AUDIN_DEVICE_ENTRY_POINTS
IAudinDevice = _types.IAudinDevice
PFREERDP_AUDIN_DEVICE_ENTRY = _types.PFREERDP_AUDIN_DEVICE_ENTRY
PFREERDP_AUDIN_DEVICE_ENTRY_POINTS = _types.PFREERDP_AUDIN_DEVICE_ENTRY_POINTS
PREGISTERAUDINDEVICE = _types.PREGISTERAUDINDEVICE
struct_FREERDP_AUDIN_DEVICE_ENTRY_POINTS = _types.struct_FREERDP_AUDIN_DEVICE_ENTRY_POINTS
struct_s_IAudinDevice = _types.struct_s_IAudinDevice

__all__ = ['AUDIN_DEVICE_EXPORT_FUNC_NAME', 'AudinReceive', 'FREERDP_AUDIN_DEVICE_ENTRY_POINTS', 'IAudinDevice', 'PFREERDP_AUDIN_DEVICE_ENTRY', 'PFREERDP_AUDIN_DEVICE_ENTRY_POINTS', 'PREGISTERAUDINDEVICE', 'struct_FREERDP_AUDIN_DEVICE_ENTRY_POINTS', 'struct_s_IAudinDevice']
