"""
Mirror of <freerdp/client/channels.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
DYNVC_PLUGIN_INIT_FN = _types.DYNVC_PLUGIN_INIT_FN
DYNVC_PLUGIN_TERMINATE_FN = _types.DYNVC_PLUGIN_TERMINATE_FN
GENERIC_CHANNEL_CALLBACK = _types.GENERIC_CHANNEL_CALLBACK
GENERIC_DYNVC_PLUGIN = _types.GENERIC_DYNVC_PLUGIN
GENERIC_LISTENER_CALLBACK = _types.GENERIC_LISTENER_CALLBACK
struct_GENERIC_CHANNEL_CALLBACK = _types.struct_GENERIC_CHANNEL_CALLBACK
struct_GENERIC_DYNVC_PLUGIN = _types.struct_GENERIC_DYNVC_PLUGIN
struct_GENERIC_LISTENER_CALLBACK = _types.struct_GENERIC_LISTENER_CALLBACK

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_channels_addin_list_free',  # void (ctypes.POINTER(ctypes.POINTER(FREERDP_ADDIN)))
    'freerdp_channels_client_find_static_entry',  # ctypes.c_void_p (ctypes.c_char_p, ctypes.c_char_p)
    'freerdp_channels_list_addins',  # ctypes.POINTER(ctypes.POINTER(FREERDP_ADDIN)) (LPCSTR, LPCSTR, LPCSTR, DWORD)
    'freerdp_channels_load_static_addin_entry',  # PVIRTUALCHANNELENTRY (LPCSTR, LPCSTR, LPCSTR, DWORD)
    'freerdp_generic_DVCPluginEntry',  # UINT (ctypes.POINTER(IDRDYNVC_ENTRY_POINTS), ctypes.c_char_p, ctypes.c_char_p, ctypes.c_size_t, ctypes.c_size_t, ctypes.POINTER(IWTSVirtualChannelCallback), DYNVC_PLUGIN_INIT_FN, DYNVC_PLUGIN_TERMINATE_FN)
    'freerdp_initialize_generic_dynvc_plugin',  # BOOL (ctypes.POINTER(GENERIC_DYNVC_PLUGIN))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['DYNVC_PLUGIN_INIT_FN', 'DYNVC_PLUGIN_TERMINATE_FN', 'FUNCTIONS', 'GENERIC_CHANNEL_CALLBACK', 'GENERIC_DYNVC_PLUGIN', 'GENERIC_LISTENER_CALLBACK', 'bind', 'struct_GENERIC_CHANNEL_CALLBACK', 'struct_GENERIC_DYNVC_PLUGIN', 'struct_GENERIC_LISTENER_CALLBACK']
