"""
Mirror of <freerdp/client/client_cliprdr_file.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
CliprdrFileContext = _types.CliprdrFileContext

# --- functions declared in this header ---
FUNCTIONS = (
    'cliprdr_file_context_clear',  # BOOL (ctypes.POINTER(CliprdrFileContext))
    'cliprdr_file_context_current_flags',  # UINT32 (ctypes.POINTER(CliprdrFileContext))
    'cliprdr_file_context_free',  # void (ctypes.POINTER(CliprdrFileContext))
    'cliprdr_file_context_get_context',  # ctypes.c_void_p (ctypes.POINTER(CliprdrFileContext))
    'cliprdr_file_context_has_local_support',  # BOOL (ctypes.POINTER(CliprdrFileContext))
    'cliprdr_file_context_init',  # BOOL (ctypes.POINTER(CliprdrFileContext), ctypes.POINTER(CliprdrClientContext))
    'cliprdr_file_context_new',  # ctypes.POINTER(CliprdrFileContext) (ctypes.c_void_p)
    'cliprdr_file_context_notify_new_client_format_list',  # UINT (ctypes.POINTER(CliprdrFileContext))
    'cliprdr_file_context_notify_new_server_format_list',  # UINT (ctypes.POINTER(CliprdrFileContext))
    'cliprdr_file_context_remote_get_flags',  # UINT32 (ctypes.POINTER(CliprdrFileContext))
    'cliprdr_file_context_remote_set_flags',  # BOOL (ctypes.POINTER(CliprdrFileContext), UINT32)
    'cliprdr_file_context_set_locally_available',  # BOOL (ctypes.POINTER(CliprdrFileContext), BOOL)
    'cliprdr_file_context_uninit',  # BOOL (ctypes.POINTER(CliprdrFileContext), ctypes.POINTER(CliprdrClientContext))
    'cliprdr_file_context_update_client_data',  # BOOL (ctypes.POINTER(CliprdrFileContext), ctypes.c_char_p, ctypes.c_size_t)
    'cliprdr_file_context_update_server_data',  # BOOL (ctypes.POINTER(CliprdrFileContext), ctypes.POINTER(wClipboard), ctypes.c_void_p, ctypes.c_size_t)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['CliprdrFileContext', 'FUNCTIONS', 'bind']
