"""
Mirror of <freerdp/client/cmdline.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
FREERDP_SETTINGS_CMD_PARSE_NO_FLAGS = 0
FREERDP_SETTINGS_CMD_PARSE_SUPPRESS_WARNINGS = 2

# --- types declared in this header ---
FREERDP_SETTINGS_CMD_PARSE_FLAGS = _types.FREERDP_SETTINGS_CMD_PARSE_FLAGS
freerdp_command_line_handle_option_t = _types.freerdp_command_line_handle_option_t

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_client_add_device_channel',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.c_size_t, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_client_add_dynamic_channel',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.c_size_t, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_client_add_static_channel',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.c_size_t, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_client_del_dynamic_channel',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.c_char_p)
    'freerdp_client_del_static_channel',  # BOOL (ctypes.POINTER(rdpSettings), ctypes.c_char_p)
    'freerdp_client_load_addins',  # BOOL (ctypes.POINTER(rdpChannels), ctypes.POINTER(rdpSettings))
    'freerdp_client_print_buildconfig',  # BOOL ()
    'freerdp_client_print_buildconfig_ex',  # BOOL (ctypes.c_int, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_client_print_command_line_help',  # BOOL (ctypes.c_int, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_client_print_command_line_help_ex',  # BOOL (ctypes.c_int, ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(COMMAND_LINE_ARGUMENT_A))
    'freerdp_client_print_version',  # BOOL ()
    'freerdp_client_print_version_ex',  # BOOL (ctypes.c_int, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_client_settings_command_line_status_print',  # ctypes.c_int (ctypes.POINTER(rdpSettings), ctypes.c_int, ctypes.c_int, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_client_settings_command_line_status_print_ex',  # ctypes.c_int (ctypes.POINTER(rdpSettings), ctypes.c_int, ctypes.c_int, ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(COMMAND_LINE_ARGUMENT_A))
    'freerdp_client_settings_parse_command_line_arguments',  # ctypes.c_int (ctypes.POINTER(rdpSettings), ctypes.c_int, ctypes.POINTER(ctypes.c_char_p), BOOL)
    'freerdp_client_settings_parse_command_line_arguments_ex',  # ctypes.c_int (ctypes.POINTER(rdpSettings), ctypes.c_int, ctypes.POINTER(ctypes.c_char_p), BOOL, ctypes.POINTER(COMMAND_LINE_ARGUMENT_A), ctypes.c_size_t, freerdp_command_line_handle_option_t, ctypes.c_void_p)
    'freerdp_client_settings_parse_command_line_arguments_with_flags',  # ctypes.c_int (ctypes.POINTER(rdpSettings), ctypes.c_int, ctypes.POINTER(ctypes.c_char_p), BOOL, ctypes.POINTER(COMMAND_LINE_ARGUMENT_A), ctypes.c_size_t, freerdp_command_line_handle_option_t, ctypes.c_void_p, UINT32, ...)
    'freerdp_client_warn_deprecated',  # void (ctypes.c_int, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_client_warn_experimental',  # void (ctypes.c_int, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_client_warn_unmaintained',  # void (ctypes.c_int, ctypes.POINTER(ctypes.c_char_p))
    'freerdp_parse_hostname',  # BOOL (ctypes.c_char_p, ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(ctypes.c_int))
    'freerdp_parse_username',  # BOOL (ctypes.c_char_p, ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(ctypes.c_char_p))
    'freerdp_set_connection_type',  # BOOL (ctypes.POINTER(rdpSettings), UINT32)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FREERDP_SETTINGS_CMD_PARSE_FLAGS', 'FREERDP_SETTINGS_CMD_PARSE_NO_FLAGS', 'FREERDP_SETTINGS_CMD_PARSE_SUPPRESS_WARNINGS', 'FUNCTIONS', 'bind', 'freerdp_command_line_handle_option_t']
