"""
Mirror of <freerdp/client/disp.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
DispClientContext = _types.DispClientContext
pcDispCaps = _types.pcDispCaps
pcDispSendMonitorLayout = _types.pcDispSendMonitorLayout
struct_s_disp_client_context = _types.struct_s_disp_client_context

__all__ = ['DispClientContext', 'pcDispCaps', 'pcDispSendMonitorLayout', 'struct_s_disp_client_context']
