"""
Mirror of <freerdp/client/drdynvc.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
DrdynvcClientChannelStat = _types.DrdynvcClientChannelStat
DrdynvcClientContext = _types.DrdynvcClientContext
pcDrdynvcGetChannelStats = _types.pcDrdynvcGetChannelStats
pcDrdynvcGetVersion = _types.pcDrdynvcGetVersion
pcDrdynvcOnChannelAttached = _types.pcDrdynvcOnChannelAttached
pcDrdynvcOnChannelConnected = _types.pcDrdynvcOnChannelConnected
pcDrdynvcOnChannelDetached = _types.pcDrdynvcOnChannelDetached
pcDrdynvcOnChannelDisconnected = _types.pcDrdynvcOnChannelDisconnected
struct_DrdynvcClientChannelStat = _types.struct_DrdynvcClientChannelStat
struct_s_drdynvc_client_context = _types.struct_s_drdynvc_client_context

__all__ = ['DrdynvcClientChannelStat', 'DrdynvcClientContext', 'pcDrdynvcGetChannelStats', 'pcDrdynvcGetVersion', 'pcDrdynvcOnChannelAttached', 'pcDrdynvcOnChannelConnected', 'pcDrdynvcOnChannelDetached', 'pcDrdynvcOnChannelDisconnected', 'struct_DrdynvcClientChannelStat', 'struct_s_drdynvc_client_context']
