"""
Mirror of <freerdp/client/encomsp.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
EncomspClientContext = _types.EncomspClientContext
pcEncomspApplicationCreated = _types.pcEncomspApplicationCreated
pcEncomspApplicationRemoved = _types.pcEncomspApplicationRemoved
pcEncomspChangeParticipantControlLevel = _types.pcEncomspChangeParticipantControlLevel
pcEncomspFilterUpdated = _types.pcEncomspFilterUpdated
pcEncomspGraphicsStreamPaused = _types.pcEncomspGraphicsStreamPaused
pcEncomspGraphicsStreamResumed = _types.pcEncomspGraphicsStreamResumed
pcEncomspParticipantCreated = _types.pcEncomspParticipantCreated
pcEncomspParticipantRemoved = _types.pcEncomspParticipantRemoved
pcEncomspShowWindow = _types.pcEncomspShowWindow
pcEncomspWindowCreated = _types.pcEncomspWindowCreated
pcEncomspWindowRemoved = _types.pcEncomspWindowRemoved
struct_s_encomsp_client_context = _types.struct_s_encomsp_client_context

__all__ = ['EncomspClientContext', 'pcEncomspApplicationCreated', 'pcEncomspApplicationRemoved', 'pcEncomspChangeParticipantControlLevel', 'pcEncomspFilterUpdated', 'pcEncomspGraphicsStreamPaused', 'pcEncomspGraphicsStreamResumed', 'pcEncomspParticipantCreated', 'pcEncomspParticipantRemoved', 'pcEncomspShowWindow', 'pcEncomspWindowCreated', 'pcEncomspWindowRemoved', 'struct_s_encomsp_client_context']
