"""
Mirror of <freerdp/client/geometry.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
GeometryClientContext = _types.GeometryClientContext
MAPPED_GEOMETRY = _types.MAPPED_GEOMETRY
pcMappedGeometryAdded = _types.pcMappedGeometryAdded
pcMappedGeometryClear = _types.pcMappedGeometryClear
pcMappedGeometryUpdate = _types.pcMappedGeometryUpdate
struct_S_MAPPED_GEOMETRY = _types.struct_S_MAPPED_GEOMETRY
struct_s_geometry_client_context = _types.struct_s_geometry_client_context

# --- functions declared in this header ---
FUNCTIONS = (
    'mappedGeometryRef',  # void (ctypes.POINTER(MAPPED_GEOMETRY))
    'mappedGeometryUnref',  # void (ctypes.POINTER(MAPPED_GEOMETRY))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'GeometryClientContext', 'MAPPED_GEOMETRY', 'bind', 'pcMappedGeometryAdded', 'pcMappedGeometryClear', 'pcMappedGeometryUpdate', 'struct_S_MAPPED_GEOMETRY', 'struct_s_geometry_client_context']
