"""
Mirror of <freerdp/client/location.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
LocationClientContext = _types.LocationClientContext
pcLocationSend = _types.pcLocationSend
pcLocationStart = _types.pcLocationStart
pcLocationStop = _types.pcLocationStop
struct_s_location_client_context = _types.struct_s_location_client_context

__all__ = ['LocationClientContext', 'pcLocationSend', 'pcLocationStart', 'pcLocationStop', 'struct_s_location_client_context']
