"""
Mirror of <freerdp/client/printer.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
pcClosePrintJob = _types.pcClosePrintJob
pcCreatePrintJob = _types.pcCreatePrintJob
pcEnumPrinters = _types.pcEnumPrinters
pcFindPrintJob = _types.pcFindPrintJob
pcGetPrinter = _types.pcGetPrinter
pcReferencePrinter = _types.pcReferencePrinter
pcReferencePrinterDriver = _types.pcReferencePrinterDriver
pcReleaseEnumPrinters = _types.pcReleaseEnumPrinters
pcSetDeviceForPrinterDriver = _types.pcSetDeviceForPrinterDriver
pcWritePrintJob = _types.pcWritePrintJob
rdpPrintJob = _types.rdpPrintJob
rdpPrinter = _types.rdpPrinter
rdpPrinterDriver = _types.rdpPrinterDriver
struct_rdp_print_job = _types.struct_rdp_print_job
struct_rdp_printer = _types.struct_rdp_printer
struct_rdp_printer_driver = _types.struct_rdp_printer_driver

__all__ = ['pcClosePrintJob', 'pcCreatePrintJob', 'pcEnumPrinters', 'pcFindPrintJob', 'pcGetPrinter', 'pcReferencePrinter', 'pcReferencePrinterDriver', 'pcReleaseEnumPrinters', 'pcSetDeviceForPrinterDriver', 'pcWritePrintJob', 'rdpPrintJob', 'rdpPrinter', 'rdpPrinterDriver', 'struct_rdp_print_job', 'struct_rdp_printer', 'struct_rdp_printer_driver']
