"""
Mirror of <freerdp/client/rail.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
RailClientContext = _types.RailClientContext
pcRailClientActivate = _types.pcRailClientActivate
pcRailClientCaretBlinkRate = _types.pcRailClientCaretBlinkRate
pcRailClientCloak = _types.pcRailClientCloak
pcRailClientCompartmentInfo = _types.pcRailClientCompartmentInfo
pcRailClientExecute = _types.pcRailClientExecute
pcRailClientGetAppIdRequest = _types.pcRailClientGetAppIdRequest
pcRailClientHandshake = _types.pcRailClientHandshake
pcRailClientInformation = _types.pcRailClientInformation
pcRailClientLanguageBarInfo = _types.pcRailClientLanguageBarInfo
pcRailClientLanguageIMEInfo = _types.pcRailClientLanguageIMEInfo
pcRailClientNotifyEvent = _types.pcRailClientNotifyEvent
pcRailClientSnapArrange = _types.pcRailClientSnapArrange
pcRailClientSystemCommand = _types.pcRailClientSystemCommand
pcRailClientSystemMenu = _types.pcRailClientSystemMenu
pcRailClientSystemParam = _types.pcRailClientSystemParam
pcRailClientTextScale = _types.pcRailClientTextScale
pcRailClientWindowMove = _types.pcRailClientWindowMove
pcRailOnOpen = _types.pcRailOnOpen
pcRailServerCloak = _types.pcRailServerCloak
pcRailServerExecuteResult = _types.pcRailServerExecuteResult
pcRailServerGetAppIdResponse = _types.pcRailServerGetAppIdResponse
pcRailServerGetAppidResponseExtended = _types.pcRailServerGetAppidResponseExtended
pcRailServerHandshake = _types.pcRailServerHandshake
pcRailServerHandshakeEx = _types.pcRailServerHandshakeEx
pcRailServerLanguageBarInfo = _types.pcRailServerLanguageBarInfo
pcRailServerLocalMoveSize = _types.pcRailServerLocalMoveSize
pcRailServerMinMaxInfo = _types.pcRailServerMinMaxInfo
pcRailServerPowerDisplayRequest = _types.pcRailServerPowerDisplayRequest
pcRailServerSystemParam = _types.pcRailServerSystemParam
pcRailServerTaskBarInfo = _types.pcRailServerTaskBarInfo
pcRailServerZOrderSync = _types.pcRailServerZOrderSync
struct_s_rail_client_context = _types.struct_s_rail_client_context

# --- functions declared in this header ---
FUNCTIONS = (
    'client_rail_server_start_cmd',  # UINT (ctypes.POINTER(RailClientContext))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'RailClientContext', 'bind', 'pcRailClientActivate', 'pcRailClientCaretBlinkRate', 'pcRailClientCloak', 'pcRailClientCompartmentInfo', 'pcRailClientExecute', 'pcRailClientGetAppIdRequest', 'pcRailClientHandshake', 'pcRailClientInformation', 'pcRailClientLanguageBarInfo', 'pcRailClientLanguageIMEInfo', 'pcRailClientNotifyEvent', 'pcRailClientSnapArrange', 'pcRailClientSystemCommand', 'pcRailClientSystemMenu', 'pcRailClientSystemParam', 'pcRailClientTextScale', 'pcRailClientWindowMove', 'pcRailOnOpen', 'pcRailServerCloak', 'pcRailServerExecuteResult', 'pcRailServerGetAppIdResponse', 'pcRailServerGetAppidResponseExtended', 'pcRailServerHandshake', 'pcRailServerHandshakeEx', 'pcRailServerLanguageBarInfo', 'pcRailServerLocalMoveSize', 'pcRailServerMinMaxInfo', 'pcRailServerPowerDisplayRequest', 'pcRailServerSystemParam', 'pcRailServerTaskBarInfo', 'pcRailServerZOrderSync', 'struct_s_rail_client_context']
