"""
Mirror of <freerdp/client/rdpdr.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
RDPDR_HOTPLUG_CHECK_FOR_CHANGES = 1
RDPDR_HOTPLUG_FIRST_CHECK = 0

# --- types declared in this header ---
RdpdrClientContext = _types.RdpdrClientContext
RdpdrHotplugEventType = _types.RdpdrHotplugEventType
pcRdpdrHotplugDevice = _types.pcRdpdrHotplugDevice
pcRdpdrRegisterDevice = _types.pcRdpdrRegisterDevice
pcRdpdrUnregisterDevice = _types.pcRdpdrUnregisterDevice
struct_s_rdpdr_client_context = _types.struct_s_rdpdr_client_context

__all__ = ['RDPDR_HOTPLUG_CHECK_FOR_CHANGES', 'RDPDR_HOTPLUG_FIRST_CHECK', 'RdpdrClientContext', 'RdpdrHotplugEventType', 'pcRdpdrHotplugDevice', 'pcRdpdrRegisterDevice', 'pcRdpdrUnregisterDevice', 'struct_s_rdpdr_client_context']
