"""
Mirror of <freerdp/client/rdpei.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
RdpeiClientContext = _types.RdpeiClientContext
pcRdpeiAddContact = _types.pcRdpeiAddContact
pcRdpeiAddPen = _types.pcRdpeiAddPen
pcRdpeiGetFeatures = _types.pcRdpeiGetFeatures
pcRdpeiGetVersion = _types.pcRdpeiGetVersion
pcRdpeiPen = _types.pcRdpeiPen
pcRdpeiPenRawEvent = _types.pcRdpeiPenRawEvent
pcRdpeiPenRawEventVA = _types.pcRdpeiPenRawEventVA
pcRdpeiResumeTouch = _types.pcRdpeiResumeTouch
pcRdpeiSuspendTouch = _types.pcRdpeiSuspendTouch
pcRdpeiTouchEvent = _types.pcRdpeiTouchEvent
pcRdpeiTouchRawEvent = _types.pcRdpeiTouchRawEvent
pcRdpeiTouchRawEventVA = _types.pcRdpeiTouchRawEventVA
struct_s_rdpei_client_context = _types.struct_s_rdpei_client_context

__all__ = ['RdpeiClientContext', 'pcRdpeiAddContact', 'pcRdpeiAddPen', 'pcRdpeiGetFeatures', 'pcRdpeiGetVersion', 'pcRdpeiPen', 'pcRdpeiPenRawEvent', 'pcRdpeiPenRawEventVA', 'pcRdpeiResumeTouch', 'pcRdpeiSuspendTouch', 'pcRdpeiTouchEvent', 'pcRdpeiTouchRawEvent', 'pcRdpeiTouchRawEventVA', 'struct_s_rdpei_client_context']
