"""
Mirror of <freerdp/client/rdpgfx.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
RdpgfxClientContext = _types.RdpgfxClientContext
gdiGfxSurface = _types.gdiGfxSurface
pcRdpgfxCacheImportOffer = _types.pcRdpgfxCacheImportOffer
pcRdpgfxCacheImportReply = _types.pcRdpgfxCacheImportReply
pcRdpgfxCacheToSurface = _types.pcRdpgfxCacheToSurface
pcRdpgfxCapsAdvertise = _types.pcRdpgfxCapsAdvertise
pcRdpgfxCapsConfirm = _types.pcRdpgfxCapsConfirm
pcRdpgfxCreateSurface = _types.pcRdpgfxCreateSurface
pcRdpgfxDeleteEncodingContext = _types.pcRdpgfxDeleteEncodingContext
pcRdpgfxDeleteSurface = _types.pcRdpgfxDeleteSurface
pcRdpgfxEndFrame = _types.pcRdpgfxEndFrame
pcRdpgfxEvictCacheEntry = _types.pcRdpgfxEvictCacheEntry
pcRdpgfxExportCacheEntry = _types.pcRdpgfxExportCacheEntry
pcRdpgfxFrameAcknowledge = _types.pcRdpgfxFrameAcknowledge
pcRdpgfxGetCacheSlotData = _types.pcRdpgfxGetCacheSlotData
pcRdpgfxGetSurfaceData = _types.pcRdpgfxGetSurfaceData
pcRdpgfxGetSurfaceIds = _types.pcRdpgfxGetSurfaceIds
pcRdpgfxImportCacheEntry = _types.pcRdpgfxImportCacheEntry
pcRdpgfxMapSurfaceToOutput = _types.pcRdpgfxMapSurfaceToOutput
pcRdpgfxMapSurfaceToScaledOutput = _types.pcRdpgfxMapSurfaceToScaledOutput
pcRdpgfxMapSurfaceToScaledWindow = _types.pcRdpgfxMapSurfaceToScaledWindow
pcRdpgfxMapSurfaceToWindow = _types.pcRdpgfxMapSurfaceToWindow
pcRdpgfxMapWindowForSurface = _types.pcRdpgfxMapWindowForSurface
pcRdpgfxOnClose = _types.pcRdpgfxOnClose
pcRdpgfxOnOpen = _types.pcRdpgfxOnOpen
pcRdpgfxQoeFrameAcknowledge = _types.pcRdpgfxQoeFrameAcknowledge
pcRdpgfxResetGraphics = _types.pcRdpgfxResetGraphics
pcRdpgfxSetCacheSlotData = _types.pcRdpgfxSetCacheSlotData
pcRdpgfxSetSurfaceData = _types.pcRdpgfxSetSurfaceData
pcRdpgfxSolidFill = _types.pcRdpgfxSolidFill
pcRdpgfxStartFrame = _types.pcRdpgfxStartFrame
pcRdpgfxSurfaceCommand = _types.pcRdpgfxSurfaceCommand
pcRdpgfxSurfaceToCache = _types.pcRdpgfxSurfaceToCache
pcRdpgfxSurfaceToSurface = _types.pcRdpgfxSurfaceToSurface
pcRdpgfxUnmapWindowForSurface = _types.pcRdpgfxUnmapWindowForSurface
pcRdpgfxUpdateSurfaceArea = _types.pcRdpgfxUpdateSurfaceArea
pcRdpgfxUpdateSurfaces = _types.pcRdpgfxUpdateSurfaces
pcRdpgfxUpdateWindowFromSurface = _types.pcRdpgfxUpdateWindowFromSurface
struct_s_rdpgfx_client_context = _types.struct_s_rdpgfx_client_context

# --- functions declared in this header ---
FUNCTIONS = (
    'rdpgfx_client_context_free',  # void (ctypes.POINTER(RdpgfxClientContext))
    'rdpgfx_client_context_new',  # ctypes.POINTER(RdpgfxClientContext) (ctypes.POINTER(rdpContext))
    'rdpgfx_stats_max_index',  # ctypes.c_size_t ()
    'rdpgfx_stats_name_for_index',  # ctypes.c_char_p (ctypes.c_size_t)
    'rdpgfx_stats_value_for_index',  # ctypes.c_uint64 (ctypes.POINTER(RdpgfxClientContext), ctypes.c_size_t)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'RdpgfxClientContext', 'bind', 'gdiGfxSurface', 'pcRdpgfxCacheImportOffer', 'pcRdpgfxCacheImportReply', 'pcRdpgfxCacheToSurface', 'pcRdpgfxCapsAdvertise', 'pcRdpgfxCapsConfirm', 'pcRdpgfxCreateSurface', 'pcRdpgfxDeleteEncodingContext', 'pcRdpgfxDeleteSurface', 'pcRdpgfxEndFrame', 'pcRdpgfxEvictCacheEntry', 'pcRdpgfxExportCacheEntry', 'pcRdpgfxFrameAcknowledge', 'pcRdpgfxGetCacheSlotData', 'pcRdpgfxGetSurfaceData', 'pcRdpgfxGetSurfaceIds', 'pcRdpgfxImportCacheEntry', 'pcRdpgfxMapSurfaceToOutput', 'pcRdpgfxMapSurfaceToScaledOutput', 'pcRdpgfxMapSurfaceToScaledWindow', 'pcRdpgfxMapSurfaceToWindow', 'pcRdpgfxMapWindowForSurface', 'pcRdpgfxOnClose', 'pcRdpgfxOnOpen', 'pcRdpgfxQoeFrameAcknowledge', 'pcRdpgfxResetGraphics', 'pcRdpgfxSetCacheSlotData', 'pcRdpgfxSetSurfaceData', 'pcRdpgfxSolidFill', 'pcRdpgfxStartFrame', 'pcRdpgfxSurfaceCommand', 'pcRdpgfxSurfaceToCache', 'pcRdpgfxSurfaceToSurface', 'pcRdpgfxUnmapWindowForSurface', 'pcRdpgfxUpdateSurfaceArea', 'pcRdpgfxUpdateSurfaces', 'pcRdpgfxUpdateWindowFromSurface', 'struct_s_rdpgfx_client_context']
