"""
Mirror of <freerdp/client/rdpsnd.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
RDPSND_DEVICE_EXPORT_FUNC_NAME = 'freerdp_rdpsnd_client_subsystem_entry'

# --- types declared in this header ---
FREERDP_RDPSND_DEVICE_ENTRY_POINTS = _types.FREERDP_RDPSND_DEVICE_ENTRY_POINTS
PFREERDP_RDPSND_DEVICE_ENTRY = _types.PFREERDP_RDPSND_DEVICE_ENTRY
PFREERDP_RDPSND_DEVICE_ENTRY_POINTS = _types.PFREERDP_RDPSND_DEVICE_ENTRY_POINTS
PREGISTERRDPSNDDEVICE = _types.PREGISTERRDPSNDDEVICE
pcClose = _types.pcClose
pcDefaultFormat = _types.pcDefaultFormat
pcFormatSupported = _types.pcFormatSupported
pcFree = _types.pcFree
pcGetVolume = _types.pcGetVolume
pcOpen = _types.pcOpen
pcPlay = _types.pcPlay
pcPlayEx = _types.pcPlayEx
pcServerFormatAnnounce = _types.pcServerFormatAnnounce
pcSetVolume = _types.pcSetVolume
pcStart = _types.pcStart
rdpsndDevicePlugin = _types.rdpsndDevicePlugin
rdpsndPlugin = _types.rdpsndPlugin
struct_FREERDP_RDPSND_DEVICE_ENTRY_POINTS = _types.struct_FREERDP_RDPSND_DEVICE_ENTRY_POINTS
struct_rdpsnd_device_plugin = _types.struct_rdpsnd_device_plugin

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_rdpsnd_get_context',  # ctypes.POINTER(rdpContext) (ctypes.POINTER(rdpsndPlugin))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FREERDP_RDPSND_DEVICE_ENTRY_POINTS', 'FUNCTIONS', 'PFREERDP_RDPSND_DEVICE_ENTRY', 'PFREERDP_RDPSND_DEVICE_ENTRY_POINTS', 'PREGISTERRDPSNDDEVICE', 'RDPSND_DEVICE_EXPORT_FUNC_NAME', 'bind', 'pcClose', 'pcDefaultFormat', 'pcFormatSupported', 'pcFree', 'pcGetVolume', 'pcOpen', 'pcPlay', 'pcPlayEx', 'pcServerFormatAnnounce', 'pcSetVolume', 'pcStart', 'rdpsndDevicePlugin', 'rdpsndPlugin', 'struct_FREERDP_RDPSND_DEVICE_ENTRY_POINTS', 'struct_rdpsnd_device_plugin']
