"""
Mirror of <freerdp/client/sshagent.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
SSHAgentClientContext = _types.SSHAgentClientContext
struct_SSHAgentClientContext = _types.struct_SSHAgentClientContext

__all__ = ['SSHAgentClientContext', 'struct_SSHAgentClientContext']
