"""
Mirror of <freerdp/client/tsmf.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
RDP_PIXFMT_I420 = 0x30323449
RDP_PIXFMT_YV12 = 0x32315659

# --- types declared in this header ---
TSMF_VIDEO_FRAME_EVENT = _types.TSMF_VIDEO_FRAME_EVENT
TsmfClientContext = _types.TsmfClientContext
pcTsmfFrameEvent = _types.pcTsmfFrameEvent
struct_TSMF_VIDEO_FRAME_EVENT = _types.struct_TSMF_VIDEO_FRAME_EVENT
struct_s_tsmf_client_context = _types.struct_s_tsmf_client_context

__all__ = ['RDP_PIXFMT_I420', 'RDP_PIXFMT_YV12', 'TSMF_VIDEO_FRAME_EVENT', 'TsmfClientContext', 'pcTsmfFrameEvent', 'struct_TSMF_VIDEO_FRAME_EVENT', 'struct_s_tsmf_client_context']
