"""
Mirror of <freerdp/client/video.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
VideoClientContext = _types.VideoClientContext
VideoClientContextPriv = _types.VideoClientContextPriv
VideoSurface = _types.VideoSurface
pcVideoCreateSurface = _types.pcVideoCreateSurface
pcVideoDeleteSurface = _types.pcVideoDeleteSurface
pcVideoSetGeometry = _types.pcVideoSetGeometry
pcVideoShowSurface = _types.pcVideoShowSurface
pcVideoTimer = _types.pcVideoTimer
struct_VideoSurface = _types.struct_VideoSurface
struct_s_VideoClientContext = _types.struct_s_VideoClientContext

# --- functions declared in this header ---
FUNCTIONS = (
    'VideoClient_CreateCommonContext',  # ctypes.POINTER(VideoSurface) (ctypes.c_size_t, UINT32, UINT32, UINT32, UINT32)
    'VideoClient_DestroyCommonContext',  # void (ctypes.POINTER(VideoSurface))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'VideoClientContext', 'VideoClientContextPriv', 'VideoSurface', 'bind', 'pcVideoCreateSurface', 'pcVideoDeleteSurface', 'pcVideoSetGeometry', 'pcVideoShowSurface', 'pcVideoTimer', 'struct_VideoSurface', 'struct_s_VideoClientContext']
