"""
Mirror of <freerdp/crypto/ber.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
BER_CLASS_APPL = 0x40
BER_CLASS_CTXT = 0x80
BER_CLASS_MASK = 0xc0
BER_CLASS_PRIV = 0xc0
BER_CLASS_UNIV = 0
BER_CONSTRUCT = 0x20
BER_PC_MASK = 0x20
BER_PRIMITIVE = 0
BER_TAG_BIT_STRING = 3
BER_TAG_BOOLEAN = 1
BER_TAG_ENUMERATED = 0xa
BER_TAG_INTEGER = 2
BER_TAG_MASK = 0x1f
BER_TAG_OBJECT_IDENFIER = 6
BER_TAG_OCTET_STRING = 4
BER_TAG_SEQUENCE = 0x10
BER_TAG_SEQUENCE_OF = 0x10

# --- functions declared in this header ---
FUNCTIONS = (
    '_ber_sizeof_length',  # ctypes.c_size_t (ctypes.c_size_t)
    'ber_read_BOOL',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(BOOL))
    'ber_read_application_tag',  # BOOL (ctypes.POINTER(wStream), BYTE, ctypes.POINTER(ctypes.c_size_t))
    'ber_read_bit_string',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_size_t), ctypes.POINTER(BYTE))
    'ber_read_char_from_unicode_octet_string',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_char_p))
    'ber_read_contextual_tag',  # BOOL (ctypes.POINTER(wStream), BYTE, ctypes.POINTER(ctypes.c_size_t), BOOL)
    'ber_read_enumerated',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(BYTE), BYTE)
    'ber_read_integer',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(UINT32))
    'ber_read_integer_length',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_size_t))
    'ber_read_length',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_size_t))
    'ber_read_octet_string',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(ctypes.POINTER(BYTE)), ctypes.POINTER(ctypes.c_size_t))
    'ber_read_octet_string_tag',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_size_t))
    'ber_read_sequence_tag',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_size_t))
    'ber_read_unicode_octet_string',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(LPWSTR))
    'ber_read_universal_tag',  # BOOL (ctypes.POINTER(wStream), BYTE, BOOL)
    'ber_sizeof_contextual_integer',  # ctypes.c_size_t (UINT32)
    'ber_sizeof_contextual_octet_string',  # ctypes.c_size_t (ctypes.c_size_t)
    'ber_sizeof_contextual_tag',  # ctypes.c_size_t (ctypes.c_size_t)
    'ber_sizeof_integer',  # ctypes.c_size_t (UINT32)
    'ber_sizeof_octet_string',  # ctypes.c_size_t (ctypes.c_size_t)
    'ber_sizeof_sequence',  # ctypes.c_size_t (ctypes.c_size_t)
    'ber_sizeof_sequence_tag',  # ctypes.c_size_t (ctypes.c_size_t)
    'ber_write_BOOL',  # void (ctypes.POINTER(wStream), BOOL)
    'ber_write_application_tag',  # void (ctypes.POINTER(wStream), BYTE, ctypes.c_size_t)
    'ber_write_char_to_unicode_octet_string',  # ctypes.c_size_t (ctypes.POINTER(wStream), ctypes.c_char_p)
    'ber_write_contextual_char_to_unicode_octet_string',  # ctypes.c_size_t (ctypes.POINTER(wStream), BYTE, ctypes.c_char_p)
    'ber_write_contextual_integer',  # ctypes.c_size_t (ctypes.POINTER(wStream), BYTE, UINT32)
    'ber_write_contextual_octet_string',  # ctypes.c_size_t (ctypes.POINTER(wStream), BYTE, ctypes.POINTER(BYTE), ctypes.c_size_t)
    'ber_write_contextual_tag',  # ctypes.c_size_t (ctypes.POINTER(wStream), BYTE, ctypes.c_size_t, BOOL)
    'ber_write_contextual_unicode_octet_string',  # ctypes.c_size_t (ctypes.POINTER(wStream), BYTE, LPWSTR)
    'ber_write_enumerated',  # void (ctypes.POINTER(wStream), BYTE, BYTE)
    'ber_write_integer',  # ctypes.c_size_t (ctypes.POINTER(wStream), UINT32)
    'ber_write_length',  # ctypes.c_size_t (ctypes.POINTER(wStream), ctypes.c_size_t)
    'ber_write_octet_string',  # ctypes.c_size_t (ctypes.POINTER(wStream), ctypes.POINTER(BYTE), ctypes.c_size_t)
    'ber_write_octet_string_tag',  # ctypes.c_size_t (ctypes.POINTER(wStream), ctypes.c_size_t)
    'ber_write_sequence_tag',  # ctypes.c_size_t (ctypes.POINTER(wStream), ctypes.c_size_t)
    'ber_write_universal_tag',  # ctypes.c_size_t (ctypes.POINTER(wStream), BYTE, BOOL)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['BER_CLASS_APPL', 'BER_CLASS_CTXT', 'BER_CLASS_MASK', 'BER_CLASS_PRIV', 'BER_CLASS_UNIV', 'BER_CONSTRUCT', 'BER_PC_MASK', 'BER_PRIMITIVE', 'BER_TAG_BIT_STRING', 'BER_TAG_BOOLEAN', 'BER_TAG_ENUMERATED', 'BER_TAG_INTEGER', 'BER_TAG_MASK', 'BER_TAG_OBJECT_IDENFIER', 'BER_TAG_OCTET_STRING', 'BER_TAG_SEQUENCE', 'BER_TAG_SEQUENCE_OF', 'FUNCTIONS', 'bind']
