"""
Mirror of <freerdp/crypto/certificate_store.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
CERT_STORE_MATCH = 0
CERT_STORE_MISMATCH = -1
CERT_STORE_NOT_FOUND = 1

# --- types declared in this header ---
freerdp_certificate_store_result = _types.freerdp_certificate_store_result
rdpCertificateStore = _types.rdpCertificateStore

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_certificate_store_contains_data',  # freerdp_certificate_store_result (ctypes.POINTER(rdpCertificateStore), ctypes.POINTER(rdpCertificateData))
    'freerdp_certificate_store_free',  # void (ctypes.POINTER(rdpCertificateStore))
    'freerdp_certificate_store_get_cert_path',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificateStore), ctypes.c_char_p, UINT16)
    'freerdp_certificate_store_get_certs_path',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificateStore))
    'freerdp_certificate_store_get_hosts_path',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificateStore))
    'freerdp_certificate_store_load_data',  # ctypes.POINTER(rdpCertificateData) (ctypes.POINTER(rdpCertificateStore), ctypes.c_char_p, UINT16)
    'freerdp_certificate_store_new',  # ctypes.POINTER(rdpCertificateStore) (ctypes.POINTER(rdpSettings))
    'freerdp_certificate_store_remove_data',  # BOOL (ctypes.POINTER(rdpCertificateStore), ctypes.POINTER(rdpCertificateData))
    'freerdp_certificate_store_save_data',  # BOOL (ctypes.POINTER(rdpCertificateStore), ctypes.POINTER(rdpCertificateData))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['CERT_STORE_MATCH', 'CERT_STORE_MISMATCH', 'CERT_STORE_NOT_FOUND', 'FUNCTIONS', 'bind', 'freerdp_certificate_store_result', 'rdpCertificateStore']
