"""
Mirror of <freerdp/crypto/certificate_data.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
rdpCertificateData = _types.rdpCertificateData

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_certificate_data_equal',  # BOOL (ctypes.POINTER(rdpCertificateData), ctypes.POINTER(rdpCertificateData))
    'freerdp_certificate_data_free',  # void (ctypes.POINTER(rdpCertificateData))
    'freerdp_certificate_data_get_fingerprint',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificateData))
    'freerdp_certificate_data_get_hash',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificateData))
    'freerdp_certificate_data_get_host',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificateData))
    'freerdp_certificate_data_get_issuer',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificateData))
    'freerdp_certificate_data_get_pem',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificateData))
    'freerdp_certificate_data_get_pem_ex',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificateData), BOOL)
    'freerdp_certificate_data_get_port',  # UINT16 (ctypes.POINTER(rdpCertificateData))
    'freerdp_certificate_data_get_subject',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificateData))
    'freerdp_certificate_data_hash',  # ctypes.c_char_p (ctypes.c_char_p, UINT16)
    'freerdp_certificate_data_new',  # ctypes.POINTER(rdpCertificateData) (ctypes.c_char_p, UINT16, ctypes.POINTER(rdpCertificate))
    'freerdp_certificate_data_new_from_file',  # ctypes.POINTER(rdpCertificateData) (ctypes.c_char_p, UINT16, ctypes.c_char_p)
    'freerdp_certificate_data_new_from_pem',  # ctypes.POINTER(rdpCertificateData) (ctypes.c_char_p, UINT16, ctypes.c_char_p, ctypes.c_size_t)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'rdpCertificateData']
