"""
Mirror of <freerdp/crypto/certificate.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
FREERDP_CERT_RSA_E = 0
FREERDP_CERT_RSA_N = 1

# --- types declared in this header ---
rdpCertificate = _types.rdpCertificate

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_certificate_check_eku',  # BOOL (ctypes.POINTER(rdpCertificate), ctypes.c_int)
    'freerdp_certificate_free',  # void (ctypes.POINTER(rdpCertificate))
    'freerdp_certificate_free_dns_names',  # void (ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t), ctypes.POINTER(ctypes.c_char_p))
    'freerdp_certificate_get_common_name',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificate), ctypes.POINTER(ctypes.c_size_t))
    'freerdp_certificate_get_der',  # ctypes.POINTER(BYTE) (ctypes.POINTER(rdpCertificate), ctypes.POINTER(ctypes.c_size_t))
    'freerdp_certificate_get_dns_names',  # ctypes.POINTER(ctypes.c_char_p) (ctypes.POINTER(rdpCertificate), ctypes.POINTER(ctypes.c_size_t), ctypes.POINTER(ctypes.POINTER(ctypes.c_size_t)))
    'freerdp_certificate_get_email',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificate))
    'freerdp_certificate_get_fingerprint',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificate))
    'freerdp_certificate_get_fingerprint_by_hash',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificate), ctypes.c_char_p)
    'freerdp_certificate_get_fingerprint_by_hash_ex',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificate), ctypes.c_char_p, BOOL)
    'freerdp_certificate_get_hash',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificate), ctypes.c_char_p, ctypes.POINTER(ctypes.c_size_t))
    'freerdp_certificate_get_issuer',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificate))
    'freerdp_certificate_get_param',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificate), ctypes.c_int, ctypes.POINTER(ctypes.c_size_t))
    'freerdp_certificate_get_pem',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificate), ctypes.POINTER(ctypes.c_size_t))
    'freerdp_certificate_get_pem_ex',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificate), ctypes.POINTER(ctypes.c_size_t), BOOL)
    'freerdp_certificate_get_public_key',  # BOOL (ctypes.POINTER(rdpCertificate), ctypes.POINTER(ctypes.POINTER(BYTE)), ctypes.POINTER(DWORD))
    'freerdp_certificate_get_signature_alg',  # WINPR_MD_TYPE (ctypes.POINTER(rdpCertificate))
    'freerdp_certificate_get_subject',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificate))
    'freerdp_certificate_get_upn',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificate))
    'freerdp_certificate_get_validity',  # ctypes.c_char_p (ctypes.POINTER(rdpCertificate), BOOL)
    'freerdp_certificate_is_rdp_security_compatible',  # BOOL (ctypes.POINTER(rdpCertificate))
    'freerdp_certificate_is_rsa',  # BOOL (ctypes.POINTER(rdpCertificate))
    'freerdp_certificate_new',  # ctypes.POINTER(rdpCertificate) ()
    'freerdp_certificate_new_from_der',  # ctypes.POINTER(rdpCertificate) (ctypes.POINTER(BYTE), ctypes.c_size_t)
    'freerdp_certificate_new_from_file',  # ctypes.POINTER(rdpCertificate) (ctypes.c_char_p)
    'freerdp_certificate_new_from_pem',  # ctypes.POINTER(rdpCertificate) (ctypes.c_char_p)
    'freerdp_certificate_verify',  # BOOL (ctypes.POINTER(rdpCertificate), ctypes.c_char_p)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FREERDP_CERT_RSA_E', 'FREERDP_CERT_RSA_N', 'FUNCTIONS', 'bind', 'rdpCertificate']
