"""
Mirror of <freerdp/crypto/crypto.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
rdpCertInfo = _types.rdpCertInfo
struct_rdp_CertInfo = _types.struct_rdp_CertInfo

# --- functions declared in this header ---
FUNCTIONS = (
    'crypto_base64_decode',  # void (ctypes.c_char_p, ctypes.c_size_t, ctypes.POINTER(ctypes.POINTER(BYTE)), ctypes.POINTER(ctypes.c_size_t))
    'crypto_base64_encode',  # ctypes.c_char_p (ctypes.POINTER(BYTE), ctypes.c_size_t)
    'crypto_base64_encode_ex',  # ctypes.c_char_p (ctypes.POINTER(BYTE), ctypes.c_size_t, BOOL)
    'crypto_base64url_decode',  # void (ctypes.c_char_p, ctypes.c_size_t, ctypes.POINTER(ctypes.POINTER(BYTE)), ctypes.POINTER(ctypes.c_size_t))
    'crypto_base64url_encode',  # ctypes.c_char_p (ctypes.POINTER(BYTE), ctypes.c_size_t)
    'crypto_read_pem',  # ctypes.c_char_p (ctypes.c_char_p, ctypes.POINTER(ctypes.c_size_t))
    'crypto_write_pem',  # BOOL (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_size_t)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'rdpCertInfo', 'struct_rdp_CertInfo']
