"""
Mirror of <freerdp/crypto/der.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    '_der_skip_length',  # ctypes.c_int (ctypes.c_int)
    'der_get_content_length',  # ctypes.c_int (ctypes.c_int)
    'der_skip_contextual_tag',  # ctypes.c_int (ctypes.c_int)
    'der_skip_octet_string',  # ctypes.c_int (ctypes.c_int)
    'der_skip_sequence_tag',  # ctypes.c_int (ctypes.c_int)
    'der_write_contextual_tag',  # ctypes.c_int (ctypes.POINTER(wStream), BYTE, ctypes.c_int, BOOL)
    'der_write_length',  # ctypes.c_int (ctypes.POINTER(wStream), ctypes.c_int)
    'der_write_octet_string',  # void (ctypes.POINTER(wStream), ctypes.POINTER(BYTE), ctypes.c_int)
    'der_write_sequence_tag',  # ctypes.c_int (ctypes.POINTER(wStream), ctypes.c_int)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
