"""
Mirror of <freerdp/crypto/er.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
ER_CLASS_APPL = 0x40
ER_CLASS_CTXT = 0x80
ER_CLASS_MASK = 0xc0
ER_CLASS_PRIV = 0xc0
ER_CLASS_UNIV = 0
ER_CONSTRUCT = 0x20
ER_PC_MASK = 0x20
ER_PRIMITIVE = 0
ER_TAG_BIT_STRING = 3
ER_TAG_BOOLEAN = 1
ER_TAG_ENUMERATED = 0xa
ER_TAG_GENERALIZED_TIME = 0x18
ER_TAG_GENERAL_STRING = 0x1b
ER_TAG_INTEGER = 2
ER_TAG_MASK = 0x1f
ER_TAG_OBJECT_IDENTIFIER = 6
ER_TAG_OCTET_STRING = 4
ER_TAG_SEQUENCE = 0x30
ER_TAG_SEQUENCE_OF = 0x30

# --- functions declared in this header ---
FUNCTIONS = (
    '_er_skip_length',  # ctypes.c_int (ctypes.c_int)
    'er_get_content_length',  # ctypes.c_int (ctypes.c_int)
    'er_read_BOOL',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(BOOL))
    'er_read_application_tag',  # BOOL (ctypes.POINTER(wStream), BYTE, ctypes.POINTER(ctypes.c_int))
    'er_read_bit_string',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_int), ctypes.POINTER(BYTE))
    'er_read_contextual_tag',  # BOOL (ctypes.POINTER(wStream), BYTE, ctypes.POINTER(ctypes.c_int), BOOL)
    'er_read_enumerated',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(BYTE), BYTE)
    'er_read_integer',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(UINT32))
    'er_read_integer_length',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_int))
    'er_read_length',  # void (ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_int))
    'er_read_octet_string',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_int))
    'er_read_sequence_tag',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(ctypes.c_int))
    'er_read_universal_tag',  # BOOL (ctypes.POINTER(wStream), BYTE, BOOL)
    'er_skip_contextual_tag',  # ctypes.c_int (ctypes.c_int)
    'er_skip_integer',  # ctypes.c_int (INT32)
    'er_skip_octet_string',  # ctypes.c_int (ctypes.c_int)
    'er_skip_sequence',  # ctypes.c_int (ctypes.c_int)
    'er_skip_sequence_tag',  # ctypes.c_int (ctypes.c_int)
    'er_write_BOOL',  # void (ctypes.POINTER(wStream), BOOL)
    'er_write_application_tag',  # void (ctypes.POINTER(wStream), BYTE, ctypes.c_int, BOOL)
    'er_write_bit_string_tag',  # BOOL (ctypes.POINTER(wStream), UINT32, BYTE, BOOL)
    'er_write_contextual_tag',  # ctypes.c_int (ctypes.POINTER(wStream), BYTE, ctypes.c_int, BOOL, BOOL)
    'er_write_enumerated',  # void (ctypes.POINTER(wStream), BYTE, BYTE, BOOL)
    'er_write_integer',  # ctypes.c_int (ctypes.POINTER(wStream), INT32)
    'er_write_length',  # ctypes.c_int (ctypes.POINTER(wStream), ctypes.c_int, BOOL)
    'er_write_octet_string',  # void (ctypes.POINTER(wStream), ctypes.POINTER(BYTE), ctypes.c_int, BOOL)
    'er_write_octet_string_tag',  # ctypes.c_int (ctypes.POINTER(wStream), ctypes.c_int, BOOL)
    'er_write_sequence_tag',  # ctypes.c_int (ctypes.POINTER(wStream), ctypes.c_int, BOOL)
    'er_write_universal_tag',  # void (ctypes.POINTER(wStream), BYTE, BOOL)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['ER_CLASS_APPL', 'ER_CLASS_CTXT', 'ER_CLASS_MASK', 'ER_CLASS_PRIV', 'ER_CLASS_UNIV', 'ER_CONSTRUCT', 'ER_PC_MASK', 'ER_PRIMITIVE', 'ER_TAG_BIT_STRING', 'ER_TAG_BOOLEAN', 'ER_TAG_ENUMERATED', 'ER_TAG_GENERALIZED_TIME', 'ER_TAG_GENERAL_STRING', 'ER_TAG_INTEGER', 'ER_TAG_MASK', 'ER_TAG_OBJECT_IDENTIFIER', 'ER_TAG_OCTET_STRING', 'ER_TAG_SEQUENCE', 'ER_TAG_SEQUENCE_OF', 'FUNCTIONS', 'bind']
