"""
Mirror of <freerdp/crypto/per.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'per_read_choice',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(BYTE))
    'per_read_enumerated',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(BYTE), BYTE)
    'per_read_integer',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(UINT32))
    'per_read_integer16',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(UINT16), UINT16)
    'per_read_length',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(UINT16))
    'per_read_number_of_sets',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(BYTE))
    'per_read_numeric_string',  # BOOL (ctypes.POINTER(wStream), UINT16)
    'per_read_object_identifier',  # BOOL (ctypes.POINTER(wStream), (BYTE * 6))
    'per_read_octet_string',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(BYTE), UINT16, UINT16)
    'per_read_padding',  # BOOL (ctypes.POINTER(wStream), UINT16)
    'per_read_selection',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(BYTE))
    'per_write_choice',  # BOOL (ctypes.POINTER(wStream), BYTE)
    'per_write_enumerated',  # BOOL (ctypes.POINTER(wStream), BYTE, BYTE)
    'per_write_integer',  # BOOL (ctypes.POINTER(wStream), UINT32)
    'per_write_integer16',  # BOOL (ctypes.POINTER(wStream), UINT16, UINT16)
    'per_write_length',  # BOOL (ctypes.POINTER(wStream), UINT16)
    'per_write_number_of_sets',  # BOOL (ctypes.POINTER(wStream), BYTE)
    'per_write_numeric_string',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(BYTE), UINT16, UINT16)
    'per_write_object_identifier',  # BOOL (ctypes.POINTER(wStream), (BYTE * 6))
    'per_write_octet_string',  # BOOL (ctypes.POINTER(wStream), ctypes.POINTER(BYTE), UINT16, UINT16)
    'per_write_padding',  # BOOL (ctypes.POINTER(wStream), UINT16)
    'per_write_selection',  # BOOL (ctypes.POINTER(wStream), BYTE)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
