"""
Mirror of <freerdp/crypto/privatekey.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
rdpPrivateKey = _types.rdpPrivateKey

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_key_free',  # void (ctypes.POINTER(rdpPrivateKey))
    'freerdp_key_generate',  # BOOL (ctypes.POINTER(rdpPrivateKey), ctypes.c_char_p, ctypes.c_size_t, ...)
    'freerdp_key_get_bits',  # ctypes.c_size_t (ctypes.POINTER(rdpPrivateKey))
    'freerdp_key_get_pem',  # ctypes.c_char_p (ctypes.POINTER(rdpPrivateKey), ctypes.POINTER(ctypes.c_size_t), ctypes.c_char_p)
    'freerdp_key_is_rsa',  # BOOL (ctypes.POINTER(rdpPrivateKey))
    'freerdp_key_new',  # ctypes.POINTER(rdpPrivateKey) ()
    'freerdp_key_new_from_file',  # ctypes.POINTER(rdpPrivateKey) (ctypes.c_char_p)
    'freerdp_key_new_from_file_enc',  # ctypes.POINTER(rdpPrivateKey) (ctypes.c_char_p, ctypes.c_char_p)
    'freerdp_key_new_from_pem',  # ctypes.POINTER(rdpPrivateKey) (ctypes.c_char_p)
    'freerdp_key_new_from_pem_enc',  # ctypes.POINTER(rdpPrivateKey) (ctypes.c_char_p, ctypes.c_char_p)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind', 'rdpPrivateKey']
