"""
Mirror of <freerdp/emulate/scard/smartcard_emulate.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ...._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
SmartcardEmulationContext = _types.SmartcardEmulationContext

# --- functions declared in this header ---
FUNCTIONS = (
    'Emulate_Free',  # void (ctypes.POINTER(SmartcardEmulationContext))
    'Emulate_GetOpenCardNameA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), LPOPENCARDNAMEA)
    'Emulate_GetOpenCardNameW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), LPOPENCARDNAMEW)
    'Emulate_IsConfigured',  # BOOL (ctypes.POINTER(SmartcardEmulationContext))
    'Emulate_New',  # ctypes.POINTER(SmartcardEmulationContext) (ctypes.POINTER(rdpSettings))
    'Emulate_SCardAccessStartedEvent',  # HANDLE (ctypes.POINTER(SmartcardEmulationContext))
    'Emulate_SCardAddReaderToGroupA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, LPCSTR)
    'Emulate_SCardAddReaderToGroupW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, LPCWSTR)
    'Emulate_SCardAudit',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, DWORD)
    'Emulate_SCardBeginTransaction',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDHANDLE)
    'Emulate_SCardCancel',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT)
    'Emulate_SCardCancelTransaction',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDHANDLE)
    'Emulate_SCardConnectA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, DWORD, DWORD, LPSCARDHANDLE, LPDWORD)
    'Emulate_SCardConnectW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, DWORD, DWORD, LPSCARDHANDLE, LPDWORD)
    'Emulate_SCardControl',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDHANDLE, DWORD, LPCVOID, DWORD, LPVOID, DWORD, LPDWORD)
    'Emulate_SCardDisconnect',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDHANDLE, DWORD)
    'Emulate_SCardDlgExtendedError',  # LONG (ctypes.POINTER(SmartcardEmulationContext))
    'Emulate_SCardEndTransaction',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDHANDLE, DWORD)
    'Emulate_SCardEstablishContext',  # LONG (ctypes.POINTER(SmartcardEmulationContext), DWORD, LPCVOID, LPCVOID, LPSCARDCONTEXT)
    'Emulate_SCardForgetCardTypeA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR)
    'Emulate_SCardForgetCardTypeW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR)
    'Emulate_SCardForgetReaderA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR)
    'Emulate_SCardForgetReaderGroupA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR)
    'Emulate_SCardForgetReaderGroupW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR)
    'Emulate_SCardForgetReaderW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR)
    'Emulate_SCardFreeMemory',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPVOID)
    'Emulate_SCardGetAttrib',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDHANDLE, DWORD, LPBYTE, LPDWORD)
    'Emulate_SCardGetCardTypeProviderNameA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, DWORD, ctypes.c_char_p, LPDWORD)
    'Emulate_SCardGetCardTypeProviderNameW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, DWORD, ctypes.c_void_p, LPDWORD)
    'Emulate_SCardGetDeviceTypeIdA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, LPDWORD)
    'Emulate_SCardGetDeviceTypeIdW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, LPDWORD)
    'Emulate_SCardGetProviderIdA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, LPGUID)
    'Emulate_SCardGetProviderIdW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, LPGUID)
    'Emulate_SCardGetReaderDeviceInstanceIdA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, LPSTR, LPDWORD)
    'Emulate_SCardGetReaderDeviceInstanceIdW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, LPWSTR, LPDWORD)
    'Emulate_SCardGetReaderIconA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, LPBYTE, LPDWORD)
    'Emulate_SCardGetReaderIconW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, LPBYTE, LPDWORD)
    'Emulate_SCardGetStatusChangeA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, DWORD, LPSCARD_READERSTATEA, DWORD)
    'Emulate_SCardGetStatusChangeW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, DWORD, LPSCARD_READERSTATEW, DWORD)
    'Emulate_SCardGetTransmitCount',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDHANDLE, LPDWORD)
    'Emulate_SCardIntroduceCardTypeA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, LPCGUID, LPCGUID, DWORD, LPCBYTE, LPCBYTE, DWORD)
    'Emulate_SCardIntroduceCardTypeW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, LPCGUID, LPCGUID, DWORD, LPCBYTE, LPCBYTE, DWORD)
    'Emulate_SCardIntroduceReaderA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, LPCSTR)
    'Emulate_SCardIntroduceReaderGroupA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR)
    'Emulate_SCardIntroduceReaderGroupW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR)
    'Emulate_SCardIntroduceReaderW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, LPCWSTR)
    'Emulate_SCardIsValidContext',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT)
    'Emulate_SCardListCardsA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCBYTE, LPCGUID, DWORD, ctypes.c_char_p, LPDWORD)
    'Emulate_SCardListCardsW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCBYTE, LPCGUID, DWORD, ctypes.c_void_p, LPDWORD)
    'Emulate_SCardListInterfacesA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, LPGUID, LPDWORD)
    'Emulate_SCardListInterfacesW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, LPGUID, LPDWORD)
    'Emulate_SCardListReaderGroupsA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPSTR, LPDWORD)
    'Emulate_SCardListReaderGroupsW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPWSTR, LPDWORD)
    'Emulate_SCardListReadersA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, LPSTR, LPDWORD)
    'Emulate_SCardListReadersW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, LPWSTR, LPDWORD)
    'Emulate_SCardListReadersWithDeviceInstanceIdA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, LPSTR, LPDWORD)
    'Emulate_SCardListReadersWithDeviceInstanceIdW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, LPWSTR, LPDWORD)
    'Emulate_SCardLocateCardsA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, LPSCARD_READERSTATEA, DWORD)
    'Emulate_SCardLocateCardsByATRA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPSCARD_ATRMASK, DWORD, LPSCARD_READERSTATEA, DWORD)
    'Emulate_SCardLocateCardsByATRW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPSCARD_ATRMASK, DWORD, LPSCARD_READERSTATEW, DWORD)
    'Emulate_SCardLocateCardsW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, LPSCARD_READERSTATEW, DWORD)
    'Emulate_SCardReadCacheA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, ctypes.POINTER(UUID), DWORD, LPSTR, PBYTE, ctypes.POINTER(DWORD))
    'Emulate_SCardReadCacheW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, ctypes.POINTER(UUID), DWORD, LPWSTR, PBYTE, ctypes.POINTER(DWORD))
    'Emulate_SCardReconnect',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDHANDLE, DWORD, DWORD, DWORD, LPDWORD)
    'Emulate_SCardReleaseContext',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT)
    'Emulate_SCardReleaseStartedEvent',  # void (ctypes.POINTER(SmartcardEmulationContext))
    'Emulate_SCardRemoveReaderFromGroupA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, LPCSTR)
    'Emulate_SCardRemoveReaderFromGroupW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, LPCWSTR)
    'Emulate_SCardSetAttrib',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDHANDLE, DWORD, LPCBYTE, DWORD)
    'Emulate_SCardSetCardTypeProviderNameA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCSTR, DWORD, LPCSTR)
    'Emulate_SCardSetCardTypeProviderNameW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, LPCWSTR, DWORD, LPCWSTR)
    'Emulate_SCardState',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDHANDLE, LPDWORD, LPDWORD, LPBYTE, LPDWORD)
    'Emulate_SCardStatusA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDHANDLE, LPSTR, LPDWORD, LPDWORD, LPDWORD, LPBYTE, LPDWORD)
    'Emulate_SCardStatusW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDHANDLE, LPWSTR, LPDWORD, LPDWORD, LPDWORD, LPBYTE, LPDWORD)
    'Emulate_SCardTransmit',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDHANDLE, LPCSCARD_IO_REQUEST, LPCBYTE, DWORD, LPSCARD_IO_REQUEST, LPBYTE, LPDWORD)
    'Emulate_SCardUIDlgSelectCardA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), LPOPENCARDNAME_EXA)
    'Emulate_SCardUIDlgSelectCardW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), LPOPENCARDNAME_EXW)
    'Emulate_SCardWriteCacheA',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, ctypes.POINTER(UUID), DWORD, LPSTR, PBYTE, DWORD)
    'Emulate_SCardWriteCacheW',  # LONG (ctypes.POINTER(SmartcardEmulationContext), SCARDCONTEXT, ctypes.POINTER(UUID), DWORD, LPWSTR, PBYTE, DWORD)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'SmartcardEmulationContext', 'bind']
