"""
Mirror of <freerdp/codec/av1.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
FREERDP_AV1_CBR = 1
FREERDP_AV1_CONTEXT_OPTION_BITRATE = 2
FREERDP_AV1_CONTEXT_OPTION_PROFILE = 0
FREERDP_AV1_CONTEXT_OPTION_RATECONTROL = 1
FREERDP_AV1_CONTEXT_OPTION_USAGETYPE = 3
FREERDP_AV1_CQ = 2
FREERDP_AV1_Q = 3
FREERDP_AV1_VBR = 0

# --- types declared in this header ---
FREERDP_AV1_CONTEXT = _types.FREERDP_AV1_CONTEXT
FREERDP_AV1_CONTEXT_OPTION = _types.FREERDP_AV1_CONTEXT_OPTION
FREERDP_AV1_RATECONTROL = _types.FREERDP_AV1_RATECONTROL

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_av1_compress',  # INT32 (ctypes.POINTER(FREERDP_AV1_CONTEXT), ctypes.POINTER(BYTE), DWORD, UINT32, UINT32, UINT32, ctypes.POINTER(RECTANGLE_16), ctypes.POINTER(ctypes.POINTER(BYTE)), ctypes.POINTER(UINT32), ctypes.POINTER(RDPGFX_H264_METABLOCK))
    'freerdp_av1_context_free',  # void (ctypes.POINTER(FREERDP_AV1_CONTEXT))
    'freerdp_av1_context_get_option',  # UINT32 (ctypes.POINTER(FREERDP_AV1_CONTEXT), FREERDP_AV1_CONTEXT_OPTION)
    'freerdp_av1_context_new',  # ctypes.POINTER(FREERDP_AV1_CONTEXT) (BOOL)
    'freerdp_av1_context_reset',  # BOOL (ctypes.POINTER(FREERDP_AV1_CONTEXT), UINT32, UINT32)
    'freerdp_av1_context_set_option',  # BOOL (ctypes.POINTER(FREERDP_AV1_CONTEXT), FREERDP_AV1_CONTEXT_OPTION, UINT32)
    'freerdp_av1_decompress',  # INT32 (ctypes.POINTER(FREERDP_AV1_CONTEXT), ctypes.POINTER(BYTE), UINT32, ctypes.POINTER(BYTE), DWORD, UINT32, UINT32, UINT32, ctypes.POINTER(RECTANGLE_16), UINT32)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FREERDP_AV1_CBR', 'FREERDP_AV1_CONTEXT', 'FREERDP_AV1_CONTEXT_OPTION', 'FREERDP_AV1_CONTEXT_OPTION_BITRATE', 'FREERDP_AV1_CONTEXT_OPTION_PROFILE', 'FREERDP_AV1_CONTEXT_OPTION_RATECONTROL', 'FREERDP_AV1_CONTEXT_OPTION_USAGETYPE', 'FREERDP_AV1_CQ', 'FREERDP_AV1_Q', 'FREERDP_AV1_RATECONTROL', 'FREERDP_AV1_VBR', 'FUNCTIONS', 'bind']
