"""
Mirror of <freerdp/codec/bulk.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

# --- #defines and enum members declared in this header ---
L1_COMPRESSED = 1
L1_INNER_COMPRESSION = 0x10
L1_NO_COMPRESSION = 2
L1_PACKET_AT_FRONT = 4
PACKET_AT_FRONT = 0x40
PACKET_COMPRESSED = 0x20
PACKET_FLUSHED = 0x80

__all__ = ['L1_COMPRESSED', 'L1_INNER_COMPRESSION', 'L1_NO_COMPRESSION', 'L1_PACKET_AT_FRONT', 'PACKET_AT_FRONT', 'PACKET_COMPRESSED', 'PACKET_FLUSHED']
