"""
Mirror of <freerdp/codec/clear.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
CLEAR_CONTEXT = _types.CLEAR_CONTEXT

# --- functions declared in this header ---
FUNCTIONS = (
    'clear_compress',  # ctypes.c_int (ctypes.POINTER(CLEAR_CONTEXT), ctypes.POINTER(BYTE), UINT32, ctypes.POINTER(ctypes.POINTER(BYTE)), ctypes.POINTER(UINT32))
    'clear_context_free',  # void (ctypes.POINTER(CLEAR_CONTEXT))
    'clear_context_new',  # ctypes.POINTER(CLEAR_CONTEXT) (BOOL)
    'clear_context_reset',  # BOOL (ctypes.POINTER(CLEAR_CONTEXT))
    'clear_decompress',  # INT32 (ctypes.POINTER(CLEAR_CONTEXT), ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, UINT32, UINT32, UINT32, ctypes.POINTER(gdiPalette))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['CLEAR_CONTEXT', 'FUNCTIONS', 'bind']
