"""
Mirror of <freerdp/codec/dsp.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
FREERDP_DSP_CONTEXT = _types.FREERDP_DSP_CONTEXT

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_dsp_context_free',  # void (ctypes.POINTER(FREERDP_DSP_CONTEXT))
    'freerdp_dsp_context_new',  # ctypes.POINTER(FREERDP_DSP_CONTEXT) (BOOL)
    'freerdp_dsp_context_reset',  # BOOL (ctypes.POINTER(FREERDP_DSP_CONTEXT), ctypes.POINTER(AUDIO_FORMAT), UINT32)
    'freerdp_dsp_decode',  # BOOL (ctypes.POINTER(FREERDP_DSP_CONTEXT), ctypes.POINTER(AUDIO_FORMAT), ctypes.POINTER(BYTE), ctypes.c_size_t, ctypes.POINTER(wStream))
    'freerdp_dsp_encode',  # BOOL (ctypes.POINTER(FREERDP_DSP_CONTEXT), ctypes.POINTER(AUDIO_FORMAT), ctypes.POINTER(BYTE), ctypes.c_size_t, ctypes.POINTER(wStream))
    'freerdp_dsp_supports_format',  # BOOL (ctypes.POINTER(AUDIO_FORMAT), BOOL)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FREERDP_DSP_CONTEXT', 'FUNCTIONS', 'bind']
