"""
Mirror of <freerdp/codec/interleaved.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
BITMAP_INTERLEAVED_CONTEXT = _types.BITMAP_INTERLEAVED_CONTEXT

# --- functions declared in this header ---
FUNCTIONS = (
    'bitmap_interleaved_context_free',  # void (ctypes.POINTER(BITMAP_INTERLEAVED_CONTEXT))
    'bitmap_interleaved_context_new',  # ctypes.POINTER(BITMAP_INTERLEAVED_CONTEXT) (BOOL)
    'bitmap_interleaved_context_reset',  # BOOL (ctypes.POINTER(BITMAP_INTERLEAVED_CONTEXT))
    'interleaved_compress',  # BOOL (ctypes.POINTER(BITMAP_INTERLEAVED_CONTEXT), ctypes.POINTER(BYTE), ctypes.POINTER(UINT32), UINT32, UINT32, ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, UINT32, ctypes.POINTER(gdiPalette), UINT32)
    'interleaved_decompress',  # BOOL (ctypes.POINTER(BITMAP_INTERLEAVED_CONTEXT), ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, UINT32, ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, UINT32, UINT32, UINT32, ctypes.POINTER(gdiPalette))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['BITMAP_INTERLEAVED_CONTEXT', 'FUNCTIONS', 'bind']
