"""
Mirror of <freerdp/codec/jpeg.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- functions declared in this header ---
FUNCTIONS = (
    'jpeg_decompress',  # BOOL (ctypes.POINTER(BYTE), ctypes.POINTER(BYTE), ctypes.c_int, ctypes.c_int, ctypes.c_int, ctypes.c_int)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'bind']
