"""
Mirror of <freerdp/codec/nsc.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
NSC_ALLOW_SUBSAMPLING = 1
NSC_COLOR_FORMAT = 3
NSC_COLOR_LOSS_LEVEL = 0
NSC_DYNAMIC_COLOR_FIDELITY = 2

# --- types declared in this header ---
NSC_CONTEXT = _types.NSC_CONTEXT
NSC_PARAMETER = _types.NSC_PARAMETER

# --- functions declared in this header ---
FUNCTIONS = (
    'nsc_compose_message',  # BOOL (ctypes.POINTER(NSC_CONTEXT), ctypes.POINTER(wStream), ctypes.POINTER(BYTE), UINT32, UINT32, UINT32)
    'nsc_context_free',  # void (ctypes.POINTER(NSC_CONTEXT))
    'nsc_context_new',  # ctypes.POINTER(NSC_CONTEXT) ()
    'nsc_context_reset',  # BOOL (ctypes.POINTER(NSC_CONTEXT), UINT32, UINT32)
    'nsc_context_set_parameters',  # BOOL (ctypes.POINTER(NSC_CONTEXT), NSC_PARAMETER, UINT32)
    'nsc_decompose_message',  # BOOL (ctypes.POINTER(NSC_CONTEXT), ctypes.POINTER(wStream), ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, UINT32, UINT32, UINT32, UINT32)
    'nsc_process_message',  # BOOL (ctypes.POINTER(NSC_CONTEXT), UINT16, UINT32, UINT32, ctypes.POINTER(BYTE), UINT32, ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, UINT32, UINT32, UINT32, UINT32)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'NSC_ALLOW_SUBSAMPLING', 'NSC_COLOR_FORMAT', 'NSC_COLOR_LOSS_LEVEL', 'NSC_CONTEXT', 'NSC_DYNAMIC_COLOR_FIDELITY', 'NSC_PARAMETER', 'bind']
