"""
Mirror of <freerdp/codec/planar.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
PLANAR_FORMAT_HEADER_CLL_MASK = 7
PLANAR_FORMAT_HEADER_CS = 8
PLANAR_FORMAT_HEADER_NA = 0x20
PLANAR_FORMAT_HEADER_RLE = 0x10

# --- types declared in this header ---
BITMAP_PLANAR_CONTEXT = _types.BITMAP_PLANAR_CONTEXT

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_bitmap_compress_planar',  # ctypes.POINTER(BYTE) (ctypes.POINTER(BITMAP_PLANAR_CONTEXT), ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, UINT32, ctypes.POINTER(BYTE), ctypes.POINTER(UINT32))
    'freerdp_bitmap_decompress_planar',  # BOOL (ctypes.POINTER(BITMAP_PLANAR_CONTEXT), ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, UINT32, UINT32, UINT32, BOOL)
    'freerdp_bitmap_planar_context_free',  # void (ctypes.POINTER(BITMAP_PLANAR_CONTEXT))
    'freerdp_bitmap_planar_context_new',  # ctypes.POINTER(BITMAP_PLANAR_CONTEXT) (DWORD, UINT32, UINT32)
    'freerdp_bitmap_planar_context_reset',  # BOOL (ctypes.POINTER(BITMAP_PLANAR_CONTEXT), UINT32, UINT32)
    'freerdp_planar_switch_bgr',  # void (ctypes.POINTER(BITMAP_PLANAR_CONTEXT), BOOL)
    'freerdp_planar_topdown_image',  # void (ctypes.POINTER(BITMAP_PLANAR_CONTEXT), BOOL)
    'planar_decompress',  # BOOL (ctypes.POINTER(BITMAP_PLANAR_CONTEXT), ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, UINT32, UINT32, UINT32, BOOL)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['BITMAP_PLANAR_CONTEXT', 'FUNCTIONS', 'PLANAR_FORMAT_HEADER_CLL_MASK', 'PLANAR_FORMAT_HEADER_CS', 'PLANAR_FORMAT_HEADER_NA', 'PLANAR_FORMAT_HEADER_RLE', 'bind']
