"""
Mirror of <freerdp/codec/progressive.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
PROGRESSIVE_CONTEXT = _types.PROGRESSIVE_CONTEXT

# --- functions declared in this header ---
FUNCTIONS = (
    'progressive_compress',  # ctypes.c_int (ctypes.POINTER(PROGRESSIVE_CONTEXT), ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, UINT32, UINT32, ctypes.POINTER(REGION16), ctypes.POINTER(ctypes.POINTER(BYTE)), ctypes.POINTER(UINT32))
    'progressive_context_free',  # void (ctypes.POINTER(PROGRESSIVE_CONTEXT))
    'progressive_context_new',  # ctypes.POINTER(PROGRESSIVE_CONTEXT) (BOOL)
    'progressive_context_new_ex',  # ctypes.POINTER(PROGRESSIVE_CONTEXT) (BOOL, UINT32)
    'progressive_context_reset',  # BOOL (ctypes.POINTER(PROGRESSIVE_CONTEXT))
    'progressive_create_surface_context',  # INT32 (ctypes.POINTER(PROGRESSIVE_CONTEXT), UINT16, UINT32, UINT32)
    'progressive_decompress',  # INT32 (ctypes.POINTER(PROGRESSIVE_CONTEXT), ctypes.POINTER(BYTE), UINT32, ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, UINT32, ctypes.POINTER(REGION16), UINT16, UINT32)
    'progressive_delete_surface_context',  # ctypes.c_int (ctypes.POINTER(PROGRESSIVE_CONTEXT), UINT16)
    'progressive_rfx_write_message_progressive_simple',  # BOOL (ctypes.POINTER(PROGRESSIVE_CONTEXT), ctypes.POINTER(wStream), ctypes.POINTER(RFX_MESSAGE))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'PROGRESSIVE_CONTEXT', 'bind']
