"""
Mirror of <freerdp/codec/region.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
REGION16 = _types.REGION16
REGION16_DATA = _types.REGION16_DATA
struct_REGION16 = _types.struct_REGION16

# --- functions declared in this header ---
FUNCTIONS = (
    'rectangle_is_empty',  # BOOL (ctypes.POINTER(RECTANGLE_16))
    'rectangle_to_string',  # ctypes.c_char_p (ctypes.POINTER(RECTANGLE_16), ctypes.c_char_p, ctypes.c_size_t)
    'rectangles_clone',  # ctypes.POINTER(RECTANGLE_16) (ctypes.POINTER(RECTANGLE_16), ctypes.c_size_t)
    'rectangles_equal',  # BOOL (ctypes.POINTER(RECTANGLE_16), ctypes.POINTER(RECTANGLE_16))
    'rectangles_intersection',  # BOOL (ctypes.POINTER(RECTANGLE_16), ctypes.POINTER(RECTANGLE_16), ctypes.POINTER(RECTANGLE_16))
    'rectangles_intersects',  # BOOL (ctypes.POINTER(RECTANGLE_16), ctypes.POINTER(RECTANGLE_16))
    'region16_clear',  # void (ctypes.POINTER(REGION16))
    'region16_copy',  # BOOL (ctypes.POINTER(REGION16), ctypes.POINTER(REGION16))
    'region16_extents',  # ctypes.POINTER(RECTANGLE_16) (ctypes.POINTER(REGION16))
    'region16_init',  # void (ctypes.POINTER(REGION16))
    'region16_intersect_rect',  # BOOL (ctypes.POINTER(REGION16), ctypes.POINTER(REGION16), ctypes.POINTER(RECTANGLE_16))
    'region16_intersects_rect',  # BOOL (ctypes.POINTER(REGION16), ctypes.POINTER(RECTANGLE_16))
    'region16_is_empty',  # BOOL (ctypes.POINTER(REGION16))
    'region16_n_rects',  # ctypes.c_int (ctypes.POINTER(REGION16))
    'region16_print',  # void (ctypes.POINTER(REGION16))
    'region16_rects',  # ctypes.POINTER(RECTANGLE_16) (ctypes.POINTER(REGION16), ctypes.POINTER(UINT32))
    'region16_to_string',  # ctypes.c_char_p (ctypes.POINTER(REGION16))
    'region16_uninit',  # void (ctypes.POINTER(REGION16))
    'region16_union_rect',  # BOOL (ctypes.POINTER(REGION16), ctypes.POINTER(REGION16), ctypes.POINTER(RECTANGLE_16))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'REGION16', 'REGION16_DATA', 'bind', 'struct_REGION16']
