"""
Mirror of <freerdp/codec/rfx.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
RLGR1 = 0
RLGR3 = 1

# --- types declared in this header ---
RFX_CONTEXT = _types.RFX_CONTEXT
RFX_MESSAGE = _types.RFX_MESSAGE
RFX_MESSAGE_LIST = _types.RFX_MESSAGE_LIST
RFX_RECT = _types.RFX_RECT
RFX_TILE = _types.RFX_TILE
RLGR_MODE = _types.RLGR_MODE
struct_RFX_RECT = _types.struct_RFX_RECT
struct_RFX_TILE = _types.struct_RFX_TILE

# --- functions declared in this header ---
FUNCTIONS = (
    'rfx_compose_message',  # BOOL (ctypes.POINTER(RFX_CONTEXT), ctypes.POINTER(wStream), ctypes.POINTER(RFX_RECT), ctypes.c_size_t, ctypes.POINTER(BYTE), UINT32, UINT32, UINT32)
    'rfx_context_free',  # void (ctypes.POINTER(RFX_CONTEXT))
    'rfx_context_get_frame_idx',  # UINT32 (ctypes.POINTER(RFX_CONTEXT))
    'rfx_context_get_mode',  # RLGR_MODE (ctypes.POINTER(RFX_CONTEXT))
    'rfx_context_get_palette',  # ctypes.POINTER(BYTE) (ctypes.POINTER(RFX_CONTEXT))
    'rfx_context_get_pixel_format',  # UINT32 (ctypes.POINTER(RFX_CONTEXT))
    'rfx_context_new',  # ctypes.POINTER(RFX_CONTEXT) (BOOL)
    'rfx_context_new_ex',  # ctypes.POINTER(RFX_CONTEXT) (BOOL, UINT32)
    'rfx_context_reset',  # BOOL (ctypes.POINTER(RFX_CONTEXT), UINT32, UINT32)
    'rfx_context_set_mode',  # BOOL (ctypes.POINTER(RFX_CONTEXT), RLGR_MODE)
    'rfx_context_set_palette',  # void (ctypes.POINTER(RFX_CONTEXT), ctypes.POINTER(BYTE))
    'rfx_context_set_pixel_format',  # void (ctypes.POINTER(RFX_CONTEXT), UINT32)
    'rfx_encode_message',  # ctypes.POINTER(RFX_MESSAGE) (ctypes.POINTER(RFX_CONTEXT), ctypes.POINTER(RFX_RECT), ctypes.c_size_t, ctypes.POINTER(BYTE), UINT32, UINT32, ctypes.c_size_t)
    'rfx_encode_messages',  # ctypes.POINTER(RFX_MESSAGE_LIST) (ctypes.POINTER(RFX_CONTEXT), ctypes.POINTER(RFX_RECT), ctypes.c_size_t, ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, ctypes.POINTER(ctypes.c_size_t), ctypes.c_size_t)
    'rfx_message_free',  # void (ctypes.POINTER(RFX_CONTEXT), ctypes.POINTER(RFX_MESSAGE))
    'rfx_message_get_frame_idx',  # UINT32 (ctypes.POINTER(RFX_MESSAGE))
    'rfx_message_get_quants',  # ctypes.POINTER(UINT32) (ctypes.POINTER(RFX_MESSAGE), ctypes.POINTER(UINT16))
    'rfx_message_get_rect_count',  # UINT16 (ctypes.POINTER(RFX_MESSAGE))
    'rfx_message_get_rects',  # ctypes.POINTER(RFX_RECT) (ctypes.POINTER(RFX_MESSAGE), ctypes.POINTER(UINT16))
    'rfx_message_get_tile_count',  # UINT16 (ctypes.POINTER(RFX_MESSAGE))
    'rfx_message_get_tiles',  # ctypes.POINTER(ctypes.POINTER(RFX_TILE)) (ctypes.POINTER(RFX_MESSAGE), ctypes.POINTER(UINT16))
    'rfx_message_list_free',  # void (ctypes.POINTER(RFX_MESSAGE_LIST))
    'rfx_message_list_get',  # ctypes.POINTER(RFX_MESSAGE) (ctypes.POINTER(RFX_MESSAGE_LIST), ctypes.c_size_t)
    'rfx_process_message',  # BOOL (ctypes.POINTER(RFX_CONTEXT), ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, ctypes.POINTER(BYTE), UINT32, UINT32, UINT32, ctypes.POINTER(REGION16))
    'rfx_write_message',  # BOOL (ctypes.POINTER(RFX_CONTEXT), ctypes.POINTER(wStream), ctypes.POINTER(RFX_MESSAGE))
    'rfx_write_message_progressive_simple',  # BOOL (ctypes.POINTER(RFX_CONTEXT), ctypes.POINTER(wStream), ctypes.POINTER(RFX_MESSAGE))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'RFX_CONTEXT', 'RFX_MESSAGE', 'RFX_MESSAGE_LIST', 'RFX_RECT', 'RFX_TILE', 'RLGR1', 'RLGR3', 'RLGR_MODE', 'bind', 'struct_RFX_RECT', 'struct_RFX_TILE']
