"""
Mirror of <freerdp/codec/video.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
FREERDP_VIDEO_FORMAT_H264 = 2
FREERDP_VIDEO_FORMAT_MJPEG = 1
FREERDP_VIDEO_FORMAT_NONE = 0
FREERDP_VIDEO_FORMAT_NV12 = 4
FREERDP_VIDEO_FORMAT_RGB24 = 6
FREERDP_VIDEO_FORMAT_RGB32 = 7
FREERDP_VIDEO_FORMAT_YUV420P = 3
FREERDP_VIDEO_FORMAT_YUYV422 = 5

# --- types declared in this header ---
FREERDP_VIDEO_CONTEXT = _types.FREERDP_VIDEO_CONTEXT
FREERDP_VIDEO_FORMAT = _types.FREERDP_VIDEO_FORMAT

# --- functions declared in this header ---
FUNCTIONS = (
    'freerdp_video_available',  # BOOL ()
    'freerdp_video_context_free',  # void (ctypes.POINTER(FREERDP_VIDEO_CONTEXT))
    'freerdp_video_context_new',  # ctypes.POINTER(FREERDP_VIDEO_CONTEXT) (UINT32, UINT32)
    'freerdp_video_context_reconfigure',  # BOOL (ctypes.POINTER(FREERDP_VIDEO_CONTEXT), UINT32, UINT32, UINT32, UINT32, UINT32)
    'freerdp_video_conversion_supported',  # BOOL (FREERDP_VIDEO_FORMAT, FREERDP_VIDEO_FORMAT)
    'freerdp_video_format_string',  # ctypes.c_char_p (UINT32)
    'freerdp_video_sample_convert',  # BOOL (ctypes.POINTER(FREERDP_VIDEO_CONTEXT), FREERDP_VIDEO_FORMAT, ctypes.c_void_p, ctypes.c_size_t, FREERDP_VIDEO_FORMAT, ctypes.POINTER(wStream))
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FREERDP_VIDEO_CONTEXT', 'FREERDP_VIDEO_FORMAT', 'FREERDP_VIDEO_FORMAT_H264', 'FREERDP_VIDEO_FORMAT_MJPEG', 'FREERDP_VIDEO_FORMAT_NONE', 'FREERDP_VIDEO_FORMAT_NV12', 'FREERDP_VIDEO_FORMAT_RGB24', 'FREERDP_VIDEO_FORMAT_RGB32', 'FREERDP_VIDEO_FORMAT_YUV420P', 'FREERDP_VIDEO_FORMAT_YUYV422', 'FUNCTIONS', 'bind']
