"""
Mirror of <freerdp/codec/yuv.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- types declared in this header ---
YUV_CONTEXT = _types.YUV_CONTEXT

# --- functions declared in this header ---
FUNCTIONS = (
    'yuv420_context_decode',  # BOOL (ctypes.POINTER(YUV_CONTEXT), (ctypes.POINTER(BYTE) * 3), (UINT32 * 3), UINT32, DWORD, ctypes.POINTER(BYTE), UINT32, ctypes.POINTER(RECTANGLE_16), UINT32)
    'yuv420_context_encode',  # BOOL (ctypes.POINTER(YUV_CONTEXT), ctypes.POINTER(BYTE), UINT32, UINT32, (UINT32 * 3), (ctypes.POINTER(BYTE) * 3), ctypes.POINTER(RECTANGLE_16), UINT32)
    'yuv444_context_decode',  # BOOL (ctypes.POINTER(YUV_CONTEXT), BYTE, (ctypes.POINTER(BYTE) * 3), (UINT32 * 3), UINT32, (ctypes.POINTER(BYTE) * 3), (UINT32 * 3), DWORD, ctypes.POINTER(BYTE), UINT32, ctypes.POINTER(RECTANGLE_16), UINT32)
    'yuv444_context_encode',  # BOOL (ctypes.POINTER(YUV_CONTEXT), BYTE, ctypes.POINTER(BYTE), UINT32, UINT32, (UINT32 * 3), (ctypes.POINTER(BYTE) * 3), (ctypes.POINTER(BYTE) * 3), ctypes.POINTER(RECTANGLE_16), UINT32)
    'yuv_context_free',  # void (ctypes.POINTER(YUV_CONTEXT))
    'yuv_context_new',  # ctypes.POINTER(YUV_CONTEXT) (BOOL, UINT32)
    'yuv_context_reset',  # BOOL (ctypes.POINTER(YUV_CONTEXT), UINT32, UINT32)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'YUV_CONTEXT', 'bind']
