"""
Mirror of <freerdp/codec/zgfx.h> (FreeRDP 3.31.1).

Generated by scripts/gen_bindings.py - do not edit.
"""
import ctypes  # noqa: F401

from ..._core import types as _types, functions as _functions  # noqa: E402

# --- #defines and enum members declared in this header ---
ZGFX_PACKET_COMPR_TYPE_RDP8 = 4
ZGFX_SEGMENTED_MAXSIZE = 0xffff
ZGFX_SEGMENTED_MULTIPART = 0xe1
ZGFX_SEGMENTED_SINGLE = 0xe0

# --- types declared in this header ---
ZGFX_CONTEXT = _types.ZGFX_CONTEXT

# --- functions declared in this header ---
FUNCTIONS = (
    'zgfx_compress',  # ctypes.c_int (ctypes.POINTER(ZGFX_CONTEXT), ctypes.POINTER(BYTE), UINT32, ctypes.POINTER(ctypes.POINTER(BYTE)), ctypes.POINTER(UINT32), ctypes.POINTER(UINT32))
    'zgfx_compress_to_stream',  # ctypes.c_int (ctypes.POINTER(ZGFX_CONTEXT), ctypes.POINTER(wStream), ctypes.POINTER(BYTE), UINT32, ctypes.POINTER(UINT32))
    'zgfx_context_free',  # void (ctypes.POINTER(ZGFX_CONTEXT))
    'zgfx_context_new',  # ctypes.POINTER(ZGFX_CONTEXT) (BOOL)
    'zgfx_context_reset',  # void (ctypes.POINTER(ZGFX_CONTEXT), BOOL)
    'zgfx_decompress',  # ctypes.c_int (ctypes.POINTER(ZGFX_CONTEXT), ctypes.POINTER(BYTE), UINT32, ctypes.POINTER(ctypes.POINTER(BYTE)), ctypes.POINTER(UINT32), UINT32)
)


def bind(lib, strict=False):
    """Attach restype/argtypes of this header's functions to a loaded library."""
    return _functions.bind(lib, names=FUNCTIONS, strict=strict)

__all__ = ['FUNCTIONS', 'ZGFX_CONTEXT', 'ZGFX_PACKET_COMPR_TYPE_RDP8', 'ZGFX_SEGMENTED_MAXSIZE', 'ZGFX_SEGMENTED_MULTIPART', 'ZGFX_SEGMENTED_SINGLE', 'bind']
